### ISSUE TITLE
suggestion for readme

### ISSUE THREAD

**Issue by noir-Z** [Askannz/optimus-manager#101]
Due to my own ignorance (mainly not knowing what was meant by keys) i managed to not recognize the importance of this step:

* **Manjaro KDE** : Manjaro ships with a default configuration for SDDM (the default login manager for KDE) which overrides some keys needed by optimus-manager. To fix this, you need to edit the file `/etc/sddm.conf` and simply put a `#` before the line starting with `DisplayCommand`and the one starting with `DisplayStopCommand`.

everything appeared to be working fine, the log didn't show anything out of order, the modules were loaded but it was never actually switching to nvidia.
So i tried every other troubleshooting solution before finally editing sddm.conf :D 

Since there is probably other people as unknowing as me i would like to suggest clarification regarding the necessity of this step. Maybe just leave the "To fix this," out as it somehow implied to me that it might or might not be broken without that step even though when read carefully it is obvious that it's necessary.

**Comment by Askannz** [comment]
Good point. I moved the instructions to their own section for additional emphasis.
