### ISSUE TITLE
Unable to disable Nouveau module

### ISSUE THREAD

**Issue by codexvn** [Askannz/optimus-manager#104]
**Describe the bug**
Unable to disable Nouveau module
**System info**
* Kernel: x86_64 Linux 5.2.1-arch1-1-ARCH
* Desktop manager: DDE
* Display manager: LightDM

**Detail**
![QQ图片20190717172625](https://user-images.githubusercontent.com/24852067/61364287-1b7aeb00-a8b8-11e9-92cd-4d7707e5aa4e.jpg)

if i add "alias nouveau off" to "/etc/modprobe.d/blacklist.conf",i can solve problem.

**Comment by Askannz** [comment]
optimus-manager loads nouveau itself when you are switched to the Intel card, that's why your blacklists are ignored. If you want to disable that behavior, use the following configuration :

```
[optimus]
switching=none
```
