### ISSUE TITLE
[Question] Backend nouveau secound monitor

### ISSUE THREAD

**Issue by Mario156090** [Askannz/optimus-manager#110]
Hi dear dev, is possible do work secound monitor with nouveau backend on intel mode?
Is required other configuration?

**Comment by Askannz** [comment]
Yes, if you set the switching backend to "nouveau", then the nouveau driver is loaded on the Nvidia card when you are in Intel mode. That should allow external video outputs to work.

**Comment by DOGGO20** [comment]
for some reason the external video output with the nouveau backend does not work, even when i use intel-virtual-output command, the display just keeps receiving a signal but will not actually display it and it keeps alternating between no signal and HDMI 1 1080p 60hz. it also causes my computer to lock up after waking from suspend in prime mode, so i have switched to the bbswitch backend for now.

**Comment by JavaCafe01** [comment]
@DOGGO20 do you have any tearing on the second monitor while using the bbswitch backend?

**Comment by Askannz** [comment]
@DOGGO20 nouveau might simply not work with your card. Unfortunately that sometimes happen. In any case, I can't diagnose it without logs.

Closing this issue since the original question was answered.
