### ISSUE TITLE
If you minimize the game, the desktop lags

### ISSUE THREAD

**Issue by tux871** [Askannz/optimus-manager#111]
Hi, problem is true for game Unturned, for other games, the problem does not occur
. When i alt tab, the cursor lags, the scroll in the browser lags. How can this be fixed?

My system:
5.2.2-1-MANJARO
NVIDIA GM108M [GeForce MX110] driver 430.26

**Comment by tux871** [comment]
I found out something, the problem appear because when minimizing the Unturned, the rendering does not stop, the GPU load is 100%, as in the game. While other games correctly stop rendering when minimized. Maybe someone knows how to solve the problem?

**Comment by Askannz** [comment]
This is not an optimus-manager bug. optimus-manager merely sets up the X session, whatever happens after the session has started is beyond its control.

This more likely a bug with the game, your desktop environment, or a translation layer you're using (Wine, Proton, DXVK...).
