### ISSUE TITLE
Can't switch between cards, Xorg wont shut down, goes into soft lock.

### ISSUE THREAD

**Issue by TheScrawl** [Askannz/optimus-manager#116]
**Describe the bug**
I installed optimus-manager by following the steps provided for Manjaro (i.e making sure bumblebeed is disabled, and disabling mhwd.conf)

~~When I start my PC, it will boot correctly, and I can run `startx` to launch into i3. At this point I can run `optimus-manager --print-mode` and it will tell me I am running on intel. Systemctl shows the service as running.
From here, if I try to switch modes, I will encounter errors.
If for any reason I attempt to close my Xserver and then restart it (including using my i3 binding to shut down the server, or when it forces a shutdown when I run `optimus-manager --switch nvidia`) my system will go into soft lock upon rerunning it, and I get the errors saying `Waiting for X server to start accepting connections` and then `[<numbers>] watchdog: BUG: soft lockup - CPU#<number> stuck for 21s!` - this will continue until I press by power button, in which case it attempt to run systemd shutdown jobs, which will never end (i.e they keep extending the job time), until I press and hold the power button, and restart, which puts me back where I started~~ This can be disregarded, its poorly written and I've made changes since. 

EDIT: I've made some progress I think but i'm still getting errors
I now run primus-offload on starting of the Xserver by putting it in my xinitrc
I have switched to bbswitch
Now, when I run `optimus-manager --switch nvidia` it will close to the tty, however there are still issues
The Xserver refuses to to die, and I have been trying to kill it with `killall Xorg`, which I assume is working
When I run `prime-switch` the system freezes, and starts slowly sending `[<numbers>] watchdog: BUG: soft lockup - CPU#<number> stuck for 22s!` errors. This continues until I press and hold the power to shut my laptop off.

**System info**
Manjaro,
i3-gaps
No display manager (afaik)
Xiaomi Laptop Pro, MX150, 8gb, Intel 15-8250U

**Logs**
EDIT: I uploaded the wrong logs, oops. Heres the right one.
[boot_setup.log](https://github.com/Askannz/optimus-manager/files/3511780/boot_setup.log)

**Comment by Askannz** [comment]
Nothing wrong in the log, but I suspect another low-level power switching issue.

To verify that, could you try again with those options in your config file ?

```
[optimus]
switching=none
pci_power_control=no
```

**Comment by TheScrawl** [comment]
I tried these settings, and they worked. I had them set to bbswitch and yes respectively. Thanks for this!

**Comment by Askannz** [comment]
Sorry, I should have been more clear. Those settings fix the issue by completely disable power switching, which isn't a proper solution since it'll hurt your battery life.

I would suggest leaving `switching` to `none` but set `pci_power_control` to `yes`, and see if the battery life improves.

**Comment by Askannz** [comment]
I'm closing this issue since it's yet another case of hardware issues related to power switching. Version v1.2 and the [power management guide](https://github.com/Askannz/optimus-manager/wiki/A-guide--to-power-management-options) provide some mitigations and workarounds.
