### ISSUE TITLE
Blank screen with cursor

### ISSUE THREAD

**Issue by ccxex29** [Askannz/optimus-manager#120]
**Describe the bug**
Booting takes way longer and the system seems to have locked up and X only shows black screen with a cursor without being able to move the cursor or change tty. However, bumblebee optirun, primusrun, primusvk, and nvidia-xrun works just fine (Makes me think that it's unrelated to the lockup problem in FAQ). 
*I disabled bumblebeed.service and removed all nvidia/intel related xorg configs beforehand
*optimus-manager configuration files are not modified
*Journal shows nouveau errors that may be related.

**System info**
- Distribution: Manjaro Linux 18.0.4
- DE/WM: XFCE 4.14.0 (XFWM4)
- DM : LightDM 1.30.0
- Laptop : Acer Nitro 5 AN515-52-52LD

**Logs**
/var/log/optimus-manager/* logs: https://pastebin.com/BQ1RcAhs
Journal Log: https://pastebin.com/BXyJ9sdP

**Comment by m-dwyer** [comment]
You could try changing `switching=nouveau` to `switching=none` in your optimus-manager.conf file.

I have a HP ZBook Studio x360 G5 which has an Optimus setup, and it appears with `switching=nouveau`, when the nouveau kernel module loads, my machine slows to a crawl and will crash (sometimes I'll catch nouveau errors in a TTY before it completely freezes).

It seems the nouveau driver doesn't play nicely with some Optimus setups when running in Hybrid mode..

**Comment by Askannz** [comment]
What @m-dwyer said. I'm going to disable `nouveau` by default in the next release because that's really causing issues for a lot of people.

Try with `switching=none` and `pci_power_control=no`. If that works (i.e you can log in without issues), re-enable power control. If the battery life is still bad, try with `switching=bbswitch`.

**Comment by ccxex29** [comment]
> Try with `switching=none` and `pci_power_control=no`. If that works (i.e you can log in without issues), re-enable power control. If the battery life is still bad, try with `switching=bbswitch`.

`switching=none` and `switching=bbswitch` works on my laptop. Which should I prefer if I don't feel noticable difference in power usage?

**Comment by Askannz** [comment]
@ccxex29 sorry, I missed your message. If bbswitch makes no difference on your battery life, then it's probably best to disable it with `switching=none`.
