### ISSUE TITLE
Adding Screen section to xorg-*.conf

### ISSUE THREAD

**Issue by gaalcaras** [Askannz/optimus-manager#124]
Hi there,

First of, thanks a lot for your work. It has solved a lot of problems and headaches for me!

To make it work properly though (I use i3 with X, no display manager), I had to add a small screen section to my `/etc/X11/xorg.conf.d` direction, like so:

```
Section "Screen"
  Identifier "Screen0"
  Device "nvidia"
EndSection
```

I know that you can edit the `/etc/optimus-manager/xorg-nvidia.conf` to change the Device section: it would be really nice if we had a way to add a Screen section as well, maybe through another config file. Right now I have to wrap `prime-switch` with some additional commands to add that Screen section. It works, but a less hacky way would make the whole thing more reliable.

**Comment by Askannz** [comment]
I believe that's the same bug as https://github.com/Askannz/optimus-manager/issues/99, and should have been fixed by https://github.com/Askannz/optimus-manager/commit/98f00e03572651471a24df00916946ab40a723f0 (included from release 1.1 onwards).

Feel free to re-open if it's not the case.
