### ISSUE TITLE
Can't resume after suspend when using Nvidia GPU

### ISSUE THREAD

**Issue by gaalcaras** [Askannz/optimus-manager#125]
**Describe the bug**
When using Nvidia GPU, I can't wake up the computer after supending it. I can't switch TTYs either, so I have to force shutdown my machine and boot it up again. 

**System info**
Please include :
- Your distribution : Arch Linux
- I use i3 with X (using `startx`), no DM or DE
- Your laptop model : [X1 Extreme](https://wiki.archlinux.org/index.php/Lenovo_ThinkPad_X1_Extreme)
- The version of optimus-manager you are using : latest stable release (optimus-manager)
- Also I add this screen config to my `/etc/X11/xorg.conf.d` directory to make the Nvidia config work:

```
Section "Screen"
  Identifier "Screen0"
  Device "nvidia"
EndSection
```

**Logs**

System log:

```
Sep 02 20:07:34 batcave systemd-sleep[7013]: Suspending system...
Sep 02 20:42:37 batcave systemd-sleep[7013]: System resumed.
Sep 02 20:42:37 batcave systemd-sleep[7013]: /usr/bin/nvidia-sleep.sh: line 49: /proc/driver/nvidia/suspend: No such file or directory
```

The only thing of notice I can see in `/var/log/optimus-manager/` is the following:

```
2019-09-02 08:44:31 PM +0200 ==================== 

Optimus Manager (Setup script) version 1.1
Setting up PRIME
Checking status of optimus-manager.service
Loading config
Running xrandr commands
Error : cannot setup PRIME : Cannot setup PRIME : Failed to execute 'xrandr --setprovideroutputsource modesetting NVIDIA-0' : 
```

but it's probably something else since it takes place 2 minutes after the bug (so probably something I did after rebooting).

**What I've tried so far**
I've tried a bunch of general solutions (such as blacklisting `nvidiafb` module) without success. I've also tried to run a bunch of commands before `/usr/bin/nvidia-sleep.sh resume` in `/lib/systemd/system-sleep/nvidia`, such as `prime-switch-boot` and `prime-offload`, but that didn't work either.

**Comment by TomJannes** [comment]
Any news on this issue? I have the same problem

**Comment by Askannz** [comment]
Unfortunately there's not much I can do here. Suspend/wakeup is notoriously broken with Nvidia cards, and optimus-manager doesn't add any layer on top of your system that could interfere with the drivers: once you are switched to a GPU mode, it should behave exactly as if you wrote the Xorg configuration yourself.

The only fixes I can suggest is to try playing with the modeset power control options in the config file, and see if it makes any difference.

**Comment by gaalcaras** [comment]
> Unfortunately there's not much I can do here.

Yeah, I figured as much, but it was worth a try!

> The only fixes I can suggest is to try playing with the modeset power control options in the config file, and see if it makes any difference.

Thanks for the idea. I'll close the issue for now, but I'll follow up here if I solve the problem.
