### ISSUE TITLE
Freeze when changing display configuration on Nvidia

### ISSUE THREAD

**Issue by ryan-bickel** [Askannz/optimus-manager#126]
**System Info**
- Razer Blade 15 Advanced (Mid-2019)
- Distribution: Manjaro Linux
- DE/WM: i3gaps
- DM: LightDM

I have my laptop running optimus-manager connected to a Thunderbolt 3 dock and an external monitor connected to the dock. The display configuration is incorrect: the external monitor runs at 60hz instead of 144, and the displays are placed on top of one another (so I see what's going on on the 1080p laptop screen in the top left corner of the 1440p external screen). However, whenever I try to alter the display configuration (display positions or refresh rate) using xrandr or arandr, the external screen goes black and the system freezes (cannot even access tty).

**What I've tried**
- Switching kernels (tried 4.19 and 5.2)
- Changing the total size of the xscreen using `xrandr --fb 4480x1440` and then configuring the display positions in arandr
- Using intel mode (doesn't work because the Thunderbolt port is connected only to the Nvidia card)

**Comment by Askannz** [comment]
Unfortunately if it's a driver bug there's not much I can do, optimus-manager only sets up the kernel modules/Xorg configuration and doesn't interfere with the system after that.

There's a possibility that the xrandr command required for Prime are messing with your setup ; in that case, you would need to uninstall optimus-manager and [set up the Xorg config yourself](https://wiki.archlinux.org/index.php/NVIDIA_Optimus#Use_NVIDIA_graphics_only) (without the xrandr commands) to see if the problem disappears.

The only other thing I can suggest is setting `modeset=no` for Nvidia in the configuration file.

**Comment by ryan-bickel** [comment]
Ok, thank you. I have already tried setting `modeset=no`. I will probably switch distros or try installing a different display manager, as I remember optimus-manager working on this same laptop when I had Manjaro KDE installed, which uses SDDM instead of LightDM like Manjaro i3. However, I did not have the dock/external monitor then so the problem may still be present.
