### ISSUE TITLE
New feature: new mods for nvidia 435

### ISSUE THREAD

**Issue by michaldybczak** [Askannz/optimus-manager#129]
I stumbled upon this article:

https://www.gamingonlinux.com/articles/the-handy-nvidia-optimus-gpu-switcher-just-added-support-for-more-linux-desktops.14985

and it hit me, it could be also added to optimus-manager.

Currently, there are many reasons why we should not switch to 435 series like:

- nvidia is not fully powered down so it uses more battery
- nvidia isn't used automatically like on windows and a parameter must be added to launch (or maybe I read this wrong?) command, so basically it looks it's working somewhat similarly like it was with bumblebee
- output ports attached to nvidia seems to be not working so if someone has for example hdmi slot with nvidia (like me), it won't work, etc.

and because of that I still am on 430 drivers.

However, with that in mind, splitting modes into more than one seems to be an interesting idea although I'm not sure how it would work if I had added a launch parameter and then switched to only nvidia mode?

Anyway, just wanted to pass the idea since some future driver releases will have this off-loading feature anyway. So optimus-manager could detect if we have a proper driver version and if so, offer more GPU mods.

This is only an idea. You can close it after the reading unless you think it's a valid feature.
And oh, adding Nvidia settings to the menu also seems like a nice touch.

**Comment by eadwu** [comment]
1. I don't think this program can power down the device fully anyway, and from what I've read, it does, but only for Turing+ GPUs.
2. At this point, you're better off using windows instead of Linux. Linux isn't still a full on replacement for games on the desktop so if you automatic offloading just goto Windows.

**Comment by Askannz** [comment]
> I stumbled upon this article:
> 
> https://www.gamingonlinux.com/articles/the-handy-nvidia-optimus-gpu-switcher-just-added-support-for-more-linux-desktops.14985
> 
> and it hit me, it could be also added to optimus-manager.

This app is just a convenient frontend to `prime-select` on Ubuntu, nothing more. If you want something similar for optimus-manager, I'd recommend [optimus-manager-qt](https://github.com/Shatur95/optimus-manager-qt).

> Currently, there are many reasons why we should not switch to 435 series like:
> 
>     * nvidia is not fully powered down so it uses more battery

The new power management in 435 is completely optional, whatever power switching method you currently use in optimus-manager will still work.

> and because of that I still am on 430 drivers.

I don't understand your reasoning here. The new 435 driver did not remove *any* feature, you can just install them and anything optimus-manager currently does will still work. You'll just have the offloading feature available if you want to use it. optimus-manager now offers a "hybrid" mode for that purpose.

>     2. At this point, you're better off using windows instead of Linux. Linux isn't still a full on replacement for games on the desktop so if you automatic offloading just goto Windows.

I disagree, I've been running Linux-only for years and I play a lot of games.  I have to use Linux for dev stuff anyways, so even if the gaming experience isn't on par with Windows it's still many times more convenient than maintaining a dual-boot. But that's an off-topic discussion anyways.

**Comment by michaldybczak** [comment]
Ah, I treat optimus-manager-qt as a while with optimus-manager so I forgot I should post it there. If this hybrid approach is already there then it is exactly what I was asking about.

Nice to ask for a feature and to find out it's already there.

OK, thanks for the clarification. Closing.
