### ISSUE TITLE
Issue with modesetting to intel.

### ISSUE THREAD

**Issue by inzar98** [Askannz/optimus-manager#13]
I need to use intel driver instead of modesetting. I have a lot of tearing in modesetting driver (Tried dri 3 - 2 no matter). And script doesnt allow me change to intel.

**Comment by Askannz** [comment]
That's a good idea, the config file needs an option for choosing between modesetting and Intel. I'll try to slip that in a release.

**Comment by inzar98** [comment]
Dont forget to add some paramertes for intel. Like "sna" "xna" select and "tearfree" option like. And I wanna say thats perfect work man. Thanks for it... But I need to wait for intel

**Comment by Askannz** [comment]
All that has been added to release v0.3 :wink:
