### ISSUE TITLE
Startup mode intel freezes system on login

### ISSUE THREAD

**Issue by xFichtl1** [Askannz/optimus-manager#131]
**Describe the bug**
When using:
`optimus-manager --set-startup intel`
Freezing after login in or go to Terminal

When I set nvidia as startup mode and then switch to intel, there are no problems

**System info**
- Manjaro
- KDE
- SDDM
- Gigabyte Aero 15x
- optimus-manager 1.1-1

**Logs**
https://pastebin.com/NdBxxiUD

**Comment by Askannz** [comment]
This is likely another hardware-specific power switching bug. Please install new new optimus-manager version (1.2) and follow the new [guide](https://github.com/Askannz/optimus-manager/wiki/A-guide--to-power-management-options) on power management.
