### ISSUE TITLE
ERROR : cannot get current display manager name : No display-manager.service file found

### ISSUE THREAD

**Issue by notaduck** [Askannz/optimus-manager#134]
**Describe the bug**
When I try to switch from intel -> nvidia do I get the following message,
```
[~] optimus-manager --switch nvidia

ERROR : cannot get current display manager name : No display-manager.service file found
You are about to switch GPUs. This will forcibly close all graphical sessions and all your applications WILL CLOSE.
(you can pass the --no-confirm option to disable this warning)
Continue ? (y/N)
> y
Switching to mode : nvidia
Logging out the current desktop session
```

However nothing happends, It doesn't close the current X server and if I do it manually and starts one again, then will the intel gpu still be in use.

**System info**
Please include :
- Distribution: Manjaro
- Window Manager: DWM
- Display Manager: None
- Optimus Manager (Client) version 1.1

**Logs**
https://termbin.com/rrsy

**Comment by pssncp142** [comment]
Did you check this?
https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting#i-do-not-use-a-display-manager-i-use-startx-or-xinit

**Comment by notaduck** [comment]
I missed that point! thank you.
