### ISSUE TITLE
conflicting with nvidia-xruns bbswitch config

### ISSUE THREAD

**Issue by deisi** [Askannz/optimus-manager#135]
I encountered some issues due to a prior config with nvidia-xrun. optimus-manager was not able to use bbswitch to switch between the GPUs. I thus like to share my findings. Maybe we can improve documentation a little.

After following the instructions, I was not able to follow https://github.com/Askannz/optimus-manager/wiki/A-guide--to-power-management-options#configuration-3--bbswitch even though I knew it works due to prior bbswitch usage. To get everything working, I needed to also revert nivida-xrun config. I did:

```
# Revert loading of bbswitch module
rm /etc/modules-load.d/bbswitch.conf

# Revert disabeleing of nvidia gpu
rm /etc/modprobe.d/bbswitch.conf 

# Revert xinit config
rm ~/.nvidia-xinitrc
```

I basically followed https://wiki.archlinux.org/index.php/Nvidia-xrun#Configuration backwards.

I'm not sure how to best mention this in the readme or wiki. Maybe a warning saying that optimus-manager cant use bbswitch correctly if nvidia-xrun config is not reverted or something along these lines. I think in most cases people are able to do what I did and just read nvidia-xrun config section backwords. However a tip that this might be necessary is useful IMO.

**Comment by calebreister** [comment]
I encountered the same issue on my ThinkPad T470p, and can confirm that removing the specified files does indeed fix the issue. It is worth noting that the issue is *not* with bbswitch, since I was able to turn the GPU on and off without any trouble.

**Comment by Askannz** [comment]
Interesting, thanks raising the issue. Seems like it's indeed worth adding a warning about nvidia-xrun in the doc.

**Comment by Askannz** [comment]
Added a warning in the README.
