### ISSUE TITLE
bbswitch is loaded, unloaded and then loaded again on startup

### ISSUE THREAD

**Issue by melentye** [Askannz/optimus-manager#137]
**Describe the bug**

When using default intel mode, `switching=bbswitch` and `pci_reset=no`, `bbswitch` kernel module is loaded, unloaded and then loaded again during optimus-manager initialization.

Looking at the code, unloading of `bbswitch` happens unconditionally before the PCI reset, even if PCI reset is disabled. Would the right thing to do be to consider the `pci_reset=no` and do not unload `bbswitch` in this scenario?

**System info**

Arch, GNOME, GDM, latest stable optimus-manager

**Comment by Askannz** [comment]
Yes that's indeed a bug, bbswitch should not be unloaded with `pci_reset=no`. See the discussion at https://github.com/Askannz/optimus-manager/pull/142#discussion_r328987780

**Comment by Askannz** [comment]
Fixed by https://github.com/Askannz/optimus-manager/commit/783092b746450bf414868ea6c6d7df382a72a62c
