### ISSUE TITLE
Can't switch to nvidia

### ISSUE THREAD

**Issue by indaleto** [Askannz/optimus-manager#139]
Everything was fine until I upgraded my system to v1.2, along with optimus-manager-qt. After that I rollback to version 1.1 (thks to timeshift) and the switch produce effects again.
Neither works with optimus-manager-qt nor with cli.

Manjaro
Cinnamon
LightDM
Asus A55vj
optimus-manager 1.2, optimus-manager-qt 1.3.1-1

Log:
Optimus Manager (Setup script) version 1.2
Setting up PRIME
Checking status of optimus-manager.service
Loading config
No user config at /var/lib/optimus-manager/config_copy.conf
Running xrandr commands
Error : cannot setup PRIME : Cannot setup PRIME : Failed to execute 'xrandr --setprovideroutputsource modesetting NVIDIA-0' : 

By the way, the file /var/lib/optimus-manager/config_copy.conf does not exists...

**Comment by Siege0x** [comment]
I had the same issus,due to bbswitch unload error,follow the #136 could temperory fix this.

**Comment by indaleto** [comment]
Thanks for your response, but unfortunately that didn't work...

**Comment by Askannz** [comment]
Could you post *all* the logs from `/var/log/optimus-manager/` ? I can't do much from that single Prime log.

> No user config at /var/lib/optimus-manager/config_copy.conf
> By the way, the file /var/lib/optimus-manager/config_copy.conf does not exists...
Yeah that's expected, nothing to worry about here. There's definitely something wrong with `cannot setup PRIME` though.

**Comment by fvguilherme** [comment]
Install `bbswitch` has solved the problem for me on Arch.

**Comment by indaleto** [comment]
YES!!! That did the trick. Thank you.
Thank you Askannz anyway, but I've been busy and I didn't had the time to search and post my logs here....

Problem solved :)
