### ISSUE TITLE
Intel backlight config

### ISSUE THREAD

**Issue by nikola3244** [Askannz/optimus-manager#14]
Hi, before using optimus-manager, I've had the following in my `xorg.conf`:

```
Section "Device"
    Identifier "Card0"
    Driver     "intel"
    Option     "TearFree" "true"
    Option     "Backlight"  "intel_backlight"
EndSection
```

How can I have the last option with optimus-manager when I'm switched to Intel? Specifically: `Option     "Backlight"  "intel_backlight"`

**Comment by Askannz** [comment]
Checkout the new v0.4 release, I added a feature to pass extra options to Xorg. In your case, you just have to write `Option "Backlight" "intel_backlight"` to `/etc/optimus-manager/xorg-intel.conf`.

**Comment by nikola3244** [comment]
Hey, I did just that but `xbacklight` is still not working, it's just saying `No outputs have backlight property` :cry: 

I did reboot, wasn't sure if restarting X was enough

If you need any logs, just let me know

**Comment by nikola3244** [comment]
Fixed, just had to add this to the main config file:

```
[intel]
driver=intel
```

Works perfectly now!
