### ISSUE TITLE
Can't unload nvidia modules preventing switch to nvidia

### ISSUE THREAD

**Issue by mdlss** [Askannz/optimus-manager#140]
Arch Linux
SDDM + i3
Latest Stable

When trying to switch to nvidia (I have it set up for hybrid, so switching set to none) the system can't seem to unload nvidia_modeset. I installed bbswitch to bypass the unload errors in the boot log.

[boot_setup.log](http://ix.io/1WEq)
[gpu_setup.log](http://ix.io/1WEr)
[prime_setup.log](http://ix.io/1WJx)

**Comment by fvguilherme** [comment]
Install `bbswitch` has solved the problem for me on Arch.

**Comment by Askannz** [comment]
@fvguilherme you're referring to https://github.com/Askannz/optimus-manager/issues/133 which is a different bug.

**Comment by fvguilherme** [comment]
oh, it is. My mistake. Sorry.

**Comment by mdlss** [comment]
Hey, I'm just wondering what seems to be causing this? Is there any additional troubleshooting information I can provide?

**Comment by Askannz** [comment]
Wow, I'm sorry for letting this issue stale for so long. Does it still happen with `optimus-manager-git` ? Does it happen when booting straight into nvidia mode ?

**Comment by mdlss** [comment]
That's okay. I just tested again with boot parameter set to nvidia and it is still not working. Additionally it's complaining  that there is no nvidia enable/nvidia disable script. I'm just looking more into why this isn't there.

**Comment by mdlss** [comment]
Sorry about the delay on my end also! I appear to still be having this issue.

**Comment by Askannz** [comment]
Is it still an issue ?

**Comment by gustavocardosomoreira** [comment]
I can confirm this issue still happens. I get an error when trying to run optimus-manager.
``subprocess.CalledProcessError: Command 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia' returned non-zero exit status 1.``

Configs:
Arch Linux
gdm-prime
optimus-manager-git (with or without bbswitch installed)

**Comment by es20490446e** [comment]
The logs seem gone. If you are still experiencing this bug:

1. Reupload the logs into GitHub directly.
2. Reopen the issue.
