### ISSUE TITLE
NVIDIA built-in power management not detected

### ISSUE THREAD

**Issue by wizonesolutions** [Askannz/optimus-manager#143]
**Describe the bug**
I followed https://github.com/Askannz/optimus-manager/wiki/A-guide--to-power-management-options#configuration-3--bbswitch option 1 (I have an RTX 2080 Max-Q), but when I run `sudo optimus-manager --switch nvidia`, I still see:

```
WARNING : no power management option is currently enabled (this is the default since v1.2). Switching between GPUs will work but you will likely experience poor battery life.
```

**System info**
Please include :
- Your distribution
Manjaro 18.1.0
- Your desktop manager (KDE, GNOME, Cinnamon...), if you have one
KDE
- You display manager (SDDM, GDM, LightDM...), if you have one. If you do not know, you are probably using the one coming with your desktop manager.
SDDM
- Your laptop model, if you think it could be related to the problem
Razer Blade 15 Advanced Model Mid-2019 RTX 2080 Max-Q
- The version of optimus-manager you are using : latest stable release (optimus-manager), or the latest Git version (optimus-manager-git)
latest stable release

**Logs**
If you are able to, please attach all the logs you can find in `/var/log/optimus-manager/`. *Do not directly copy paste the logs into the GitHub issue.* Join them as text files or save them to pastebins (https://pastebin.com/) and post the links here.
Will attach if relevant.

I suspect this message always displays without actually checking the power management mode...and if so, I apologize for the incorrect bug report. I just wanted to check if I had set up power management properly. I do see that when I `cat` the PCI device, it says `auto`, so I think I have.

**Comment by Askannz** [comment]
Yeah you are correct, that's actually not a bug. optimus-manager doesn't check if the new Nvidia power management is enabled or not, so it always print the warning if you use the default configuration.

I'll try to find a way to reliably detect if Runtime D3 power management is enabled or not. Unfortunately checking the value of `/sys/bus/pci/devices/<bus ID>/power/control` is not enough : even if it's set to `auto`, there is [more setup](http://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/dynamicpowermanagement.html) required to get it to work. If you have already followed those steps and power management is working, you can safely ignore this warning.

**Comment by Askannz** [comment]
c81e1c2e6592bb1801543b617c897a9014d93893 changes the warning message to cover the new power management.
