### ISSUE TITLE
`--print-mode` reports "intel" in hybrid mode

### ISSUE THREAD

**Issue by Askannz** [Askannz/optimus-manager#144]
Title. Opening this one myself as a reminder.

**Comment by chabad360** [comment]
I'm still having this bug...

**System Details:**
`Uname -a`: `Linux MendelsLaptop 5.3.7-arch1-1-ARCH #1 SMP PREEMPT Fri Oct 18 00:17:03 UTC 2019 x86_64 GNU/Linux`
CPU: Intel Core i7-8750H
iGPU: Intel UHD Graphics 630
dGPU: NVIDIA GeForce RTX 2060 Mobile

**Comment by SlawekNowy** [comment]
That's beacuse xrand doesn't seem to list nvidia as provider.
