### ISSUE TITLE
Couldn't control brightness from intel to nvidia by optimus-manager

### ISSUE THREAD

**Issue by kktt007** [Askannz/optimus-manager#145]
Archlinux plasma sddm
I have install nvidia sddm and optimus-manager(have set switching=bbswitch driver=modesetting etc).
May i know if i shoud configure nvidia somewhere(like /etc/default/grub add nvidia-drm.modeset=1 etc. you known).
Many thanks.

**Comment by Askannz** [comment]
Could you reformulate your question ? I'm not sure what you're asking.

optimus-manager takes care of loading kernel modules with appropriate parameters, so there's no need to add anything to `/etc/default/grub`.

**Comment by kktt007** [comment]
> 
> 
> Could you reformulate your question ? I'm not sure what you're asking.
> 
> optimus-manager takes care of loading kernel modules with appropriate parameters, so there's no need to add anything to `/etc/default/grub`.

I switch to Nvidia and re-login, 
1.  Screen brightbess  seems to be adjusting, but it is not brightening (when use f7 f8) etc.

Then i close the cover of my laptop, 

2. Black screen when waking from suspend. No cursor.The fan sounds loud. 

Thank you in advanced.

**Comment by kktt007** [comment]
Please close the issue, I have solve my issue about blacklight. All my issues are about Nvidia and ACPI. Not optimus-manager. Thank you optimus-manager, wish be better in the tufure.

**Comment by haoadoresorange** [comment]
@kktt007: I'm having the similar problem. What was that you fixed with nvidia acpi ?

**Comment by kktt007** [comment]
> @kktt007: I'm having the similar problem. What was that you fixed with nvidia acpi ?

add "acpi_osi=Linux acpi_backlight=vendor" to "GRUB_CMLINE_LINUX_DEFAULT", it does work for me. In a word, the quiestion is caused by acpi.
