### ISSUE TITLE
Hybrid mode, doesn't work nvidia.

### ISSUE THREAD

**Issue by Mario156090** [Askannz/optimus-manager#151]
Hi, I am triying execute glxgears with nvidia on hybrid mode but it show me a error:
![image](https://user-images.githubusercontent.com/47507975/66259143-29cbfb00-e773-11e9-8883-1500538f1df9.png)

**Comment by Oscar-Macdonald** [comment]
What is the output of `glxinfo | grep "OpenGL renderer"`?

**Comment by Mario156090** [comment]
> What is the output of `glxinfo | grep "OpenGL renderer"`?

Hi, only show me intel graphic card.
![image](https://user-images.githubusercontent.com/47507975/66260926-af0eda00-e78a-11e9-9a38-6137729028c1.png)

**Comment by Askannz** [comment]
Is your Xorg server patched for offloading ? It won't work with the default package in your distribution repo.

**Comment by Mario156090** [comment]
> Is your Xorg server patched for offloading ? It won't work with the default package in your distribution repo.
Ok, i am using Arch Linux with Xorg 1.25.
Should I install Xorg 1.26 or anything?
![image](https://user-images.githubusercontent.com/47507975/66263237-c82c8080-e7b4-11e9-9f1c-cbf5d38e10d1.png)

**Comment by Askannz** [comment]
No, the patches haven't been released in any official repo yet (as far as I know). Here's the version I've been using, it's from an Nvidia developer : https://gitlab.freedesktop.org/aplattner/arch-xorg-server/blob/master/PKGBUILD

**Comment by Mario156090** [comment]
> No, the patches haven't been released in any official repo yet, or even in AUR (as far as I know). Here's the version I've been using, it's from an Nvidia developer : https://gitlab.freedesktop.org/aplattner/arch-xorg-server/blob/master/PKGBUILD
![image](https://user-images.githubusercontent.com/47507975/66267804-925eba80-e7fb-11e9-8bcd-fb344596e2e2.png)
It doesn't work for me. I couldn't install this. :(

**Comment by niciuffo** [comment]
I'm having the same issue trying to install xorg-server. Which package should be installed to satisfy the `gl` dependency?

**Comment by Mario156090** [comment]
I don't know. :(

**Comment by Algebro7** [comment]
> No, the patches haven't been released in any official repo yet, or even in AUR (as far as I know). 

Does this mean we need a patched xorg to use RTD3 power management described in the wiki? I’m trying to figure out how to get this to work because apparently bbswitch doesn’t work on my current gen xps

**Comment by gibsonjareds** [comment]
@niciuffo @Mario156090 This is PR for xorg-server relates to our mutual issue: https://gitlab.freedesktop.org/xorg/xserver/merge_requests/292

It looks like the libraries providing `gl` changed the versioning, so now it shows as `1.2`. Best solution if you don't feel like manually doing all of this is to wait, most likely, though you could create a patch from that PR and apply it in the PKGBUILD in order to get it going

**Comment by gibsonjareds** [comment]
@Mario156090 @niciuffo 
[patch_for_meson.zip](https://github.com/Askannz/optimus-manager/files/3703940/patch_for_meson.zip)

copy the patches to the root of the `arch-xorg-server` root that you checked out, then do `git apply patch_for_meson.patch` and it should work if your `gl` is reporting as version `1.2`

**Comment by Mario156090** [comment]
> @Mario156090 @niciuffo
> [patch_for_meson.zip](https://github.com/Askannz/optimus-manager/files/3703940/patch_for_meson.zip)
> 
> copy the patches to the root of the `arch-xorg-server` root that you checked out, then do `git apply patch_for_meson.patch` and it should work if your `gl` is reporting as version `1.2`

Thank's a lot, this works for me.

**Comment by Algebro7** [comment]
Worth pointing out that once you get the patched xorg-server installed, you can get PRIME set up on arch with the `prime` aur package.

**Comment by Mario156090** [comment]
Well, the issue is fixed. Then I going to close the thread.
