### ISSUE TITLE
Arch/KDE Plasma Scaling Issue on Nvidia

### ISSUE THREAD

**Issue by ssean** [Askannz/optimus-manager#154]
Let me start by saying - I'm not sure if this is directly related to optimus-manager..

I have a ThinkPad X1 Extreme with a 4K monitor (3840x2160).

Prior to installing optimus-manager, I was having scaling issues which was fixed by the following:

Export the following variable: `PLASMA_USE_QT_SCALING=1` to `~/.bash_profile`

Source: https://www.reddit.com/r/kde/comments/94zn22/scaling_problems_in_plasma_512/

-----

When I'm using Intel, everything looks perfect.

When I switch to Nvidia, the scaling is terrible.

Any ideas?

**Comment by ssean** [comment]
In case anyone else runs into this issue.. 

I ran `xrandr` in intel mode: My display is listed as: eDP1
I ran `xrandr` in nvidia mode: My display is listed as: eDP-1-1

I was able to fix it by doing the following:

`export QT_SCREEN_SCALE_FACTORS=$QT_SCREEN_SCALE_FACTORS"eDP-1-1=2"`

to the following location:

~/.config/plasma-workspace/env/test.sh

----

Source: https://www.reddit.com/r/Kubuntu/comments/acjek5/scaling_issues_with_nvidiaprime_and_4k_screen

**Comment by Askannz** [comment]
Glad that you found a fix, but I assume that only applies to Qt apps. I don't own a 4K monitor so I can't reproduce the issue, but maybe it's possible to fix it by setting a different value for `DPI` in the `[nvidia]` section of the config file.
