### ISSUE TITLE
Screen Resolution Reset - KDE Plasma 

### ISSUE THREAD

**Issue by scoronado12** [Askannz/optimus-manager#155]
I've just started using `optimus-manager` and ever since, for some reason on each start of the kwin session... I'm finding my display resolution on my HiDPI display is reset to the native `2880x1620` from my comfortable `1920x1080` 

What do others do so that this nonsense stops?

**Comment by Askannz** [comment]
This likely happens because optimus-manager executes `xrandr --auto`, which resets all monitors to their preferred modes. No solution for that yet, but I'll try to look into it.

**Comment by scoronado12** [comment]
Thanks! Didn't quite know if this was a bug, but I'm glad you taking a peek.

**Comment by Askannz** [comment]
Actually, I can't reproduce this issue. `xrandr --auto` resets the screen to native res for the login screen (which is kinda unavoidable) but then KDE takes over and sets the resolution to its own settings.

Is the "KScreen 2" service enabled ? (System settings -> Startup and Shutdown)

Maybe attach the output of `xrandr -q` while in Nvidia mode, just in case.

**Comment by scoronado12** [comment]
The issue just happened again, this time I went into hybrid mode as my steam games can run without issue like this.

> Is the "KScreen 2" service enabled ? (System settings -> Startup and Shutdown)
No. It isn't.

I'm not sure if it helps to give this after I had gone into settings and set it back to the preferred resolution.

    Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 16384 x 16384
    eDP-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 340mm x 190mm
       2880x1620     59.96 +  50.00  
       2560x1600     59.97  
       2560x1440     59.95  
       2048x1536     60.00  
       1920x1440     60.00  
       1856x1392     60.01  
       1792x1344     60.01  
       2048x1152     59.98    59.90    59.91  
       1920x1200     59.88    59.95  
       1920x1080     59.97    59.96*   59.93  
       1600x1200     60.00  
       1680x1050     59.95    59.88  
       1400x1050     59.98  
       1600x900      59.99    59.94    59.95    59.82  
       1280x1024     60.02  
       1400x900      59.96    59.88  
       1280x960      60.00  
       1440x810      60.00    59.97  
       1368x768      59.88    59.85  
       1280x800      59.99    59.97    59.81    59.91  
       1280x720      60.00    59.99    59.86    59.74  
       1024x768      60.04    60.00  
       960x720       60.00  
       928x696       60.05  
       896x672       60.01  
       1024x576      59.95    59.96    59.90    59.82  
       960x600       59.93    60.00  
       960x540       59.96    59.99    59.63    59.82  
       800x600       60.00    60.32    56.25  
       840x525       60.01    59.88  
       864x486       59.92    59.57  
       700x525       59.98  
       800x450       59.95    59.82  
       640x512       60.02  
       700x450       59.96    59.88  
       640x480       60.00    59.94  
       720x405       59.51    58.99  
       684x384       59.88    59.85  
       640x400       59.88    59.98  
       640x360       59.86    59.83    59.84    59.32  
       512x384       60.00  
       512x288       60.00    59.92  
       480x270       59.63    59.82  
       400x300       60.32    56.34  
       432x243       59.92    59.57  
       320x240       60.05  
       360x202       59.51    59.13  
       320x180       59.84    59.32  
    DP-1 disconnected (normal left inverted right x axis y axis)
    HDMI-1 disconnected (normal left inverted right x axis y axis)
    DP-2 disconnected (normal left inverted right x axis y axis)
    HDMI-2 disconnected (normal left inverted right x axis y axis)

**Comment by scoronado12** [comment]
Seems that this issue had stopped occurring. Closing.
