### ISSUE TITLE
Request for a detailed Power management Wiki for v1.2

### ISSUE THREAD

**Issue by mechaprabal** [Askannz/optimus-manager#156]
I am currently using `optimus-manager` in the device xps7590 with coffee lake and turing generation GPU. The wiki available [here](https://github.com/Askannz/optimus-manager/wiki/A-guide--to-power-management-options) for configuration 1 is not detailed. Can we get a step-by-step process to enable configuration 1 on this device?

**Comment by Vinno97** [comment]
I am not sure if this is the right place to post this or I should create a new issue, but I have another suggestion for the power management guide:
In the section [Configuration 2 : PCI power control](https://github.com/Askannz/optimus-manager/wiki/A-guide--to-power-management-options#configuration-2--pci-power-control), it says _However nouveau can also be really unstable on some cards, so if you encounter any issue, disable it_. 

Are there methods to test the configuration? If so, it would be very helpful to also have those included. 
For instance, right now I _think_ my laptop is not switching off the Nvidia GPU without any way of knowing for sure. Additionally, "instability" is not easy to quantify. If a system is running for a while without any issues and then has an accidental issue, I do not expect a user's/my first instinct to be to check the optimus configuration. I think any hints that can point to an issue would be helpful here.

**Comment by thomas-phillips-nz** [comment]
I agree, I am trying Configuration 2 out and I don't know if the nvidia GPU is being powered off correctly. I have set `pci_remove` to `yes`, and the nvidia GPU no longer shows up on the PCI bus. But is it powered off?

**Comment by nwildner** [comment]
Sup folks. 

If this is still a bug, please reopen it with more details. Optimus-manager is getting back on it's tracks recently and anyone using it should be tracking the `optimus-manager-git` package which got all PR's merged recently.

Since this is a 4 year old discussion, but feel free to reopen it with more recent data if you are still facing any issues. 

Have a nice week.
