### ISSUE TITLE
Short freeze/lag when querying optimus-manager

### ISSUE THREAD

**Issue by mindrunner** [Askannz/optimus-manager#160]
**Describe the bug**
I have a script which queries optimus-manager periodically to output nvidia-smi statistics when on nvidia or hybrid mode. I was previously using bbswitch, but migrated to 'no external power manager', because it seems that the integrated switching works more stable than bbwitch on my laptop.

However, executing `optimus-manager --status seems to produce a super short freeze of my whole desktop. Thus, when calling the script once a second, I experience constant mouse and scrolling lags.

I am not sure if that is related to my setup or a bug or by design. Maybe someone can clarify / confirm on this?

**System info**
- Arch
- i3
- LightDM
- Lenovo ThinkPad W530
- aur/optimus-manager 1.2.1-1 (+18 3.46%) (Installed)

**Logs**
Quick checked the logs, did not see anything which seems related. Will attach when necessary

**Comment by Askannz** [comment]
Honestly, the `--status` command is not intended for constant polling. It does a lot of things at once (including invoking external commands like xrandr and glxinfo) so it's not surprising that it causes high CPU usage.

I can't reproduce the stutters on my machine, but with a 1s interval I definitely see the CPU usage ramp up here too.

There's nothing I can do to fix this.
