### ISSUE TITLE
Optimus manager logs out with no DM installed

### ISSUE THREAD

**Issue by andrhua** [Askannz/optimus-manager#163]
**Describe the bug**
OM logs me out even though I have no DM, therefore X server exit script is not being executed properly

**System info**
Arch + i3, no DM, Dell Inspiron 7577

**Comment by Askannz** [comment]
Oh yeah, the FAQ is outdated actually, thanks for pointing that out. Auto-logout now works for supported window managers even without a DM.

This part is still valid though :

> Just like above, you must make sure to run /usr/bin/prime-offload (as normal user) just after the X server is started, and /usr/bin/prime-switch (as root) after it has stopped.

**Comment by Askannz** [comment]
FAQ has been updated. Feel free to re-open if you are experiencing issues when manually executing the scripts.
