### ISSUE TITLE
no system tray icon after installing optimus-manager-qt

### ISSUE THREAD

**Issue by OmerBit** [Askannz/optimus-manager#165]
Hello so i have installed optimus-manager and its working very good!!, I'm using gdm and gnome.
But one thing not have working is the tray icon, I tried to find in the settings maybe i need to enable it but could not find anything there.
Please have a look maybe need to update the package?
Thank!!! brilliant package you have created!!
My laptop model is asus gl753ve
arch linux 5.3.7-arch1-1-ARCH

**Comment by Mario156090** [comment]
What is your DE?
For me works very well but always the icon appears after 3 reboots or anaything.

**Comment by OmerBit** [comment]
> What is your DE?
> For me works very well but always the icon appears after 3 reboots or anaything.
@Mario156090 
im using Gnome and GDM, well i tried to reboot many times but nothing changes still cant see the icon.

**Comment by Mario156090** [comment]
> > What is your DE?
> > For me works very well but always the icon appears after 3 reboots or anaything.
> > @Mario156090
> > im using Gnome and GDM, well i tried to reboot many times but nothing changes still cant see the icon.

Well, I believe gnome does not show that type of icons on systray, anyway, you should ask this in the optimus-manager-qt thread.

**Comment by Askannz** [comment]
As @Mario156090  said optimus-manager-qt is a separate project, so you should post an issue to https://github.com/Shatur95/optimus-manager-qt instead.
