### ISSUE TITLE
Proper power management

### ISSUE THREAD

**Issue by mindrunner** [Askannz/optimus-manager#166]
I have some struggle finding the correct mode for my laptop (ThinkPad W530)

```
00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
01:00.0 VGA compatible controller: NVIDIA Corporation GK107GLM [Quadro K2000M] (rev a1)
```

**nouveau:**
not really a fan. cannot remember why, but the experience was not pleasant. Also, does nouveau turn off the card? It rather keeps it on low-clock, right? Then, this is not an option anyways. Seeking for long battery life.

**bbswitch:**
Works quite nicely, but sometimes messes up the NVidia card when rebooting the laptop. Only full power cycle will get it back.

**acpi_call:**
Switching back and forth works. NVidia card shows up in `lspci`. Not sure what that means. But also, my Logitech USB receiver for my mouse seems to stop working on intel mode. Maybe acpi_call shuts something down it is not supposed to do. So, not really an option on my box.

**none:
pci_power_control=yes
pci_reset=no
pci_remove=yes**

Seems to completely turn off the nvidia card. Switching between all three modes works nicely, but my suspend/hibernate is broken. black screen freeze when waking up.

**none:
pci_power_control=yes
pci_reset=no
pci_remove=no**

My current setting. First attempt to go to hibernate failed. Need to investigate more. But also, it seems the NVIDIA card is visible (lscpi). Does that mean, it is not powered down?

So now, what to do? I read somewhere about a laptop-compatibility list, but cannot find it anywhere. Does this list exist? If not, shall we create one in the wiki?

Is there any proper way to see if the nvidia card is sucking any power?

**Comment by DOGGO20** [comment]
seems like you havent given acpi_call a shot yet, try that maybe.

**Comment by mindrunner** [comment]
`acpi_call` makes it even worse. I updated my post above.

**Comment by DOGGO20** [comment]
try using pci_reset=hot reset or function level, hot reset fixed my resume from suspend issue with bbswitch. maybe it'll work for your problem too.

**Comment by Askannz** [comment]
Yeah none of those options are optimal, I know :confused:  and the kind of random issues you've mentioned is really what I've come to expect from laptops these days. All I can do is offer a range of options and let people pick the "less worse" one. At least Intel and Nvidia are finally standardizing that power switching crap, so hopefully things should improve on newer models from now on.

> **bbswitch:**
> Works quite nicely, but sometimes messes up the NVidia card when rebooting the laptop. Only full power cycle will get it back.

Could you elaborate on this ? Does the card not work at all after a reboot ? I mean I believe you, it's just that I've not seen that behavior before.

> But also, it seems the NVIDIA card is visible (lscpi). Does that mean, it is not powered down?

No, the card still shows up even if it's off (unless it was explicitly removed from the PCI bus).

> So now, what to do? I read somewhere about a laptop-compatibility list, but cannot find it anywhere. Does this list exist? If not, shall we create one in the wiki?

No such list exists to my knowledge, at least not for optimus-manager. It wouldn't be a bad idea to have one, though I'm not sure GitHub would be the best place for that.

> Is there any proper way to see if the nvidia card is sucking any power?

Not really, unfortunately. Some laptops have a LED indicator, but for others the surest way is to check of fast the battery charge decreases.

**Comment by mindrunner** [comment]
ThinkPad broke down.... So probably not into this issue too much anymore :(
