### ISSUE TITLE
make startup mode depend on battery/AC 

### ISSUE THREAD

**Issue by real-or-random** [Askannz/optimus-manager#168]
It would be nice to have the startup mode depend on the power status, e.g., a setting like
 - AC: nvidia
 - battery: intel

I could hack together a script for this locally but I'm willing to contribute a proper PR if there is interest in this feature. Maybe there could be simply a setting `power` that is defined as above.

**Comment by aouerfelli** [comment]
This would be pretty nice to have. I think it's better to keep the power option separate, with the defaults being `hybrid` for both `battery` and `ac`, to avoid changing the already existing default behavior.

**Comment by real-or-random** [comment]
> I'm willing to contribute a proper PR if there is interest in this feature.

Sorry, I take this back. I needed to switch to wayland (for unrelated reasons), so I'm personally not interested in this anymore, and moreover it would be hard to test for me now.

**Comment by kdhoermann** [comment]
This would be great.  I happened upon this trying to determine if it would be possible to dynamically set the startup mode by detecting a connected thunderbolt dock.  Using power status is probably a better idea.

I'm willing to help with a PR, but it will take me a while to determine what needs to happen and where.  Are there any references or similar projects I could use to help speed my understanding of how optimus-manager is working?

**Comment by aouerfelli** [comment]
I've made a PR for this at #220 if you'd like to take a look and give feedback.
