### ISSUE TITLE
Unable to switch to nvidia unless I manually remove nvidia_uvm kernel module

### ISSUE THREAD

**Issue by Fuxino** [Askannz/optimus-manager#169]
**Describe the bug**
I am unable to switch to nvidia mode, both from intel and hybrid. The problem seems related to the `nvidia_uvm` kernel module, which is loaded even in intel mode and not unloaded automatically, preventing the `nvidia` module to be unloaded.

In intel mode:
```
$lsmod | grep nvidia
nvidia_uvm           1044480  0
nvidia              19558400  1 nvidia_uvm
ipmi_msghandler        69632  2 ipmi_devintf,nvidia
```
In hybrid mode:
```
$lsmod | grep nvidia
nvidia_uvm           1044480  0
nvidia_drm             57344  2
nvidia_modeset       1126400  3 nvidia_drm
nvidia              19558400  84 nvidia_uvm,nvidia_modeset
ipmi_msghandler        69632  2 ipmi_devintf,nvidia
drm_kms_helper        212992  2 nvidia_drm,i915
drm                   516096  7 drm_kms_helper,nvidia_drm,i915
```
If I try to switch from intel or hybrid to nvidia, I always end up back in intel mode. If I boot in nvidia mode and try to switch to hybrid, I end up in intel mode instead. I'm then unable to switch back to nvidia. But I can successfully switch to nvidia mode if I manually run `modprobe -r nvidia_uvm nvidia` first.

**System info**
- Distribution:  Arch Linux
- Desktop Manager: None, I use Openbox as Window Manager
- Display Manager: LightDM
- I'm using the latest stable release (i.e. 1.2.2)

**Logs**
[boot_setup.log](https://github.com/Askannz/optimus-manager/files/3775776/boot_setup.log)
[gpu_setup.log](https://github.com/Askannz/optimus-manager/files/3775777/gpu_setup.log)
[prime_setup.log](https://github.com/Askannz/optimus-manager/files/3775778/prime_setup.log)

**Comment by Mario156090** [comment]
After Xorg server update I have a similar problem, I can't change to nvidia mode. When I set nvidia this change to hybrid. :/

**Comment by TheodoreT** [comment]
this is already reported at #147

**Comment by Askannz** [comment]
Closing as a duplicate.
