### ISSUE TITLE
Can't set fan speed in hybrid mode

### ISSUE THREAD

**Issue by chabad360** [Askannz/optimus-manager#173]
**Describe the bug**
When using the regular NVIDIA mode `"coolbits" "28"` is set. However, when running in Hybrid mode, it's not, hence I can't set any custom fan settings.

**System info**

| Property | Value |
| :---------- | :------ |
| `Uname` | `Linux MendelsLaptop 5.3.7-1-ck #1 SMP PREEMPT @1572199490 x86_64 GNU/Linux` |
| CPU | Intel i7-8750H (12)
| iGPU | Intel UHD Graphics 630 |
| dGPU | NVIDIA GeForce RTX 2060 Mobile |

**Comment by blmhemu** [comment]
Hey ! Please go through https://wiki.archlinux.org/index.php/Fan_speed_control

**Comment by chabad360** [comment]
my nvidia card's fans can be controlled through Gwe (GreenWithEnvy)
and require `coolbits` to be set, which it doesn't seem to be...

On 11/13/19, Hemanth Bollamreddi <notifications@github.com> wrote:
> Hey ! Please go through
> https://wiki.archlinux.org/index.php/Fan_speed_control
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Askannz/optimus-manager/issues/173#issuecomment-553769392


-- 
Mendel G
chabad360@gmail.com

**Comment by Askannz** [comment]
The "Coolbits" parameter is correctly written to the Xorg config even in hybrid mode, but it seems to have no effect when the Nvidia card isn't driving the display server. I can reproduce that on my machine.

Not much I can do here, you have to take that issue to Nvidia.
