### ISSUE TITLE
Optimus Manager failed to work on update 1.2.2-2

### ISSUE THREAD

**Issue by tosziro** [Askannz/optimus-manager#177]
**Describe the bug**
Optimus Manager failed to work on update 1.2.2-2

**System info**
Please include :
![Zrzut ekranu z 2019-11-15 18-12-33](https://user-images.githubusercontent.com/41963712/68961955-ca322800-07d3-11ea-9755-7dfab3f3bbc7.png)

- Manjaro Linux
- Gnome
- Matebook 13
- 1.2.2-2

Sugested comand not help.

**Comment by CZwatermelon** [comment]
I removed it and installed again, then it worked.

**Comment by Askannz** [comment]
See https://github.com/Askannz/optimus-manager/issues/175.
