### ISSUE TITLE
[Request] thinkfan nv_thermal compatibility

### ISSUE THREAD

**Issue by Nitrooo** [Askannz/optimus-manager#178]
I use [thinkfan](https://github.com/vmatare/thinkfan) on my ThinkPad. You can configure it to read the NVIDIA GPU temperature using the `nv_thermal` entry in its config file. The problem is that `optimus-manager` doesn't work properly with that configuration because it can't unload the `nvidia` module when `thinkfan` is running in that mode. I would need two scripts like `/etc/optimus-manager/nvidia-enable.sh` and `/etc/optimus-manager/nvidia-disable.sh`, but **prior to disabling** and **after enabling** the nvidia module (switch from/to nvidia AND hybrid), to reload `thinkfan` with the proper configuration (with or without the `nv_thermal` entry).

Can you add such additional scripts? What could I do otherwise?

**Comment by nwildner** [comment]
Hello @Nitrooo .

While we would love to see a feature that would integrate `thinkfan` with `optimus-manager` but I think this would be better suited for thinkfan to deal with, and not "hold" the module making the unload operation to fail, the same way there is a issue on that repo to deal with the fact hosts can miss one GPU that is being pci disabled for power 

-  [Failed to initialize NVML driver. If gpu is disabled](https://github.com/vmatare/thinkfan/issues/237)

Also, this case is really a corner-case for `optimus-manager` and it will require someone with a Thinkpad laptop to develop it so, while this community is open for pull requests that would implement those `nvidia` module load/unload hooks, we'll keep this case closed until someone comes with a PR to implement this.

We suggest you to also open a case on thinkfan repo for them to create a mechanism that `nv_thermal` will not hold module unload and deal with the fact that this module might be missing, specially on laptop environments.

Have a nice week ahead.
