### ISSUE TITLE
Login loop

### ISSUE THREAD

**Issue by JARA99** [Askannz/optimus-manager#180]
**Issue**
When I switch from intel to nvidia, it appears the login screen, I put my password and login, and then, the login screen appears again, it continues to the infinite unless I change the session to a Wayland, it let me login but it does it with the intel drivers.

**System info**
 - Manjaro
 - Gnome
 - gdm-prime
 - Dell G5 15
 - Optimus Manager (Client) version 1.2.2

**Logs**

[prime_setup.log](https://github.com/Askannz/optimus-manager/files/3881649/prime_setup.log)
[gpu_setup.log](https://github.com/Askannz/optimus-manager/files/3881650/gpu_setup.log)
[boot_setup.log](https://github.com/Askannz/optimus-manager/files/3881651/boot_setup.log)

**Comment by Askannz** [comment]
Late reply, but
```
Failed to execute 'modprobe nvidia NVreg_UsePageAttributeTable=1' : modprobe: ERROR: could not insert 'nvidia': Invalid argument
```
Looks like your nvidia drivers were not built for the current kernel. This isn't an optimus-manager bug.

**Comment by JARA99** [comment]
**Thanks for the answer** 

Thanks, but what should I do? Downgrade my Kernel? I am new on Linux, I don't what to keep a Windows partition but I really what to get my Nvidia card working on Linux before I uninstall windows.

**Comment by JARA99** [comment]
**Thank you!!!!** 

Finally I can use the Nvidia graphics card! You give me an idea, I uninstall the Nvidia driver installed by Manjaro and download the driver directly from nvidia page, install it and... that was all!  Optimus manager working!

**Comment by Askannz** [comment]
You're welcome, but I wouldn't recommend installing drivers straight from Nvidia's website, because it creates files that aren't tracked by the package manager and can cause file conflicts later. Also, it's going to break at the next kernel upgrade unless they have been installed with DKMS (maybe they are, I don't remember).

You should use Manjaro's built-in MHWD tool, or install `nvidia-dkms` if you have a custom kernel.

**Comment by JARA99** [comment]
When I install the drivers with the Manjaro MHWD tool, it doesn't work, I am not shure why, but the best answer was yours, the driver installed is not for my Kernel... 

I don't know how to install the driver via nvidia-dkms.

Thanks
