### ISSUE TITLE
[Question] Run an application with specified GPU on Hybrid Mode

### ISSUE THREAD

**Issue by Zamolskis** [Askannz/optimus-manager#183]
Hello,

Pretty much the question:
Is it possible to define for example, that on Hybrid mode I want to run Firefox using NVIDIA GPU?

Thank you!

**Comment by DOGGO20** [comment]
http://download.nvidia.com/XFree86/Linux-x86_64/440.26/README/primerenderoffload.html

**Comment by Zamolskis** [comment]
> http://download.nvidia.com/XFree86/Linux-x86_64/440.26/README/primerenderoffload.html

I've tried using the " __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME="nvidia" __VK_LAYER_NV_optimus="NVIDIA_only" firefox" but it still uses the INTEL one, I've checked it through about:support

**Comment by Askannz** [comment]
Updated the wiki with a [dedicated page](https://github.com/Askannz/optimus-manager/wiki/Nvidia-GPU-offloading-for-%22hybrid%22-mode) on GPU offloading. That was long overdue, I was waiting for a compatible Xorg server version to make its way into the stable repos, then kinda forgot about it :upside_down_face:

**Comment by bratekarate** [comment]
Sooo...firefox does not support this? Issue poster mentioned it but it was not addressed.

**Comment by kivancyuksel** [comment]
This doesn't work for me.

`prime-run firefox` doesn't start firefox with nvidia. Do you know what might be the problem?
