### ISSUE TITLE
--temp-config doesn't work with relative path.

### ISSUE THREAD

**Issue by mohsen-mohammadi** [Askannz/optimus-manager#184]
I was trying to use temporary configs to find out the power management solution that would work on my laptop and I kept failing. After consulting the `/var/log/optimus-manager` it turns out that optimus-manager is not able to locate my temporary config file. I could solve this by providing an absolute path instead of just providing the temporary config file name in my working directory.

**Comment by Askannz** [comment]
Fixed, thanks.
