### ISSUE TITLE
Kodi and Brave crashing when switched to Nvidia graphics

### ISSUE THREAD

**Issue by Lampwick** [Askannz/optimus-manager#186]
When switched to Nvidia Kodi and Brave crash before opening. They open fine with intel graphics set and no other graphical applications seem to be effected.

**System info**
Please include :
- Distribution: Manjaro Gnome Edition
- Desktop manager: Gnome
- Display manager: GDM-prime
- Kernel: 5.3.12-1
- Nvidia Driver: 440.31-4
- Laptop model: Xiaomi Notebook Air 13 (2016)
- Graphics Card: GeForce 940MX
- The version of optimus-manager you are using : 1.2.2-2

**Logs**
[kodi_crashlog-20191209_232326.log](https://github.com/Askannz/optimus-manager/files/3943550/kodi_crashlog-20191209_232326.log)

[boot_setup.log](https://github.com/Askannz/optimus-manager/files/3943542/boot_setup.log)
[gpu_setup.log](https://github.com/Askannz/optimus-manager/files/3943543/gpu_setup.log)
[prime_setup.log](https://github.com/Askannz/optimus-manager/files/3943544/prime_setup.log)

**Comment by Askannz** [comment]
Sorry, not much I can do here. If applications crash with a specific video driver, that's outside of the control of optimus-manager (unless you can confirm that this does not happen without optimus-manager, and with a manually hardcoded nvidia config).

Maybe see if you can disable hardware acceleration for those programs ; Manjaro and Chromium have similar stability issues with Nvidia.
