### ISSUE TITLE
Support for offloading graphics display with RandR 1.4?

### ISSUE THREAD

**Issue by wizonesolutions** [Askannz/optimus-manager#187]
The NVIDIA 440 drivers apparently now allow driving a monitor with the NVIDIA card and doing the rest with the Intel card (unless the environment variables are passed, etc.)

It is detailed in http://us.download.nvidia.com/XFree86/Linux-x86_64/440.36/README/randr14.html

I'm wondering if optimus-manager plans to have support for this? It would be handy to be able to just leave my system in `hybrid` but have the monitor work when I'm at home. On Linux, I basically just use the NVIDIA card for my external monitor anyway.

**Comment by Askannz** [comment]
I think you got it backwards. This page says :

> This can be used on Optimus-based laptops to display a desktop rendered by an NVIDIA GPU on a screen connected to another graphics device, such as an Intel integrated graphics device or a USB-to-VGA adapter.

This extension allows displaying to the Intel GPU while running on the Nvidia one, but unfortunately the other way around isn't possible yet. It would require Nvidia to support Reverse PRIME, which they don't currently do.

**Comment by wizonesolutions** [comment]
Ah, I see. Then that wouldn't really offer any benefits for most.
