### ISSUE TITLE
issues with power on update drivers and kernel 

### ISSUE THREAD

**Issue by cyrstem** [Askannz/optimus-manager#188]
hello so 
 i just recently update   my system and  on my previews configuration 
 i had this setting  and on switching it work perfectly 
im on a razer blade 15  2018 base  does some one has this issue

**Comment by cyrstem** [comment]
i try to reinstall optimus- manager to see if this can fix it  but now i have to issues
poping up 

ERROR : error parsing config file /var/lib/optimus-manag>
 ERROR : cannot run /etc/optimus-manager/nvidia-enable.sh>


journalctl -u optimus-manager.service -b0
-- Logs begin at Mon 2019-10-07 14:16:10 -05, end at Fri 2019-12-20 11:14:11 -05. --
dic 20 10:55:01 n0is3 systemd[1]: Starting Optimus Manager Commands Daemon...
dic 20 10:55:01 n0is3 prime-switch-boot[722]: 2019-12-20 10:55:01 AM -0500 ====================
dic 20 10:55:01 n0is3 prime-switch-boot[722]: Optimus Manager (Setup script) version 1.2.2
dic 20 10:55:01 n0is3 prime-switch-boot[722]: Setting up boot
dic 20 10:55:01 n0is3 prime-switch-boot[722]: Removing config copy
dic 20 10:55:01 n0is3 prime-switch-boot[722]: removing last acpi_call state (if any)
dic 20 10:55:01 n0is3 prime-switch-boot[722]: Copying user config
dic 20 10:55:01 n0is3 prime-switch-boot[722]: Cleaning up leftover Xorg conf
dic 20 10:55:01 n0is3 prime-switch-boot[722]: Removed /etc/X11/xorg.conf.d/10-optimus-manager.conf
dic 20 10:55:01 n0is3 prime-switch-boot[722]: Loading config
dic 20 10:55:01 n0is3 prime-switch-boot[722]: ERROR : error parsing config file /var/lib/optimus-manag>
dic 20 10:55:01 n0is3 prime-switch-boot[722]: file: '/var/lib/optimus-manager/config_copy.conf', line:>
dic 20 10:55:01 n0is3 prime-switch-boot[722]: 'Section "Device"\n'
dic 20 10:55:01 n0is3 prime-switch-boot[722]: Reading startup mode
dic 20 10:55:01 n0is3 prime-switch-boot[722]: No kernel parameter set for startup, reading from file
dic 20 10:55:01 n0is3 prime-switch-boot[722]: Startup mode is : intel
dic 20 10:55:01 n0is3 prime-switch-boot[722]: Writing startup mode to requested GPU mode
dic 20 10:55:01 n0is3 prime-switch-boot[722]: Writing requested mode
dic 20 10:55:01 n0is3 prime-switch-boot[722]: Initial GPU setup
dic 20 10:55:01 n0is3 prime-switch-boot[722]: Checking for GDM display servers
dic 20 10:55:01 n0is3 prime-switch-boot[722]: Available kernel modules : ['nouveau', 'bbswitch', 'acpi>
dic 20 10:55:01 n0is3 prime-switch-boot[722]: Setting up base state
dic 20 10:55:01 n0is3 prime-switch-boot[722]: Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvid>
dic 20 10:55:01 n0is3 prime-switch-boot[722]: Unloading modules ['nouveau'] (if loaded)
dic 20 10:55:01 n0is3 prime-switch-boot[722]: Running /etc/optimus-manager/nvidia-enable.sh
dic 20 10:55:01 n0is3 prime-switch-boot[722]: ERROR : cannot run /etc/optimus-manager/nvidia-enable.sh>
dic 20 10:55:01 n0is3 prime-switch-boot[722]: Unloading modules ['bbswitch'] (if loaded)
dic 20 10:55:01 n0is3 prime-switch-boot[722]: Setting up Intel state
dic 20 10:55:01 n0is3 prime-switch-boot[722]: Running /etc/optimus-manager/nvidia-disable.sh
dic 20 10:55:01 n0is3 prime-switch-boot[722]: ERROR : cannot run /etc/optimus-manager/nvidia-disable.s>
dic 20 10:55:01 n0is3 prime-switch-boot[722]: Loaded extra Intel Xorg options (0 lines)
dic 20 10:55:01 n0is3 prime-switch-boot[722]: Loaded extra Nvidia Xorg options (0 lines)
dic 20 10:55:01 n0is3 prime-switch-boot[722]: Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf
dic 20 10:55:01 n0is3 systemd[1]: Started Optimus Manager Commands Daemon.
dic 20 10:55:02 n0is3 python3[836]: Optimus Manager (Daemon) version 1.2.2
dic 20 10:55:02 n0is3 python3[836]: Automatic log cropping
dic 20 10:55:02 n0is3 python3[836]: Opening UNIX socket
dic 20 10:55:02 n0is3 python3[836]: Awaiting commands


any idea why

**Comment by Askannz** [comment]
You're going to have to be more specific. What is the issue exactly ?

Also, please post _all_ the logs from `/var/log/optimus-manager/`, in pastebins or attached files.

**Comment by cyrstem** [comment]
sure the the issue started when i update to the new kernel and everything else got updated including optimus swtch  since then 
 i can't switch from intel to nvidia  if i add  (this used to work before i updated everything )
it hangs on the login screen

```
[optimus]
switching=bbswitch
pci_power_control=no
pci_remove=no
pci_reset=no
```
 if i dont add anything i can switch

**Comment by Askannz** [comment]
If you are still around and want help with this, _please_ post logs and system info. I can't do much without that.
