### ISSUE TITLE
Boot blocked after installing optimus-manager

### ISSUE THREAD

**Issue by DjebbZ** [Askannz/optimus-manager#189]
**Describe the bug**
After installing optimus-manager, rebooting the laptop is stucked before the login page. I had to mask the service in the boot parameter to recover.

**System info**
OS: Arch Linux x86_64
Laptop: Alienware 13 R3 1.7.0
Kernel: 5.4.5-arch1-1
Resolution: 2560x1440 (laptop), 3840x1600 (external)
WM: i3
Desktop: none
Display manager: none, just using startx
GPU: NVIDIA GeForce GTX 1060 Mobile
GPU: Intel HD Graphics 630
Memory: 1979MiB / 31988MiB
Optimus Manager (Client) version 1.2.2 (optimus-manager stable)

**Logs**
Since I had mask the service to be able to boot, the optimus-manager log file is quite short.

```
2019-12-20 02:23:43 PM +0100 ====================

Optimus Manager (Setup script) version 1.2.2
Setting up PRIME
Checking status of optimus-manager.service
ERROR : the optimus-manager service is not running. Aborting.
```

Here's the output of `journalctl -k -b-1` (logs of the previous boot, the one that failed) https://pastebin.com/TUkhwrwp

**Installation**
I installed it from the AUR, then installed `bbswitch`, configured optimus-manager like the following:

```
[optimus]
switching=bbswitch
```

I also removed useless lines from my `~/.xinitrc` related to setting up optimus/nvidia (they were plain wrong), then rebooted. The problem started at this moment.

Thanks in advance !

**Comment by DjebbZ** [comment]
I forgot to mention that optimus-manager seems to have managed to switch to intel mode:

```
> glxinfo | rg -i "opengl renderer"
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2)
> optimus-manager --print-mode
Current GPU mode : intel
```

I also remember that before reboot, `optimus-manager --print-mode` displayed that the current mode/gpu was nvidia and the next boot will be using intel. I don't remember the exact phrasing but there were 2 lines mentioning intel : one talking about the next "requested" mode, and one about just the next mode (sorry this is from memory).

**Comment by DjebbZ** [comment]
I've managed to fix the boot problem by setting `switching=none` and using `pci_power_control=yes` and `pci_remove=yes`. I still have a few problems though:

1. I looked at the log after hitting successfully and it seems `pci_power_control` is useless when `pci_remove` is used. I'm writing from mobile so I don't have access to the logs now but will happily provide it if necessary.
2. I see no improvement of battery life based on `acpi -b` 😔
3. I may have setup Optimus manager wrong since I haven't used the scripts `/usr/bin/prime-offload` and `/usr/bin/prime-switch` since I have no idea where/when to call them. I think ~/.xinitrc is the place for when X starts, but no idea where to put the switch script since I don't stop X, just power off or reboot.

I'll try other power management methods as described in the wiki in the meantime, but I'd still like help especially regarding my last point.

**Comment by Askannz** [comment]
Sorry for the late reply.

The symptoms you're describing when bbswitch is enabled sound like the classic case of ACPI lockup. In that case, there's a chance power management may still work with the proper kernel options. Have you followed all of the [Wiki instructions](https://github.com/Askannz/optimus-manager/wiki/A-guide--to-power-management-options#configuration-3--bbswitch) ?

Unfortunately it may also be that your laptop is one of the troublesome models with no power management support in Linux.

> I may have setup Optimus manager wrong since I haven't used the scripts /usr/bin/prime-offload and /usr/bin/prime-switch since I have no idea where/when to call them. I think ~/.xinitrc is the place for when X starts, but no idea where to put the switch script since I don't stop X, just power off or reboot.

Yes, `/usr/bin/prime-offload` should be put in .xinitrc . As for ` /usr/bin/prime-switch`, it should be fine to leave it alone as long as you don't switch GPU on the fly and restart the X server.

**Comment by DjebbZ** [comment]
Sorry for the long silence, I changed laptop and the new one only has integrated graphics. Thanks for the help.
