### ISSUE TITLE
Refuses to load Nvidia module

### ISSUE THREAD

**Issue by BushMan01** [Askannz/optimus-manager#190]
**Describe the bug**
Seems to work fine in Intel mode. I boot into X (I use i3-gaps), run "optimus-manager --switch nvidia", warns of lack of dm (which is fine, I ignore).
Exits to teletype.
After running "sudo prime-switch" command in tty, goes through everything just fine, (loads bbswitch and sets GPU power to ON). But then, after "Loading module nvidia", complains that

"Cannot setup GPU : kernel setup error : error running modprobe for nvidia : Failed to execute 'modprobe nvidia NVreg_UsePageAttributeTable=1' : modprobe: ERROR: could not insert 'nvidia' : No such device"

Interestingly, this problem does not occur when switching to Intel mode (I ran "optimus-manager --switch intel" followed by "sudo prime-switch" on the teletype to get back to the working Intel graphics mode).

PS: am I meant to run prime-offload after switching to Intel and booting up the X server, or is that only for switching to Nvidia graphics?

**System info**
Please include :
- Distribution: Arch Linux
- Your desktop manager (KDE, GNOME, Cinnamon...), if you have one: i3-gaps
- You display manager (SDDM, GDM, LightDM...), if you have one. If you do not know, you are probably using the one coming with your desktop manager.:N/A
- Your laptop model, if you think it could be related to the problem: Dell G3 15 with Nvidia GTX 1060 6GB mobile
- The version of optimus-manager you are using : latest stable release (optimus-manager), or the latest Git version (optimus-manager-git): latest stable release (I think)

**Logs**
If you are able to, please attach all the logs you can find in `/var/log/optimus-manager/`. *Do not directly copy paste the logs into the GitHub issue.* Join them as text files or save them to pastebins (https://pastebin.com/) and post the links here.:
https://pastebin.com/tCGKqZcT (boot_setup.log)
https://pastebin.com/ZkR3XLyY (gpu_setup.log)
https://pastebin.com/psVG34Qt (prime_setup.log)

**Comment by Askannz** [comment]
Does the problem happen if you disable everything power-management related ? I've had similar issues with bbswitch.

> PS: am I meant to run prime-offload after switching to Intel and booting up the X server, or is that only for switching to Nvidia graphics?

Currently, it's not necessary for Intel mode unless you have custom Xsetup scripts. But doesn't hurt.

**Comment by BushMan01** [comment]
Yes, it happens with everything power-switching related disabled. In fact, it was this issue that caused me to look into power-switching in the first place as I thought it might possibly help. I thought perhaps that the machine might have been confused by having two chips powered on at the same time, but that was evidently not it.

**Comment by BushMan01** [comment]
Added logs to original post.

**Comment by xonq** [comment]
using Dell G3 as well and the latest optimus-manager. Installed, enabled, and started - it doesn't change to nvidia after running `optimus-manager --switch nvidia` and won't start nvidia if I set as default as well. Tried changing switch from bbswitch to nouveau and blacklisting bbswitch, but got black screen after boot

**Comment by BushMan01** [comment]
> using Dell G3 as well and the latest optimus-manager. Installed, enabled, and started - it doesn't change to nvidia after running `optimus-manager --switch nvidia` and won't start nvidia if I set as default as well. Tried changing switch from bbswitch to nouveau and blacklisting bbswitch, but got black screen after boot
> EDIT: IT WORKS IF I SET STARTUP MODE TO NVIDIA. I CAN SWITCH TO INTEL, BUT NOT BACK TO NVIDIA UNLESS I RESTART THE SYSTEM.
> 
> ```
> 
> 2020-01-29 12:15:34 PM -0500 ==================== 
> 
> Optimus Manager (Setup script) version 1.2.2
> Setting up boot
> Removing config copy
> removing last acpi_call state (if any)
> Copying user config
> Cleaning up leftover Xorg conf
> Removed /etc/X11/xorg.conf.d/10-optimus-manager.conf
> Loading config
> Reading startup mode
> No kernel parameter set for startup, reading from file
> Startup mode is : intel
> Writing startup mode to requested GPU mode
> Writing requested mode
> Initial GPU setup
> Checking for GDM display servers
> Available kernel modules : ['nouveau', 'bbswitch', 'nvidia', 'nvidia_drm', 'nvidia_modeset']
> Setting up base state
> Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia'] (if loaded)
> Unloading modules ['nouveau'] (if loaded)
> Loading module bbswitch
> Setting GPU power to ON via bbswitch
> Loading module bbswitch
> Setting up Intel state
> Setting GPU power to OFF via bbswitch
> Loaded extra Intel Xorg options (0 lines)
> Loaded extra Nvidia Xorg options (0 lines)
> Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf
> ```

I wonder what is different between our laptops that causes yours to work at startup? Mine does not (just tried it)

**Comment by BushMan01** [comment]
Update: I had a look at var/log/Xorg.0.log
![15809287578276703250858119133402](https://user-images.githubusercontent.com/52748205/73873134-ec729980-4848-11ea-8045-933dd426e40c.jpg)

Seems there is something wrong with acpi

**Comment by BushMan01** [comment]
I finally was able to fix the issue. I had to go into the black tty and use my shortcut for terminal emulator and run prime-offload. I can't remember how I fixed the problem with the Nvidia module itself.

**Comment by xonq** [comment]
> I wonder what is different between our laptops that causes yours to work at startup? Mine does not (just tried it)

I have one of the early versions and a 1050M graphics card.

**Comment by BushMan01** [comment]
> > I wonder what is different between our laptops that causes yours to work at startup? Mine does not (just tried it)
> 
> I have one of the early versions and a 1050M graphics card.

Do you use a display manager? My problem in the end was that I do not.

**Comment by xonq** [comment]
> > > I wonder what is different between our laptops that causes yours to work at startup? Mine does not (just tried it)
> > 
> > 
> > I have one of the early versions and a 1050M graphics card.
> 
> Do you use a display manager? My problem in the end was that I do not.

Yes, I do. Good to know - I had problems initially installing arch, configuring the graphics card, and then configuring optimus. I had to try like 3 different installs and tried to document it all but it was too convoluted to make sense of.

**Comment by BushMan01** [comment]
> 
> Yes, I do. Good to know - I had problems initially installing arch, configuring the graphics card, and then configuring optimus. I had to try like 3 different installs and tried to document it all but it was too convoluted to make sense of.

I didn't have the foresight to document anything, but at least I only had to install once, because I just use the basic teletype login. Also, it appears my laptop also has the problem to do with only loading the Nvidia device on startup, never after. Must be something hardware specific where the Nvidia card turns off and won't turn on.

**Comment by Luc45** [comment]
I have always used only nvidia card. The integrated graphics card was always turned off in bios.

If I enable the integrated graphics card in bios and turn on the computer, the desktop environment loads fine, but running `optimus-manager --switch nvidia` doesn't work at all, even after logging out, restarting, etc.

If then I disable the integrated graphics in bios and leave only Nvidia, the desktop environment won't start at all.

I am kinda desperate for help. If I disable optimus-manager service, the desktop environment still won't go up, so I'm not sure what's going on, and whether this is related to Optimus.

I can pay someone for 1h to help me with this.
