### ISSUE TITLE
Can't uninstall optimus-manager or X won't start (black screen)

### ISSUE THREAD

**Issue by DjebbZ** [Askannz/optimus-manager#192]
**Describe the bug**
After trying several things in #189 I dediced to remove optimus-manager since this wasn't providing battery benefit for my laptop, which was the whole point of me trying it. No offense meant, it's because of combination of factors: a Pascal GPU, hardware implementation out of our control etc.
But after uninstalling it (running `optimus-manager --cleanup` before `yay -R optimus-manager`), X just won't start, I get a black screen. I had to switch to another tty and `killAll Xorg` to recover, then reinstall optimus-manager otherwise no way to start X. Unfortunaly the Xorg logs provided no help. I also tried removing every i3 plugin that displayed info in the status bar to get it in a vanilla state, same result. So I ended up reinstalling optimus-manager to be able to use my computer.

My understanding is that there's is some trace of optimus-manager left somewhere after uninstalling. Or I didn't run the provided scripts appropriately and that left the system in an inconsistent state after uninstalling.

**System info**
OS: Arch Linux x86_64
Laptop: Alienware 13 R3 1.7.0
Kernel: 5.4.5-arch1-1
No display manager (manual `startx`)
Optimus Manager (Client) version 1.2.2
WM: i3
CPU: Intel i7-7700HQ (8) @ 3.800GHz
GPU: NVIDIA GeForce GTX 1060 Mobile
GPU: Intel HD Graphics 630

**Logs**
You'll notice a lot of reboot on Saturday 21st, the day I tried a lot of power management settings *and* uninstall of optimus-manager.
https://pastebin.com/MEj1k4sr

Thanks in advance for your help!

**Comment by Askannz** [comment]
Sorry for the late reply. 

I'm a bit clueless here, there's really nothing optimus-manager could leave that could cause such issues. Maybe there was a driver update ?

I'm thinking it might be this issue : https://bbs.archlinux.org/viewtopic.php?id=251846 https://bugs.archlinux.org/task/64805

Could you post the Xorg log, just in case ?

**Comment by Artisflowing** [comment]
I think I'm having the same thing happening.
Weirdly enough I have the exact same hardware specs as @DjebbZ 
Instead of a GTX 1060 I have a 1050.

I read though the post you linked and I haven't tried anything in it but it looks promising.
