### ISSUE TITLE
SDDM scales to 100% (96 DPI) regardless of configuration

### ISSUE THREAD

**Issue by meyertime** [Askannz/optimus-manager#193]
**Describe the bug**
SDDM scaling is wrong after installing optimus-manager.  Global scaling in KDE is set to 2 due to having a 4k screen, and SDDM is configured to match with a 192 DPI.  However, after installing optimus-manager, SDDM reverts to a scale of 1 (96 DPI).

I've tracked this down to the nvidia/DPI setting in `optimus-manager.conf` having no effect.  This line:

https://github.com/Askannz/optimus-manager/blob/cd3d373bac0fd99e64e319da25a51f562f8ceca4/optimus_manager/xorg.py#L98

It always comes back with a value of `96` regardless of the configuration setting, hence why it sets the scale to that value.  I worked around it by hard-coding an empty string in the code and letting SDDM and KDE handle the scaling.

**System info**
Arch Linux, KDE, SDDM, latest stable `optimus-manager` package `1.2.2-2`, as well as `optimus-manager-qt` `1.4.5-1`.

**Logs**
Logs really weren't helpful in troubleshooting this.

**Comment by Askannz** [comment]
Possibly related to https://github.com/Askannz/optimus-manager/issues/167.

optimus-manager has to run a xrandr command to set up Prime on the laptop monitor, I'm suspecting this is what messes up custom configs. I don't know a fix for that yet, it's something I need to investigate.

**Comment by meyertime** [comment]
I removed `optimus-manager` completely in order to troubleshoot some other issues and ended up installing it again, and after that, strangely, it works fine now without my workaround.

It's most unusual since I ran into the same issue on two different laptops.  It seemed to ignore the DPI setting in `optimus-manager.conf` and that line where it reads the config would return `96` no matter what.  This issue is only related to the `xrandr` call that sets the DPI.

The only thing I can think of is that the first time I set it up I created an `optimus-manager.conf` manually before installing `optimus-manager-qt` and changing some settings through the GUI.  I had not tried to fix the scaling issue yet at that point and followed the same process on both laptops.  After removing and reinstalling `optimus-manager` and `optimus-manager-qt`, strangely, it somehow remembered my settings from before including a DPI of 192 and that seems to be taking effect now.

I'll do some more investigation on my other laptop before closing the issue.

**Comment by meyertime** [comment]
Long story short, the issue also disappeared on the other laptop after removing and reinstalling `optimus-manager` and `optimus-manager-qt`...

On that laptop, `optimus-manager` was actually broken.  When trying to switch to nvidia mode, it would just come back still in intel mode.  I couldn't really troubleshoot since it wasn't doing anything, and there was nothing in the logs.  While the engineer inside me really wanted to get to the bottom of it, the pragmatist decided to just fix it if it could be fixed.  I did the same thing as I did with the other laptop, also updating all packages in the process.  The one thing I did differently was removed `optimus-manager.conf` and started fresh, keeping the default 96 DPI setting in the GUI.  After rebooting, SDDM scaling was once again 100%.  Then I changed it to 192, rebooted, and it was scaled correctly.  Somehow it mysteriously works now.  

Sorry to be a bother.  I guess something was screwy on my end.

`Hello, IT.  Have you tried turning it off and on again?`

**Comment by stevenfang1997** [comment]
Removing and reinstalling optimus-manager and optimus-manager-qt don't work in my case, unfortunately ;(

**Comment by meyertime** [comment]
@stevenfang1997 Could you perhaps come up with some steps to reproduce?  What is your computer configuration?  Wondering what we have in common that caused it.

Also, does my first workaround work for you?  Here it is step-by-step:

1. Find and edit your local copy of `xorg.py`.  Mine was located at `/lib/python3.8/site-packages/optimus_manager/xorg.py`.
2. Find the line mentioned in the description: `dpi_str = config["nvidia"]["dpi"]`
3. Comment that line out with `#`.
4. Add a line there that sets `dpi_str = ""` to disable setting the DPI, or `dpi_str = "192"` to hard-code it to some other value.
5. Save and reboot.
6. You can also use `print()` to print arbitrary information to the log for troubleshooting.  Since this is executed during the SDDM display setup script, it will appear in the SDDM log: `journalctl -u sddm -e`

I know there's probably better ways to troubleshoot, but this is quick and dirty.  Keep in mind that updating `optimus-manager` will overwrite these changes.

**Comment by nwildner** [comment]
Cross-referencing for future use

- #208
