### ISSUE TITLE
External GPU support

### ISSUE THREAD

**Issue by mskrip** [Askannz/optimus-manager#197]
Hi, I'm running an external GPU on Arch Linux and using `optimus-manager` is a fairly straight forward setup for my requirements. It almost works out of the box. However, the generated Xorg config file is missing one option to allow the external GPU to be used. So I'd like to ask if it is somehow possible to make this change persistent between switching graphics. The option is this:

```conf
Section "Screen"
    ...
    Option "AllowExternalGpus"
EndSection
```

See: https://download.nvidia.com/XFree86/Linux-x86_64/396.51/README/egpu.html

**Comment by Askannz** [comment]
Hi,

Just to be sure, do you mean that your are using `optimus-manager` with an external GPU in place of a built-in dedicated one ?

**Comment by mskrip** [comment]
Yes, that's right.

**Comment by Askannz** [comment]
That's interesting, you're the first person to report success with such a setup.

I've added an `allow_external_gpus` setting to the config file, enabling it will add the option above to the Xorg config. It's in `optimus-manager-git`, feel free to test and report :slightly_smiling_face:

**Comment by mskrip** [comment]
I've tested it and it works as expected :wink:
