### ISSUE TITLE
My nvidia card is not fully power down in intel mode.

### ISSUE THREAD

**Issue by XRaTiX** [Askannz/optimus-manager#198]
**Describe the bug**
I think my nvidia card 1050 Ti is not fully powered down because it drains alot of batterie in intel mode and the temperature is hot like if it using the dedicated card for some reason.

I use powertop in the tab devices and it show 100% of usage the nvidia card in intel mode.
In intel mode it consumes ~700 mA (according to 'tlp-stat -b') when before i remember was consuming ~300 mA. With Hybrid mode it consumes ~900 mA and Nvidia mode ~1500 mA.

If i use nvidia-smi in intel mode it say cannot comunicate with the nvidia but it still power on i supposed..

If you need more information feel free to ask,if there is no solution not problem.

**System info**
Manjaro KDE 
SDDM
Dell Laptop 7567
Using the latest stable release 1.2.2
Kernel 5.4
Nvidia driver 440.44
I'm using bbswitch and pci_reset = no

```

$ inxi -Fxxxza --no-host
System:    Kernel: 5.4.12-1-MANJARO x86_64 bits: 64 compiler: gcc v: 9.2.0 
           parameters: BOOT_IMAGE=/boot/vmlinuz-5.4-x86_64 
           root=UUID=ed35c95e-3cc9-4279-9f3f-68b0a2ff5a85 rw apparmor=1 security=apparmor 
           udev.log_priority=3 bootsplash.bootfile=bootsplash-themes/manjaro/bootsplash 
           mitigations=off nowatchdog i915.modeset=1 nopti 
           Desktop: KDE Plasma 5.17.5 tk: Qt 5.14.0 wm: kwin_x11 dm: SDDM 
           Distro: Manjaro Linux 
Machine:   Type: Laptop System: Dell product: Inspiron 15 7000 Gaming v: N/A 
           serial: <filter> Chassis: type: 10 serial: <filter> 
           Mobo: Dell model: 0MK77P v: A00 serial: <filter> UEFI: Dell v: 1.7.0 
           date: 05/08/2018 
Battery:   ID-1: BAT0 charge: 51.7 Wh condition: 68.2/74.0 Wh (92%) volts: 12.3/11.4 
           model: SMP DELL 71JF452 type: Li-poly serial: <filter> status: Unknown 
CPU:       Topology: Quad Core model: Intel Core i5-7300HQ bits: 64 type: MCP 
           arch: Kaby Lake family: 6 model-id: 9E (158) stepping: 9 microcode: CA 
           L2 cache: 6144 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 20004 
           Speed: 2780 MHz min/max: 800/3500 MHz Core speeds (MHz): 1: 2780 2: 2859 
           3: 2741 4: 3149 
           Vulnerabilities: Type: itlb_multihit status: KVM: Vulnerable 
           Type: l1tf mitigation: PTE Inversion; VMX: vulnerable, SMT disabled 
           Type: mds status: Vulnerable; SMT disabled 
           Type: meltdown status: Vulnerable 
           Type: spec_store_bypass status: Vulnerable 
           Type: spectre_v1 status: Vulnerable: __user pointer sanitization and usercopy 
           barriers only; no swapgs barriers 
           Type: spectre_v2 status: Vulnerable, IBPB: disabled, STIBP: disabled 
           Type: tsx_async_abort status: Not affected 
Graphics:  Device-1: Intel HD Graphics 630 vendor: Dell driver: i915 v: kernel 
           bus ID: 00:02.0 chip ID: 8086:591b 
           Device-2: NVIDIA GP107M [GeForce GTX 1050 Ti Mobile] vendor: Dell 
           driver: nvidia v: 440.44 bus ID: 01:00.0 chip ID: 10de:1c8c 
           Display: x11 server: X.Org 1.20.7 driver: modesetting,nvidia 
           compositor: kwin_x11 resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 630 (Kaby Lake GT2) 
           v: 4.6 Mesa 19.3.2 compat-v: 3.0 direct render: Yes 
Audio:     Device-1: Intel CM238 HD Audio vendor: Dell driver: snd_hda_intel v: kernel 
           bus ID: 00:1f.3 chip ID: 8086:a171 
           Device-2: NVIDIA GP107GL High Definition Audio driver: snd_hda_intel v: kernel 
           bus ID: 01:00.1 chip ID: 10de:0fb9 
           Sound Server: ALSA v: k5.4.12-1-MANJARO 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Dell 
           driver: r8169 v: kernel port: d000 bus ID: 02:00.0 chip ID: 10ec:8168 
           IF: enp2s0 state: down mac: <filter> 
           Device-2: Intel Wireless 3165 driver: iwlwifi v: kernel port: d000 
           bus ID: 03:00.0 chip ID: 8086:3165 
           IF: wlp3s0 state: up mac: <filter> 
Drives:    Local Storage: total: 2.00 TiB used: 940.70 GiB (46.0%) 
           ID-1: /dev/sda vendor: Western Digital model: WDS100T2B0B-00YS70 
           size: 931.51 GiB block size: physical: 512 B logical: 512 B speed: 6.0 Gb/s 
           serial: <filter> rev: 00WD scheme: GPT 
           ID-2: /dev/sdb type: USB vendor: Seagate model: ST1000LM024 HN-M101MBB 
           size: 931.51 GiB block size: physical: 512 B logical: 512 B rotation: 5400 rpm 
           serial: <filter> scheme: MBR 
           ID-3: /dev/sdc type: USB vendor: Generic model: SD MMC MS PRO size: 183.35 GiB 
           block size: physical: 512 B logical: 512 B serial: <filter> rev: 1.00 
           scheme: MBR 
RAID:      Hardware-1: Intel 82801 Mobile SATA Controller [RAID mode] driver: ahci v: 3.0 
           port: f060 bus ID: 00:17.0 chip ID: 8086.282a rev: 31 
Partition: ID-1: / raw size: 830.65 GiB size: 816.61 GiB (98.31%) used: 156.58 GiB (19.2%) 
           fs: ext4 dev: /dev/sda2 
Sensors:   System Temperatures: cpu: 57.0 C mobo: 47.0 C sodimm: 46.0 C 
           Fan Speeds (RPM): cpu: 0 
Info:      Processes: 238 Uptime: 1h 42m Memory: 7.65 GiB used: 1.95 GiB (25.5%) 
           Init: systemd v: 242 Compilers: gcc: 9.2.0 Shell: bash v: 5.0.11 
           running in: konsole inxi: 3.0.37 

```

Here are the logs

[gpu_setup.log](https://github.com/Askannz/optimus-manager/files/4074757/gpu_setup.log)
[boot_setup.log](https://github.com/Askannz/optimus-manager/files/4074758/boot_setup.log)
[prime_setup.log](https://github.com/Askannz/optimus-manager/files/4074759/prime_setup.log)

**Comment by DOGGO20** [comment]
Helps that we have the same laptop, so in testing, both nouveau and none work quite well. nouveau needs to be used with `nouveau.noaccel=1` and dynamically adjusts the power state of the GPU. none can be used with PCI remove and the card PM will just turn it off on battery. Though please note that i have modified my DSDT to allow _OSC and ASPM to be controlled by the kernel. So its possible that it only works like that for me because i have done that.

**Comment by XRaTiX** [comment]
> Helps that we have the same laptop, so in testing, both nouveau and none work quite well. nouveau needs to be used with `nouveau.noaccel=1` and PCI Power control and dynamically adjusts the power state of the GPU. none can be used with PCI remove and PCI power control and the card PM will just turn it off on battery. Though please note that i have modified my DSDT to allow _OSC and ASPM to be controlled by the kernel. So its possible that it only works like that for me because i have done that.
> 
> BTW, update your BIOS. https://www.dell.com/support/home/us/en/19/product-support/product/inspiron-15-7567-laptop/drivers

Interesting,how do you modified the DSDT? Any particular tutorial?

I try `nouveau` with settings you said but it just freeze my system after a period of time,`none` generates more energy and more heat so don't use for me.

**Comment by DOGGO20** [comment]
> > Helps that we have the same laptop, so in testing, both nouveau and none work quite well. nouveau needs to be used with `nouveau.noaccel=1` and PCI Power control and dynamically adjusts the power state of the GPU. none can be used with PCI remove and PCI power control and the card PM will just turn it off on battery. Though please note that i have modified my DSDT to allow _OSC and ASPM to be controlled by the kernel. So its possible that it only works like that for me because i have done that.
> > BTW, update your BIOS. https://www.dell.com/support/home/us/en/19/product-support/product/inspiron-15-7567-laptop/drivers
> 
> Interesting,how do you modified the DSDT? Any particular tutorial?
> 
> I try `nouveau` with settings you said but it just freeze my system after a period of time,`none` generates more energy and more heat so don't use for me.

re-read what i said...

heres the DSDT guide. good luck.

This is a guide for how to fix ASPM on systems where these lines appear in kernel log:
 ACPI FADT declares the system doesn't support PCIe ASPM, so disable it
_OSC failed (AE_ERROR); disabling ASPM

Required: acpica

1.) Extract DSDT, FACP ACPI tables (as root(su)): # cat /sys/firmware/acpi/tables/FACP > facp.dat

2.) Decompile: iasl -d facp.dat iasl -d dsdt.dat

FACP:

3.) in FACP at this line:
                 PCIe ASPM Not Supported (V4) : 1
 replace the 1 with 0 and save the file.

4.) Increase OEM version or otherwise the kernel will not apply the modified ACPI table. 
For example: 
[018h 0024   4]                 Oem Revision : 01072009
 change 01072009 to 01072010 

DSDT:

5.) in DSDT Replace all occurences of NEXP with One

6.) Increase OEM version or otherwise the kernel will not apply the modified ACPI table.
For example: 
DefinitionBlock ("", "DSDT", 2, "DELL  ", "CBX3   ", 0x01072009)
 change 0x01072009 to 0x01072010 

7.) Compile fixed code: iasl -tc dsdt.dsl (Might want to try option -ic for C include file to insert into kernel source) 

8.) There are 2 methods to use custom ACPI tables.
        - creating a CPIO archive that is loaded by the bootloader
        - compiling it into the kernel

9.) Continue here for details on both methods: https://wiki.archlinux.org/index.php/DSDT#Using_a_CPIO_archive
