### ISSUE TITLE
Cannot switch to Nvidia

### ISSUE THREAD

**Issue by nikola3244** [Askannz/optimus-manager#2]
Hi, this looks like a great tool, but I'm having trouble with setting it up on my laptop (Toshiba C55-C-1LP).

I've tried to debug it but I have no clue what to do next.

Tried to set DRI to 2, and modeset to no, but it did not make a difference.
Tried to use "bbswitch" in "switching", but still no difference.

I'm using SDDM with i3, but I can't even get to the login screen when Nvidia is selected. Intel works just fine.

Bumblebee is disabled, and system is rebooted, and as a proof that Bumblebee is not active: `/proc/acpi/bbswitch` does not exist.

Also, I've tried adding `exec /usr/bin/optimus-manager_Xsetup` to `~/.xinitrc`, but no help. I've tried manually to play with `xrandr`, but I can't connect to the display when SDDM is active. (I could connect to it by doing `export DISPLAY=:0 xrandr`, when i3 is launched directly (and I did change `login_manager` to blank when I tested i3 without SDDM))

Specs:
```
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)
09:00.0 3D controller: NVIDIA Corporation GK208BM [GeForce 920M] (rev a1)
```

Logs:
[optimus-manager.service-journalctl.log](https://github.com/Askannz/optimus-manager/files/2592283/optimus-manager.service-journalctl.log)
[Xorg.0.log](https://github.com/Askannz/optimus-manager/files/2592284/Xorg.0.log)

I'm happy to provide any other logs or information. :slightly_smiling_face:

**Comment by kuroni** [comment]
Maybe this is due to your `bbswitch` module not loaded when booted. Try adding `bbswitch` to `/etc/modules-load.d/bbswitch.conf`, add `options bbswitch load_state=0 unload_state=1` to `/etc/modprobe.d/bbswitch.conf`, and rebuild the initramfs by `mkinitcpio -P`.

**Comment by Askannz** [comment]
@kuroni I would advise against loading bbswitch that way. optimus-manager is supposed to take care of that, and adding bbswitch at boot time would conflict with it.

@nikola3244 I just ran a quick test on my machine and it seems PRIME is broken with SDDM right now. This is why you do not see the login screen in Nvidia mode, and only a black screen.

However, the login window is still there (even if you can't see it). You should be able to enter your password and log in. Alternatively, you can try plugging in an external monitor or setup auto-login.

I'll investigating the PRIME issue and let you know.

**Comment by Askannz** [comment]
So, there were actually two problems :

- My display setup script for SDDM was broken (https://github.com/Askannz/optimus-manager/commit/958abb23e5b18e77b74da3a62a5749ea9fc5a947). I don't know how I missed that, and it's surprising that almost everything was working fine without it. It seems like the X server is smart enough to configure PRIME on its own nowadays, and only the login managers need the script.

- SDDM seems to ignore configuration files in /etc/sddm.conf.d/ and /usr/lib/sddm/sddm.conf.d/, despite what the man pages say. Could be a bug on their end. As a workaround, I instead rewrite the default setup script at /usr/share/sddm/scripts/Xsetup (https://github.com/Askannz/optimus-manager/commit/3779bf83df9f057b1f61b863304e8440f83c9956). I don't really like that (you are not supposed to write stuff to /usr/share/), but it works.

I am going to push a new release in a minute, please let me know if it fixes your problem.

**Comment by nikola3244** [comment]
It works! 

Thank you. :heart:
