### ISSUE TITLE
Checking Manjaro install and configure guide

### ISSUE THREAD

**Issue by michaldybczak** [Askannz/optimus-manager#200]
This isn't an issue thread, so you can close it at any time.

I just wanted to thank you for this wonderful piece of software! Many months ago I wrote a guide on Manjaro forum to install and configure optimus-manager to help users start with it and spread the adoption.

In the past there were some troubles, but once this SDDM issue was resolved, I noticed a bigger success rate and more interest in optimus-manager. With time optimus-manager and optimus-switch established as two major and often used solutions on Manjaro.
I oftentimes get notified when users link or use my guide. I can see if they succeeded or had issues and very often it works without problems. If there are issues, they are usually resolved. Of course, there are always some rare situations where it won't work for some reason, but luckily, with two major choices it's very likely one or the other will work in the end.

I thought, you may look at my guide and if you have something to add or correct, I gladly improve it.

https://forum.manjaro.org/t/guide-install-and-configure-optimus-manager-for-hybrid-gpu-setups-intel-nvidia/92196

Once again, thank you!

**Comment by pietrondo** [comment]
good guide.. But I don't understand about how run steam in hybrid mode with nvidia gpu.
thx

**Comment by michaldybczak** [comment]
I just modified launcher's command:

`STEAM_RUNTIME_HEAVY=1  __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia steam`

![Screenshot-2020-01-25-18-06-11](https://user-images.githubusercontent.com/10132958/73124608-785d0980-3f9d-11ea-9999-377bfca99dc3.png)

Of course this makes Steam not launch in Intel mode, so you may want to create a second launcher (.desktop file) called Steam-Hybrid or something like that. Or just launch steam via terminal, which is also a good option since it's not often needed to use it on Intel (unless you want to check library or buy something).

**Comment by Askannz** [comment]
I just added a [wiki page](https://github.com/Askannz/optimus-manager/wiki/Nvidia-GPU-offloading-for-%22hybrid%22-mode) about how to set up GPU offloading. Feel free to comment.

**Comment by michaldybczak** [comment]
I just read the entry and it's great! Very precise, clear and helpful. I'll link to it in my guide.
Perhaps one small thing is good to mention, that apps/games using Vulkan (natively or through Proton) will use automatically Nvidia as well, even without mentioned environmental variables.

So far my tests show ca. 10-20% less power consumption than in Nvidia mode (when Nvidia is not used of course), but it's still very high compared to Intel which can have nearly twice longer battery life compared to Nvidia. It looks my hardware is not modern enough (CPU of 6th gen, and GTX 970M, so clearly too old) for this complete turning off of Nvidia. Still, technology is new so maybe it a couple of years it will work better and with more common, newer hardware, this may become a standard mode. Till then secondary monitors should work with it, I hope. The feature is already requested and acknowledged, but when they will add it is unknown.

I'll check the configurations more carefully and see what I can be done. Currently, I'm using Intel on modeseting and nouveau. Bumblebee worked also in the past, so I have some options to check.

Thank you :)

**Comment by Askannz** [comment]
> Perhaps one small thing is good to mention, that apps/games using Vulkan (natively or through Proton) will use automatically Nvidia as well, even without mentioned environmental variables.

They do if Nvidia is the only Vulkan driver installed. However if you have the vulkan-intel package as well, some games will try to use the iGPU first. That's why it's safer to set all the env variables and make sure Nvidia is selected in priority.
