### ISSUE TITLE
Config Files in Power Management Guide do not exist (according to Terminal and File Manager)

### ISSUE THREAD

**Issue by StrychnosXCVII** [Askannz/optimus-manager#202]
The only files in the etc/optimus-manager/ directory are: 
xorg-intel.conf  
xorg-nvidia.conf  
xsetup-intel.sh  
xsetup-nvidia.sh
No optimus-manager.conf file as referenced in the guide.
I have no idea if I've done something wrong, something is wrong with my installation, or the guide is outdated.
I believe I'm running Version 1.2.2 of optimus manager and Manjaro XFCE 18.1.5, if that affects anything.
I'm a clueless noob so please break any instructions down really simply. Thanks in advance.

**Comment by Askannz** [comment]
As per the README :

>  edit the config file at /etc/optimus-manager/optimus-manager.conf **(or create it if it does not exist)**.

:wink:
