### ISSUE TITLE
Color depth

### ISSUE THREAD

**Issue by Filip-Sutkowy** [Askannz/optimus-manager#203]
It will be nice, if we could change color depth in easy way. I open this issue, because I feel big diffrence when I boot Windows and everything looks just better because of better colors.

**Comment by Askannz** [comment]
There could be an option in optimus-manager to specify the `DefaultDepth` parameter in the Xorg config file, I guess. But are you sure that's the issue in your case ?

If the monitor is plugged into the Nvidia card, you can configure its color parameters with this control panel :

![nvidia_monitor](https://user-images.githubusercontent.com/9202863/73240490-31685180-41f3-11ea-8a15-9986927851c0.png)

**Comment by Filip-Sutkowy** [comment]
I do not have following option

![image](https://user-images.githubusercontent.com/24491499/73362525-4acad580-42a7-11ea-9f13-8acac1e593f2.png)

I tried to edit xorg conf files, but I'm not sure where I should put monitor configuration.

**Comment by Askannz** [comment]
Ah, right, that's only for normal monitors, your laptop screen goes through Prime, so it doesn't have the color controls.

Well, no idea then. I don't think this is a problem with optimus-manager anyways, unless you can prove that it does not happen with a manual Xorg config. If you know about some command/configuration that would improve things, feel free to re-open the issue and I'll try implementing it.
