### ISSUE TITLE
glxinfo strikes again

### ISSUE THREAD

**Issue by enigmatic-system** [Askannz/optimus-manager#204]
Hello! 

I opened a previous issue here https://github.com/Askannz/optimus-manager/issues/201

Currently...
`Error reading current mode : Cannot run glxinfo : Failed to execute 'glxinfo' : Error: unable to open display`
Still persists.

**System info**
OS - Arch Linux
Kernel - 4.19.98-1-lts
WM - Openbox
DM- Lightdm
Laptop - Clevo N855HJ
GPU - Nvidia GTX 1050
Version - Optimus Manager (Client) 1.2.2 git-version

**Logs**
[boot_setup.txt](https://github.com/Askannz/optimus-manager/files/4125705/boot_setup.txt)
[gpu_setup.txt](https://github.com/Askannz/optimus-manager/files/4125706/gpu_setup.txt)
[prime_setup.txt](https://github.com/Askannz/optimus-manager/files/4125707/prime_setup.txt)

Tried switching from “nvidia” to “nvidia-dkms” to no avail. 

Nvidia-xrun can still get glxinfo to work.

Lightdm loads when the system starts.

**Comment by enigmatic-system** [comment]
I'm new so I'm not sure if you saw the update I put on the last issue and if opening a new issue is proper etiquette.

**Comment by enigmatic-system** [comment]
Tried switching from “nvidia” to “nvidia-dkms” to no avail. 

Nvidia-xrun can still get glxinfo to work some how.

**Comment by Askannz** [comment]
Yeah it makes sense, glxinfo needs a X server to work. And optimus-manager needs glxinfo to know which GPU is currently active (I've never found a better solution).

I'll push a fix so that it at least prints a proper error instead of crashing.

**Comment by enigmatic-system** [comment]
I’ve been messing around and now I’ve gotten to similar place of https://github.com/Askannz/optimus-manager/issues/192 where startx causes a black screen when optimus manager is enabled.

My Xorg logs don’t seem to catch anything that is date relevant.

**Comment by enigmatic-system** [comment]
I’ve downgraded to nvidia-utils 440-44-1 and tried adding Option “PrimaryGPU” “yes” but now I see via the logs that OM writes to 10-optimus-manager.conf each boot cycle.

**Comment by enigmatic-system** [comment]
I’m seeing now that there is no nvidia-enable.sh in my /etc/optimus-manager

**Comment by Askannz** [comment]
> My Xorg logs don’t seem to catch anything that is date relevant.

What about `/var/log/optimus-manager/` ?
Have you followed thos instructions ? https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting#i-do-not-use-a-display-manager-i-use-startx-or-xinit

> I see via the logs that OM writes to 10-optimus-manager.conf each boot cycle.

That's pretty normal. optimus-manager writes its own Xorg config at boot and on GPU switch. I'd advise against combining it with custom Xorg configs unless you know what you're doing.

> I’m seeing now that there is no nvidia-enable.sh in my /etc/optimus-manager

Yeah that's a bug in the packaging. optimus-manager may complain in the logs about that file being missing, but you can ignore it.

**Comment by enigmatic-system** [comment]
> What about /var/log/optimus-manager/ ?
Have you followed thos instructions ? https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting#i-do-not-use-a-display-manager-i-use-startx-or-xinit

> I do not use a display manager (I use startx or xinit)
Do I run `/usr/bin/prime-offload` in another tty?

**Comment by enigmatic-system** [comment]
When I run prime-offload I get... 

![7C38048E-F2D4-4EE0-BC5F-9C81AAF1FAA7](https://user-images.githubusercontent.com/7607506/73441008-2b639500-4307-11ea-8372-abf871d45737.jpeg)

Should I sudo it?

**Comment by enigmatic-system** [comment]
Did it anyways same result.

**Comment by enigmatic-system** [comment]
I’m trying to condense all of these posts I’m overloading here but one that I deleted asked if I was suppose to run prime-offload in another tty since the screen I run startx in is black.

Now we’re back at the problem of not having a display.

**Comment by Askannz** [comment]
`prime-offload` is supposed to be run *just after* the X server has started. I think that for a setup such as yours, you have to put it in your `.xinitrc`.

**Comment by enigmatic-system** [comment]
Here's the running as a normal user...
[startx.log](https://github.com/Askannz/optimus-manager/files/4133648/startx.log)

Here's running as root...
[rootStartx.log](https://github.com/Askannz/optimus-manager/files/4133657/rootStartx.log)

Since in the user log I was getting...
`xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)`

I thought I would try as root which here's the /var/log file from that...
[Xorg.0.log](https://github.com/Askannz/optimus-manager/files/4133684/Xorg.0.log)

and then going through these a bit I noticed that the user log file goes to .local/xorg which I didn't know before.
[Xorg.0.log](https://github.com/Askannz/optimus-manager/files/4133722/Xorg.0.log)

**Comment by enigmatic-system** [comment]
I ended up switching to a pure Nvidia set up. 
Thank for trying to help me out with this.
Cheers.
