### ISSUE TITLE
Can't go into full nvidia mode

### ISSUE THREAD

**Issue by Yooooomi** [Askannz/optimus-manager#206]
**Describe the bug**
Can't switch to nvidia mode, optimus-manager says current mode is hybrid and next reboot mode is nvidia but never switches to nvidia

**System info**
- Arch / Manjaro
- KDE
- SDDM
- Razerblade Mid 2019
- 1.2.2

boot_setup.log: https://pastebin.com/72HUQa7d
gpu_setup.log: https://pastebin.com/wMBptf9D
prime_setup.log: https://pastebin.com/MsKkPvQj

**Comment by Kr1ss-XD** [comment]
Could you reinstall optimus-manager and try again pls ?  Your logs state there's a file missing that should have been installed with the package (which is `/etc/optimus-manager/xsetup-nvidia.sh`).

**Comment by Yooooomi** [comment]
I reinstalled it 
These are the new logs

https://pastebin.com/87VEx6Lm
https://pastebin.com/5bngZXu1
https://pastebin.com/1kDveUZs

**Comment by Askannz** [comment]
>  optimus-manager says current mode is hybrid

That's strange. What's the output of `xrandr --listproviders` ? Do you have any extra config file at `/etc/X11/xorg.conf` or `/etc/X11/xorg.conf.d/` ?

According to the log, there is something clinging to the Nvidia GPU and preventing the kernel module from unloading. No clue what or why though, which makes the issue hard to debug.

Just in case, make sure to try with the base `optimus-manager` config (no power management options enabled).

**Comment by Yooooomi** [comment]
In hybrid mode, `xrandr --listprovides` outputs:
```
xrandr --listproviders 
Providers: number : 2
Provider 0: id: 0x43 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 1 associated providers: 0 name:modesetting
Provider 1: id: 0x26f cap: 0x0 crtcs: 0 outputs: 0 associated providers: 0 name:NVIDIA-G0
```

In intel mode, I just don't have the second line.
I don't have any extra config file 
```
 ls -R /etc/X11/
/etc/X11/:
xinit  xorg.conf.d

/etc/X11/xinit:
xinitrc  xinitrc.d  xserverrc

/etc/X11/xinit/xinitrc.d:
40-libcanberra-gtk-module.sh  50-systemd-user.sh

/etc/X11/xorg.conf.d:
00-keyboard.conf  10-optimus-manager.conf
```

I never tried to configure anything with optimus.

I'm running Manjaro so my SDDM config is edited to disable 
```
[X11]
#DisplayCommand=/usr/share/sddm/scripts/Xsetup
#DisplayStopCommand=/usr/share/sddm/scripts/Xstop
```

**Comment by Yooooomi** [comment]
Ok it seems that there were files in the additional config path of X which I don't know existed. Removing all video related files solved the issue. Eventhough hybrid more is still not working for me with two screens, nvidia is so it closes the issue.
