### ISSUE TITLE
Refresh rate defaulting to 60 hz or less on Manjaro KDE Plasma

### ISSUE THREAD

**Issue by Ashiix** [Askannz/optimus-manager#207]
**Describe the bug**
Refresh rate defaulting to 60 hz or less on KDE Plasma. Able to fix by going to Plasma display settings and switching from 144 to 60, and back to 144.

**System info**
Please include :
- Manjaro
- KDE Plasma
- SDDM
- RTX 2070, Intel graphics something-or-other
- Latest stable release of optimus-manager from AUR

**Logs**
- [boot_setup.log](https://gist.github.com/Ashiix/3b0adf16d5abfc060282f06741f7c8aa)
- [gpu_setup.log](https://gist.github.com/Ashiix/b50f8f2b8c0dbac18cfdc206690cceea)
- [prime_setup.log](https://gist.github.com/Ashiix/1495904595b576dae00c7f290c00c516)

**Comment by Askannz** [comment]
I may have a lead for this issue.

Just after booting into Nvidia mode, could you go to System settings -> Startup and Shutdown and check if "KScreen 2" is enabled and running in "Startup services" ?

Also attach the output of the command `xrandr -q`, that could be relevant.

**Comment by rnd-ash** [comment]
@Ashiix try kwin-lowlatency. This helps me quite a bit with multiple displays on Nvidia, especially when my laptop monitor is also on.

**Comment by nwildner** [comment]
Hi @Ashiix , did you had the time to try kwin-lowlatency as per the last comment?

Since the last update on this case was from 4 years ago, we'll keep this case opened for some days and close it if no answer is provided.

Have a nice week ahead.
