### ISSUE TITLE
No DisplayManager -- no switch on next login

### ISSUE THREAD

**Issue by qwelias** [Askannz/optimus-manager#211]
**Describe the bug**
I'm using GNOME, but I start it manually from tty using only `startx`.
When switching with `--switch` it just logs me out, but on the next login current GPU does not change.
Using `--set-startup` and rebooting works without any issues.

**System info**
Please include :
- Linux 5.5.2-arch1-1
- GNOME
- manual `startx`
- Laptop is fine :)
- optimus-manager 1.2.2

**Logs**
https://gist.github.com/qwelias/73b187deb1db9eebd9074906e02713a8

**Comment by xiroV** [comment]
Same thing happened for me today after updating to Linux 5.5.2-arch1-1.

My setup:
 - Linux 5.5.2-arch1-1
 - i3wm
 - lightdm
 - optimus-manager 1.2.2

**Comment by riazufila** [comment]
Source: [https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting#my-display-manager-is-not-sddm-lightdm-nor-sddm](https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting#my-display-manager-is-not-sddm-lightdm-nor-sddm)

Have you done the following? Just incase.

> My display manager is not SDDM, LightDM nor SDDM
> 
> In that case you must manually configure your display manager so that :
> 
>     It uses Xorg (no Wayland)
>     It runs the script /usr/bin/prime-offload just after starting its display server for the login screen
>     It runs the script /usr/bin/prime-switch as root after the current user has logged out.
> 
> I do not use a display manager (I use startx or xinit)
> 
> Just like above, you must make sure to run /usr/bin/prime-offload (as normal user) just after the X server is started, and /usr/bin/prime-switch (as root) after it has stopped.

**Comment by jtrudel** [comment]
Hi,

I'm having the same issue and don't really understand the part about using prime-switch after it has stopped.

I'm using bspwm and so far I need to:
- call optimus-manager --switch nvidia for example
- Xorg restarts, I'm back on the login screen
- login, Xorg starts, no GPU change
- manually call /usr/bin/prime-switch
- manually kill Xorg
- then after I login a second time it works.

Is there a way to add sudo prime-switch to the restart process or should I deactivate the auto-restart? I just want a solution where I don't have to login twice to change my GPU.
