### ISSUE TITLE
Multi-Monitor Setup

### ISSUE THREAD

**Issue by WhyDoWeWonder** [Askannz/optimus-manager#212]
I have two 1080p monitors and my laptop. After installing optimus-manager I can no longer use my 2 other monitors, even when switching to nvidia mode. One is connected via a docking port and another via HDMI, both work perfectly fine on Windows and use to work when I used only dedicated graphics on Arch. Neither of my external monitors are detected when I use `xrandr` (at least in hybrid mode) but other devices connected to my docking port still work. Is there anything I can do or that can be done to solve this?

System info:

- Switching method: Nvidia drive built-in power management
- Using: optimus-manager 1.2.2-2.2
- Operating System: 5.5.2-arch-1
- Desktop Environment: KDE Plasma 5.17.5
- Login Manager: SDDM
- CPU: Core i7-9850h
- GPU: Quadro RTX 3000

**Comment by michaldybczak** [comment]
Hybrid mode (Prime Offloading) is currently not able to send picture output to external monitors. It's simply not implemented yet in Nvidia drivers (the way it works on Linux). It's already submitted and acknowledged that there is a need for it but no certainly when this will be implemented.

So for multimonitor setup use either Intel Modesetting or Nvidia mode.

This is still a new technology with lots of flaws. Optimus-manager gives us most flexibility over the static setups, because you can easily decide which drivers are loaded (open source or proprietary ones, Intel, Nvidia, Nvidia Offloading, Nouveau, etc.).

**Comment by Askannz** [comment]
What michaldybczak said : if the external outputs are internally wired to the Nvidia card, they won't work in Intel or Hybrid mode.

However, you mentioned they don't work either in Nvidia mode, which could be a bug. Could you attach optimus-manager logs ?

**Comment by WhyDoWeWonder** [comment]
[boot_setup.log](https://github.com/Askannz/optimus-manager/files/4207659/boot_setup.log)
[gpu_setup.log](https://github.com/Askannz/optimus-manager/files/4207660/gpu_setup.log)
[prime_setup.log](https://github.com/Askannz/optimus-manager/files/4207661/prime_setup.log)

**Comment by Askannz** [comment]
Hmm, according to the logs, booting directly to nvidia mode works fine, however crashes happened when switching from another mode to this one. So maybe you weren't actually in nvidia mode when you tried to set up the monitor. One thing for sure is that they won't work in any other mode.

Just to eliminate any noise, please wipe the logs clean (`sudo rm /var/log/optimus-manager/*.log`), set startup mode to `nvidia`, and reboot. Then make sure that `optimus-manager --print-mode` says `nvidia`, and send the logs again. Also grab the output of `xrandr -q`.

**Comment by WhyDoWeWonder** [comment]
I switched to nvidia mode, after logging in my laptop went to the screen I see when the laptop switches modes (text in the top right-hand corner with a black screen), after that I had to login again. After logging in a second time everything was black except for the apps I have set to startup automatically. I restarted my computer and my monitors showed up but I couldn't actually get to my desktop. Every time I typed in my password it would bring me back to the login screen, eventually I finally got into my desktop but after a few seconds it went back to the screen I see then my laptop switches modes.
[gpu_setup.log](https://github.com/Askannz/optimus-manager/files/4238429/gpu_setup.log)
[prime_setup.log](https://github.com/Askannz/optimus-manager/files/4238430/prime_setup.log)
[boot_setup.log](https://github.com/Askannz/optimus-manager/files/4238431/boot_setup.log)

**Comment by frankvirgato** [comment]
Seeing the same issue (if i read your issue correctly).
Up until about 4 weeks ago my X1 Extreme Gen 2, with BIOS configured in Hybrid, i could move between nvidia and intel modes (nvidia at boot).  Now, in BIOS Hybrid with optimus configured for nvidia, i get the login screen loop.  Switching BIOS to dedicated GPU seems to work, though i do get a fair amount of login screen flashing, but it does login ok.

**Comment by zenitraM** [comment]
FYI - the latest Nvidia driver 450.36.06 (still on beta/only packaged on CUDA: https://bugs.archlinux.org/task/67014) has the sink functionality and allows to use the Nvidia-plugged outputs on my Thinkpad P1 from `hybrid` mode, as sinks rendered by Intel, out of the box :tada:

**Comment by michaldybczak** [comment]
Wow, great to know! Thanks! Now all it takes is to wait till 450xx will be available on Manjaro.

**Comment by Askannz** [comment]
Yes, support for Nvidia outputs is quite a big news. With that plus Prime offloading and Turing cards (with support for true power-off) becoming more common, we are essentially at the feature parity of Windows. This will make optimus-manager less of a necessity in the future :slightly_smiling_face:

**Comment by michaldybczak** [comment]
I don't think that optimus-manager will be obsolete so soon. Many people, including me, still have older GPUs (not turing ones) so true offloading won't be possible.
Most probably the transition will take 5-10 years. People are using mostly laptops nowadays and on most models we can't change GPUs) so as long the old laptops will be functioning and be a viable option for gaming or whatnot, optimus-manager will be very useful.

**Comment by Askannz** [comment]
> I don't think that optimus-manager will be obsolete so soon. Many people, including me, still have older GPUs (not turing ones) so true offloading won't be possible.

FYI, offloading works on pre-Turing cards, it's true power-off (also called "Runtime D3 power management") that doesn't.
But yes, I agree that this project will still be useful in the future, so I'm not retiring it anytime soon.

**Comment by michaldybczak** [comment]
I constantly get likes on my tutorial and the link to it is forwarded every few days or more, so optimus-manager became really popular on Manjaro.

**Comment by WhyDoWeWonder** [comment]
A note to any users who come across this thread or have similar issues.

The performance is terrible while using NVIDIA outputs without using Reverse Prime or only using the NVIDIA GPU. The only real benefit is that sink functionality works out of the box. 

I recommend setting up Reverse PRIME, and using Optimus Manager to switch when you need to. You will experience the occasional bug and some instability but (at least in my opinion) it's much better than any alternative. Until you can get comparable performance with the default sink output setup you should stick with this.

**Comment by Askannz** [comment]
@WhyDoWeWonder are you experiencing bad performance when switched directly to the Nvidia GPU ? That shouldn't happen.

**Comment by michaldybczak** [comment]
@WhyDoWeWonder, are you still experiencing problems with multimonitor setup on the 455 drivers?

**Comment by WhyDoWeWonder** [comment]
In the default sink output configuration I'm still experiencing issues. Performance has improved but it isn't nearly as close as it is to when I'm Running in Reverse PRIME. I've stuck to using Reverse Prime for now, the battery life sucks from always keeping the NVIDIA GPU on but I have an outlet almost everywhere I go so it's bearable.
