### ISSUE TITLE
Back-light adjustment impossible on nvidia

### ISSUE THREAD

**Issue by BushMan01** [Askannz/optimus-manager#213]
Hello, and thank you for this excellent utility! I have it working almost completely smoothly on my Dell G3 laptop. The only thing left to fix (which I think you cannot fix) is that the back-light brightness cannot be adjusted on Nvidia mode. The reason I do not believe it to be fixable on your end is that this did not work when I had the system running purely on the Nvidia driver only. It did (and still does work) on the Intel driver. I have not investigated hybrid mode enough to see if it might work there.
EDIT: My suspicions (see final paragraph) have been confirmed, as this does work on hybrid mode.

FYI I am running Arch, and I use xbacklight to adjust the screen brightness.

This isn't really a major problem, but I have decided to make this post both to thank you for the programme and to document the issue so other users don't waste time trying to fix something that cannot be fixed.

I think the cause of the issue might be that in Nvidia mode the dedicated card is the active card, so the back-light requests get sent to it, whereas we know they have to go to the Intel chip that actually controls the display.

**Comment by Askannz** [comment]
According to https://wiki.archlinux.org/index.php/Backlight#xbacklight :

> xbacklight currently does not work with the modesetting driver

That's very likely the issue since we have to load the modesetting driver in Nvidia mode. I can't use xbacklight either in Nvidia mode.

However this works :

```
# echo 50 > /sys/class/backlight/acpi_video0/brightness
```

**Comment by thamudi** [comment]
This might be a solution to working brightness in Hybrid mode

[Link to solution](https://forum.manjaro.org/t/amdgpu-cant-adjust-brightness-in-hybrid-mode-with-nvidia-discrete-works/90729/3?u=thamudi)
