### ISSUE TITLE
X restarting on locking, when in nvidia mode.

### ISSUE THREAD

**Issue by HakimEG** [Askannz/optimus-manager#216]
**Describe the bug**
Sometimes when doing a fresh boot, it takes several login attempts, before successfully getting logged in - it seems to restart X every time it fails.

I've also experienced that the X session will restart if I lock the pc.

All of this ONLY happens when in Nvidia mode, whereas hybrid works great. 

Looking through the logs, I do see that it has trouble with unloading nvidia-drm, but I have nothing that would keep it alive (especially at a fresh boot?)

I've read somewhere that systemd-logind could be an issue here, but it's far from something I can disable.
I did restart it at one point when i had issues with locking/unlocking restarted my session, and that did help with the problem in that boot cycle.

We are two people, both with the exact same setup, and we are both experiencing this issue.

Final note - This is all sporadic.. it doesn't ALWAYS happen, but when it does, it keeps on happening.

**System info**
Please include :
- Your distribution: Manjaro - Kernel 5.4.18-1
- Your desktop manager: Gnome
- You display manager: GDM-prime
- Your laptop model: Dell Inspiron 7590 with a GTX 1650
- The version of optimus-manager: Latest stable optimus-manager v1.2.2-2.2

**Logs**
https://pastebin.com/UCz9u4rR
https://pastebin.com/89JuTWkh
https://pastebin.com/RpMFiJ0L

**Comment by pedrovanzella** [comment]
This used to happen to me, then it stopped and it now started again. It seems to be a bug on the nvidia drivers: https://devtalk.nvidia.com/default/topic/1048609/linux/nvidia_drv-sometime-segfaults/

**Comment by Askannz** [comment]
@HakimEG so just be clear, when you boot into nvidia mode, the login screen shows up but then your session fails to start ? If that's the case, please follow those troubleshooting steps :

* Wipe optimus-manager logs (`sudo rm /var/log/optimus-manager/*.log`) and set startup mode to `nvidia`

* Reboot and try to log in

* If you experience the issue, then when you finally manage to log in, grab a log from the gdm service (`journalctl -u gdm -b0 --no-pager`). Also grab the logs from `/var/log/optimus-manager/`. Normally there should only be `prime_setup.log` and `boot_setup.log`, but if `gpu_setup.log` is there grab it as well.

Just in case, also check kernel logs for the issue @pedrovanzella mentioned (`dmesg | grep nvidia_drm`).

**Comment by HakimEG** [comment]
@Askannz Yes you are correct, but it also restarts the session when locking the laptop.

I followed your steps, but i couldnt get it to fail at login this morning, but i got a session restart when i locked after login in.

gdm log:
https://pastebin.com/Ks1dvp7x

optimus-logs:
https://pastebin.com/87vduhPx
https://pastebin.com/GWtjxFAT
https://pastebin.com/h1M3hE49

Soo.. is it because i am missing the nvidia-enable.sh ? and why would that file be missing ?

I also checked the kernel logs, and it seems to match with the issue that @pedrovanzella mentioned:
https://pastebin.com/zpEzwiFM

Is this issue still relevant then, or should i continue this with nvidia?

**Comment by Askannz** [comment]
Nothing suspicious in the logs, so yeah, looks like an Nvidia bug.
