### ISSUE TITLE
[Question] Where is xsetup-hybrid.sh file?

### ISSUE THREAD

**Issue by Mario156090** [Askannz/optimus-manager#217]
Good morning, I watch an update inside repository "support for scripts on hybrid mode" but i can't see xsetup-hybrid.sh

Should I wait yet for new update?

![image](https://user-images.githubusercontent.com/47507975/74607296-b8606980-50cf-11ea-9888-4d57d42363f7.png)

**Comment by Askannz** [comment]
Not in a release yet, you should use optimus-manager-git if you need this feature.
