### ISSUE TITLE
[Funcionality] Option      "AccelMethod"  "uxa"

### ISSUE THREAD

**Issue by Mario156090** [Askannz/optimus-manager#219]
Well, with some Intel graphic cards SNA cause flickering with OBS Studio. and the solution is set accel method uxa. 

Inside options only appears SNA and XNA, so I want to ask for add this option.

Source: https://wiki.archlinux.org/index.php/Intel_graphics#SNA_issues

Solution for me: https://www.youtube.com/watch?v=v7OJWts_e-4

**Comment by Hyper-KVM** [comment]
Hello, I've implemented the acceleration method you requested, you can try it out with my fork :)

**Comment by Mario156090** [comment]
> Hello, I've implemented the acceleration method you requested, you can try it out with my fork :)

Thank's a lot. How I can install your fork?

**Comment by Hyper-KVM** [comment]
> > Hello, I've implemented the acceleration method you requested, you can try it out with my fork :)
> 
> Thank's a lot. How I can install your fork?

You'll need to clone my [repo](https://github.com/Hyper-KVM/optimus-manager) and then go to the package folder and run `makepkg -si`

**Comment by Mario156090** [comment]
@Hyper-KVM  and your optimus manager qt?
how can I install that?

**Comment by Hyper-KVM** [comment]
> @Hyper-KVM and your optimus manager qt?
> how can I install that?

you would also have to clone that [repo](https://github.com/Hyper-KVM/optimus-manager-qt) and follow the install guide.

**Comment by Mario156090** [comment]
@Hyper-KVM  I don't understand thar instructions :/ can you put a brief explain please?

**Comment by Askannz** [comment]
It's implemented now. It would have been in v1.3 if I didn't forget about it :eyes: At least you can use it in `optimus-manager-git` now.
