### ISSUE TITLE
Nouveau method issue

### ISSUE THREAD

**Issue by inzar98** [Askannz/optimus-manager#22]
**Describe the bug**
Noveau method uses nvidia driver for firts gpu. My laptop's gpu led always stayed at red. (Intel for blue)

**System info**
Gnome-GDM

**Logs**

https://paste.ee/p/8WkEx

**Comment by Askannz** [comment]
Could you reformulate ? I don't understand what the problem is. Is it that switching to Intel does not work ?

Also, could you provide the name of your distribution and your laptop model ? It could be important in this case.

**Comment by inzar98** [comment]
Manjaro - MSI CX62-6QD

There is a led on the power button. If led is blue that means you are using Intel driver. If its red that means you are using Nvidia driver. 

Its blue in bumblebee, bbswitch method if I call optirun it turns red.

But optimus-manager's nouveau method makes it red every time, no matter using nvidia or SGI.

And starting overheating...

**Comment by inzar98** [comment]
And without " acpi_osi=! acpi_osi=\"Windows 2009\" pcie_port_pm=off " works great !

bbswitch needs that parameters..

**Comment by Askannz** [comment]
Glad to know it works for you know. Actually you raise a good point, it's possible that `pcie_port_pm=off` is incompatible with nouveau (not sure about the other one). I should probably add something about that in the README.
