### ISSUE TITLE
[Manjaro XFCE] Does not actually log out after --switch

### ISSUE THREAD

**Issue by keddad** [Askannz/optimus-manager#224]
I've met the bug exactly like in #223: it doesn't log me out after I confirm it, but works fine if I logout manually.

I'm running Manjaro 19.0 with XFCE 4.14. I've got latest stable release from AUR.

Logs: https://gist.github.com/keddad/307ec9042ec539cd5b060a9577343467

**Comment by Askannz** [comment]
Still works for me on Arch + XFCE.

Does running this command log you out ?

```
dbus-send --session --type=method_call --print-reply --dest=org.xfce.SessionManager /org/xfce/SessionManager org.xfce.Session.Manager.Logout boolean:false boolean:true
```

**Comment by keddad** [comment]
Yes, it works fine.

**Comment by keddad** [comment]
I found the problem, and the problem is me. I've been running it with sudo, it works fine when ran without it. I guess it can be useful to add some kind of warning about it?
