### ISSUE TITLE
Cannot use Reverse PRIME for Display Output.

### ISSUE THREAD

**Issue by WhyDoWeWonder** [Askannz/optimus-manager#228]
**Describe the bug**
I am unable to use Reverse PRIME to output to a secondary display. This may be somewhat related to my last post.

I recently discovered https://wiki.archlinux.org/index.php/Lenovo_ThinkPad_P52 and https://wiki.archlinux.org/index.php/PRIME. I've attempted to set this up with optimus-manager and I'm really not sure what's wrong. I made a post about it on the Arch forums here: https://bbs.archlinux.org/viewtopic.php?id=253336. That hasn't gotten anywhere so I was wondering if anyone here would know what's wrong with my system?

**System info**
Please include :
System info:

    Switching method: Nvidia drive built-in power management
    Using: optimus-manager 1.2.2-2.2
    Operating System: 5.5.8-arch-1
    Desktop Environment: KDE Plasma 5.18.3
    Login Manager: SDDM
    Laptop: Lenovo P53
    CPU: Core i7-9850h
    GPU: Quadro RTX 3000

**Comment by Hyper-KVM** [comment]
If you're trying to use the outputs in hybrid mode as far as i know it is not possible to do that yet at this point of time. You have to either:
A) use the full nvidia mode (PRIME offload) and the outputs should work then.
or B) configure optimus-manager.conf under `[intel]` to use modesetting for the nouveau driver, simply `modeset=on` and switch to intel mode.This may not work with your GPU and could cause a lockup, in which case disabling the nouveau driver before boot would solve that issue `modprobe.blacklist=nouveau` in GRUB commandline. Then just edit modeset to off.

**Comment by WhyDoWeWonder** [comment]
I do have PRIME render setup exactly as the wiki specifies. When I run
xrandr --listproviders I get this
Providers: number : 2
Provider 0: id: 0x43 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 1 associated providers: 0 name:modesetting
Provider 1: id: 0x2b5 cap: 0x0 crtcs: 0 outputs: 0 associated providers: 0 name:NVIDIA-G0
but whenver I try to run xrandr --setprovideroutputsource NVIDIA-G0 modesetting I get this error
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  35 (RRSetProviderOutputSource)
  Value in failed request:  0x2b5
  Serial number of failed request:  16
  Current serial number in output stream:  17

**Comment by Askannz** [comment]
What optimus-manager mode are you switched to ? (intel, nvidia or hybrid ?) The fact that xrandr shows NVIDIA-G0 suggests that you are in hybrid mode, but as @Hyper-KVM pointed out, external outputs only work in nvidia mode. This is a limitation of the Nvidia driver on Linux.

**Comment by WhyDoWeWonder** [comment]
I am in hybrid, though I have tried this on intel mode and with optimus-manager uninstalled. According to the Arch wiki, you can use [Reverse PRIME ](https://wiki.archlinux.org/index.php/PRIME#Reverse_PRIME) to use outputs connected through a different GPU so what am I missing? All I want to do is to have my external monitors connected when I'm at home and to have the dedicated GPU power down when I unplug my computer. Could you please help me out here?

**Comment by Hyper-KVM** [comment]
In order to use the ports on your laptop in reverse PRIME mode, you'll need to have intel mode set to use the modesetting driver, have the switching method set to nouveau and as previously mentioned, modeset under the intel section set to yes. Also as previously mentioned, the nouveau driver may cause lockups, in which case refer to my previous comment.

**Comment by WhyDoWeWonder** [comment]
Near the bottom of the page it says "Note: For the proprietary NVIDIA driver see `http://us.download.nvidia.com/XFree86/Linux-x86/375.26/README/randr14.html` instead." Implying that you can use the proprietary driver. I just want to be able to use my second monitor which has its outputs connected to the NVIDIA GPU.

**Comment by Askannz** [comment]
The wiki is written in a confusing way. The "[1]" refers to display offloading when the Nvidia GPU is used as the main one, which corresponds to `nvidia` mode in optimus-manager. External outputs won't work in any other mode.

**Comment by Askannz** [comment]
Closing this issue since it's not something that can be fixed within optimus-manager.
