### ISSUE TITLE
Unable to switch to nvidia nor hybrid modes

### ISSUE THREAD

**Issue by guybuk** [Askannz/optimus-manager#229]
Intel works fine, any attempt to `optimus-manager --switch hybrid/nvidia` just won't work.

I'll paste now all the logs I'm aware could be relevant, please let me know if I can provide anything else:

```
 guy@guy-inspiron157000gaming  ~  pacman -Q G nvidia
lib32-nvidia-440xx-utils 440.64-1
libnvidia-container 1.0.5-1
libnvidia-container-tools 1.0.5-1
linux54-nvidia-440xx 440.64-2
mhwd-nvidia-340xx 340.108-1
mhwd-nvidia-390xx 390.132-1
mhwd-nvidia-418xx 418.113-1
mhwd-nvidia-430xx 430.64-1.0
mhwd-nvidia-435xx 435.21-1.0
mhwd-nvidia-440xx 440.64-1
nvidia-440xx-utils 440.64-1
nvidia-container-toolkit 1.0.5-3
opencl-nvidia-440xx 440.64-1
```

gpu_switch.log:
```
020-03-15 07:25:34 PM +0200 ==================== 

Optimus Manager (Setup script) version 1.2.2
Setting up the GPU
Checking status of optimus-manager.service
Cleaning up leftover Xorg conf
Loading config
Requested mode : hybrid
Checking for GDM display servers
Available kernel modules : ['nouveau', 'nvidia', 'nvidia_drm', 'nvidia_modeset']
Setting up base state
Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia'] (if loaded)
Cannot setup GPU : kernel setup error : Cannot unload modules ['nvidia_drm', 'nvidia_modeset', 'nvidia'] : Failed to execute 'modprobe -r nvidia_drm nvidia_modeset nvidia' : modprobe: FATAL: Module nvidia is in use.
```
I then tried to manually remove modesets `rmmod nvidia-urm`, and tried again:
```
2020-03-15 07:26:40 PM +0200 ==================== 

Optimus Manager (Setup script) version 1.2.2
Setting up the GPU
Checking status of optimus-manager.service
Cleaning up leftover Xorg conf
Loading config
Requested mode : hybrid
Checking for GDM display servers
Available kernel modules : ['nouveau', 'nvidia', 'nvidia_drm', 'nvidia_modeset']
Setting up base state
Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia'] (if loaded)
Unloading modules ['nouveau'] (if loaded)
Running /etc/optimus-manager/nvidia-enable.sh
ERROR : cannot run /etc/optimus-manager/nvidia-enable.sh. Continuing anyways. Error is : Failed to execute '/etc/optimus-manager/nvidia-enable.sh' : bash: /etc/optimus-manager/nvidia-enable.sh: No such file or directory
Setting up Hybrid state
Loading module nvidia
Loading module nvidia_drm
Loaded extra Intel Xorg options (0 lines)
Loaded extra Nvidia Xorg options (0 lines)
Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf

2020-03-15 07:26:49 PM +0200 ==================== 

Optimus Manager (Setup script) version 1.2.2
Setting up the GPU
Checking status of optimus-manager.service
Cleaning up leftover Xorg conf
Removed /etc/X11/xorg.conf.d/10-optimus-manager.conf
Loading config
Requested mode : hybrid
Checking for GDM display servers
Available kernel modules : ['nouveau', 'nvidia', 'nvidia_drm', 'nvidia_modeset']
Setting up base state
Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia'] (if loaded)
Unloading modules ['nouveau'] (if loaded)
Running /etc/optimus-manager/nvidia-enable.sh
ERROR : cannot run /etc/optimus-manager/nvidia-enable.sh. Continuing anyways. Error is : Failed to execute '/etc/optimus-manager/nvidia-enable.sh' : bash: /etc/optimus-manager/nvidia-enable.sh: No such file or directory
Setting up Hybrid state
Loading module nvidia
Loading module nvidia_drm
Loaded extra Intel Xorg options (0 lines)
Loaded extra Nvidia Xorg options (0 lines)
Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf

2020-03-15 07:26:50 PM +0200 ==================== 

Optimus Manager (Setup script) version 1.2.2
Setting up the GPU
Checking status of optimus-manager.service
Cleaning up leftover Xorg conf
Removed /etc/X11/xorg.conf.d/10-optimus-manager.conf
Loading config
Requested mode : hybrid
Checking for GDM display servers
Available kernel modules : ['nouveau', 'nvidia', 'nvidia_drm', 'nvidia_modeset']
Setting up base state
Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia'] (if loaded)
Cannot setup GPU : kernel setup error : Cannot unload modules ['nvidia_drm', 'nvidia_modeset', 'nvidia'] : Failed to execute 'modprobe -r nvidia_drm nvidia_modeset nvidia' : modprobe: FATAL: Module nvidia_drm is in use.
```

Sorry for the clutter, please let me know if I can submit anything else that's useful

EDIT: I'm using gdm, I have `gdm-prime` installed and `WaylandEnable=false` uncommented.

**Comment by MegaShinySnivy** [comment]
I didn't want to open a new issue, but I'm also having the same problem. But it isn't giving me any error logs. I'm using KDE with SDDM.

**Comment by gueorgui** [comment]
I'm experiencing the same thing. Could it have to do with the Nvidia driver update that was released a few days ago? ([Arch package link](https://www.archlinux.org/packages/extra/x86_64/nvidia/))

**Comment by ichigo13** [comment]
I am experiencing a very familiar issue (intel works, any attempt to change to nvidia/hybrid fails and reverts back to intel) with only the last error being a little different.
The following is from the gpu_setup.log:

>Optimus Manager (Setup script) version 1.2.2
>Setting up the GPU
>Checking status of optimus-manager.service
>Cleaning up leftover Xorg conf
>Loading config
>Requested mode : nvidia
>Checking for GDM display servers
>Available kernel modules : ['nouveau', 'nvidia', 'nvidia_drm', 'nvidia_modeset']
>Setting up base state
>Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia'] (if loaded)
>Unloading modules ['nouveau'] (if loaded)
>Setting up Nvidia state
>Loading module nvidia
>Cannot setup GPU : kernel setup error : error running modprobe for nvidia : Failed to execute 'modprobe nvidia NVreg_UsePageAttributeTable=1' : modprobe: ERROR: could not insert 'nvidia': No such device

**Comment by drossbox** [comment]
Anyone get this sorted? Same problem here on an Arch install - `optimus-manager 1.2.2-2` `gdm-prime 3.34.1-1` `nvidia-dkms 440.64-8`. Everything has worked flawlessly for months, but I'm now seeing:
 `Optimus Manager (Setup script) version 1.2.2
Setting up PRIME
Checking status of optimus-manager.service
Loading config
Running xrandr commands
Error : cannot setup PRIME : Cannot setup PRIME : Failed to execute 'xrandr --setprovideroutputsource modesetting NVIDIA-0' :
`
instead of: 
`Optimus Manager (Setup script) version 1.2.2
Setting up PRIME
Checking status of optimus-manager.service
Loading config
Running xrandr commands
Running /etc/optimus-manager/xsetup-nvidia.sh
`

**Comment by MegaShinySnivy** [comment]
Are any of you running Folding@Home? For some reason, I found that uninstalling it caused Optimus-Manager to start working again.

**Comment by ichigo13** [comment]
> Are any of you running Folding@Home? For some reason, I found that uninstalling it caused Optimus-Manager to start working again.

Nope. It just stopped working for me after the January 2020 update that Manjaro had.
I did a fresh install of Manjaro and went with the Nvidia Prime drivers (dedicated GPU always on) until I need to have the switching functionality again.

**Comment by fakedeltatime** [comment]
I'm having the same problem, it broke some days ago after doing a system update on Manjaro, I can't tell if it was only a new kernel or also a new driver, but my system didn't change to the new kernel automatically anyway.

> Are any of you running Folding@Home? For some reason, I found that uninstalling it caused Optimus-Manager to start working again.

Really interesting, I disabled the foldingathome.service and now I can enable hybrid graphics, but switching to nvidia also brings me to hybrid graphics, which I don't know how to use.

**Comment by MegaShinySnivy** [comment]
What kernels are you running? It still works for me on 5.6X and 5.5X kernels. It could be weirdness with the 5.4X kernels, I don't have it installed.

**Comment by fakedeltatime** [comment]
I was on 5.5 when it suddenly stopped working, but last I remember looking at what version I was on its was 5.4, so I went back to that wondering if it would fix it.

**Comment by guybuk** [comment]
No folding@home, kernel 5.4 LTS

**Comment by Askannz** [comment]
Are you still experiencing this issue with v1.3 ?

**Comment by guybuk** [comment]
I'm not using Optimus Manager anymore, so if no one else will answer in my place then this issue can be closed.
