### ISSUE TITLE
Question : glxspheres64 slower than with optirun

### ISSUE THREAD

**Issue by ksdrummer** [Askannz/optimus-manager#231]
Hello, thank you for you work ! I just installed and configured and it seems to work.

However when I launch glxspheres64, it is as slow with nvidia as with intel.
`$ glxspheres64                   
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
GLX FB config ID of window: 0xad (8/8/8/0)
Visual ID of window: 0x27
Context is Direct
OpenGL Renderer: GeForce GTX 850M/PCIe/SSE2
62.074758 frames/sec - 69.275430 Mpixels/sec`

When I was using bumblebee, it was faster. I'm not sure it is a good indicator, so I'm just asking is this is a normal behaviour.
Is there a way to compare the speed between bumblebee and optimus-manager method ?

**Comment by Leimi** [comment]
The frame rate seems to be tied to your monitor's refresh rate here. Try running glxspheres64 with additionnal env variables in order to ignore the refresh rate.

This should work both in the intel and nvidia setups:

```
vblank_mode=0 __GL_SYNC_TO_VBLANK=0 glxspheres64
```

**Comment by ksdrummer** [comment]
OMG yes ! I never had such results with bumblebee

`$ vblank_mode=0 __GL_SYNC_TO_VBLANK=0 glxspheres64
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
GLX FB config ID of window: 0xad (8/8/8/0)
Visual ID of window: 0x27
Context is Direct
OpenGL Renderer: GeForce GTX 850M/PCIe/SSE2
1515.314483 frames/sec - 1691.090963 Mpixels/sec
1568.067448 frames/sec - 1749.963272 Mpixels/sec
1568.396046 frames/sec - 1750.329987 Mpixels/sec
`

Should I launch the games with those env variable or it is not necessary ?

**Comment by Leimi** [comment]
Well, you decide, there is no right or wrong answer here. Some people like to disable vsync especially for multiplayer FPS because of potentially added screen lag. Some people enable vsync because they see screen tearing without it. Try both if you want.

If you want to always disable vsync, so you don't have to set the env variables, you can do so in the nvidia settings gui ("sync to vblank").

**Comment by ksdrummer** [comment]
Ok thank you so much for the explanations !
I close the bug
