### ISSUE TITLE
gdm-prime and libgdm-prime are outdated

### ISSUE THREAD

**Issue by nkprince007** [Askannz/optimus-manager#235]
**Describe the bug**
AUR packages gdm-prime and libgdm-prime are outdated and one release behind gdm and libgdm packages.

**System info**
Please include :
- Your distribution: Manjaro
- Your desktop manager (KDE, GNOME, Cinnamon...), if you have one: GNOME
- You display manager (SDDM, GDM, LightDM...), if you have one. If you do not know, you are probably using the one coming with your desktop manager: GDM
- The version of optimus-manager you are using : latest stable release (optimus-manager)

**Comment by HougeLangley** [comment]
Yes, If I installed gdm-prime libgdm-prime, what even I choosen hybrid, intel or nvidia, reboot only intel I could used.

**Comment by Askannz** [comment]
Thanks, fixed.
