### ISSUE TITLE
Suggestion about Optimus Manager Indicator referenced in the README.md

### ISSUE THREAD

**Issue by andr3slelouch** [Askannz/optimus-manager#240]
Hello, using Gnome 3.36 I had problems with the argos Optimus Manager indicator, it doesn't show the menus, so I developed a Gnome Shell extension based on the argos version, so I would be happy to include my extension in the official README.md.
It was just posted in extensions.gnome.com the link for the extension is:
* [Optimus Manager Indicator](https://extensions.gnome.org/extension/2908/optimus-manager-indicator/)

**Comment by Askannz** [comment]
Thanks, added to README.
