### ISSUE TITLE
Vulkan VK_ICD_FILENAMES env not set

### ISSUE THREAD

**Issue by alcomposer** [Askannz/optimus-manager#242]
**Describe the bug**
The presence of Intel GPU drivers can block Vulkan from loading when Nvidia is used, if the environment variable VK_ICD_FILENAMES is not set:

`export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json` 
As far as I can tell, optimus-manager does not set this value.

**System info**
OS: Arch Linux x86_64 
Host: TM1701 
Kernel: 5.6.3-arch1-1  
Shell: bash 5.0.16 
Resolution: 1920x1080 
DE: GNOME 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita [GTK2/3] 
Icons: Adwaita [GTK2/3] 
CPU: Intel i7-8550U (8) @ 4.000GHz 
GPU: NVIDIA GeForce MX150 
GPU: Intel UHD Graphics 620 
Memory: 3468MiB / 15898MiB 

Optimus Manager (Client) version 1.2.2

**Comment by Askannz** [comment]
As far as I know it's not possible for an application to set system-wide environment variables, so optimus-manager can't set up `VK_ICD_FILENAMES` automatically.

There's a [FAQ entry](https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting#my-vulkan-applicationssteam-playdxvk-games-do-not-work-in-nvidia-modeS) about this issue, but it's the best we can do (if you know a way to set env vars system-wide, let me know !).

**Comment by Chermnyx** [comment]
This configuration works for me

`/etc/optimus-manager/nvidia-enable.sh`: 
```sh
#!/bin/sh
cat > /etc/profile.d/nvidia_vk.sh <<EOF
#!/bin/sh
export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json
EOF
chmod +x /etc/profile.d/nvidia_vk.sh
```

`/etc/optimus-manager/nvidia-disable.sh`:
```sh
#!/bin/sh
rm /etc/profile.d/nvidia_vk.sh
```
