### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/var/lib/optimus-manager/tmp/state.json'

### ISSUE THREAD

**Issue by riyadh144** [Askannz/optimus-manager#243]
Optimus manager doesn't start and we are in Intel mode but with the NVIDIA card still on but no processes on it.
I tried to debug it and add a few logs, to understand but no luck.
I thought it was a race condition, but I don't think that was the case. As Pre and Post are seconds away.
I also looking into the case if the file wasn't closing but that doesn't seem to solve it.

**System info**
Please include :
Distro:Manjaro
Kernel:Tried on 5.4,5.5, 5.6
DM: Gnome
Laptop: Razer Blade 15
Optimus Manager -git, and directly from the repo

**log**
 https://pastebin.com/nUdBwLQj

optimus-manager --status
ERROR: a GPU setup was initiated but Xorg post-start hook did not run.
Log at /var/log/optimus-manager/switch/switch-20200414T234235.log
If your login manager is GDM, make sure to follow those instructions:
https://github.com/Askannz/optimus-manager#important--gnome-and-gdm-users
If your display manager is neither GDM, SDDM nor LightDM, or if you don't use one, read the wiki:
https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting

Cannot execute command because of previous errors.

**Comment by uno20001** [comment]
I know it's a hack, but you could try running `sudo chmod -R 777 /var/lib/optimus-manager/persistent/` and rebooting to see if anything changes.

**Comment by riyadh144** [comment]
I tried that, it didn't work. I even tried changing the permissions when creating the files in the program itself.

**Comment by uno20001** [comment]
That's interesting. Do you get the same error? Can you confirm that the permissions stay 777 after loggin out and loggin in again?

**Comment by Askannz** [comment]
Should be fixed in -git now. Feel free to reopen if it persists.
