### ISSUE TITLE
Prime display high refresh-rate

### ISSUE THREAD

**Issue by rnd-ash** [Askannz/optimus-manager#244]
**Describe the bug**
When using any desktop environment, I've noticed that my internal laptop 144Hz display is a lot smoother using the intel mode compared to when i am using the NVIDIA mode.

Although the mouse appears smooth, moving windows / scrolling etc on NVIDIA appears to be a lot more jittery in comparison. Interestingly though, when playing games, they report 144fps, but its still noticeably smoother when using the intel driver.

**System info**
- Your distribution - Arch linux
- Your desktop manager - KDE (With kwin-lowlatency), or gnome with gdm-prime
- You display manager - SDDM/GDM
- Your laptop - Razer blade 2018 Advanced
- The version of optimus-manager you are using - optimus-manager 1.2.2

**Logs**
* [Boot setup log](https://pastebin.com/S4mM7yFw)
* [GPU setup log](https://pastebin.com/aVf0stpC)
* [prime setup log](https://pastebin.com/qfvjhFSg)

**Comment by Askannz** [comment]
Getting refresh rates to behave properly in KDE + Nvidia can be quite the headache, but that's not an issue with optimus-manager.

Try playing with backend/vysnc options in the compositor settings, or disable the compositor entirely and use https://github.com/Askannz/nvidia-force-comp-pipeline to get rid of tearing.
