### ISSUE TITLE
PKGBUILD strangeness

### ISSUE THREAD

**Issue by uno20001** [Askannz/optimus-manager#247]
As far as I can tell the program uses `/var/lib/optimus-manager/persistent/startup_mode` and `/var/lib/optimus-manager/persistent/requested_mode`, but the PKGBUILD file still uses `/var/lib/optimus-manager/startup_mode` and `/var/lib/optimus-manager/requested_mode` both in `package()` and `backup` parts. I'm not sure if that's an actual problem, but I think it's better if the developer(s) know about it.

**Comment by Askannz** [comment]
Thanks, good catch. Fixed.
