### ISSUE TITLE
Compatibility with AMD/NVIDIA hybrids

### ISSUE THREAD

**Issue by obackhoff** [Askannz/optimus-manager#248]
Hello, 

Just a quick question here. Is it possible to make this work with a combination of Ryzen CPUs and Nvidia GPUs? 
Currenty I am very interested in some Asus G14 laptops because of their Ryzen 9 4000 CPUs + good Nvidia cards as well. I don't intend to use Windows for the most part, so it is vital for me that Linux works well, meaning that I should able to switch the GPUs.
In any case, if there is some other way (or information about it) please let me know. I have found very little information about AMD/NVIDIA hybrid configurations.

BTW, I find optimus-manager project to be important and relevant to the Linux community :)
Thanks!

**Comment by Kr1ss-XD** [comment]
I'm currently using a [fork](https://github.com/Kr1ss-XD/optimus-manager/tree/amdigpu-compat) w/ added modes for AMD iGPU's,

There are some upstream commits though which I haven't yet had the time to merge, so the state is currently matching this repo some weeks ago (march 14, to be exact). I intend to eventually merge the options for 'Intel' and 'AMD' iGPUS into _just_ something like 'iGPU', and submit that as a PR. What hindered me so far is lack of skills as well as time.
Therefore there are some unsolved issues, but I'm using it mainly in 'ac_auto' mode w/ a Ryzen 5 and nVidia GTX 1050 and it's pretty comfortable.

If you're on Arch, there's a package in the AUR - [optimus-manager-amd-git](https://aur.archlinux.org/packages/optimus-manager-amd-git/) - which build from this fork.

Hat tip @yaliv btw, who integrated the AMD options first.

**Comment by obackhoff** [comment]
Thank you very much for update and the advice! I am indeed on an Arch based system so I will try it out! :D
