### ISSUE TITLE
[Question] Black screen after suspension in nvidia mode

### ISSUE THREAD

**Issue by Mario156090** [Askannz/optimus-manager#254]
Hi, I don't know if this is a problem from optimus manager or nvidia directly.
Always after suspend my notebook I try continue my work but my screen is black mode and I should force power off and restart my notebook.

Exist any fix for this? what happend?

I test with lightdm and gdm-prime.

**Comment by Askannz** [comment]
The nvidia driver has always had issues with suspend. This is likely not something that can be fixed from within optimus-manager. Sorry.
