### ISSUE TITLE
optimus-manager not working in udev rules

### ISSUE THREAD

**Issue by DarkFighterLuke** [Askannz/optimus-manager#256]
Hi, I am trying to change GPU every time that I change from power supply to battery and vice versa. 
I made a udev rule executing the command as my user profile, but nothing happens.
After some trials and errors I figured out that the problem is related to X server in some way, in fact if I execute the command in the udev rule from the graphical tty it works, but if I execute it from a CLI tty it doesn't work.

Can someone help me?
Thanks.

**Comment by sebirdman** [comment]
@DarkFighterLuke I'm trying to figure something like this out as well. I'm still working on all the kinks, but here's what i've got so far

my udev rule execute a systemd service like so:

```
ACTION=="add", SUBSYSTEM=="usb", ATTRS{idVendor}=="28de", TAG+="systemd", ENV{SYSTEMD_USER_WANTS}+="nvidia.service"
ACTION=="unbind", SUBSYSTEM=="usb", ENV{PRODUCT}=="28de/1142/1", TAG+="systemd", ENV{SYSTEMD_USER_WANTS}+="hybrid.service"
```

where my systemd service is in:
/usr/lib/systemd/user/hybrid.service
/usr/lib/systemd/user/nvidia.service

and my services look like:

```
[Unit]
Description=Goes into Hybrid Mode 

[Service]
ExecStart=/home/bird/scripts/hybrid

[Install]
WantedBy=default.target
```


in my script is:

```
#!/bin/bash
optimus-manager --switch hybrid --no-confirm
```

**Comment by DarkFighterLuke** [comment]
Thank you for your answer.
I finally did it in a different way, the problem was just the graphical session. I managed to kill the session with another command and now it works fine.
