### ISSUE TITLE
Missing the first underscore at the arguments for Steam Launch

### ISSUE THREAD

**Issue by guster23** [Askannz/optimus-manager#258]
**Describe the bug**
[Nvidia GPU offloading for "hybrid" mode - For Steam](https://github.com/Askannz/optimus-manager/wiki/Nvidia-GPU-offloading-for-%22hybrid%22-mode#for-steam)
This section says to add this at the launch settings to Steam's games:
`_NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME="nvidia" __VK_LAYER_NV_optimus="NVIDIA_only" %command%`

This don't work because is missing one underscore to the `NV_PRIME_RENDER_OFFLOAD` argument.
So at the wiki it should said:
`__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME="nvidia" __VK_LAYER_NV_optimus="NVIDIA_only" %command%`

**Comment by Askannz** [comment]
Good catch, thank you !
