### ISSUE TITLE
Don't advertise optimus-manager-argos anymore

### ISSUE THREAD

**Issue by rodolpheh** [Askannz/optimus-manager#259]
Neither Argos nor optimus-manager-argos is maintained anymore, see https://github.com/inzar98/optimus-manager-argos/issues/9#issuecomment-598566615

**Comment by Askannz** [comment]
Thanks for letting me know.

**Comment by rodolpheh** [comment]
In fact, it's not totally abandoned, there is still people trying to fix it and make it working, but this extension has had too much problems with Gnome updates. I think it could go in the README but not as a recommended solution and with a big warning stating that this extension is not stable (due to Argos unstability with Gnome versions).
