### ISSUE TITLE
DPI not set correctly

### ISSUE THREAD

**Issue by ghost** [Askannz/optimus-manager#26]
**Describe the bug**
When switching from Intel to the Nvidia driver, the DPI looks like it is set to 75 instead of the native mode of 96.  There is something in the logs about "Unable to get display device for DPI computation".  I have worked around the problem by adding "xrandr --dpi 96" to the Xsetup file, but this isn't optimal, obviously, as it will get overwritten with an update.

**System info**
Distribution:  Arch linux
Desktop Manager: Plasma (KDE)
Display Manager: SDDM
Laptop: Dell XPS 9560

**Logs**
Xorg :  [https://pastebin.com/KhPgy708](https://pastebin.com/KhPgy708)
Display manager : No output
Daemon : No output

**Comment by Askannz** [comment]
I never tried to play around with that option. I wonder if this is why everything looks so small on my Nvidia GPU, haha.

Anyway, it looks simple enough to implement. I'll just add an option to the config file to set the DPI and generate the Xsetup script accordingly.

Thanks for the suggestion !

**Comment by openmindead** [comment]
Yeah this affects SDDM too, right after switching to Nvidia mode and SDDM restart.

**Comment by Askannz** [comment]
You can now specify the DPI for Nvidia mode in the configuration file (see https://github.com/Askannz/optimus-manager/blob/master/optimus-manager.conf). Please let me know how it works for you.

**Comment by Askannz** [comment]
Ouch, late reply, sorry.

@Shamash2014 That sounds like a configuration error. Maybe you have a leftover configuration file in `/etc/X11/` or `/etc/X11/xorg.conf.d/` ? Also (in case you don't know), don't use nvidia-xconfig. It autogenerates an outdated configuration which causes bug like this.

**Comment by Shamash2014** [comment]
@Askannz Thanks for the response.  I got a backup files only I believe: 

```
$ ls /etc/X11/xorg.conf.d/
00-keyboard.conf  10-optimus-manager.conf  90-mhwd.conf.bak
```

```
 ls /etc/X11/mhwd.d/
intel.conf.bak
```

Should I remove them in order to use optimus manager?

**Comment by Askannz** [comment]
I don't think X11 processes files that don't end in .conf, but maybe move them elsewhere just in case.

**Comment by mikeyerolemou** [comment]
> You can now specify the DPI for Nvidia mode in the configuration file (see https://github.com/Askannz/optimus-manager/blob/master/optimus-manager.conf). Please let me know how it works for you.

That fixed the problem for me. I just used "xdpyinfo | grep dots" on Intel mode to figure out what resolution it was and chage it on the optimus-manager.conf

Thanks a lot again!

**Comment by Rafrobeat** [comment]
> @Askannz When I try to switch to nvidia I have to run `xrandr --output eDP-1-1 --mode 1920x1080 ` and restart window manager. Is it possible to save screen resolution on light dm reboot?

Hello! I have the same problem. Do you fix this problem?

**Comment by ArArgyridis** [comment]
I also face the same thing. Yes setting the DPI in optimus-manager.conf solves the issue, however there are still issues if I connect an external monitor with different DPI size. Is there any workaround?
