### ISSUE TITLE
Can't switch modes on newer LTS kernels

### ISSUE THREAD

**Issue by SalvatorePerri** [Askannz/optimus-manager#260]
**Describe the bug**
On 5.4 I am able to switch to Nvidia and Hybrid modes only if I warm boot after I booted the Windows partiton. I suppose this is some kind of missing firmware and not your fault. Also the only kernel I previously managed to run the Nvidia mode on (not hybrid) was the 4.14.

**System info**
- Manjaro, 5.4.40-1-MANJARO
- GNOME
- GDM with patch applied
- Lenovo Z50-70, dGPU Nvidia 840m, driver nvidia-440.82
- optimus-manager version 1.2.2

**Logs**
optimus-manager --status does not reveal errors. As for the log files suggested in /var/log/optimus-manager/ I have no switch and daemon folders.
Please tell me the logs I should post.

**Comment by Askannz** [comment]
Update to the latest version (v1.3 at the moment) and try `optimus-manager --status` again.

**Comment by SalvatorePerri** [comment]
> Update to the latest version (v1.3 at the moment) and try `optimus-manager --status` again.

I confirm that now it works on 5.4, it is possible to switch to Hybrid, Nvidia and Intel modes.

`optimus-manager --status` does not show any errors.
