### ISSUE TITLE
Suspend/resume powers up dGPU in intel mode

### ISSUE THREAD

**Issue by k9bbzJavftZaqAqSW3dY** [Askannz/optimus-manager#270]
My power draw goes up from 10 watt idle to 15 watt idle after resuming from suspend (everything works correctly from fresh boot).

**System info**
- Manjaro
- KDE
- SDDM
- Laptop model: Asus UX550VD
- Optimus manager v1.3-1
- Non-standard config file settings:
switching=bbswitch
pci_reset=function_level (tried 'no' as well)
tearfree=yes
ignore_abi=yes

**Logs**
No errors thrown

**Workaround**
After resume, issuing the following command reduces power draw (I have both bbswitch and acpi_call installed):
`echo "\_SB.PCI0.PEG0.PEGP._OFF" > /proc/acpi/call`
The pure acpi_call switching method has the same problem though.

**Comment by Askannz** [comment]
Yeah, suspend on Nvidia is kinda broken in general and particularly with Optimus. Not much I can do about it unfortunately.

As a slightly cleaner workaround, you could try sending the OFF command to bbswitch directly, instead of relying on ACPI calls: `echo OFF | sudo tee /proc/acpi/bbswitch`.

**Comment by Askannz** [comment]
This issue may be fixed in the latest master, see https://github.com/Askannz/optimus-manager/issues/191#issuecomment-706513965
