### ISSUE TITLE
Not using settings in my .conf file for some reason

### ISSUE THREAD

**Issue by pjentsch0** [Askannz/optimus-manager#273]
**Describe the bug**
I set `startup_mode=nvidia` in my .conf file, at `/etc/optimus-manager/optimus-manager.conf', but my computer still always starts up in 'intel' mode. Switching to nvidia mode afterwards works well.

**System info**
Please include :
-Manjaro Linux x86_64
- Cinnamon
- unsure
- Dell XPS 15 7590 
- Latest stable release
- .conf file:
```
[optimus]

startup_mode=nvidia
```
Although I have tried many variations on the above.
**Logs**
Run `optimus-manager --status` in a console, and if an error message appears, post it here. The message should also point you to a log path, attach it here as well. If there is no error message but you are still experiencing issues, grab the most recent files in `/var/log/optimus-manager/switch/` and `/var/log/optimus-manager/daemon/`.

output of the above command:
```
Current GPU mode : nvidia
GPU mode requested for next login : no change
GPU at startup : intel
Temporary config path: no
```

**Comment by Askannz** [comment]
What's the output of `python -c "from optimus_manager.config import load_config; print(load_config()[\"optimus\"][\"startup_mode\"])"` ?

Make sure there is at least one reboot between setting `startup_mode=nvidia` in the config file and running this command.

**Comment by pjentsch0** [comment]
```
[peterj@peter-xps157590 ~]$ python -c "from optimus_manager.config import load_config; print(load_config()[\"optimus\"][\"startup_mode\"])"
intel
```

**Comment by pjentsch0** [comment]
Installing `optimus-manager-qt` and using that to set options works. I guess I made an error manually setting the config file somewhere. Thanks for the great package!
