### ISSUE TITLE
spotify tracks issues

### ISSUE THREAD

**Issue by kuba1909** [Askannz/optimus-manager#28]
**Describe the bug**
When using optimus-manager, I am no longer able to skip songs on `spotify 1.0.94.262-1` (latest AUR package). I can't even play the same song again (by going back). Also, when in a playlist, the next song won't get played. I didn't have the issues with `nvidia-xrun`. Tested while in nvidia mode, didn't try with intel.

**System info**
Arch Linux
XFCE 4
LightDM

**Logs**
I read the logs and didn't find them helpful at all. It is likely, that the bug is easily reproducible, though.

**Comment by kuba1909** [comment]
> Do you mean you tried running Spotify on the Nvidia GPU using nvidia-xrun, or just in the default desktop session (running on Intel) with nvidia-xrun installed on your system ?

Before using optimus-manager, I started my xfce4 session with `nvidia-xrun`. I had no issues at all back then. But I remember, before doing so I even used another method. I ran my whole X server on the nvidia GPU and had the issue too.

**Comment by Askannz** [comment]
Well, I can't reproduce the bug. Spotify works fine for me.


Also, since you said :
> I ran my whole X server on the nvidia GPU and had the issue too.

It doesn't seem to be a bug in optimus-manager.

To be sure, you could try removing optimus-manager completely, as well as any custom Xorg configuration, and see if the problem persists.

**Comment by kuba1909** [comment]
Sorry, you were right. I resolved the issue and it wasn't graphically-related at all.
