### ISSUE TITLE
ERROR: a GPU setup was initiated but Xorg post-start hook did not run

### ISSUE THREAD

**Issue by spacedlevo** [Askannz/optimus-manager#280]
**Describe the bug**
I am not sure what I have updated, but I keep getting the above error no matter what command I use. 

**System info**
Please include :
- Your distribution Manjaro
- Your desktop manager (KDE, GNOME, Cinnamon...), Plasma
- You display manager (SDDM, GDM, LightDM...), I am guessing the default, I am not sure
- Your laptop model: Acer Nitro 5 AN515-52-50vr
- The version of optimus-manager you are using : latest stable release (optimus-manager)
- Your custom optimus-manager configuration file at `/etc/optimus-manager/optimus-manager.conf`,never made one

**Logs**
Run `optimus-manager --status` in a console, and if an error message appears, post it here. The message should also point you to a log path, attach it here as well. If there is no error message but you are still experiencing issues, grab the 
[switch-20200701T085626.log](https://github.com/Askannz/optimus-manager/files/4860722/switch-20200701T085626.log)
most recent files in `/var/log/optimus-manager/switch/` and `/var/log/optimus-manager/daemon/`.

**Comment by Askannz** [comment]
Do you have any configuration file in `/etc/sddm.conf.d/` that may be overriding the `DisplayCommand=` property of SDDM ?

**Comment by spacedlevo** [comment]
Not that I can see. In that directory is the 20-optimus-manager.conf which has;

```
[X11]
DisplayCommand=/sbin/prime-offload
DisplayStopCommand=/sbin/prime-switch

```

and
virtualkeyboard.conf
which has one line;
`InputMethod=qtvirtualkeyboard`

**Comment by spacedlevo** [comment]
Fixed the issue, I think it was my own ignorance. I didn't consider that KDE and Plasma were the same thing and therefore hadn't followed the README notes. I think made worse that I had it working before hand and it was only an update somewhere the seemed to break it.
