### ISSUE TITLE
No GPU switching on Manjaro, SDDM, bbswitch

### ISSUE THREAD

**Issue by Alarg** [Askannz/optimus-manager#288]
I'm using the latest build of Manjaro on Lenovo Ideapad S540-14IWL

I have the most current Nvidia drivers, and modeset installed.

When I try to switch graphics to Nvidia, it doesn't switch:

> [alarg@ALEKSA ~]$ glxinfo | grep vendor
> server glx vendor string: SGI
> client glx vendor string: Mesa Project and SGI
> OpenGL vendor string: Intel

The same is with hybrid mode, too.

After a failed switch, I get this error:

> [alarg@ALEKSA ~]$ optimus-manager --status
> ERROR: a GPU setup was initiated but Xorg post-start hook did not run.
> Log at /var/log/optimus-manager/switch/switch-20200709T141305.log
> If your login manager is GDM, make sure to follow those instructions:
> https://github.com/Askannz/optimus-manager#important--gnome-and-gdm-users
> If your display manager is neither GDM, SDDM nor LightDM, or if you don't use one, read the wiki:
> https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting
> 
> Cannot execute command because of previous errors.

The contents of the log file:

> [23] INFO: # Xorg pre-start hook
> [23] INFO: Requested mode is: intel
> [24] INFO: Checking for GDM display servers
> [467] INFO: Available modules: ['nouveau', 'bbswitch', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
> [468] INFO: Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] (if loaded)
> [474] INFO: Loading module bbswitch
> [482] INFO: Setting GPU power to OFF via bbswitch
> [586] INFO: Loaded extra Intel Xorg options (0 lines)
> [586] INFO: Loaded extra Intel Xorg options (0 lines)
> [586] INFO: Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf
> [587] INFO: Writing state {'type': 'pending_post_xorg_start', 'switch_id': '20200709T141305', 'requested_mode': 'intel'}
> [587] INFO: Xorg pre-start hook completed successfully.

Any help would be greatly appreciated!

**Comment by Alarg** [comment]
I've just tried using optimus-manager-qt-git and it's still not working. I suppose the issue comes from somewhere in the program, as it always thinks that I wish to switch to intel when I click on Nvidia or Hybrid.

**Comment by Alarg** [comment]
UPDATE: It works.
I tried the method described in [this thread](https://github.com/Askannz/optimus-manager/issues/279). I edited the /etc/sddm.conf to this values:
`display-setup-script=/usr/bin/prime-offload
display-stopped-script=/usr/bin/prime-switch`

It can switch now!

I'll close the thread soon if there are no issues, just have to check whether everything is working.

**Comment by Hyper-KVM** [comment]
This seems to be a confirmed issue with setting up sddm.conf, another user on discord just did what you did and it worked. I suggest reopening the issue so askannz can see it.

**Comment by BirdmanTunes** [comment]
Confirmed that the solution in https://github.com/Askannz/optimus-manager/issues/279 works,
I edited the /etc/sddm.conf to this values(simply added this at the bottom of the file:
display-setup-script=/usr/bin/prime-offload 
display-stopped-script=/usr/bin/prime-switch

This really should be added to the readme

**Comment by Alarg** [comment]
I'm grateful that I could help others with this!

Regarding the issue #279 I should note, also, that these scripts exist too:
`[alarg@ALEKSA ~]$ ls /sbin/prime*

/sbin/prime-offload  /sbin/prime-run  /sbin/prime-switch
`
As much as I understood, these scripts are the same as the ones located in `/usr/bin/`. I don't understand yet whether these scripts are accessible the same way as in `/usr/bin`, so I will check to see whether they work, just in case.

Askkanz, thanks for the great work! I don't have much time to check your code, so I don't know whether there exists the option to load these scripts by default. If it exists, you should then add this solution to the Troubleshooting section.

**Comment by Kr1ss-XD** [comment]
@Alarg `/sbin` - as well as `/bin` and `/usr/sbin` - are just symlinks to `/usr/bin`, since these are legacy paths and no more used in most modern distros. See : 

```
ls -l /{,usr/}
```

Hence `/sbin/prime-*` and `/usr/bin/prime*` actually _are_ identical.

**Comment by BirdmanTunes** [comment]
After applying the fix in #279 i shut down my computer and when i open it again the gpu switching isn't permanent, i had to manually edit the optimus-manager.conf file and set the startup to this
`startup_mode=nvidia`

**Comment by Alarg** [comment]
You have that option in the Optimus manager qt, however it would be nice that you can keep the configuration from the last session while rebooting. That's for a to-do list, it isn't a feature yet as far as I'm aware

**Comment by Askannz** [comment]
FYI, the SDDM thing is a known issue with Manjaro KDE and is mentioned in the readme: https://github.com/Askannz/optimus-manager#important--manjaro-kde-users

(the fix suggested in the readme is equivalent to overriding `DisplayCommand` and `DisplayStopCommand`, since optimus-manager sets those values itself in `/etc/sddm.conf.d/20-optimus-manager.conf`. The default config file takes priority however, which is what causes the problem in the first place).

@BirdmanTunes yes, that's expected behavior. The gpu mode at boot is defined by the startup options (either `startup_mode=nvidia` or the kernel parameter `optimus-manager.startup`, not the last mode you switched to).
