### ISSUE TITLE
[Question] Does HDMI audio passtrough works for you?

### ISSUE THREAD

**Issue by Nathoufresh** [Askannz/optimus-manager#292]
Hi all,
from what I've seen on the internet audio passtrough is working fine on VLC with pulseaudio nowadays. It does not work for me, I mean video and stereo is working fine but my TV can't manage 5.1 so I have to passtrough the audio stream to my home theater to have good sound. Most of the problems I have are related to nvidia optimus so I wonder if you guys are facing the same issue.
Btw hdmi audio passtrough works well on windows.

**Comment by Askannz** [comment]
Are you using optimus-manager ?

If your laptop has its HDMI port wired to the Nvidia card, then that card is also responsible for audio passthrough. Which can lead to some issues with Optimus. In particular, the used to be a bug where the audio chip would not wake up even when the card was powered on. Seems to be fixed on my machine though:

![image](https://user-images.githubusercontent.com/9202863/87487661-9b7d9180-c681-11ea-9c1b-d1ed54bc3d91.png)

**Comment by nwildner** [comment]
Closing case since this question was answered back in 2020 and the original reported didn't came back. 

Please fell free to reopen it if there are still any pending queries.
