### ISSUE TITLE
Unable to switch to nvidia after manjaro upgrade

### ISSUE THREAD

**Issue by vmf** [Askannz/optimus-manager#293]
Hi guys!
I ran a full system upgrade(pacman -Syu) on Sunday(07/19). After that I was unable to switch to nvidia.

When I try to switch using the following command:  **optimus-manager --switch nvidia**
```
ERROR: the latest GPU setup attempt failed at Xorg pre-start hook.
Log at /var/log/optimus-manager/switch/switch-20200720T220038.log

Cannot execute command because of previous errors.
```

```
~ >>> cat /var/log/optimus-manager/switch/switch-20200720T220038.log                                                                              [1]
[8] INFO: # Xorg pre-start hook
[8] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'nvidia', 'current_mode': 'intel'}
[8] INFO: Requested mode is: nvidia
[8] INFO: Checking for GDM display servers
[89] INFO: Available modules: ['nouveau']
[89] INFO: Unloading modules ['nouveau'] (if loaded)
[115] INFO: Loading module nvidia
[115] ERROR: Xorg pre-start setup error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 45, in main
    setup_kernel_state(config, prev_state, requested_mode)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 21, in setup_kernel_state
    _nvidia_up(config)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 56, in _nvidia_up
    _load_nvidia_modules(config, available_modules)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 109, in _load_nvidia_modules
    _load_module(available_modules, "nvidia", options="NVreg_UsePageAttributeTable=%d" % pat_value)
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 175, in _load_module
    raise KernelSetupError(
optimus_manager.kernel.KernelSetupError: module nvidia is not available for current kernel. Is the corresponding package installed ?
[116] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[116] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20200720T220038', 'requested_mode': 'nvidia'}
```

The hybrid driver as shown below is installed:
```
sudo mhwd -a pci nonfree 0300                                                                                                                  

[sudo] password for vmf: 
> Skipping already installed config 'video-hybrid-intel-nvidia-440xx-prime' for device: 0000:00:02.0 (0300:8086:3e9b) Display controller Intel Corporation UHD Graphics 630 (Mobile)
```

Kernel info:
```
~ >>> mhwd-kernel -li                                                                                                                                
Currently running: 5.7.9-1-MANJARO (linux57)
The following kernels are installed in your system:
   * linux56
   * linux57
```

It was working ok with my previous kernel version(linux56). I know this issue may not be related to this project at all but do you guys have any idea about whats's happening?

**Comment by Alarg** [comment]
It was working on 5.7 pre-upgrade, I used it. I'm experiencing the same issue, I'll let you know if I make something work.

**Comment by Alarg** [comment]
Hey,

Just to let you know. I didn't change a single thing nor installed another kernel module, and it has just started working. I just tried switching on a whim and both Nvidia and Hybrid modes work. Just to let you know that something truly odd is happening with these programs. If only it would be so easy for Manjaro devs to add switchable graphics and/or Nvidia to finally add proprietary tool, and everything would be pure bliss.

Try it for yourself, maybe it will work.

Regards,
Alarg

**Comment by Askannz** [comment]
Sounds like the update broke your Nvidia driver. It's likely that the kernel was updated but somehow Manjaro didn't rebuild the driver against the new version. No clue why though. You can confirm it by trying to load nvidia manually, eg `sudo modprobe nvidia`. In your case it should return an error.

Closing the issue since it's not an optimus-manager bug. You'll have to take that to Manjaro.

**Comment by vmf** [comment]
I was able to solve the issue by reinstalling the nvidia driver. I'll certainly take that to Manjaro because I'm under the impression that this will continue to happen on the next kernel upgrades. 

I used the following steps to fix the issue:

`$ sudo pacman -S linux57-headers`
`$ sudo mhwd -r pci video-hybrid-intel-nvidia-440xx-prime`
`$ reboot`
`$ sudo mhwd -a pci nonfree 0300`
