### ISSUE TITLE
Manjaro 20.04 GNOME defaulting to 60hz after switching to nvidia

### ISSUE THREAD

**Issue by illidanomg** [Askannz/optimus-manager#294]
Hello, when I use optimus manager to switch to nvidia from the integrated gpu GNOME defaults the display to 60hz. I can set it back to 120hz in the GNOME settings but it seems that only the cursor moves at 120hz while everything else is still rendered at 60hz, including games. Is there any way to fix this? I am using the AMD/NVIDIA fork of optimus manager that someone else has posted here.

This is the output of optimus-manager --status.

```
Optimus Manager (Client) version 1.2.2

Current GPU mode : nvidia
GPU mode requested for next login : nvidia
GPU mode for next startup : intel
Temporary config path: no
```

This is the output of xrandr --listproviders

```
Providers: number : 2
Provider 0: id: 0x1b8 cap: 0x1, Source Output crtcs: 4 outputs: 2 associated providers: 1 name:NVIDIA-0
Provider 1: id: 0x1e4 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 4 outputs: 2 associated providers: 1 name:modesetting

```
**System info**
Please include :
- Manjaro
- GNOME
- GDM-prime
- ASUS FX706II running AMD 4600h, Vega 8 iGPU/GTX 1650 TI dedicated GPU

**Logs**
[boot_setup.log](https://github.com/Askannz/optimus-manager/files/4957713/boot_setup.log)
[gpu_setup.log](https://github.com/Askannz/optimus-manager/files/4957715/gpu_setup.log)
[prime_setup.log](https://github.com/Askannz/optimus-manager/files/4957716/prime_setup.log)

**Comment by Askannz** [comment]
Sorry, I can't really offer support for that fork, I didn't write it and it's based on an old version of optimus-manager (I plan on adding upstream AMD support soon, though).

You could run `xrandr -q` and check what framerate Xorg is running your screen at. If it looks correct, then it may be an issue with the Gnome compositor.
