### ISSUE TITLE
ERROR: the active card is "intel" but it should be "nvidia".

### ISSUE THREAD

**Issue by KB-china** [Askannz/optimus-manager#295]
When I tried to switch to nvidia mode.There's something wrong.

>uname -r
`5.7.9-arch1-1`

> lspci | grep NVIDIA
`01:00.0 3D controller: NVIDIA Corporation GM108M [GeForce 940MX] (rev a2)`

>vim /var/log/optimus-manager/switch/switch-***.log
`[11] ERROR: Cannot setup PRIME : Failed to execute 'xrandr --setprovideroutputsource modesetting NVIDIA-0' :
Could not find provider with name NVIDIA-0`

>xrandr --listproviders
`Providers: number : 2
Provider 0: id: 0x46 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 4 associated providers: 0 name:modesetting
Provider 1: id: 0x7e2 cap: 0x0 crtcs: 0 outputs: 0 associated providers: 0 name:modesetting`

> nvidia-smi
`+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.57       Driver Version: 450.57       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce 940MX       Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   38C    P8    N/A /  N/A |      0MiB /   983MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+`

I can't fix it.How can I do?

**Comment by KB-china** [comment]
When it auto start nvidia mode.The screen breaking black.

**Comment by KB-china** [comment]
I'm using the optimus-manager-git

**Comment by Askannz** [comment]
Please don't ignore the issue template. What's your distribution ? Desktop environment ? Login manager ?

What does `optimus-manager --status` say ?

**Comment by nwildner** [comment]
Hello @KB-china .

Are you still interested on this issue? Are you still facing this problem in more recent versions of `optimus-manager` and a more modern Linux Distribution install?

This case dates back from 4 years, when `450.57 ` was the stable driver version.
