### ISSUE TITLE
Possible feature: startup mode dependent on if plugged in

### ISSUE THREAD

**Issue by OctarineSourcerer** [Askannz/optimus-manager#296]
I was wondering if there's any reasonable way to, if the laptop is plugged in, start in `hybrid` or `nvidia` mode; otherwise, start in `intel` mode. That is, without manually choosing a boot entry with the boot parameters set thusly.

I think this would be useful, as often I start my laptop with it plugged in, and later wish to use something more intensive, only to realise I'm in `intel` mode. Power isn't so much an issue when plugged in, so being in `hybrid` only then would be a very nice option to have.

**Comment by Askannz** [comment]
It's already a feature: https://github.com/Askannz/optimus-manager/blob/6775ab3ba4056ad823a115d2949677f5afaf02d9/optimus-manager.conf#L43
