### ISSUE TITLE
set-startup has no effect

### ISSUE THREAD

**Issue by NerosTie** [Askannz/optimus-manager#3]
When I type ```sudo optimus-manager --set-startup nvidia``` then restart my laptop, I run on the Intel GPU.

I use SDDM / ArchLinux / KDE.

```
sudo systemctl status optimus-manager.service          
[sudo] Mot de passe de neros :         
● optimus-manager.service - Optimus Manager
   Loaded: loaded (/etc/systemd/system/optimus-manager.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2018-11-18 02:10:49 CET; 8min ago
 Main PID: 1257 (python)
    Tasks: 1 (limit: 4915)
   Memory: 45.5M
   CGroup: /system.slice/optimus-manager.service
           └─1257 /usr/bin/python -u /usr/bin/optimus-manager-daemon --startup

nov. 18 02:10:49 Neros systemd[1]: Started Optimus Manager.
nov. 18 02:10:50 Neros python[1257]: Optimus Manager (Daemon) version 0.1
nov. 18 02:10:50 Neros python[1257]: Startup mode : nvidia
nov. 18 02:10:50 Neros python[1257]: Switching to Nvidia
nov. 18 02:10:50 Neros python[1257]: Loading Nvidia modules
nov. 18 02:10:51 Neros python[1257]: Configuring Xorg...
nov. 18 02:10:51 Neros python[1257]: Configuring login managers..
nov. 18 02:10:51 Neros python[1257]:         Configuring SDDM
nov. 18 02:10:51 Neros python[1257]:         Configuring LightDM
nov. 18 02:10:51 Neros python[1257]: Awaiting commands
```

```
 cat /etc/X11/xorg.conf.d/10-optimus-manager.conf 
Section "Module"
        Load "modesetting"
EndSection

Section "Device"
        Identifier "nvidia"
        Driver "nvidia"
        BusID "02:00:0"
        Option "AllowEmptyInitialConfiguration"
        Option "Coolbits" "28"
        Option "DRI" "3"
EndSection
```
```
 cat /etc/sddm.conf.d/10-optimus-manager.conf
[X11]
DisplayCommand=/usr/bin/optimus-manager_Xsetup
```

**Comment by Askannz** [comment]
Everything looks fine in those logs, your computer is indeed starting in Nvidia mode.

However, I just found out that there's a problem between SDDM and optimus-manager. I would bet that your problem is the same as this other issue : https://github.com/Askannz/optimus-manager/issues/2

You can try the workarounds I have proposed in this issue while I investigate the problem.

**Comment by NerosTie** [comment]
When I set ```sudo optimus-manager --set-startup nvidia``` then reboot, I'm on the Intel GPU but bbswitch tells me the Nvidia is ON.

(If I type ```sudo optimus-manager --set-startup intel```, bbswitch tells me it's OFF, in that case, it's ok)

**Comment by NerosTie** [comment]
Hm, the logs was before I switched to bbswitch. When optimus-manager is set to use Nouveau, bbswitch is completely disabled. But I didn't know how to check if the Nvidia card was ON or OFF with Nouveau...

**Comment by Askannz** [comment]
Could you please test the new v0.3 release and see if the problem is still there ?

**Comment by NerosTie** [comment]
It works! :tada: I can close this issue. Thanks!
