### ISSUE TITLE
computer feezes often, when switching to nvidia, when trying to shutdown, quit the i3 session etc

### ISSUE THREAD

**Issue by Araly** [Askannz/optimus-manager#30]
**Describe the bug**
My computer freezes (I can't do anything, change to a tty, so at that point I just stay pressed on the power button), when I'm trying to switch from intel to nvidia, with the login_manager_control=yes (login_manager_control=no, I don't have that problem), when I try to shutdown (in modes intel and nvidia both I think, but not always, so maybe there's a context in which I can, but I haven't discovered the pattern). When I exit i3 too, which is supposed to get me back to the display manager's greeter. I'm confident these issues appeared when I started using optimus-manager, though they weren't there at first. I did a clean install of my system again, in case it was something that I wouldn't know how to repair, and as I added optimus-manager they came back. The issue maybe lies somewhere else, but optimus-manager seems the be the one triggering the issues.

I tried to follow what was in the README, but I wasn't able to add kernel parameters at boot, I was having errors on that.

I disabled the service, will see if i continue having problems with it disabled, maybe rely on nvidia-xrun for the moment, be confident the issues dissapear, but I'd rather have optimus-manager working the way it should. I was using the package in the extra repositories of manjaro, I switched to the one in the AUR today, which is on version 0.5 instead of 0.4, hoping it would change something.

Something I want to try too, is to run the switch command, with login_manager_control=no, try to restart lightdm, and see if i can use that instead.

**System info**
Please include :
- Your distribution: 4.19.6-1-MANJARO
- Your desktop manager: i3 (manjaro's i3 community edition)
- You display manager: LightDM
- Your laptop model: Lenovo Legion Y520

**Logs**
Please attach the following logs (if you are able to):
- Kernel : I can't do anything once the bug occurs
- Xorg : https://pastebin.com/TTPVr8zj logs from the session I'm writing this from, after a forced shutdown.
- Display manager : https://pastebin.com/vL0XbDND
- Daemon : https://pastebin.com/SYr1gaWX

**Comment by Askannz** [comment]
Thanks for providing logs.

> Something I want to try too, is to run the switch command, with login_manager_control=no, try to restart lightdm, and see if i can use that instead.

Yes please do, that may help narrowing down the issue.
Something else you can try is disabling modesetting for the Nvidia driver (set `modeset` to `no` in the `[nvidia]` section).

I am currently investigating a bug that sounds similar to your problem, I'll let you know if I find a fix.

**Comment by Araly** [comment]
sorry for not replying ealier.

Even when running the optimus-manager cleanup, disabling the service and rebooting, I would still get all the issues I used too, computer freezing and unable to be used for anything, with the only way would be to hard shut down the computer.

I was getting messages though, when I was lucky enough to be in a tty when it happened, that one of my cores of my CPU was not responding, and on the same task for more than 20s if I remember correctly. I figured out that that was probably what was causing the freezing, unless it's just a symptom of the overall freezing ?

I reinstalled manjaro, and in a way that would allow me to reinstall again easily if I needed to. I tried optimus-manager again, but the same issues arrived quite as I reinstalled it. I ended up reinstalling again, this time using nvidia-xrun. It works well as of now, with a few issues that I don't think are related, for example if I change the luminosity too fast, i3 freezes (but not the apps in it, so I can still play around the apps that are displayed, I just can't switch to another workspace, or pop a terminal for example. I can switch to another tty and shutdown though, so it's not a real problem)

I can probably try again, if you have specific things you want me to look for, like that modesetting thing. I'll probably do that somewhere in the week, when I'm able. Let me know if there's something else I can help with, and thanks for your time and the great (otherwise ^^) software

**Comment by Askannz** [comment]
Sorry for the delay, could you test the new v0.6 release I've just pushed to AUR ? It includes a couple of fixes for similar issues, with some luck they'll fix your problem too.

**Comment by Araly** [comment]
I tried using optimus-manager v0.6, the one in the community repositories of manjaro.

It went somewhat fine for a day, but today when I tried changing the mode to nvidia, it froze (screen with the yes no option, you could see that I have said yes, but nothing afterwards, and no possibility to interact with anything, no possibility to switch to a tty), so forced my computer to shut down. As I rebooted, it brought up that it failed to launch lightdm correctly, and something along the lines of "failed to reach target graphical interface", with an invite to check the status of the lightdm service.

`sudo systemctl status lightdm.service`
https://pastebin.com/7GRbUgP4

I switched to an available tty, to get the above output, and tried to remove optimus-manager, see what happens (because the first times, when I removed it, issues stayed). This time seems fine, I'll report back if I see that issues still appear (I'm thinking of the one that froze one of my cores, and that would therefore freeze my computer, I guess when something important was assigned to it).

I want to talk about the actual removal of optimus-manager though, it was interesting. The tty I was in kept refreshing, kept clearing everything on screen, so it was difficult to write a command, as I would write a start, and it would dissapear after, I can try to show it with an example if it's not clear:

with `$` representing the command prompt, before a refresh:
```
$ sudo systemctl stat
```
then suddenly a refresh:
```

```
and if I try to continue the command, by remembering where I left it:
```
us lightdm.service
```

that would work, because for the tty I'm still writing on the same line, it's just for me that the screen gets refreshed.

So I ran `sudo optimus-manager --cleanup` and I removed the package. As soon as I did that, lightdm restarted in the tty I was in, and the greeter appeared. I gave my password, and I got access to my usual setup. I think the refreshes of the tty was trying to launch lightdm, which finally was possible when the file it used changed (I guess by the cleanup).

Here's an output for the status of the lightdm service now that it's working:
`sudo systemctl status lightdm.service`
https://pastebin.com/biLPxXeH

I tried to run `journalctl -u display-manager -b0 --no-pager` but nothing interesting comes up:
```


Let me know if there's something else I can test

**Comment by Araly** [comment]
I've tried reinstalling optimus-manager and using is with various combination of modesetting off for nvidia, of login-manager-control=no, but no matter what the options are, lightdm always fails if I have optimus-manager installed, even if I don't do anything with it. I think lightdm might be pissed off at how many times I ask it to restart and doesn't like the new kid on the block that's the cause of all this ^^

The first time I had it installed, the thing my previous comment was about, the two worked together, but now they really don't. I think there might be left over from optimus-manager, something that lightdm remembers, that's not forgotten with optimus-manager --cleanup and removing the package.

**Comment by Askannz** [comment]
Thanks for the logs ! You actually uncovered a bug.
In short, what was happening was that the temporary file normally containing the requested GPU mode had an empty value, which crashed the whole program and prevented the file from being overwritten. Thus, the part of optimus-manager that does the actual switching would not work as long as this file was there. I think that's why optimus-manager suddenly stopped working even though it was working before.

I don't know how the file got that empty value, perhaps your computer was force rebooted while the file was open. But the fact that the program crashed on an invalid value was definitely a bug.

Anyway, please remove `/var/lib/optimus-manager/requested_mode` and let me know if it works again.

I'm going to include some additional safeties so that this kind of thing does not happen again.

**Comment by Araly** [comment]
removing the `/var/lib/optimus-manager/requested_mode` file solves the issue of lightdm being stuck in a failure loop without having to completely remove the optimus-manager package.

I tried switching to nvidia, it froze so I force rebooted, and lightdm failed. I removed the file and on the next reboot, lightdm was up again.

I tried switching to nvidia with login manager control to no. The switching goes well, but if I try to restart the lightdm service inside a running X session, it freezes, exactly the same way as switching with login manager control to no.

I then tried the same idea, but restarting lightdm from another tty, froze again.

I then tried the same idea, but logging off first, so I could try logging on, or when logged off, restarting lightdm. On logging off, that made the cpu issue come back, with a beautiful error along the lines of "softlock bug, cpu #0 stuck for 22s"

A side note I can add is that it's messing with my sensors. A usual  number would be around 40°C, but it's now displaying 511°C and when I booted this session it was at 1°C [here's the output of `sensors` if you want a giggle](https://pastebin.com/ez1vLJ4U), the first value was probably not there before using optimus-manager.

**Comment by Askannz** [comment]
Sorry for the very late reply.

Could you test the latest Git version and see if the problem persists ?
This version introduces some major changes to the way optimus-manager works, so you need to reboot after upgrading to make sure everything is reloaded up properly.

**Comment by Araly** [comment]
I gave optimus manager a try a month ago or so, and it works well. I has some strnage behaviors sometimes, I feel like maybe it resets some settings but I haven't looked into it. I'm using the AUR build.

Should I still try out the git version ? I think the AUR package was updated a couple days ago (maybe a week ?) so maybe I've already been using the changes.

Anyways, thank you for updating it and getting it to work. I'll close the issue as the problems I was having are no more (although my sensors still go haywire ^^), but I'll happily try the git version if you think it would help

**Comment by Askannz** [comment]
All the major improvements that were on the Git version have been added to v1.0, so I'd recommend that you just update the normal package to the latest version. I can't say if it is going to fix your sensors problem, but the new version is a lot less aggressive about restarting critical system processes, so it's worth a shot.
