### ISSUE TITLE
My laptop alternates between amd and nvidia mode on every logout after switching to nvidia

### ISSUE THREAD

**Issue by ethan0150** [Askannz/optimus-manager#301]
**Describe the bug**
As the title suggests, it switches back and forth between nvidia and amd mode by itself after I executed ```optimus-manager --switch nvidia```.
To be more precise, after executing the above command, everything works as intended the first time I logout(which is triggered by the command) and log back in. ```glxgears``` runs on the dGPU normally according to ```nvidia-smi```. However, if I logout again via the application launcher it unloads all of the nvidia_* drivers, leaving only nvidia loaded (even if I use ```optimus-manager --switch nvidia``` to logout instead it still does so) , and ```optimus-manager --status``` says it's on amd mode. Afterwards, if I login and logout yet again, the nvidia_* drivers are loaded back again and ```optimus-manager --status``` says it's on nvidia mode again.
In other words, only on the odd-numbered times of login after the first ```optimus-manager --switch nvidia``` is it actually on nvidia mode and on the 
the even-numbered times it switches to amd mode on its own.
Only nvidia mode has this issue though. Everything will work as intended if I run ```optimus-manager --switch amd``` yet as soon as I run ```optimus-manager --switch nvadia```, this self-switching cycle starts again.

Also, after the bug happens, I sometimes can't shutdown/reboot and have to hold the power button (there seems to be no process be killed/terminated. I can still launch stuff like firefox and the only noticible change is that the shutdown and the reboot button dissappeared from my applications launcher.)

**System info**
- Distro: Arch Linux (Kernel version: 5.7.10-arch1-1)
- Desktop manager: KDE plasma 5.19.3
- Display manager: SDDM 0.18.1-2
- Display server: xorg-server 1.20.8-2
- Laptop model: ASUS TUF Gaming FX505DT (the one with a Ryzen 3750h + a GTX1650)
- Version of optimus-manager: latest optimus-manager-amd-git from AUR
- Config files: This bug seems to appear regardless of config. I played around with pretty much every option available (didn't try nouveau and bbswitch simply refused to load) in optimus-manager.conf and it still happens. This is the one I used when generating the following logs
[optimus-manager.conf.txt](https://github.com/Askannz/optimus-manager/files/4993973/optimus-manager.conf.txt)

 
**Logs**

```optimus-manager --status``` before any attempt to switch to nvidia or after running ```optimus-manager --switch amd```: 

```
Optimus Manager (Client) version 1.2.2

Current GPU mode : amd
GPU mode requested for next login : amd
GPU mode for next startup : amd
Temporary config path: no
```

```optimus-manager --status```, ```lsmod | grep -e amd -e nvidia``` and ```nvidia-smi```(with ```glxgears``` running) on the odd-numbered times of login after running ```optimus-manager --switch nvidia```: 

```
$ optimus-manager --status

Optimus Manager (Client) version 1.2.2

Current GPU mode : nvidia
GPU mode requested for next login : nvidia
GPU mode for next startup : amd
Temporary config path: no
```

```
$ lsmod | grep -e amd -e nvidia
nvidia_drm             57344  6
nvidia_modeset       1187840  12 nvidia_drm
nvidia              19726336  624 nvidia_modeset
amdgpu               5742592  2
gpu_sched              40960  1 amdgpu
i2c_algo_bit           16384  1 amdgpu
ttm                   118784  1 amdgpu
drm_kms_helper        253952  2 amdgpu,nvidia_drm
edac_mce_amd           32768  0
pinctrl_amd            32768  1
drm                   581632  11 gpu_sched,drm_kms_helper,amdgpu,nvidia_drm,ttm
```

```
$ nvidia-smi
Wed Jul 29 15:41:21 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.57       Driver Version: 450.57       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 1650    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   52C    P0    24W /  N/A |    249MiB /  3911MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      8168      G   /usr/lib/Xorg                     169MiB |
|    0   N/A  N/A      8265      G   /usr/bin/kwin_x11                  45MiB |
|    0   N/A  N/A      8301      G   /usr/bin/plasmashell               28MiB |
|    0   N/A  N/A     10145      G   glxgears                            2MiB |
+-----------------------------------------------------------------------------+
```

```optimus-manager --status```, ```lsmod | grep -e amd -e nvidia``` and ```nvidia-smi``` on the even-numbered times of login after running ```optimus-manager --switch nvidia```: 

```
$ optimus-manager --status

Optimus Manager (Client) version 1.2.2

Current GPU mode : amd
GPU mode requested for next login : nvidia
GPU mode for next startup : amd
Temporary config path: no
```

```
$ lsmod | grep -e amd -e nvidia
nvidia              19726336  0
amdgpu               5742592  19
gpu_sched              40960  1 amdgpu
i2c_algo_bit           16384  1 amdgpu
ttm                   118784  1 amdgpu
drm_kms_helper        253952  1 amdgpu
edac_mce_amd           32768  0
pinctrl_amd            32768  1
drm                   581632  11 gpu_sched,drm_kms_helper,amdgpu,ttm
```

```
$ nvidia-smi
Wed Jul 29 15:59:58 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.57       Driver Version: 450.57       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 1650    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   42C    P0     3W /  N/A |      0MiB /  3911MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

I logged-in 3 times in total after running ```optimus-manager --switch nvidia``` , here are the .log files in /var/log/optimus-manager. Since i ran```rm *``` under /var/log/optimus-manager before ```optimus-manager --switch nvidia```, there's no boot_setup.log.
[gpu_setup_.log](https://github.com/Askannz/optimus-manager/files/4993960/gpu_setup_.log)
[prime_setup_.log](https://github.com/Askannz/optimus-manager/files/4993961/prime_setup_.log)

**Comment by Hyper-KVM** [comment]
You're using an old version that's a fork that is not supported. I suggest uninstalling this version and using https://github.com/Askannz/optimus-manager/tree/amd_support instead.

**Comment by ethan0150** [comment]
> You're using an old version that's a fork that is not supported. I suggest uninstalling this version and using https://github.com/Askannz/optimus-manager/tree/amd_support instead.

LUL bruh moment for me. Forgot to check the source in the PKGBUILD for optimus-manager-amd-git. But how 2 install that branch? The optimus-manager package is for the master branch and there's no package for the amd branch :/

**Comment by Kr1ss-XD** [comment]
Just change
```
source=("git+https://github.com/Askannz/optimus-manager.git#branch=master")
```
to
```
source=("git+https://github.com/Askannz/optimus-manager.git#branch=amd_support")
```
in the PKGBUILD of `optimus-manager-git`.

**Comment by ethan0150** [comment]
> Just change
> 
> ```
> source=("git+https://github.com/Askannz/optimus-manager.git#branch=master")
> ```
> 
> to
> 
> ```
> source=("git+https://github.com/Askannz/optimus-manager.git#branch=amd_support")
> ```
> 
> in the PKGBUILD of `optimus-manager-git`.

After installing amd branch properly, I haven't encountered any issue yet. So far everything works like a charm. Thx for the help :))
