### ISSUE TITLE
Screen is cut off when switching to the Nvidia GPU

### ISSUE THREAD

**Issue by 9las** [Askannz/optimus-manager#302]
When I switch to the Nvidia GPU the screen is cut off as seen here:

![20200730_181416](https://user-images.githubusercontent.com/16062130/88949706-e27ba180-d293-11ea-984a-e8ddcada5813.jpg)

**System info**
- Distribution: Arch Linux
- Desktop manager: none
- Display manager: none
- Window manager: aesophor/wmderland
- Laptop model: Lenovo Legion Y540-15IRH 81SX
- Version of optimus-manager: 1.3.1-1

**Logs**
No error message appears when running `optimus-manager --status`. Logs are attached:
[daemon-20200730T181525.log](https://github.com/Askannz/optimus-manager/files/5002680/daemon-20200730T181525.log)
[daemon-20200730T182712.log](https://github.com/Askannz/optimus-manager/files/5002681/daemon-20200730T182712.log)
[switch-20200730T182505.log](https://github.com/Askannz/optimus-manager/files/5002684/switch-20200730T182505.log)
[switch-20200730T182712.log](https://github.com/Askannz/optimus-manager/files/5002685/switch-20200730T182712.log)
[Xorg.0.log](https://github.com/Askannz/optimus-manager/files/5002690/Xorg.0.log)

In the Xorg.0.log it is observed that the virtual screen size is determined to be 640 x 480

**Comment by tuxinal** [comment]
could possibly be related to #167 can you show the output of `xrandr -q`?

**Comment by es20490446e** [comment]
Probably fixed. Reopen if not.
