### ISSUE TITLE
Using outputs wired to Nvidia GPU in hybrid mode is possible

### ISSUE THREAD

**Issue by Ingvix** [Askannz/optimus-manager#303]
I'm not sure if the wiki is just outdated or if I missed some point in there but in [Nvidia GPU offloading for "hybrid" mode](https://github.com/Askannz/optimus-manager/wiki/Nvidia-GPU-offloading-for-%22hybrid%22-mode) it is claimed as one of the caveats that you can't use the outputs wired to Nvidia GPU while this is very much possible via so-called Reverse Prime, at least on my Thinkpad P50.

**Comment by mindrunner** [comment]
Yes, it is possible and it is super cutting edge and considered as experimental. Mileage varies and many people reporting huge latencies and slow desktops using Reverse Prime. Hopefully NVidia improves this in the future. I personally decided against Lenovo, because I had too much trouble relying on my NVidia card in the past.

**Comment by Ingvix** [comment]
I have to admit that I sort of fell into to a meme when I was getting a new laptop and decided on P50. I would look for a different device if I was as well aware of the limitations as I am now. Nevertheless I've been quite in content with Reverse Prime on P50 though it's incredibly annoying that the Nvidia card won't stop completely if it's not actually used.

Only latency-related problem I've had has been with Zoom which I'm forced to use in my studies. Not sure if it's even related to Reverse Prime but Zoom makes my cursor really laggy. Not so when using a browser to join a session so I try not to use the client unless I have to.

**Comment by Askannz** [comment]
Yeah I forgot to update the wiki. Done now.

**Comment by WhyDoWeWonder** [comment]
How did you get this working? I've been trying to get outputs to work in hybrid mode for since before #212!

**Comment by Ingvix** [comment]
@WhyDoWeWonder, all I have to do to get it to work after launching X in hybrid mode is run `xrandr --setprovideroutputsource NVIDIA-0 modesetting` as instructed in [Arch Wiki](https://wiki.archlinux.org/index.php/PRIME#Reverse_PRIME) and after that I have all the outputs available in xrandr. Your providers might be named differently, to find them out, run `xrandr --listproviders`.

**Comment by Ingvix** [comment]
Though now I had a look at your issue and you seem to have already been using Reverse Prime so I don't have any improvements to offer over that as this issue was all about Reverse Prime making it possible use all the outputs.

**Comment by WhyDoWeWonder** [comment]
Battery life is terrible compared to hybrid when not connected to external monitors among a host of other issues. The displays show up in KDE but when I try to use them all displays go black, with only a mouse cursor on the primary laptop display visible. I can still interact with applications, (type, click, run commands, audio still plays etc...) but I can't see what I'm doing.

**Comment by Ingvix** [comment]
Can't really help you there since it's working for me. Have you tried if setting the display configuration with xrandr does any better in case the KDE for some reason screws up something when using reverse prime?

**Comment by WhyDoWeWonder** [comment]
Solved, was an issue with the GPL condom introduced in kernel 5.9.
