### ISSUE TITLE
wine not working in nvidia mode

### ISSUE THREAD

**Issue by xdrie** [Askannz/optimus-manager#306]
**Describe the bug**

after switching to `nvidia` mode, any invocations of wine that use graphics (including `winecfg`!!) simply hang.

`wine` functions normally in `intel` mode.

installed nvidia packages:
```
local/nvidia-beta-dkms 450.57-2
    NVIDIA driver sources for linux (beta version)
local/nvidia-cg-toolkit 3.1-6
    NVIDIA Cg libraries
local/nvidia-prime 1.0-4
    NVIDIA Prime Render Offload configuration and utilities
local/nvidia-settings-beta 450.57-1
    Tool for configuring the NVIDIA graphics driver (beta version)
local/nvidia-utils-beta 450.57-1
    NVIDIA drivers utilities (beta version)
local/lib32-libvdpau 1.4-1
    Nvidia VDPAU library
local/lib32-nvidia-cg-toolkit 3.1-7
    NVIDIA Cg libraries
local/lib32-nvidia-utils-beta 450.57-1
    NVIDIA drivers utilities (32-bit, beta version)
```

**System info**
Please include :
- Distro: Manjaro
- Desktop: i3
- Display Manager: SDDM
- XPS 9570 (Intel i7-8750H, GTX 1050 Ti)
- Latest stable `optimus-manager`

`optimus-manager.conf`:
```
[intel]
DRI=3
accel=
driver=modesetting
modeset=yes
tearfree=

[nvidia]
DPI=192
PAT=yes
allow_external_gpus=no
ignore_abi=no
modeset=yes
options=overclocking

[optimus]
auto_logout=yes
startup_auto_battery_mode=intel
startup_auto_extpower_mode=intel
startup_mode=intel

switching=nouveau
pci_power_control=yes
pci_remove=no
pci_reset=no
```

**Logs**
```
❯ optimus-manager --status

Optimus Manager (Client) version 1.3

Current GPU mode : nvidia
GPU mode requested for next login : no change
GPU at startup : intel
Temporary config path: no
```

**Comment by xdrie** [comment]
More system information:

GLXgears says it's working
```
❯ glxgears -info
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
GL_RENDERER   = GeForce GTX 1050 Ti/PCIe/SSE2
GL_VERSION    = 4.6.0 NVIDIA 450.57
GL_VENDOR     = NVIDIA Corporation
```

Linux OpenGL games function normally.

Weirdly enough, running `vkmark` shows intel, despite `optimus-manager` saying we're in nvidia mode:
```
❯ vkmark
=======================================================
    vkmark 2017.08
=======================================================
    Vendor ID:      0x8086
    Device ID:      0x3E9B
    Device Name:    Intel(R) UHD Graphics 630 (CFL GT2)
    Driver Version: 83890181
=======================================================
[vertex] device-local=true:
```

this application also hangs. It displays a window but nothing is drawn to it and it is not refreshed.

**Comment by Askannz** [comment]
Strange. What applications have you tried in wine ? Anything shows up in the console output when the app hang ?

**Comment by xdrie** [comment]
I've tried even simple things such as `winecfg` and `wine uninstaller`, which are built into WINE, and have this issue. There is no console output, it just freezes. It works normally in `intel` mode, the issues are only in NVIDIA. There are no other discernable differences in system configuration. It's really bizarre, yeah.

**Comment by Askannz** [comment]
`vkmark` probably shows Intel because it picks it up as the first Vulkan device. `vkcube` does that, and a few games too. You can force it to use Nvidia by setting `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json`. I have no clue about Wine, though.

**Comment by xdrie** [comment]
Interesting, setting the ICD loader explicitly solved my problem. It works perfectly as expected now, thanks!
