### ISSUE TITLE
G-SYNC, 240 Hz

### ISSUE THREAD

**Issue by wizonesolutions** [Askannz/optimus-manager#310]
I just got a Samsung Odyssey G9 monitor (5120x1440 @ 240 Hz). I'm wondering how to enable G-SYNC and how to get it to run at 240 Hz. I'm asking here because it isn't recommended to use NVIDIA's config tool at the same time as optimus-manager, from what I understand, at least if I ever want to switch back and forth between `hybrid` mode and `nvidia` mode.

**Comment by Askannz** [comment]
Assuming you have a compatible monitor connected via DisplayPort, you can enable G-Sync via the Nvidia control panel. optimus-manager doesn't prevent it.

Keep in mind that G-Sync has some limitations on Linux, though. Only works if a single monitor is enabled and the application must be full screen.
