### ISSUE TITLE
Unable to switch from intel to nvidia/hybrid drivers

### ISSUE THREAD

**Issue by TJRegan** [Askannz/optimus-manager#315]
**Describe the bug**
Attempting to switch to nvidia/hybrid fails after automatic logout/login, left still running the Intel drivers. 

**System info**
- Arch Linux
- KDE 
- SDDM
- Lenovo ThinkPad T420 (with nvidia NVS 4200m chip)
- 1.3.1-1 (stable)

**Logs**
ERROR: the latest GPU setup attempt failed at Xorg pre-start hook.
Log at /var/log/optimus-manager/switch/switch-20200901T161544.log

Cannot execute command because of previous errors.

[switch-20200901T161544.log](https://github.com/Askannz/optimus-manager/files/5157305/switch-20200901T161544.log)

**Comment by Askannz** [comment]
What is your `optimus-manager.conf` ?

**Comment by TJRegan** [comment]
> What is your `optimus-manager.conf` ?

[intel]
DRI=3
accel=
driver=modesetting
modeset=yes
tearfree=

[nvidia]
DPI=96
PAT=yes
allow_external_gpus=no
ignore_abi=yes
modeset=yes
options=overclocking

[optimus]
auto_logout=yes
pci_power_control=no
pci_remove=no
pci_reset=no
startup_auto_battery_mode=intel
startup_auto_extpower_mode=nvidia
startup_mode=intel
switching=none

**Comment by TJRegan** [comment]
> What is your `optimus-manager.conf` ?


[intel]
DRI=3
accel=
driver=modesetting
modeset=yes
tearfree=

[nvidia]
DPI=96
PAT=yes
allow_external_gpus=no
ignore_abi=yes
modeset=yes
options=overclocking

[optimus]
auto_logout=yes
pci_power_control=no
pci_remove=no
pci_reset=no
startup_auto_battery_mode=intel
startup_auto_extpower_mode=nvidia
startup_mode=intel
switching=none

**Comment by Askannz** [comment]
While in intel mode and with your current config, what happens if you do `sudo modprobe nvidia` ?

**Comment by nwildner** [comment]
Is this still reproducible on a modern distribution with updated linux kernel, nvidia driver version and using the `optimus-manager-git` package? The project is facing a revamp so, please stick with the `-git` version of this package.

Looks like this is specific from `nvidia` module not being able to load with `nvidia NVreg_UsePageAttributeTable=1'` parameter:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/kernel.py", line 179, in _load_module
    exec_bash("modprobe %s %s" % (module, options))
  File "/usr/lib/python3.8/site-packages/optimus_manager/bash.py", line 18, in exec_bash
    raise BashError(
optimus_manager.bash.BashError: Failed to execute 'modprobe nvidia NVreg_UsePageAttributeTable=1' :
modprobe: ERROR: could not insert 'nvidia': No such device

```
Let me know if this issue is still relevant to you ok?  Can you reproduce in a more modern environment as explained above?

Have a nice week.
