### ISSUE TITLE
GPU turns itself on after resume from sleep.

### ISSUE THREAD

**Issue by omaregb** [Askannz/optimus-manager#317]
**Describe the bug**
After going into suspend and resuming, I noticed the power draw of my laptop jumps by about 20W, and the GPU fan starts spinning even though optimus-manager has it set to the intel GPU since boot. 
I use Manjaro KDE with SSDM
My laptop is a Dell Inspiron 7577 with an Nvidia GTX 1060 MaxQ
I'm using the stable version of optimus-manager

This is my conf  file
`[intel]
DRI=3
accel=
driver=modesetting
modeset=yes
tearfree=

[nvidia]
DPI=96
PAT=yes
allow_external_gpus=no
ignore_abi=no
modeset=yes
options=overclocking

[optimus]
auto_logout=yes
pci_power_control=yes
pci_remove=no
pci_reset=hot_reset
startup_auto_battery_mode=intel
startup_auto_extpower_mode=nvidia
startup_mode=intel
switching=acpi_call`
Nothing seems odd in the logs.

**Comment by omaregb** [comment]
Just noticed similar behaviour has been reported in the past and there's no real solution. Thought I should add that hibernate does work correctly and can be used instead. This limitation should probably be documented.

**Comment by Askannz** [comment]
This issue may be fixed in the latest master, see https://github.com/Askannz/optimus-manager/issues/191#issuecomment-706513965
