### ISSUE TITLE
can no longer boot into hybrid mode

### ISSUE THREAD

**Issue by sebirdman** [Askannz/optimus-manager#318]
**Describe the bug**

I'm not sure what happened, but as of today i noticed that i can no longer boot into hybrid mode. I've been plugged in on nvidia mode for some time so i'm sure i've received some kind of update that broke this along the way.

**System info**
Please include :
- Arch
- XFCE
- Light DM
- X1E Gen2
- latest stable release (optimus-manager)

```
[intel]
DRI=3
accel=
driver=modesetting
modeset=yes
tearfree=

[nvidia]
#DPI=96
PAT=yes
ignore_abi=no
modeset=no
options=overclocking
allow_external_gpus=no

[optimus]
auto_logout=yes
pci_power_control=no
pci_remove=no
pci_reset=no
switching=none
startup_auto_extpower_mode=nvidia
startup_auto_battery_mode=intel
startup_mode=auto
```

**Logs**

None of my logs seem to ever get to the point where they show anything

**Comment by Askannz** [comment]
> i can no longer boot into hybrid mode.
What happens at boot exactly ?

> None of my logs seem to ever get to the point where they show anything
What do you mean ? Are there no files created in `/var/log/optimus-manager/` ?

**Comment by sebirdman** [comment]
@Askannz the screen is black, i can also no longer switch into hybrid mode either. LightDM never starts up.

Yup, not seeing any logs from the boot or switch during this time.

**Comment by sebirdman** [comment]
@Askannz Looks like the fix here: https://github.com/Askannz/optimus-manager/commit/a5b04156bad51254eb41cccf77e1ec86f3d518cf suddenly started applying to my device. Managed to get some weird acpi error logs and noticed the commit.

updating to master fixed this. might be a good idea to get a hotfix in with this.

**Comment by DAMO238** [comment]
I can confirm this behaviour with the latest NVIDIA drivers on Arch using bbswitch.

**Comment by sebirdman** [comment]
Whatever this was, it appears fixed now.
