### ISSUE TITLE
What goes into /etc/optimus-manager/xorg-hybrid.conf?

### ISSUE THREAD

**Issue by smac89** [Askannz/optimus-manager#319]
I was just reading the [docs](https://github.com/Askannz/optimus-manager#configuration), and I noticed that it says we can add options to `/etc/optimus-manager/xorg-hybrid.conf`.

```
Option "nvidiaXineramaInfo" "false"
```

I just tried adding some nvidia options in there, and nothing happened, so I was wondering what options are actually meant to go in there. Thanks.

**Comment by Askannz** [comment]
Late reply, but yes, that looks correct.

You can open the Xorg configuration file generated by optimus-manager at `/etc/X11/xorg.conf.d/10-optimus-manager.conf` and the option you added should be there too.

**Comment by nwildner** [comment]
Sup folks. Closing this case since it looks like this was a general question and it was answered by the repo owner.

Feel free to reopen it if any extra help on this matter is needed.
