### ISSUE TITLE
Optimal way to setup monitor resolution and relative positions?

### ISSUE THREAD

**Issue by hegzploit** [Askannz/optimus-manager#323]
since i can't use my xorg.conf file to configure my external monitors layout, what's the best way to do this?
I'm currently using a xrandr script in my i3 config file but sometimes the timing is off so i have to restart some services to get everything working properly.
I have tried placing the script inside /etc/optimus-manager/xsetup-nvidia.sh but it seems to have no effect for soem reason.
thanks!

**Comment by kinglouie** [comment]
My solution for this is to create a layout using xrandr or arandr, then saving that layout with autorandr. I configured my DM to run `autorandr -c` after display setup so lightdm shows the loginscreen with the correct resolutions and display layouts. 
If you're also using lightdm you have to check out the commands that optimus-mananger runs in the display setup hook and make sure they're still called before running `autorandr -c`.

**Comment by YusufHegazy** [comment]
> My solution for this is to create a layout using xrandr or arandr, then saving that layout with autorandr. I configured my DM to run `autorandr -c` after display setup so lightdm shows the loginscreen with the correct resolutions and display layouts.
> If you're also using lightdm you have to check out the commands that optimus-mananger runs in the display setup hook and make sure they're still called before running `autorandr -c`.

I'm using manjaro with i3 and lightdm atm and my solution was basically running an xrandr script in my i3 config but sometimes it works and sometimes i need to reload i3 for it to work properly, and it can't get the login screen to work would you point me in the right direction to find these starup hooks so i can get my login screen to appear!
thanks!

**Comment by kinglouie** [comment]
It is the diplay setup command here:
https://github.com/Askannz/optimus-manager/blob/master/login_managers/lightdm/20-optimus-manager.conf
You can point to to a shell script but do mind you have to rum prime offload in that script.
