### ISSUE TITLE
Switch from hybrid to Intel with a black screen

### ISSUE THREAD

**Issue by wallena3** [Askannz/optimus-manager#326]
**Describe the bug**
If you add the following three envs in hybird, must remove them before switch to Intel mode.Otherwise, the screen will be black.
It's just a reminder. Maybe add it to Wiki
```bash
__NV_PRIME_RENDER_OFFLOAD=1
__GLX_VENDOR_LIBRARY_NAME="nvidia"
__VK_LAYER_NV_optimus="NVIDIA_only"
```

**System info**
Please include :
- Arch
- KDE
- SDDM
- 80SH Lenovo XiaoXin 700-15ISK
- 1.3
- without custom optimus-manager configuration file

**Comment by Askannz** [comment]
You're right, it seems that Prime offloading breaks compositing in KDE for some reason. I added a warning to the wiki page.
