### ISSUE TITLE
My driver fails to load when i install optimus-manager therefore can't switch to nvidia

### ISSUE THREAD

**Issue by Ivche1337** [Askannz/optimus-manager#334]
**Describe the bug**

**System info**
Please include :
- Arch btw
- i3gaps
- Light DM
- Lenovo 510-15IKB Laptop (ideapad)
- 1.3 version

`optimus-manager --status`  output 
`ERROR: a GPU setup was initiated but Xorg post-start hook did not run.
Log at /var/log/optimus-manager/switch/switch-20201022T212016.log
If your login manager is GDM, make sure to follow those instructions:
https://github.com/Askannz/optimus-manager#important--gnome-and-gdm-users
If your display manager is neither GDM, SDDM nor LightDM, or if you don't use one, read the wiki:
https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting
Cannot execute command because of previous errors`

`lspci -v` output

`03:00.0 3D controller: NVIDIA Corporation GM108M [GeForce 940MX] (rev ff) (prog-if ff)
	!!! Unknown header type 7f
	Kernel modules: nouveau, nvidia_drm, nvidia`

**Comment by Askannz** [comment]
Please post the contents of the switch log.
