### ISSUE TITLE
Add missing check for AMD driver

### ISSUE THREAD

**Issue by Shatur** [Askannz/optimus-manager#337]
For GUI client @Hyper-KVM added a check for AMD driver [here](https://github.com/Shatur95/optimus-manager-qt/blob/6edbe845fccf83fa6b3710f8215c99fdb6be30bf/src/optimusmanager.cpp#L343). I think that in the console version it should also be present.

Also could you put [_check_number_of_sessions()](https://github.com/Askannz/optimus-manager/blob/67d51d01161bcbe9b10eebd97e6844293f1c841d/optimus_manager/client/client_checks.py#L21) before [_check_wayland()](https://github.com/Askannz/optimus-manager/blob/67d51d01161bcbe9b10eebd97e6844293f1c841d/optimus_manager/client/client_checks.py#L16)? In C++ I should [get sessions first](https://github.com/Shatur95/optimus-manager-qt/blob/6edbe845fccf83fa6b3710f8215c99fdb6be30bf/src/optimusmanager.cpp#L267) and then detect if one of them is Wayland. This will not affect anything for you, but this way the GUI client code will look more similar :)

**Comment by es20490446e** [comment]
Just open a pull request, mention me, and I will accept it within a couple of days.
