### ISSUE TITLE
No shell when switching to nVidia

### ISSUE THREAD

**Issue by bphd** [Askannz/optimus-manager#340]
PlasmaShell launch automatically on Intel but not on nVidia session opening
Which is kind of annoying

**Comment by StarGazerM** [comment]
same.....I have to restart plasma by hand .
running manjaro 20 with KDE 5.76, Plasma5.20.3

**Comment by bphd** [comment]
My workaround is to set a key shortcut/binding to `killall plasmashell; plasmashell` for the time when even Yakuake is not opened at the session reload and that we're basically stuck

We're waiting for a solution

**Comment by Askannz** [comment]
Closing as a duplicate of https://github.com/Askannz/optimus-manager/issues/267 (and probably https://github.com/Askannz/optimus-manager/issues/289). Unfortunately I can't reproduce this issue yet.
