### ISSUE TITLE
How to run QEMU/KVM on the GPU ?

### ISSUE THREAD

**Issue by Araly** [Askannz/optimus-manager#341]
Hello,

I'm using VMs with QEMU/KVM and virt-manager.
I can't find a way to whatever needs to be run on the GPU.

I'm using the hybrid mode, but even on nvidia mode, the GPU is not used for the VMs, and I can't find anything related to my VMs in nvtop.

Is there a way to pass the hybrid environment variables to QEMU, to Spice, QXL (I have no idea what should be run on the GPU).

libvirtd.service is run by systemd at startup, and I think it's pretty much what runs all of the things, so maybe I can start there. Can I run a systemd service on the GPU via optimus-manager ?

**Comment by yatish609** [comment]
As far as I've researched, currently, there's no documentation on hardware acceleration using GPU on KVMs. The best you can do for now is GPU passthrough.

**Comment by Askannz** [comment]
Sorry, but this question is not specific to optimus-manager, can't help you there.
I believe Optimus should behave like any dual-GPU setup as far as virtualization is concerned (unless you're in intel/integrated mode and the nvidia driver is unloaded).
