### ISSUE TITLE
gdm-prime package is outdated

### ISSUE THREAD

**Issue by machine-mind** [Askannz/optimus-manager#344]
The official gnome package is already at 3.38.2-1 for some time now. However gdm-prime is still at 3.36.3-1

https://aur.archlinux.org/packages/gdm-prime/
https://www.archlinux.org/packages/extra/x86_64/gdm/

Is there something holding back rebasing the gdm-prime package on the current gdm version? Anything I can do to help?

**Comment by Askannz** [comment]
Fixed, sorry for the delay.
