### ISSUE TITLE
optimus-manager is giving me problems on GNOME Shell

### ISSUE THREAD

**Issue by gabrieleavi** [Askannz/optimus-manager#346]
Good afternoon,
after completing a clean installation of Arch Linux, I followed all the steps to get optimus-manager working on GNOME shell. I installed yay, then I installed gdm-prime and when prompted removed the standard gdm package to avoid conflicts. Afterwards, I edited the file in /etc/gdm/custom.conf. I installed then optimus-manager, I enabled it with systemctl, and then rebooted the system. I logged into my GNOME session, but when I tried to change my graphics card (with the command optimus-manager --switch), this was what the command line gave me:
ERROR: a GPU setup was initiated but Xorg post-start hook did not run.
Log at /var/log/optimus-manager/switch/switch-20201128T144046.log
If your login manager is GDM, make sure to follow those instructions:
https://github.com/Askannz/optimus-manager#important--gnome-and-gdm-users
If your display manager is neither GDM, SDDM nor LightDM, or if you don't use one, read the wiki:
https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting

I tried to read the faq, and common issues and the troubleshooting, but I didn't find a solution. When I try to install the GUI extension for the GNOME shell via GNOME extensions, when I enable it, a pop-up appears saying that I need to install gdm-prime, even if I have gdm-prime installed in my system.
Here are the logs that I received after trying to switch:
[switch-20201128T144046.log](https://github.com/Askannz/optimus-manager/files/5610697/switch-20201128T144046.log)
[switch-20201128T143608.log](https://github.com/Askannz/optimus-manager/files/5610699/switch-20201128T143608.log)
[switch-20201128T142527.log](https://github.com/Askannz/optimus-manager/files/5610700/switch-20201128T142527.log)

I think there is a problem with the gdm-prime package because I saw another recent comment (it was yesterday) on the AUR page that was reporting a similar problem.
Yours faithfully
Gabriele

I'm using:
OS: Arch Linux x86_64
Kernel: [edit] now I am using linux-zen, with nvidia-dkms drivers, however the problem still persists.
DE: GNOME 3.38.1
DM: gdm-prime 3.38.2-1
CPU: Intel i7-6500U
GPU: Nvidia geforce 920MX
GPU: Intel Skylake GT2
RAM: 8GB
optimus-prime version: latest stable release (optimus-manager AUR)
My custom optimus-manager configuration at /etc/optimus-manager/optimus-manager.conf:

> [optimus]
startup_mode=nvidia

[EDIT]
I found out that if I run on the command line prime-offload, I can switch to Nvidia graphics without any problem, but the problem reappears after reboot.

**Comment by lakotamm** [comment]
I am experiencing the exact same error on 2 different laptops.

Lenovo Thinkpad T490 i7-8565U, M250
- Running Manjaro Gnome with kernel 5.9
Acer V3-575G i5-6200U GTX940M
- Running Manjaro Gnome with kernel 5.9
- Running Arch with Gnome with kernel 5.9

Exactly same symptoms and exactly same looking logs. Running prime-offload also temporarily fixes my issue.

**Comment by chebro** [comment]
I'm facing the same issue as well with the same errors and logs. And yes running `prime-offload` does fix the issue for now.

I'm using: 
Kernel: 5.9.11-3-MANJARO
CPU: Intel Core i7-8750H
iGPU: Intel UHD Graphics 630
dGPU: NVIDIA GP107M [GeForce GTX 1050 Mobile]
Driver: video-hybrid-intel-nvidia-455xx-prime
GDM: 3.38.2

**Comment by Shagasresthaa** [comment]
I'm also facing the same issue but it was not after a clean install. I updated gdm-prime to 3.38.2-1 and after that optimus manager stopped working. I'm using
Kernel: 5.9.10-arch1-1
CPU: Intel Core i7 8750H
IGPU: Intel UHD 630
dGPU: NVIDIA GP106M [NVIDIA GTX 1060 Mobile]
GDM: 3.38.2

Here is my log:
[swtch-20201130T112002.log](https://github.com/Askannz/optimus-manager/files/5614049/swtch-20201130T112002.log)

**Comment by Askannz** [comment]
Should be fixed on `-git` by https://github.com/Askannz/optimus-manager/commit/27405889297fb68a89468ce92b3c88b8b5cbaab6, feel free to re-open otherwise.
