### ISSUE TITLE
Can't switch to nvidia

### ISSUE THREAD

**Issue by michaldybczak** [Askannz/optimus-manager#35]
Manjaro KDE testing
kernel 4.19
bumblebee-nvidia non-free setup via mhwd (years ago)

My bumblebee was working great but since my battery died and I need to have laptop always plugged into AC I thought I will switch to nvidia but still wanted to have an option to switch just in case.

I followed the instructions and issued the command:

`optimus-manager --switch nvidia`

Session correctly reloads but I'm still on intel. I have no idea why isn't it working. I don't have nouveau, but it should use bbwistch instead? Also, I don't see any new config files in the areas where I was supposed to clear of configs so it looks as if optimus-manager failed to create own configs in /etc/optimus-manager/
Meaning, there are configs for intel and nvidia there, but only the hashed beginning and not the real lines with configurations, so for example:

```
# You can use this file to add Xorg options which are not covered in the configuration file.
#
# Everything you put here will go to the "Device" section corresponding
# to the Nvidia GPU in the Xorg configuration.
# Lines starting with # are ignored.
#
# Example :
#
# Option "ConnectToAcpid" "0" 
```
and then nothing more.

I haven't rebooted yet but the guide didn't mention this to be necessary and I afraid system won't be bootable. I can revert changes in tty but still I wanted to solve it before doing reboot.

```
sudo systemctl status optimus-manager
● optimus-manager.service - Optimus Manager Commands Daemon
   Loaded: loaded (/usr/lib/systemd/system/optimus-manager.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2018-12-25 13:20:01 CET; 13min ago
 Main PID: 6133 (python)
    Tasks: 1 (limit: 4915)
   Memory: 17.6M
   CGroup: /system.slice/optimus-manager.service
           └─6133 /usr/bin/python -u /usr/bin/optimus-manager-daemon
```

```
optimus-manager --print-mode
Current mode : intel
```

```
sudo journalctl -u display-manager.service
-- Logs begin at Sat 2018-08-11 22:16:00 CEST, end at Tue 2018-12-25 13:57:31 CET. --
-- No entries --
```

Later on after few other tries journalctl shows:

```
-- Logs begin at Sat 2018-08-11 22:16:00 CEST, end at Tue 2018-12-25 18:43:00 CET. --
gru 25 13:20:01 alienware-PC systemd[1]: Started Optimus Manager Commands Daemon.
gru 25 13:20:01 alienware-PC python[6133]: Optimus Manager (Daemon) version 0.5
gru 25 13:20:01 alienware-PC python[6133]: Awaiting commands
gru 25 13:23:45 alienware-PC python[6133]: Received command : nvidia
gru 25 13:23:45 alienware-PC python[6133]: Writing requested mode
gru 25 13:23:45 alienware-PC python[6133]: Restarting login manager
gru 25 13:26:38 alienware-PC python[6133]: Received command : nvidia
gru 25 13:26:38 alienware-PC python[6133]: Writing requested mode
gru 25 13:26:38 alienware-PC python[6133]: Restarting login manager
gru 25 16:19:24 alienware-PC python[6133]: Received command : nvidia
gru 25 16:19:24 alienware-PC python[6133]: Writing requested mode
gru 25 16:19:24 alienware-PC python[6133]: Restarting login manager
gru 25 16:35:06 alienware-PC python[6133]: Received command : nvidia
gru 25 16:35:06 alienware-PC python[6133]: Writing requested mode
gru 25 16:35:06 alienware-PC python[6133]: Restarting login manager
gru 25 17:48:08 alienware-PC python[6133]: Received command : nvidia
gru 25 17:48:08 alienware-PC python[6133]: Writing requested mode
gru 25 17:48:08 alienware-PC python[6133]: Restarting login manager
```

Here is what I did:

> 1. Installation
> 
> sudo pacman -S optimus-manager
> 
> 2. Cleaning driver configuration to backups
> 
> sudo mv /etc/X11/nvidia-xorg.conf /etc/X11/nvidia-xorg.conf.bak
> 
> sudo mv /etc/X11/xorg.conf.d/20-intel.conf /etc/X11/xorg.conf.d/20-intel.conf.bak
> sudo mv /etc/X11/xorg.conf.d/90-mhwd.conf /etc/X11/xorg.conf.d/90-mhwd.conf.bak
> 
> sudo mv /etc/X11/mhwd.d/intel.conf /etc/X11/mhwd.d/intel.conf.bak
> 
> My xorg.conf was already disabled years so I didn’t have to back it up (I already had some ancient xorg.conf.bak file) and skip that part.
>
> 3. Turning Bumblebee off (now and on boot)
> 
> sudo systemctl stop bumblebeed
> sudo systemctl disable bumblebeed
> 
> 4. Make sure the bbswitch module is not loaded at boot time
> 
> Check /etc/modules-load.d/
> All my confs don't have bbswitch there so I'm fine.
> 
> Make backups of the files to be able restore original settings manually, just in case:
> 
> sudo cp /etc/modules-load.d/linux414-virtualbox-host-modules.conf /etc/modules-load.d/linux414-virtualbox-host-modules.conf.bak
> sudo cp /etc/modules-load.d/linux419-virtualbox-host-modules.conf /etc/modules-load.d/linux419-virtualbox-host-modules.conf.bak
> sudo cp /etc/modules-load.d/mhwd-gpu.conf /etc/modules-load.d/mhwd-gpu.conf.bak
> sudo cp /etc/modules-load.d/modules.conf /etc/modules-load.d/modules.conf.bak
> 
> 5. Start optimus-manager (now and on boot):
> 
> sudo systemctl start optimus-manager.service
> sudo systemctl enable optimus-manager.service
> 
> 6. Check if optimus-manager.service is running:
> 
> sudo systemctl status optimus-manager
> 
> 7. Use
> 
> optimus-manager --switch nvidia
> optimus-manager --switch intel

**Comment by michaldybczak** [comment]
OK, found the solution. It was... reboot... ;)

Please, add this to your guide, without it it's incomplete. Current version suggests as it could work without reboot and I was trying to do that because I was afraid that system may not be bootable after changes so I wanted to revert changes during time system was up just in case. Turned out optimus-manager can't work properly without reboot, so first set up, reboot and then use switch commands.

By the way, reverting changes broke my bumblebee setup and it stopped working although I thought that was an easy process: I stopped/disabled optimus-manager, brought back old confs, started/enabled bumblebee, did the --cleanup command, restart and... it fails to unload nouveau so X fails. Optimus-manager did some more changes and I have no idea where and what so I can't revert to the previous configuration.

I believe that documentation should include all the changes and possible manual cleanup so we could revert to the previous configuration which --cleanup command is not doing correctly.

However, since I got optimus-manager working, this isn't that much of a big deal and I'll keep the new setup, it's working correctly.

Thanks

**Comment by Askannz** [comment]
I think you're right : since optimus-manager modifies the Systemd unit corresponding to the display manager, a reboot is probably necessary to have the changes take effect. Thanks, I'll add it to the README.

> By the way, reverting changes broke my bumblebee setup and it stopped working although I thought that was an easy process: I stopped/disabled optimus-manager, brought back old confs, started/enabled bumblebee, did the --cleanup command, restart and... it fails to unload nouveau so X fails. Optimus-manager did some more changes and I have no idea where and what so I can't revert to the previous configuration.

Yes, that's normal. I changed the way optimus-manager works a while ago : now the pre-configuration of the X server and the cleanup are handled by pre/post execution scripts registered to Systemd. Which means they are always executed, even if the optimus-manager daemon is disabled.

At the moment, if you do not want to use optimus-manager anymore, there is no other way than completely removing it.

**Comment by michaldybczak** [comment]
Thanks for the response.

At the moment optimus-manager works great for me so I'm sticking with it. I tried to help someone to make it work but it didn't pan out from some weird reason. It was hard to communicate with this guy because of his poor English but I tried to lay out very carefully all the steps so it would be all very orderly and sure so you can see what we did and maybe you will notice flaws and possible solutions. Maybe it will show you some insights of average users attempts to make it run and give you an idea how to improve it?

Anyway, if you have the stamina to read this lengthy thread, see here:

https://forum.manjaro.org/t/after-install-video-nvidia-manjaro-cant-boot/69146

Since the issue is resolved for me, I'm closing this. Thanks again for the response. I hope that mhwd will incorporate optimus-manager for more easy and trouble-free setup.
