### ISSUE TITLE
Can't switch due to Key Error, and manager in inconsistent state

### ISSUE THREAD

**Issue by nicklan** [Askannz/optimus-manager#350]
**Describe the bug**
Trying to run any `optimus-manager` commands gives me: 
```
ERROR: a GPU setup was initiated but Xorg post-start hook did not run.
Log at /var/log/optimus-manager/switch/switch-20201203T103246.log
If your login manager is GDM, make sure to follow those instructions:
https://github.com/Askannz/optimus-manager#important--gnome-and-gdm-users
If your display manager is neither GDM, SDDM nor LightDM, or if you don't use one, read the wiki:
https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting

Cannot execute command because of previous errors.
```

The mentioned log file:
```
[35] INFO: # Xorg pre-start hook
[35] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'nvidia', 'current_mode': None}
[35] INFO: Requested mode is: nvidia
[35] INFO: Checking for GDM display servers
[1202] INFO: Available modules: ['nouveau', 'bbswitch', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[1202] INFO: Unloading modules ['nouveau'] (if loaded)
[1256] INFO: Loading module nvidia
[1996] INFO: Loading module nvidia_drm
[2747] INFO: Loaded extra Intel Xorg options (0 lines)
[2748] INFO: Loaded extra Intel Xorg options (1 lines)
[2748] INFO: Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf
[2748] INFO: Writing state {'type': 'pending_post_xorg_start', 'switch_id': '20201203T103246', 'requested_mode': 'nvidia'}
[2748] INFO: Xorg pre-start hook completed successfully.
```

Also, when trying to switch from the graphical interface I get this in the journal:
```
Dec 03 10:26:37 host python3[1723]: [54608] INFO: Received command : {
Dec 03 10:26:37 host python3[1723]:     "args": {
Dec 03 10:26:37 host python3[1723]:         "mode": "nvidia"
Dec 03 10:26:37 host python3[1723]:     },
Dec 03 10:26:37 host python3[1723]:     "type": "switch"
Dec 03 10:26:37 host python3[1723]: }
Dec 03 10:26:37 host python3[1723]: [54608] INFO: Writing requested GPU mode nvidia
Dec 03 10:26:37 host python3[1723]: [54608] ERROR: Invalid command  "{
Dec 03 10:26:37 host python3[1723]:     "args": {
Dec 03 10:26:37 host python3[1723]:         "mode": "nvidia"
Dec 03 10:26:37 host python3[1723]:     },
Dec 03 10:26:37 host python3[1723]:     "type": "switch"
Dec 03 10:26:37 host python3[1723]: }
Dec 03 10:26:37 host python3[1723]: " ! Key error : 'current_mode'
```

This coincided with the update to python 3.9, so might be related to #349, but I've reinstalled all the related packages already.

**System info**
Please include :
- Your distribution: arch
- Your desktop manager: i3
- You display manager: LightDM
- The version of optimus-manager you are using : latest stable release (optimus-manager)
- Your custom optimus-manager configuration file at `/etc/optimus-manager/optimus-manager.conf`:
```
[optimus]

# This parameter defines the method used to power switch the Nvidia card. See the documentation
# for a complete description of what each value does. Possible values :
#
# - nouveau : load the nouveau module on the Nvidia card.
# - bbswitch : power off the card using the bbswitch module (requires the bbswitch dependency).
# - acpi_call : try various ACPI method calls to power the card on and off (requires the acpi_call dependency)
# - custom: use custom scripts at /etc/optimus-manager/nvidia-enable.sh and /etc/optimus-manager/nvidia-disable.sh
# - none : do not use an external module for power management. For some laptop models it's preferable to
#          use this option in combination with pci_power_control (see below).
switching=none

# Enable PCI power management in Intel mode.
# This option is incompatible with acpi_call and bbswitch, so it will be ignored in those cases.
pci_power_control=no

# Remove the Nvidia card from the PCI bus.
# May prevent crashes caused by power switching.
# Ignored if switching=nouveau or switching=bbswitch.
pci_remove=no

# Reset the Nvidia card at the PCI level before reloading the nvidia module.
# Ensures the card is in a fresh state before reloading the nvidia module.
# May fix some switching issues. Possible values :
#
# - no : does not perform any reset
# - function_level : perform a light "function-level" reset
# - hot_reset : perform a "hot reset" of the PCI bridge. ATTENTION : this method messes with the hardware
#         directly, please read the online documentation of optimus-manager before using it.
#         Also, it will perform a PCI remove even if pci_remove=no.
#
pci_reset=no

# Automatically log out the current desktop session when switching GPUs.
# This feature is currently supported for the following DE/WM :
# KDE Plasma, GNOME, XFCE, LXDE, Deepin, i3, Openbox, AwesomeWM, bspwm
# If this option is disabled or you use a different desktop environment,
# GPU switching only becomes effective at the next graphical session login.
auto_logout=yes

# GPU mode to use at computer startup. Possible values: nvidia, intel, hybrid, auto
# "auto" is a special mode that auto-detects if the computer is running on battery
# and selects a proper GPU mode. See the other options below.
startup_mode=nvidia
# GPU mode to select when startup_mode=auto and the computer is running on battery.
# Possible values: nvidia, intel, hybrid
startup_auto_battery_mode=nvidia
# GPU mode to select when startup_mode=auto and the computer is running on external power.
# Possible values: nvidia, intel, hybrid
startup_auto_extpower_mode=nvidia


[intel]

# Driver to use for the Intel GPU. Possible values : modesetting, intel
# To use the intel driver, you need to install the package "xf86-video-intel".
driver=modesetting

# Acceleration method (corresponds to AccelMethod in the Xorg configuration).
# Only applies to the intel driver.
# Possible values : sna, xna, uxa
# Leave blank for the default (no option specified)
accel=

# Enable TearFree option in the Xorg configuration.
# Only applies to the intel driver.
# Possible values : yes, no
# Leave blank for the default (no option specified)
tearfree=

# DRI version. Possible values : 2, 3
DRI=3

# Whether or not to enable modesetting for the nouveau driver.
# Does not affect modesetting for the Intel GPU driver !
# This option only matters if you use nouveau as the switching backend.
modeset=yes

[nvidia]

# Whether or not to enable modesetting. Required for PRIME Synchronization (which prevents tearing).
modeset=yes

# Whether or not to enable the NVreg_UsePageAttributeTable option in the Nvidia driver.
# Recommended, can cause poor CPU performance otherwise.
PAT=yes

# DPI value. This will be set using the Xsetup script passed to your login manager.
# It will run the command
# xrandr --dpi <DPI>
# Leave blank for the default (the above command will not be run).
DPI=96

# If you're running an updated version of xorg-server (let's say to get PRIME Render offload enabled),
# the nvidia driver may not load because of an ABI version mismatch. Setting this flag to "yes"
# will allow the loading of the nvidia driver.
ignore_abi=no

# Set to yes if you want to use optimus-manager with external Nvidia GPUs (experimental)
allow_external_gpus=no

# Comma-separated list of Nvidia-specific options to apply.
# Available options :
# - overclocking : enable CoolBits in the Xorg configuration, which unlocks clocking options
#   in the Nvidia control panel. Note: does not work in hybrid mode.
# - triple_buffer : enable triple buffering.
options=overclocking
```

**Logs**
Run `optimus-manager --status` in a console, and if an error message appears, post it here: see above

**Comment by biggus-dickus** [comment]
The same thing happened to me after I decided to upgrade the [`gdm-prime`](https://aur.archlinux.org/packages/gdm-prime/) to 3.38.2-1. Also had to rebuild `optimus-manager` first due to the mentioned Python 3.9 issue.

Everything's still working fine with `gdm-prime 3.36.3-1` though.

**Comment by gabrieleavi** [comment]
Having the same problem in GNOME shell, when I installed gdm-prime 3.38.2-1 after a clean install of Arch, the error appears when I try to switch to nvidia graphics. If you want to solve the problem temporarily, try to run prime-offload, it will restart Xorg post-hook and it will allow you to switch graphics card, however, the problem reappears after reboot.
I created an issue 8 days ago about this, #346.
I had to rebuild optimus-manager too after python 3.9 update.

I'm using:
OS: Arch Linux x86_64
Kernel: linux-zen, with nvidia-dkms drivers
DE: GNOME 3.38.1
GDM-PRIME: 3.38.2-1
CPU: Intel i7-6500U @ 3.100 GHz
GPU: Nvidia geforce 920MX
GPU: Intel Skylake GT2 [Intel HD Graphics 520]
RAM: 8GB

**Comment by ksdrummer** [comment]
I have the exact same problem (and same logs). Thank you @gabrieleavi for the hint, running `prime-offload` does allow to switch to nvidia :smiley: 

OS : Arch Linux x86_64
Kernel : 5.9.12-arch1-1
DE : Gnome 3.38.2
GDM-PRIME : 3.38.2-1

**Comment by gabrieleavi** [comment]
> I have the exact same problem (and same logs). Thank you @gabrieleavi for the hint, running `prime-offload` does allow to switch to nvidia 
> 
> OS : Arch Linux x86_64
> Kernel : 5.9.12-arch1-1
> DE : Gnome 3.38.2
> GDM-PRIME : 3.38.2-1

No problem! Let's just hope now that Askannz will solve this issue.

**Comment by Askannz** [comment]
@biggus-dickus, @gabrieleavi, @ksdrummer The problem should now be fixed on GDM (see https://github.com/Askannz/optimus-manager/commit/27405889297fb68a89468ce92b3c88b8b5cbaab6).

Seems that LightDM breaks for a different reason, though.
@nicklan, do you have any custom configuration in `/etc/lightdm/lightdm.conf` or `/etc/lightdm/lightdm.conf.d/` ?

**Comment by nicklan** [comment]
thanks @Askannz. in my `lightdm.conf` these are the only options set:

```
[LightDM]
run-directory=/run/lightdm

[Seat:*]
session-wrapper=/etc/lightdm/Xsession
display-setup-script=/home/user/.screenlayout/login.sh
```

that login.sh just runs xrandr to set the correct resolution

I do have a `/etc/lightdm/lightdm.conf.d/20-optimus-manager.conf`. that file is:
```
[Seat:*]
# Force using X
type=local
display-setup-script=/sbin/prime-offload
display-stopped-script=/sbin/prime-switch
```

**Comment by Askannz** [comment]
```
display-setup-script=/home/user/.screenlayout/login.sh
```
That's the issue. This line overrides the configuration installed by optimus-manager, which adds a hook at Xorg start-up (`prime-offload`) to set up the laptop screen.

If you have custom commands to run a Xorg start-up for nvidia mode, you can put them in `/etc/optimus-manager/xsetup-nvidia.sh` instead.

**Comment by deesnook** [comment]
> @biggus-dickus, @gabrieleavi, @ksdrummer The problem should now be fixed on GDM (see [2740588](https://github.com/Askannz/optimus-manager/commit/27405889297fb68a89468ce92b3c88b8b5cbaab6)).

That's good news! do we know which version the commit will be included in?

**Comment by Askannz** [comment]
Not sure yet, there are a few changes I would like to implement before releasing a new version, but I haven't had a ton of time/motivation for that recently.

You can use optimus-manager-git in the meantime, it points to the master branch which includes this commit.

**Comment by nwildner** [comment]
@biggus-dickus, @gabrieleavi, @ksdrummer, could you please confirm if this issue still affects you?

Since the last update on this case was from 3 years ago, we'll keep this case opened for some days and close it if no answer is provided.

Have a nice week ahead.

**Comment by ksdrummer** [comment]
Sorry I don't use it anymore...

**Comment by biggus-dickus** [comment]
> @biggus-dickus, @gabrieleavi, @ksdrummer, could you please confirm if this issue still affects you?

I think you should've closed it 3 years ago :-D

The issue hasn't affected me ever since, although I stopped using GDM in late 2021.
