### ISSUE TITLE
GDM not working

### ISSUE THREAD

**Issue by inzar98** [Askannz/optimus-manager#36]
**Describe the bug**
I cant switch to nvidia with nouveau mode. In bbswitch mode I cant turn back to intel :confused: 

I dont want to use bbswitch tho cuz my hardware not works good with it 

**** LightDM with Gnome works but gnome with lightdm doesnt have lockscreen etc. ****

**System info**
Manjaro
Gnome
GDM

**Logs**
Please attach the following logs (if you are able to):
- Kernel : https://paste.ee/p/7FRmw
- Xorg : https://paste.ee/p/D6UGD
- Display manager : https://paste.ee/p/pskEr
- Daemon : https://paste.ee/p/Cfoni

When I set modeset=no in nvidia, I can switch to nvidia but I cant back to intel:
```
Ara 26 23:52:32 Tux python[2183]: Requested mode : intel
Ara 26 23:52:32 Tux python[2183]: Switching to Intel
Ara 26 23:52:32 Tux python[2183]: Unloading Nvidia modules
Ara 26 23:52:32 Tux python[2183]: Cannot switch GPUS : Cannot unload Nvidia modules : Failed to execute 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia' : modprobe: FATAL: Module nvidia_drm is in use.
Ara 26 23:52:32 Tux systemd[1]: Started GNOME Display Manager.
Ara 26 23:52:32 Tux gdm-launch-environment][2200]: accountsservice: Could not get current seat: Veri yok
Ara 26 23:52:38 Tux gdm-password][2375]: accountsservice: Could not get current seat: Veri yok
Ara 26 23:52:42 Tux gdm-password][2375]: pam_unix(gdm-password:session): session opened for user loradona by (uid=0)
```

**Comment by inzar98** [comment]
On intel driver script switching to modesetting, on modesetting driver script switching gonna same modesetting driver

**Comment by inzar98** [comment]
![ekran goruntusu - 2018-12-27 00-49-49](https://user-images.githubusercontent.com/4786066/50458073-7aefc880-0971-11e9-8f98-5b37902b615c.png)
I have forked https://github.com/p-e-w/argos for gnome indicator. When U solved the issue I'm gonna share it :)

**Comment by inzar98** [comment]
My hdd burned today. Idk when I buy a hdd or ssd  :sob:

**Comment by inzar98** [comment]
Okey turning to intel is solved. But I need to use "optimus-manager --switch nvidia" twice. First use isnt allow me to use nvidia

**Comment by inzar98** [comment]
https://github.com/inzar98/optimus-manager-argos

Can you add this to README ? Its will be useful for people :smile:

**Comment by inzar98** [comment]
And https://paste.ee/p/gwtJx nearly fixed but I need to switch twice :/

**Comment by Askannz** [comment]
Alright, thanks for testing. The problem is likely here :

```
Cannot unload modules : Failed to execute 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia nouveau' : modprobe: FATAL: Module nouveau is in use.
```

and here

```
Cannot unload modules : Failed to execute 'modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia nouveau' : modprobe: FATAL: Module nvidia_drm is in use.
```

Looks like something is holding onto the GPU even after the session has been terminated, preventing module unloading. The faulty process could be `systemd-logind`, as @kuroni suggested in his PR. The problem is, his fix causes `systemctl` to hang on my machine, so I'm looking for an alternate solution.

Here's another PKGBUILD, could you try it ? https://pastebin.com/uz69nqnh
This branch includes a fix to try to kill `systemd-logind` directly, plus some additional logging.
If it doesn't work, there should be a log file created in `/var/log/optimus_manager_dri.log`. Please post it as well.

I'll add the applet to the README :+1:

**Comment by Askannz** [comment]
Excellent ! So looks like `systemd-logind` was indeed the culprit. I'll merge that fix and push a new release soon.

**Comment by Askannz** [comment]
New v0.6 release pushed to AUR should have the fix.
