### ISSUE TITLE
keys for extra xorg.conf options

### ISSUE THREAD

**Issue by civic9** [Askannz/optimus-manager#364]
Hi,

Keys in envs.py for extra xorg.conf options:
```
EXTRA_XORG_OPTIONS_PATHS = {
    "integrated-gpu": "/etc/optimus-manager/xorg-integrated-gpu.conf",
    "nvidia-gpu": "/etc/optimus-manager/xorg-nvidia-gpu.conf"
}
```
are different than keys used in config generation code, e.g.
_make_nvidia_device_section @ xorg.py:
line.285: ``` if "nvidia" in xorg_extra.keys():```

So extra options are now ignored (at least for nvidia, I didn't check others).

**Comment by Askannz** [comment]
Thanks, good catch !

To prevent further confusion, each `(mode, gpu)` pair now has its own file under `/etc/optimus-manager/xorg/`.
