### ISSUE TITLE
nvidia modules aren't unloaded

### ISSUE THREAD

**Issue by frstrikerman** [Askannz/optimus-manager#37]
When I switch back to intel I have to manually unload nvidia kernel modules here is the log:

[optimus-manger.log](https://github.com/Askannz/optimus-manager/files/2712141/optimus-manger.log)

[lightdm.log](https://github.com/Askannz/optimus-manager/files/2712143/lightdm.log)

**Comment by frstrikerman** [comment]
I just tried and that didn't fix anything

**Comment by inzar98** [comment]
Try last pkgbuild it works

**Comment by frstrikerman** [comment]
I just build and reboot and when I execute `glxspheres64` after switching back to intel : 
```
62464 (61 spheres * 1024 polys/spheres)

ERROR in line 643:
Could not obtain RGB visual with requested properties
```
[lightdm.log](https://github.com/Askannz/optimus-manager/files/2718187/lightdm.log)
[optimus-manger.log](https://github.com/Askannz/optimus-manager/files/2718188/optimus-manger.log)

**Comment by Askannz** [comment]
Did you use the new PKGBUILD I posted here ? https://github.com/Askannz/optimus-manager/issues/36#issuecomment-450611712

If you did, there should be a log file in `/var/log/optimus_manager_dri.log`. Please post it as well.

**Comment by frstrikerman** [comment]
Yeah and Its empty

**Comment by Askannz** [comment]
Apologies, there was a mistake in my logging command. Could you try again ? You can use the same PKGBUILD, just make sure to delete the previously built package first.

**Comment by frstrikerman** [comment]
So this time logs are still empty but everything seams to work and I can't reproduce the issue

**Comment by Askannz** [comment]
Weird. Literally all I did was changing the logging, it should not affect anything else. Can you post the new LightDM log ?

**Comment by frstrikerman** [comment]
[optimus-manger.log](https://github.com/Askannz/optimus-manager/files/2718330/optimus-manger.log)
[lightdm.log](https://github.com/Askannz/optimus-manager/files/2718331/lightdm.log)

**Comment by inzar98** [comment]
you have to remove optimus-manager-git firstly have you done it ?

**Comment by inzar98** [comment]
> Did you use the new PKGBUILD I posted here ? [#36 (comment)](https://github.com/Askannz/optimus-manager/issues/36#issuecomment-450611712)
> 
> If you did, there should be a log file in `/var/log/optimus_manager_dri.log`. Please post it as well.

conflicts=('optimus-manager') is wrong. Have to add optimus-manager-git too

**Comment by frstrikerman** [comment]
Pacman found a conflict and asked me to replace it

**Comment by frstrikerman** [comment]
But I have only one version installed it's `optimus-manager-logind-fix`

**Comment by Askannz** [comment]
Better to uninstall everything and rebuild the package from scratch using the PKGBUILD.

**Comment by Askannz** [comment]
Looks like the problem is fixed then. A new release has been pushed to AUR.
