### ISSUE TITLE
How to set custom reslution for external monitor? `xrandr` don't work.

### ISSUE THREAD

**Issue by shivanshu-semwal** [Askannz/optimus-manager#372]
**Describe the bug**
So I do ` X11 optimus-manager --switch nvidia` and it works. Now `xrandr -q`, and it detect the external monitor (`HDMI-0 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 300mm x 230mm
`), but the resolution I want to use (`1600x900`) is missing, i used `xrandr` to add new mode but i get this error,
```
X Error of failed request:  BadName (named color or font does not exist)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  16 (RRCreateMode)
  Serial number of failed request:  50
  Current serial number in output stream:  50
```
I tried googling this but I can't find any suitable article.

Now how should I set the custom resolution (1600x900).

**System info**
Please include :
- Your distribution - Manjaro
- Your desktop manager - GNOME
- You display manager - LightDM 
- Your laptop model, if you think it could be related to the problem - `Lenovo Legion Y540`
- The version of optimus-manager you are using : `Optimus Manager (Client) version 1.3`
- Your custom optimus-manager configuration file at `/etc/optimus-manager/optimus-manager.conf`, if you made one

**Logs**
`/var/log/optimus-manager/switch/` and `/var/log/optimus-manager/daemon/`.
[logs](https://gist.github.com/shivanshu-semwal/f728571d1d7e6cc19ffa2a21c51413ae)

**Comment by sakutty** [comment]
Did you fix this??
