### ISSUE TITLE
When I switch to Nvidia, the built-in screen of the laptop stays black but I can still input my password or use monitors plugged to a video output

### ISSUE THREAD

**Issue by erikdrozina** [Askannz/optimus-manager#375]
**Describe the bug**
When I switch to Nvidia, the built-in screen of the laptop stays black but I can still input my password or use monitors plugged to a video output

**System info**
Please include :
- Distribution: **Manjaro**
- Desktop manager: **KDE**
- Display manager: **SDDM, i already commented DisplayCommand and DisplayStopCommand**
- Your laptop model: **Hp Pavilion 15bn450ns with integrated intel gpu and Nvidia 1050 mobile**
- The version of optimus-manager you are using : **tried both versions but still same issue with black screen on inbuilt laptop screen, now on git version**
- Your custom optimus-manager configuration file: **default optimus-manager.conf: https://del.dog/sylunafiby**

**Logs**
optimus-manager --status : **no error**
/var/log/optimus-manager/daemon/ : https://del.dog/imycinguna
/var/log/optimus-manager/switch/ : https://del.dog/ulifappyck

Thanks in advance

**Comment by nwildner** [comment]
Closing this case: Logfiles are not available anymore + this case is 3+ years old and might not be reproducing.
A lot has changed recently, please track `optimus-manager-git` to get the recent fixes made to the project.
