### ISSUE TITLE
After suspend, getting "ERROR: a GPU setup was initiated but Xorg post-start hook did not run."

### ISSUE THREAD

**Issue by nariox** [Askannz/optimus-manager#377]
**Describe the bug**
After suspend, I get `ERROR: a GPU setup was initiated but Xorg post-start hook did not run.` when trying to run any `optimus-manager` command. 

**System info**
- Archlinux (fully up-to-date as of 02/15/21)
- Running GNOME 3.38.3
- GDM (using patched gdm-prime and libgdm-prim from AUR)
- T480 with mx150 (I don't think it is related to the problem)
- `optimus-manager` version 1.3.1 (latest stable)
- No significant changes in conf file. Using `bbswitch` and disabled auto log-off

**Workaround**
Running `# prime-offload` after suspend fixes the issue. And I can run `optimus-manager` commands. I could set-up systemd to run prime-offload after wake, but I'm not sure if this would cause issues or if there is a right-way-to-solve-it™

**Comment by nariox** [comment]
The full output of `optimus-manager` is:
```
ERROR: a GPU setup was initiated but Xorg post-start hook did not run.
Log at /var/log/optimus-manager/switch/switch-20210216T084509.log
If your login manager is GDM, make sure to follow those instructions:
https://github.com/Askannz/optimus-manager#important--gnome-and-gdm-users
If your display manager is neither GDM, SDDM nor LightDM, or if you don't use one, read the wiki:
https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting

Cannot execute command because of previous errors.
```

The logs don't really show anything (that I can see), but I'm posting it here: [LINK](https://pastebin.com/c0Q2DSqv)

**Comment by nwildner** [comment]
Hi @nariox . Is this still happening with a more up-to-date distro install and using `optimus-manager-git` ?

Since the last comment on this case was from 3 years ago and a lot has changed in many aspects of multiple software(nvidia, optimus-manager, linux), we'll keep this case opened for some days and close it if no answer is provided.

Have a nice week ahead.
