### ISSUE TITLE
Allow saving of XFCE sessions (or execution of custom scripts) when switching

### ISSUE THREAD

**Issue by jsmnbom** [Askannz/optimus-manager#38]
Feature request:

It would be lovely if optimus-manager could save my XFCE session before switching GPU, so the programs I had open will automatically reopen.

The only way I know of to do this is to execute:
``` bash
dbus-send --session --dest=org.xfce.SessionManager --print-reply /org/xfce/SessionManager org.xfce.Session.Manager.Checkpoint string:""
```

So either implementing some Desktop Environment integration to do this properly across mulitple DEs, or simply providing a way to execute a script before switching would be amazing to have.

**Comment by Askannz** [comment]
I'll look into it, but no promises. To be honest I'd rather not have too much code that's dependent on a specific DE, and it looks like there is no DE-agnostic way to save a session yet.

In the meantime, you can always wrap `optimus-manager` into a custom script, like so :

```
#!/bin/bash

dbus-send --session --dest=org.xfce.SessionManager --print-reply /org/xfce/SessionManager org.xfce.Session.Manager.Checkpoint string:""
optimus-manager --switch auto --no-confirm
```

**Comment by jsmnbom** [comment]
Yea, I do understand wanting it to be DE-agnostic. I do still think that it would be benificial to allow executing a script before switching though - especially if a systray like #40 gets implemented (which would bypass the custom script suggestion).
Thanks for that suggestion tho, I will use it for now ^^

**Comment by Zeioth** [comment]
I also use XFCE, but +1 to keep it DE agnostic. After all it won't be necessary to reboot once nvidia implements [render offload](https://devtalk.nvidia.com/default/topic/957981/linux/prime-render-offloading-on-nvidia-optimus/post/4971507/#4971507).

**Comment by nwildner** [comment]
Hello @jsmnbom 
Is this issue still relevant to you? It's been 5 years since the last comment from this case and a lot has changed on all aspects(nvidia drivers, optimus-manager, render offload, etc)

I'll keep this case opened for some days and close if no answer is provided

Cheers
