### ISSUE TITLE
some confusion

### ISSUE THREAD

**Issue by StoicIndividual** [Askannz/optimus-manager#380]
I'm a little confused on which one I'm supposed to use for nvidia optimus, nvidia-prime or optimus manager, I know you can manually run applications using the nvidia gpu by running them with nvidia-prime, and that you can switch the graphic card entirely with optimus manager, but since optimus manager has a hybrid option (which as far as I know does the same thing nvidia-prime does just automatically?), I want to know whether they are completely different things or incompatible.

**Comment by Kr1ss-XD** [comment]
Basically, the `nvidia-prime` package can be used in `optimus-manager`'s hybrid mode to run applications on the dGPU, on a per-case base. For this purpose, it provides the `prime-run` command.

This command sets some variables in the environment of the launched application, which cause it to utilize the nvidia card. You can also manually set these variables, as described in this [wiki paragraph](https://github.com/Askannz/optimus-manager/wiki/Nvidia-GPU-offloading-for-%22hybrid%22-mode#setup); `prime-run` just simplifies this.

On the other hand, if you want your computer to _always_ run in hybrid mode, you could use `nvidia-prime` without `optimus-manager`, if you so prefer.

**Comment by StoicIndividual** [comment]
Ah, I see, thanks for clearing up the confusion
