### ISSUE TITLE
cannot stat 'config/xsetup-intel.sh': No such file or directory ==>  01-03-2021.

### ISSUE THREAD

**Issue by rapoma** [Askannz/optimus-manager#385]
after running pacaur -Syu (01/03/2021)
the error appears during build, the following logs

==> Starting package()...
install: cannot stat 'config/xsetup-intel.sh': No such file or directory

and indeed its not there seeing the source in github 

**System info**
- Arch
- Plasma
- Optimus Manager (Client) version 1.3

**Logs**
The current version work well no error

**Comment by Kr1ss-XD** [comment]
@rapoma As mentioned in [the comments](https://aur.archlinux.org/packages/optimus-manager/#comment-794148), if you remove (or comment) the line
```sh
install -Dm755 config/xsetup-intel.sh "$pkgdir/etc/optimus-manager/xsetup-intel.sh"
```
the build runs through. That line is a leftover from the previous PKGBUILD, and has been forgotten to remove.

**Comment by rapoma** [comment]
thanks

**Comment by lenuswalker** [comment]
Shouldn't this stay open until the PKGBUILD file is fixed?
