### ISSUE TITLE
Monitor doesn't work when on hybrid mode.

### ISSUE THREAD

**Issue by sticsk** [Askannz/optimus-manager#387]
On my ASUS TUF Gaming FX505DT with GTX1650 and AMD Ryzen 5 3550H, when I'm on Hybrid mode, I can see my monitor on `nvidia-settings` but it doesn't have any output. 

Whenever I want to use my monitor or TV, I have to switch to nvidia in order to get it work and it's pretty incovenient, is it any way to fix this?

**Comment by PeterBadzhakov** [comment]
Same issue on FX505DT 3750H, 1650.

**Comment by bzgec** [comment]
Same here:
- Arch Linux
- Acer Nitro AN515-44
  - AMD Ryzen 7 4800H
  - Nvidia GTX 1650-Ti (Mobile)

**Comment by tgelter** [comment]
Depending on your hardware, you may be out of luck. For example, I have this laptop: https://wiki.archlinux.org/index.php/Lenovo_ThinkPad_X1_Extreme
>Both the HDMI port and DisplayPort outputs created when using either a USB-C adapter or Thunderbolt dock are wired to the Nvidia dGPU.

**Comment by bjsowa** [comment]
Nvidia added support for AMDGPU Reverse PRIME with the 470.42.01 version of the driver. I recommend updating it and trying again as it worked in my case.

**Comment by tgelter** [comment]
> Nvidia added support for AMDGPU Reverse PRIME with the 470.42.01 version of the driver. I recommend updating it and trying again as it worked in my case.

I've been testing this out since yesterday morning (thanks for the tip @bjsowa!) and things mostly work. However, I've noticed that if I try to disable my built-in laptop display, I saw some crashes, including when trying to suspend the laptop.

**Comment by nwildner** [comment]
Hello @sticsk  Is this still reproducible on a modern distribution with updated linux kernel, nvidia driver version and using the `optimus-manager-git` package? The project is facing a revamp so, please stick with the `-git` version of this package.

Let me know if this issue is still relevant to you ok?

Have a nice week.
