### ISSUE TITLE
[Possible Feature Request] How to make optimus-manager to use last option to boot.

### ISSUE THREAD

**Issue by mhasadi78** [Askannz/optimus-manager#388]
Hi.
I simply want that when I switch to NVIDIA it stays at that mode until I change it manually, but now it resets at every reboot to integrated mode.
I don't know if there is a way to do it or this is a feature request.

P.S.  I do know that I can use configure file to boot every time with NVIDIA but what I want is to boot with the last mode that I used. Either Intel or NVIDIA.

Thanks.

**Comment by Kr1ss-XD** [comment]
Hi @mhasadi78 

There used to be an option `--set-startup`, but that has has been removed in favor of the setting in the configuration file.

However, you could add something like this to your shell startup file : 

```sh
optimus() {
	case "$1" in
		integrated|nvidia)
			((EUID)) && local sudo=sudo
			$sudo sed -i "/^[[:blank:]]*startup_mode/s/=.*/=$1/" /etc/optimus-manager/optimus-manager.conf &&
			optimus-manager --switch $1;;
		*)
			echo 'Usage:  optimus [integrated|nvidia]'
			return 1
	esac
}
```

This would enable you to switch modes _and_ set the startup mode in one step. The example is written for bash, not sure about different shells.

**Comment by es20490446e** [comment]
Just edit `/etc/optimus-manager/optimus-manager.conf` to have:

```
[optimus]
startup_mode=nvidia
```
