### ISSUE TITLE
RTD3 amd integrated support 

### ISSUE THREAD

**Issue by jorge1b3** [Askannz/optimus-manager#389]
Runtime D3 status:          Not supported
Video Memory:               Active

GPU Hardware Support:
 Video Memory Self Refresh: Supported
 Video Memory Off:          Supported

CPU: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx
GPU: GeForce GTX 1650

ASUS TUF Gaming FX505DT_FX505DT

**Comment by whenov** [comment]
RTD3 is only supported on Intel Coffeelake (8th gen) and above. There is no evidence yet that it works with AMD processors.

**Comment by pm4rcin** [comment]
I have the Legion 5-15ARH05.

OS: EndeavourOS 5.11.10-arch1-1
CPU: AMD Ryzen 5 4600H
GPU: Geforce GTX 1650

Output looks like it has support for that (disabled):
```
cat /proc/driver/nvidia/gpus/0000:01:00.0/power
Runtime D3 status:          Disabled
Video Memory:               Active

GPU Hardware Support:
 Video Memory Self Refresh: Supported
 Video Memory Off:          Supported
```
I can help with testing if you have any ideas.
