### ISSUE TITLE
Massive battery drain both in integrated and nvidia mode

### ISSUE THREAD

**Issue by Krzysztof-Dziardziel** [Askannz/optimus-manager#392]
Good morning,

Firstly, thanks for making optimus-manager - it's awesome!

I'm having an issue because even if I'm working in integrated mode, the battery drains ultra fast:
- before installation of optimus-manager: ~5h of work in IDEA,
- after installation in integrated mode: ~1h of work in IDEA.
 
I suppose nvidia isn't turned off properly in integrated mode because laptop is heating up much more than before install.

Also when I plug into my docking station (WD19TB) it doesn't switch to nvidia automatically which I think it should.

XPS 9500
UHD+ screen

Here's my config:
```
[optimus]

switching=none
pci_power_control=no
pci_remove=no
pci_reset=no
auto_logout=yes
startup_mode=integrated
startup_auto_battery_mode=integrated
startup_auto_extpower_mode=nvidia

[intel]

driver=modesetting
accel=
tearfree=
DRI=3
modeset=yes

[amd]

driver=modesetting
tearfree=
DRI=3

[nvidia]

modeset=yes
PAT=yes
DPI=96
ignore_abi=no
allow_external_gpus=no
options=overclocking
dynamic_power_management=no
dynamic_power_management_memory_threshold=
```

Thanks for help!

**Comment by whenov** [comment]
I had the same problem before. When the nvidia drivers were not loaded, the power consumption of my nvidia card was ~20W. Changing to hybrid mode reduced it to ~5W. 

The acpi_call and bbswitch methods doesn't work for me, so I guess I have to accept this suboptimal result.

**Comment by whenov** [comment]
I just tried the integrated mode with `pci_remove=yes` and the result is very good. The nvidia card doesn't consume any power at all.

**Comment by Krzysztof-Dziardziel** [comment]
> I just tried the integrated mode with `pci_remove=yes` and the result is very good. The nvidia card doesn't consume any power at all, which leaves me a total discharging rate at 6.8W.

Is this how the file should look like?
```
...

[intel]

driver=modesetting
accel=
tearfree=
DRI=3
modeset=yes
pci-remove=yes

...
```

**Comment by Kr1ss-XD** [comment]
@Krzysztof-Dziardziel `pci-remove=yes` needs to be in the `[optimus]` section, not `[intel]`.
Otherwise it looks okay to me.

**Comment by Krzysztof-Dziardziel** [comment]
It works awesome guys! Thanks for help!
