### ISSUE TITLE
[GNOME + GDM] Stopping login services does not stop the desktop environment

### ISSUE THREAD

**Issue by kuroni** [Askannz/optimus-manager#4]
To my experience, I always seem to stuck at `Warning : Xorg server does not want to stop.` when trying to switch. This leads to many issues, including having to manually logging out the DE and restarting the login service when switching to nvidia, and the login service (in this case `gdm`) crashes when trying to switch back to intel. However, when I first log out of the desktop environment and run the switching script in a virtual terminal, everything works fine and dandy.

**Login manager**: GDM 3.30.2
**Desktop environment**: GNOME 3.30.2

**Comment by Askannz** [comment]
I frankensteined GDM on top of my KDE install to test it, and the results have been...weird.

First, I can't reproduce your issue. Stopping GDM does seem to stop the X server as well. Maybe that's because I'm using KDE, I don't know.

But then, after restarting, everything goes crazy. So far, I've had :

- a black screen after restart
- nvidia-drm spamming errors in dmesg
- my wifi applet broke
- even a kernel panic (how tf is that even possible)

I'm going to test your PR and see if things are more stable.

**Comment by Askannz** [comment]
I completely overhauled the way display managers are handled. Could you please test the new v0.3 release and see if the problem is still there ?

**Comment by kuroni** [comment]
The problem is still there sadly :(

**Comment by Askannz** [comment]
So, small update : I still can't reproduce your issue with GDM+KDE. However, someone else has been able to confirm that when using GDM+GNOME, stopping the gdm service does *not*stop the X servers.

So it's GNOME doing something to keep servers alive even when GDM is gone.

**Comment by kuroni** [comment]
As the PR has been merged, can you ask the other person to test whether GDM+GNOME still poses problems?

**Comment by Askannz** [comment]
He doesn't use an Optimus laptop, I just asked him to check the behavior of GDM on his GNOME install.

**Comment by Askannz** [comment]
It would be great if someone else could test it, though.

**Comment by inzar98** [comment]
Stili have issue on gdm gnome. Cant stop xserver, starting New one

**Comment by Askannz** [comment]
Are you pulling the code directly from GitHub ? I have not pushed a new release to AUR yet.

**Comment by Askannz** [comment]
I just pushed v0.4 to AUR, you can try that.

**Comment by inzar98** [comment]
Worked like a charm! Thanks for bug fixing :)

**Comment by Askannz** [comment]
Great ! Thanks for testing.
