### ISSUE TITLE
[Question] Do we need optimus manager for Nvidia Turing Cards?

### ISSUE THREAD

**Issue by prolific** [Askannz/optimus-manager#403]
First of all I would like to thank all the contributors (specially @Askannz ) for such an awesome package.

I recently upgraded my device and bought Lenovo Legion 5Pi (RTX 2060) and since then I am wondering if I am getting any real advantage with Optimus Manager. I have tried using my device with and without optimus manager but couldn't figure out on my own whether there is any real advantage of using it anymore.

Points to Consider:

- With latest nvidia graphics (turing cards), there is an inbuilt support for RTD3 power management.
- Because of RTD3, there is no more a need to switch between integrated mode and hybrid mode. Hybrid mode allows on demand resources while also saving power when idle. And i think the main purpose of optimus manager is switching which in turn helped save power.

Having said that, are there any other features baked into optimus manager which makes it worthy of continued use? Can we just stop using it for modern cards?

There is a whole section under power management related to [configuration for turing cards](https://github.com/Askannz/optimus-manager/wiki/A-guide--to-power-management-options#configuration-1--dynamic-power-management-inside-the-nvidia-driver-runtime-d3-power-management). So there must be something which I am missing here. Why use optimus manager at all?

Also, support for wayland seems to be growing so I think by not using optimus manager we can freely move away from Xorg and still utilize all the benefits?

Please feel free to let me if I am wrong at any point. Just asking questions based on my own **limited** understanding of the package as well as the mess created by nvidia.

**Comment by hausofwong** [comment]
As per the notes in the [configuration for Turing cards](https://github.com/Askannz/optimus-manager/wiki/A-guide--to-power-management-options#configuration-1--dynamic-power-management-inside-the-nvidia-driver-runtime-d3-power-management) section, you might find that external monitors run poorly/laggy in hybrid mode. 

In my case I could only get my ultrawide monitor working correctly in 'nvidia' mode.

**Comment by nwildner** [comment]
Closing case since this question was answered back in 2021 and the original reported didn't came back. 

Please fell free to reopen it if there are still any pending queries.
