### ISSUE TITLE
(using startx) How do I exactly run /usr/bin/prime-switch as root after the current user has logged out

### ISSUE THREAD

**Issue by ndavd** [Askannz/optimus-manager#404]
Could this be a bit more specific https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting#i-do-not-use-a-display-manager-i-use-startx-or-xinit ?

**Comment by karl-tye** [comment]
First enable the `prime-switch` script to be executed from your account by appending this to `/etc/sudoers`
```
<username> ALL = NOPASSWD: /usr/bin/prime-switch
```

Then in your `.xinitrc` execute `/usr/bin/prime-offload` before your display manager. Also execute `sudo /usr/bin/prime-switch` after your display manager (executed when you log out).
Mine looks like this

```
/usr/bin/prime-offload
ssh-agent dwm
sudo /usr/bin/prime-switch
```

**Comment by ndavidq0** [comment]
And by doing that are you sure it does what we want? Because it seems that it executes the script after the window manager starts

**Comment by BachoSeven** [comment]
@ndavidq0 it does exactly what described in the wiki, namely running a command just after xorg starts(but before dwm starts), and another one after it stops

**Comment by ndavidq0** [comment]
Thanks I'll try that

**Comment by ndavidq0** [comment]
This didn't work for me (i.e. after I do the switch command it logs off, I execute startx and get a black-screen)
```
/usr/bin/prime-offload
exec bspwm
sudo /usr/bin/prime-switch
```
What am I doing wrong here?

**Comment by X-m7** [comment]
Does removing the `exec` bit work? So like:
```
/usr/bin/prime-offload
bspwm
sudo /usr/bin/prime-switch
```

**Comment by es20490446e** [comment]
Reopen if the last comment doesn't work.

**Comment by es20490446e** [comment]
Reopen if that doesn't work.
