### ISSUE TITLE
AMD/Nvidia in hybdrid mode doesn't seem to use Nvidia at all. Also, it doesn't work at all after Hibernation. 

### ISSUE THREAD

**Issue by denijane** [Askannz/optimus-manager#409]
**Describe the bug**
When I do "optimus-manager --switch nvidia", all works fine and the nvidia works great. 
With "optimus-manager --switch hybrid", however, when I do $prime-run glxspheres64, I sometimes get "Nvidia" but the fps are the same as for the AMD or I don't get NVIDIA at all and it either says "AMD Renoir" or it gives an error "X Error of failed request:  BadValue (integer parameter out of range for operation)". 

It seems to me that there is a problem with switching between Nvidia and AMD in the hybrid mode and especially after hibernation, it even doesn't pretend it's using the nvidia, just straight on say AMD. Can we expect improved support for the AMD/Nvidia combination in the future? 

**System info**
Asus TUF Gaming, and I have an AMD Renoir and  NVIDIA Geforce RTX 3060. I'm with MANJARO 5.12, with KDE and SDDM and Optimus Manager (Client) version 1.4

**Logs**
I don't see errors in the logs:
$optimus-manager --status
Optimus Manager (Client) version 1.4

Current GPU mode : hybrid
GPU mode requested for next login : no change
GPU at startup : integrated
Temporary config path: no

**Comment by nwildner** [comment]
Hello @denijane 

 Is this still reproducible on a modern distribution with updated linux kernel, nvidia driver version and using the `optimus-manager-git` package? The project is facing a revamp so, please stick with the `-git` version of this package.

Let me know if this issue is still relevant to you ok?

Have a nice week.
