### ISSUE TITLE
Can't switch graphics (AwesomeWM)

### ISSUE THREAD

**Issue by gabrielbelli** [Askannz/optimus-manager#418]
Running with:
_- Archlinux
- AwesomeWM
- LightDM
- HP OMEN 15
- The latest Git version (optimus-manager-git)_

**When I try to switch graphics I get the following error:**

```
Switching to mode : integrated
/bin/sh: line 1: i3-msg: command not found
/bin/sh: line 1: openbox: command not found
Failed to open connection to "session" message bus: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
E: dbus-send failed.
/bin/sh: line 1: bspc: command not found
/bin/sh: line 1: qtile-cmd: command not found
```

**Comment by kiocosta** [comment]
Did you manage to solve this?
I have the same issue.

**Comment by 3070720260** [comment]
I don't know if you solve it, I understand, don't run this command as root, and then the system will restart and switch modes as previously said

**Comment by es20490446e** [comment]
Reopen if still there.
