### ISSUE TITLE
Openrc + XMonad Support

### ISSUE THREAD

**Issue by iRealistiX** [Askannz/optimus-manager#426]
**Describe the bug**
Well, I think from the title, the problem is clear. I use Artix Linux (openrc edition), so I found on the aur the `optimus-manager-openrc-git` packages, which can be added to openrc, **cool**. Now the problem is that it tries to stop the current window manager, which in my case, is XMonad, but I can't close it. Leading in a fail for it to switch

**System info**
Please include :
- **Distro:** Artix Linux (Openrc)
- Your desktop environment: none. I use `XMonad` which is a Window Manager
- **Display/Login Manager:** SDDM.
- **The version of optimus-manager you are using :** latest git version for openrc
- Your custom optimus-manager config file: I don't have one

**Logs.**
[daemon-20210727T111749.log](https://github.com/Askannz/optimus-manager/files/6884734/daemon-20210727T111749.log)
[switch-20210727T111749.log](https://github.com/Askannz/optimus-manager/files/6884735/switch-20210727T111749.log)

**Comment by karimrir1** [comment]
You should probably use the openrc version from the artix linux universe repo, And the non systemd versions of optimus-manager are community maintained, If you want help then make a post on the artix forums.
