### ISSUE TITLE
Switching from the Intel iGPU to the Nvidia dGPU requires two logout/logins despite the Nvidia modules being loaded on the first

### ISSUE THREAD

**Issue by hombiebearcat** [Askannz/optimus-manager#428]
**Description**
When using optimus-manager (via optimus-manager-qt) to switch to the Nvidia GPU from the Intel GPU, I have to log out and in twice to effect the change. optimus-manager claims that the change is pending after the first logout/login, yet nvidia-smi confirms that the Nvidia drivers have been loaded. This is only a problem with switching from Integrated to Nvidia (switching back to Integrated and switching back and forth from Hybrid works fine).

**System info**
Distro: Arch Linux
Desktop Environment: KDE Plasma 5
Display Manager: SDDM
Laptop Model: Dell XPS 9500 (GTX 1650-Ti)
optimus-manager Version: Latest stable (1.4-2)
Full contents of /etc/optimus-manager/optimus-manager.conf:

```
[amd]
DRI=3
driver=modesetting
tearfree=

[intel]
DRI=3
accel=uxa
driver=intel
modeset=yes
tearfree=no

[nvidia]
#%23%20When%20dynamic_power_management=fine, this options controls the threshold of memory utilization
DPI=96
PAT=yes
allow_external_gpus=no
dynamic_power_management=no
dynamic_power_management_memory_threshold=0
ignore_abi=no
modeset=no
options=overclocking

[optimus]
#%23%20%20%20%20%20%20%20%20%20Also%2C%20it%20will%20perform%20a%20PCI%20remove%20even%20if%20pci_remove#=no.
#%23%20GPU%20mode%20to%20select%20when%20startup_mode=auto and the computer is running on external #power.
#%23%20Ignored%20if%20switching="nouveau or switching=bbswitch."
auto_logout=yes
pci_power_control=no
pci_remove=no
pci_reset=no
startup_auto_battery_mode=integrated
startup_auto_extpower_mode=nvidia
startup_mode=integrated
switching=bbswitch

```

**Logs**
The only error message outputted by optimus-manager --status is:
`Config parsing : error in option "dynamic_power_management_memory_threshold" in section [nvidia] : non-blank integer value required
`
The following are the most recent log files:
[daemon-20210807T091610.log](https://github.com/Askannz/optimus-manager/files/6948934/daemon-20210807T091610.log)
[daemon-20210807T101935.log](https://github.com/Askannz/optimus-manager/files/6948935/daemon-20210807T101935.log)
[daemon-20210807T104001.log](https://github.com/Askannz/optimus-manager/files/6948936/daemon-20210807T104001.log)
[switch-20210807T091610.log](https://github.com/Askannz/optimus-manager/files/6948941/switch-20210807T091610.log)
[switch-20210807T101935.log](https://github.com/Askannz/optimus-manager/files/6948942/switch-20210807T101935.log)
[switch-20210807T103632.log](https://github.com/Askannz/optimus-manager/files/6948943/switch-20210807T103632.log)
[switch-20210807T103758.log](https://github.com/Askannz/optimus-manager/files/6948944/switch-20210807T103758.log)
[switch-20210807T103834.log](https://github.com/Askannz/optimus-manager/files/6948945/switch-20210807T103834.log)
[switch-20210807T104001.log](https://github.com/Askannz/optimus-manager/files/6948946/switch-20210807T104001.log)
[switch-20210807T104023.log](https://github.com/Askannz/optimus-manager/files/6948947/switch-20210807T104023.log)
[switch-20210807T104859.log](https://github.com/Askannz/optimus-manager/files/6948948/switch-20210807T104859.log)

**Comment by openmindead** [comment]
Yeah. Same happens to me from time to time, too. SDDM, MX150.

**Comment by nwildner** [comment]
Sup folks. Is this still happening while using `optimus-manager-git` and more recent version of your respective distributions?

Since this issue isn't active for the last 3 years ago and a lot has changed in many aspects of multiple software, we'll keep this case opened for some days and close it if no further comments are provided.

Have a nice week ahead.

**Comment by es20490446e** [comment]
Reopen if still there.
