### ISSUE TITLE
Can't overclock even with coolbits enabled.

### ISSUE THREAD

**Issue by blacktoz** [Askannz/optimus-manager#431]
**Describe the bug**
I cannot overclock, with Greenwithenvy, tuxclocker and Nvidia X server settings, tried to change coolbits manually but still doesn't work with that 

**System info**
Please include :
- Arch Linux 5.13.10-arch1-1
- Using Gnome on Xorg
- Using GDM
- MSI GF65 9SEXR
- optimus-manager
- My optimus-manager config file :
[optimus-manager.txt](https://github.com/Askannz/optimus-manager/files/6995486/optimus-manager.txt)

**Logs**
No error. here is both file :
[daemon-20210816T230724.log](https://github.com/Askannz/optimus-manager/files/6995497/daemon-20210816T230724.log)
[switch-20210816T230808.log](https://github.com/Askannz/optimus-manager/files/6995498/switch-20210816T230808.log)

Thanks :D

**Comment by blacktoz** [comment]
Note : i'm in nvidia mode, not hybrid.

**Comment by blacktoz** [comment]
Note 2 : I have an RTX 2060 Mobile if that can help

**Comment by blacktoz** [comment]
Fixed it by creating the following file : /etc/X11/Xwrapper.config with the content :
needs_root_rights = yes

**Comment by saikat0511** [comment]
This worked for me. Thanks!

I think this has something to do with rootless xorg mode used by gdm by default. SDDM still uses xorg in root for now so its unaffected.

**Comment by nwildner** [comment]
Closing this issue since it is a corner case and it got added to the wiki [here](https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting#overclocking-and-fan-control-stay-locked-in-hybrid-mode-even-though-coolbits-are-set)
