### ISSUE TITLE
Loading with bbswitch makes laptop unable to boot

### ISSUE THREAD

**Issue by ghost** [Askannz/optimus-manager#438]
**Describe the bug**
A clear and concise description of what the bug is:
I set the switching mode to bbswitch, and after doing so I cannot boot. I cannot enter tty. I just go through the initial boot sequence and then it freezes on a black screen before sddm (should) load. Bbswitch is installed, optimus-manager is, i have the nvidia driver, my kernel headers, correct kernel, etc. I am not sure what I am doing wrong.

**System info**
Please include :
- Your distribution: Arch Linux
- Your desktop manager: KDE
- You display manager: SDDM
- Your laptop model, if you think it could be related to the problem: XPS 15 9560
- The version of optimus-manager you are using : latest stable release (optimus-manager)
- Your custom optimus-manager configuration file at `/etc/optimus-manager/optimus-manager.conf`, if you made one

`[amd]
DRI=3
driver=modesetting
tearfree=

[intel]
DRI=3
accel=
driver=modesetting
modeset=yes
tearfree=

[nvidia]
DPI=96
PAT=yes
allow_external_gpus=no
dynamic_power_management=no
ignore_abi=no
modeset=yes
options=overclocking

[optimus]
auto_logout=yes
pci_power_control=no
pci_remove=no
pci_reset=no
startup_auto_battery_mode=integrated
startup_auto_extpower_mode=nvidia
startup_mode=integrated
switching=bbswitch
`

**Logs**
Run `optimus-manager --status` in a console, and if an error message appears, post it here. The message should also point you to a log path, attach it here as well. If there is no error message but you are still experiencing issues, grab the most recent files in `/var/log/optimus-manager/switch/` and `/var/log/optimus-manager/daemon/`.

My log files from boots with this issue are empty. If there is a way to get it to log somehow, I will post them.

**Comment by dapherino** [comment]
To add: this occurs in integrated mode. I haven't tried other modes because I have no interest in ever using them. I only want the nvidia gpu disabled.

**Comment by CygnusTerminal** [comment]
Do you have a GTX 10xx GPU? Have you added the `acpi_osi` kernel option to your bootloader? Mine did the same until i added `acpi_osi=!` and `acpi_osi='Windows 2009'`

**Comment by nwildner** [comment]
Closing this case since a `CMDLINE` with `acpi_osi` option was provided but the original reported deleted his/her/they github account
