### ISSUE TITLE
System crashes on set-startup intel

### ISSUE THREAD

**Issue by reikdas** [Askannz/optimus-manager#44]
**Describe the bug**
When I set optimus-manager to use intel on boot using optimus-manager --set-startup intel, my computer crashes a few seconds after entering my desktop environment. 
If I have nvidia on startup and then switch to intel, it works fine.

**System info**
- Your distribution - Manjaro
- Your desktop manager - i3wm
- You display manager - lightdm
- Your laptop model, if you think it could be related to the problem - MSI GS65 (https://wiki.archlinux.org/index.php/MSI_GS65)

**Logs** (After booting with startup intel, I changed startup to nvidia and then rebooted. After that I switched to intel and then posted the logs)
- Kernel - https://pastebin.com/Wi7xdYhN
- Xorg : https://pastebin.com/3bVNNZyZ

**Comment by Askannz** [comment]
How does it crash ? Is it just the X server exiting or are you completely locked out of your computer ? (i.e not able to switch to a TTY with Ctrl+Alt+Fx).

Try setting `pci_reset=no` in the configruation file.

**Comment by reikdas** [comment]
> Try setting `pci_reset=no` in the configruation file.

This worked. Thanks.

**Comment by Askannz** [comment]
Good :)

Just to help me debug, are you using the default `nouveau` mode or have you configured optimus-manager to use `bbswitch` ?

**Comment by reikdas** [comment]
The default nouveau mode.

**Comment by Askannz** [comment]
I just realized...the `pci_reset` option should not affect startup in any way. PCI reset only happens after the display manager has stopped.

Could you do the following ?

* Re-enable `pci_reset` and set startup mode to intel.
* Reboot and let the crash occur
* Reboot again in Nvidia mode, and grab the logs from the previous boot using `journalctl -u lightdm -b-1 --no-pager` and `journalctl -k -b-1 --no-pager`.

Really curious to see what the output is going to be there.

**Comment by reikdas** [comment]
Strangely, I am unable to reproduce the error with `pci_reset=yes` in the config file.

**Comment by reikdas** [comment]
I realised something. I was facing this error when the config file being used was /usr/share/optimus-manager.conf but when I created a new config file (https://pastebin.com/Bh6yTbbx) at /etc/optimus-manager/optimus-manager.conf it fixed the issue.
