### ISSUE TITLE
support arch linux-lts kernel packages

### ISSUE THREAD

**Issue by keelson** [Askannz/optimus-manager#45]
I just tried to install the aur and see a depency to the linux kernel package. 
Is it possible to support linux-lts instead of the linux kernel package?

Thanks!

**Comment by Askannz** [comment]
That dependency is probably coming from bbswitch, which does not have a package for linux-lts.

I don't see how to fix that at a packaging level though...

The best solution is probably to mark bbswitch as an optional dependency and check at runtime if it is available.

**Comment by JpegXguy** [comment]
There's a `bbswitch-dkms` I think

**Comment by Askannz** [comment]
The bbswitch dependency has been removed. optimus-manager now checks at runtime if bbswitch is available, and outputs a warning message if it isn't and you try to set the "bbswitch" option.
