### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by cryptodan** [Askannz/optimus-manager#452]
I would like to make a suggestion to build optimus-manager with wayland support now that Nvidia 495 includes enhanced support for wayland.

**Comment by Askannz** [comment]
It's not dead, I just lack time to work on it. From my quick testing and other users reports Wayland happens to work fine but I need to do more testing before it can be officially supported.

**Comment by cryptodan** [comment]
I can test for you after April 29th when my eye sight is better.

**Comment by ErickHoward** [comment]
> It's not dead, I just lack time to work on it. From my quick testing and other users reports Wayland happens to work fine but I need to do more testing before it can be officially supported.

Sorry for that slightly stupid message. I hadn't checked the repo in a few months and last time I checked I hadn't seen any new commits. I have switched to Fedora now but if I ever switch back to Arch I will look forward to using Optimus Manager on Wayland

**Comment by ambition-echo** [comment]
So is there anything new about wayland support?🥺

**Comment by Reireiyan** [comment]
When using optimus-manager and setting it to nvidia mode on KDE, it can start plasma with the most important thing running on the GPU, kwin_x11, but it can't do the same thing on Wayland with kwin_wayland. With the GPU set to Nvidia, nothing starts with the GPU. The only way I could get it to work was by setting __NV_PRIME_RENDER_OFFLOAD=1. In the environment variable /etc/enviroment, then, every application, including plasmashell, runs on the NVIDIA GPU again, except the most important thing, kwin_wayland.

**Comment by Reireiyan** [comment]
If there is a way to force kwin_wayland to use the NVIDIA GPU, I don't know.
![Screenshot_20230110_172400](https://user-images.githubusercontent.com/62414119/211665623-0a1d78f8-e70c-458c-ab05-1793a9968df3.png)

**Comment by D3vil0p3r** [comment]
@Askannz bro thank you for your effort. Let us know if there is some news about Wayland support.

And enable GitHub Sponsor button, because I think that people can sponsor your project.

**Comment by bennett-nguyen** [comment]
Any updates on the Wayland situation?

**Comment by optimizasean** [comment]
As a hyprland lover and all for the security and features of wayland - I really hope this can get working on wayland. (tested, it doesn't and can't figure it out with xwayland either).

For those of you that need a solution that *works*...

make a script with these contents (I called it enable_external_displays.sh):
```sh
# Enable external ports and use nvidia card
sudo modprobe nvidia-drm modeset=1
```

You can run it to switch to nvidia (Hyprland auto changes over for my config - pretty basic including waybar, mako, ...).
Only downside is you have to reboot to go back to integrated graphics. Unfortunate patch but it will hold me over :laughing: 
At least I can enable monitors when I need them haha.

Thanks for an excellent tool (old ubuntu user), but I hope for wayland now that we have good nvidia-wayland support!

**Comment by es20490446e** [comment]
I think that the goal here shall be the smallest improvement that enhances the current situation.

Even if incomplete or not on pair with xorg features. It can be improved later on.

**Comment by nwildner** [comment]
That's correct. Start with baby steps and improve as soon as we get more people collaborating with the project.

I've just pinned this thread to use it as our central point for any Wayland related discussions(support, requests) and avoid all the "Is my <Wayland Compositor> supported yet?"

**Comment by es20490446e** [comment]
Good idea 👍

**Comment by es20490446e** [comment]
I think I figured it out 😁

Could you verify if this works for your?

Create `/etc/profile.d/optimus-manager.sh` with the following content:
```

#! /bin/sh

if [[ "${XDG_SESSION_TYPE}" == "wayland" ]]; then
	export __GLX_VENDOR_LIBRARY_NAME=nvidia
	export __VK_LAYER_NV_optimus=NVIDIA_only
fi

```

Then restart, and run a native game to see if it works.

With "[The Dark Mod](https://thedarkmod.com/)" the difference is quite noticeable.

The desktop shall report that it is using the integrated GPU for its rendering, but it will be using the dedicated GPU for GLX and Vulkan rendering.

**Comment by awsms** [comment]
99dfe2f it's happening!

**Comment by es20490446e** [comment]
I have just added the most basic Wayland support.

On my KDE Plasma desktop it works flawlessly without further configuration.

Lets see if this is the case for everyone else.

**Comment by es20490446e** [comment]
The trick is that Wayland display managers run on EGL, while 3D games either on GLX or Vulkan.

So instead of offloading the complete desktop session, you just offload GLX and Vulkan apps.

This makes the desktop to still run on integrated graphics, and any other 3D app on Nvidia.

This doesn't work for x11, causing garbage. But on Wayland it delivers optimal performance.
