### ISSUE TITLE
optimus-manager.service: Failed with result 'exit-code'.

### ISSUE THREAD

**Issue by miaochangq** [Askannz/optimus-manager#453]
**Describe the bug**
× optimus-manager.service - Optimus Manager Commands Daemon
     Loaded: loaded (/usr/lib/systemd/system/optimus-manager.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Tue 2021-12-14 08:51:00 CST; 4min 9s ago
    Process: 393 ExecStartPre=/usr/bin/python3 -u -m optimus_manager.hooks.pre_daemon_start (code=exited, status=1/FAILURE)
    Process: 431 ExecStartPre=/usr/bin/python3 -u -m optimus_manager.hooks.pre_xorg_start (code=exited, status=1/FAILURE)
    Process: 440 ExecStart=/usr/bin/python3 -u -m optimus_manager.daemon (code=exited, status=1/FAILURE)
    Process: 452 ExecStopPost=/usr/bin/python3 -u -m optimus_manager.hooks.post_daemon_stop (code=exited, status=1/FAILURE)
   Main PID: 440 (code=exited, status=1/FAILURE)
        CPU: 66ms

12月 14 08:50:59 mcq systemd[1]: Starting Optimus Manager Commands Daemon...
12月 14 08:50:59 mcq python3[393]: /usr/bin/python3: Error while finding module specification for 'optimus_manager.hooks.pre_daemon_start' (ModuleNotFoundError: No module na>
12月 14 08:50:59 mcq python3[431]: /usr/bin/python3: Error while finding module specification for 'optimus_manager.hooks.pre_xorg_start' (ModuleNotFoundError: No module name>
12月 14 08:50:59 mcq systemd[1]: Started Optimus Manager Commands Daemon.
12月 14 08:51:00 mcq python3[440]: /usr/bin/python3: Error while finding module specification for 'optimus_manager.daemon' (ModuleNotFoundError: No module named 'optimus_man>
12月 14 08:51:00 mcq systemd[1]: optimus-manager.service: Main process exited, code=exited, status=1/FAILURE
12月 14 08:51:00 mcq python3[452]: /usr/bin/python3: Error while finding module specification for 'optimus_manager.hooks.post_daemon_stop' (ModuleNotFoundError: No module na>
12月 14 08:51:00 mcq systemd[1]: optimus-manager.service: Control process exited, code=exited, status=1/FAILURE
12月 14 08:51:00 mcq systemd[1]: optimus-manager.service: Failed with result 'exit-code'.

**System info**
Please include :
- Arch Linux 
- KDE and I3wm
- sddm
- The version of optimus-manager you are using : 1.6.4
- Your custom optimus-manager configuration file at `/etc/optimus-manager/optimus-manager.conf`, if you made one

**Logs**
Run `optimus-manager --status` in a console, and if an error message appears, post it here. 
Traceback (most recent call last):
  File "/usr/bin/optimus-manager", line 33, in <module>
    sys.exit(load_entry_point('optimus-manager==1.4', 'console_scripts', 'optimus-manager')())
  File "/usr/bin/optimus-manager", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for optimus-manager

The message should also point you to a log path, attach it here as well. If there is no error message but you are still experiencing issues, grab the most recent files in `/var/log/optimus-manager/switch/` and `/var/log/optimus-manager/daemon/`.

[mcq@mcq ~]$ cat /var/log/optimus-manager/daemon/daemon-20211213T082234.log
[24] INFO: # Daemon pre-start hook
[24] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[25] INFO: Copying /etc/optimus-manager/optimus-manager.conf to /var/lib/optimus-manager/tmp/config_copy.conf
[29] INFO: Startup mode is: integrated
[29] INFO: Writing state {'type': 'pending_pre_xorg_start', 'requested_mode': 'integrated', 'current_mode': None}
[30] INFO: Daemon pre-start hook completed successfully.
[30] INFO: Calling Xorg pre-start hook.
[2] INFO: # Commands daemon
[2] INFO: Opening UNIX socket
[2] INFO: Awaiting commands
[33691718] INFO: Process stop requested
[33691718] INFO: Closing and removing the socket...
[33691718] INFO: Goodbye !

**Comment by ajburns651** [comment]
Am having this too, not sure what the solution is

**Comment by Kr1ss-XD** [comment]
Rebuild the optimus-manager package, and you should be fine. Python 3.10 has just been pushed the repos.

**Comment by kevindirect** [comment]
This bash script will find and rebuld all python dependent AUR packages. It needs pactree from pacman-contrib to work:

```
#!/usr/bin/bash
# Find the AUR packages that require python and rebuild them

aur=$(pacman -Qqm | sort);
req=$(pactree -rl -d 1 "python" | sort);
yay -S --rebuild $(comm -12 <(echo "$aur") <(echo "$req"));
```
I tried to create a hook that would run it non-interactively when python updates.

/etc/pacman.d/scripts/aur-python-rebuild:
```
#!/usr/bin/bash
# Find the AUR packages that require python and rebuild them

aur=$(pacman -Qqm | sort);
req=$(pactree -rl -d 1 "python" | sort);
sudo -u $SUDO_USER yay -S --answerclean=None --rebuild $(comm -12 <(echo "$aur") <(echo "$req"));
```
/etc/pacman.d/hooks/aur-python-rebuild.hook:
```
[Trigger]
Operation = Install
Operation = Upgrade
Type = Package
Target = python

[Action]
Description = Rebuilding AUR packages that depend on python...
When = PostTransaction
Depends = coreutils
Depends = pacman
Depends = pacman-contrib
Depends = yay
Exec = /etc/pacman.d/scripts/aur-python-rebuild
```

The problem is pacman keeps the package db locked during the hook. If anyone knows of a workaround to automate this please let me know.

**Comment by kevindirect** [comment]
BTW in the meantime I have a warning hook below. If you want to use it create and add the files at the given paths with the correct permissions.

/etc/pacman.d/scripts/aur-python-warn:
```
#!/usr/bin/bash
# Warning to rebuild the AUR packages that require python

aur=$(pacman -Qqm | sort);
req=$(pactree -rl -d 1 "python" | sort);
aurreq=$(comm -12 <(echo "$aur") <(echo "$req"));
command=$(echo "yay -S --rebuild " $aurreq);

echo "PYTHON UPDATE WARNING: REBUILD THESE AUR PACKAGES:" $aurreq;
echo "RUN THIS COMMAND:" $command;
```

/etc/pacman.d/hooks/aur-python-warn.hook:
```
[Trigger]
Operation = Install
Operation = Upgrade
Type = Package
Target = python

[Action]
Description = Warning to rebuild AUR packages that depend on python...
When = PostTransaction
Depends = coreutils
Depends = sudo
Depends = pacman
Depends = pacman-contrib
Exec = /etc/pacman.d/scripts/aur-python-warn
```

**Comment by miaochangq** [comment]
Thank You very much，there are very useful for me.
BTW,forgave my pool english

**Comment by Askannz** [comment]
As mentioned this is caused by Arch upgrading from Python 3.9 to 3.10. You can fix it by rebuilding the package from AUR. Or if you use an AUR helper like yay, just upgrade to the latest version, I've pushed an update to force AUR helpers to rebuild.
