### ISSUE TITLE
Package can't be built from AUR, won't install Optimus Manager

### ISSUE THREAD

**Issue by fennkit** [Askannz/optimus-manager#454]
Optimus manager and Optimus manager Qt can't be built from the AUR (paru or yay) or when cloned from this github repo. There doesn't seem to be any current way to install it. Could this be related to the release of Python 3.10?

**System info**
- Arch Linux
- KDE Plasma
- X11
- sddm
- Nvidia 495.46 Drivers
- Linux 15.5 Kernel
- HP Omen 15 2021

**Logs**
: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
fetching devel info...
==> Making package: optimus-manager 1.4-2 (Mon 13 Dec 2021 07:57:57 PM PST)
==> Retrieving sources...
  -> Updating optimus-manager git repo...
Fetching origin
==> Validating source files with sha256sums...
    optimus-manager ... Skipped
==> Making package: optimus-manager 1.4-2 (Mon 13 Dec 2021 07:58:00 PM PST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating optimus-manager git repo...
Fetching origin
==> Validating source files with sha256sums...
    optimus-manager ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of optimus-manager git repo...
Cloning into 'optimus-manager'...
done.
Switched to a new branch 'makepkg'
==> Sources are ready.
optimus-manager-1.4-2: parsing pkg list...
==> Making package: optimus-manager 1.4-2 (Mon 13 Dec 2021 07:58:03 PM PST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting build()...
Traceback (most recent call last):
  File "/home/user/.cache/paru/clone/optimus-manager/src/optimus-manager/setup.py", line 3, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'optimus-manager-1.4-2':
error: packages failed to build: optimus-manager-1.4-2

*changed my user directory to "user" in this post

**Comment by kevindirect** [comment]
Try reinstalling `python-setuptools` first. It's an optimus-manager dependency. It looks like your system thinks you have it but it can't be found.

**Comment by fennkit** [comment]
I ran sudo pacman -Sy python-setuptools, and it did reinstall; though I get the same message trying to build optimus-manager
