### ISSUE TITLE
Python lib (optimus-manager) is missing

### ISSUE THREAD

**Issue by User-green** [Askannz/optimus-manager#457]
There is some kind of dep. problem. Here a photo.

After reboot SDDM dosent apper, only blackscreen. 
Same with `startx` (but I can hear welcome .ogg playing)

This happend after update.

**System info**
- Manjaro
- KDE (kwin)
- SDDM
- Optimus-manager 1.4-3
- (Will include later)

**Logs**
`optimus-manager --status` is broken.

UPD. KDE connect also DO work. 

**WORKAROUND**:
Rollback to version 1.4-1

**Comment by User-green** [comment]
[Here is a photo](https://storage.tslp.tk/index.php/s/Kf624HDDyxPZXTs)

**Comment by CyanWoods** [comment]
Here is systemctl output 
same problem.
```
❯ systemctl status optimus-manager
× optimus-manager.service - Optimus Manager Commands Daemon
     Loaded: loaded (/usr/lib/systemd/system/optimus-manager.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Sat 2021-12-18 19:50:13 CST; 35s ago
    Process: 1479 ExecStartPre=/usr/bin/python3 -u -m optimus_manager.hooks.pre_daemon_start (code=exited, status=1/FAILURE)
    Process: 1480 ExecStartPre=/usr/bin/python3 -u -m optimus_manager.hooks.pre_xorg_start (code=exited, status=1/FAILURE)
    Process: 1481 ExecStart=/usr/bin/python3 -u -m optimus_manager.daemon (code=exited, status=1/FAILURE)
    Process: 1482 ExecStopPost=/usr/bin/python3 -u -m optimus_manager.hooks.post_daemon_stop (code=exited, status=1/FAILURE)
   Main PID: 1481 (code=exited, status=1/FAILURE)
        CPU: 72ms

Dec 18 19:50:13 Inspiron-7577 systemd[1]: Starting Optimus Manager Commands Daemon...
Dec 18 19:50:13 Inspiron-7577 python3[1479]: /usr/bin/python3: Error while finding module specification for 'optimus_manager.hooks.pre_daemon_start' >
Dec 18 19:50:13 Inspiron-7577 python3[1480]: /usr/bin/python3: Error while finding module specification for 'optimus_manager.hooks.pre_xorg_start' (M>
Dec 18 19:50:13 Inspiron-7577 systemd[1]: Started Optimus Manager Commands Daemon.
Dec 18 19:50:13 Inspiron-7577 python3[1481]: /usr/bin/python3: Error while finding module specification for 'optimus_manager.daemon' (ModuleNotFoundE>
Dec 18 19:50:13 Inspiron-7577 systemd[1]: optimus-manager.service: Main process exited, code=exited, status=1/FAILURE
Dec 18 19:50:13 Inspiron-7577 python3[1482]: /usr/bin/python3: Error while finding module specification for 'optimus_manager.hooks.post_daemon_stop' >
Dec 18 19:50:13 Inspiron-7577 systemd[1]: optimus-manager.service: Control process exited, code=exited, status=1/FAILURE
Dec 18 19:50:13 Inspiron-7577 systemd[1]: optimus-manager.service: Failed with result 'exit-code'.
```

**Comment by Biscad** [comment]
Same issue for me.
my HDMI external monitor did work but the eDP intenal monitor was not detected, with either the integrated amd gpu or the nvidia gpu.

rollback to 1.4-1 works as a workaround

system :

Manjaro
KDE (kwin)
SDDM
Optimus-manager 1.4-3
amd ryzen 5 5600h
nvidia rtx 3060

**Comment by CyanWoods** [comment]
hey guys, try this 
https://www.reddit.com/r/archlinux/comments/rf6c84/psa_python_310_is_in_core_rebuild_your_aur/
It works for me

**Comment by definitelynobody** [comment]
`yay -S $(pacman -Qoq /usr/lib/python3.9) --answerclean All`

did *not* work for me

**Comment by andrey-akhmatkhanov** [comment]
> hey guys, try this https://www.reddit.com/r/archlinux/comments/rf6c84/psa_python_310_is_in_core_rebuild_your_aur/ It works for me
It doesn't look to be related as Manjaro is still on Python 3.9 (at least in stable branch).

**Comment by donkey55** [comment]
Same issue for me.

**Comment by chknatwork** [comment]
> Same issue for me.
> After I installed optimus-manager and reboot my computer, i tried to run `optimus-manger`, and then it failed. The error is same to @User-green

Try downgrading to 1.4.1 git from the AUR. I believe this is because Manjaro has upgraded to Python 3.10 from 3.9.

**Comment by Biscad** [comment]
> Same issue for me. my HDMI external monitor did work but the eDP intenal monitor was not detected, with either the integrated amd gpu or the nvidia gpu.
> 
> rollback to 1.4-1 works as a workaround
> 
> system :
> 
> Manjaro KDE (kwin) SDDM Optimus-manager 1.4-3 amd ryzen 5 5600h nvidia rtx 3060

Optimus-manager 1.4-3 works now for me with the last manjaro updates, not sure which one fixed it, there were many. 
Optimus-manager 1.4-1 did not work though.

**Comment by andrey-akhmatkhanov** [comment]
> Optimus-manager 1.4-3 works now for me with the last manjaro updates, not sure which one fixed it, there were many.

I confirm - last manjaro stable update (2022-01-02) fixes the issue. I think it can be closed now.

**Comment by User-green** [comment]
> > Optimus-manager 1.4-3 works now for me with the last manjaro updates, not sure which one fixed it, there were many.
> 
> I confirm - last manjaro stable update (2022-01-02) fixes the issue. I think it can be closed now.

Please, declare versions of the related software you are useing.

**Comment by Askannz** [comment]
Closing this, if you're still having issues you need to rebuild the package from AUR to force it to match your system Python version.

**Comment by andrey-akhmatkhanov** [comment]
> Please, declare versions of the related software you are useing.

Right now I am on optimus-manager 1.4.3
Python is 3.10.2
System: Manjaro KDE (stable branch)

P.S. I can see optimus-manager 1.4.4 available, but I haven't tried it yet.
