### ISSUE TITLE
[Question] Is there a way to select the appplications/process to use my specified gpu?

### ISSUE THREAD

**Issue by Goldenfreddy0703** [Askannz/optimus-manager#474]
Hey there, im sorry for asking but i have been doing alot of research with optimus-manager and i feel dumb for asking this but is there a way to manage specific applications like firedragon, ffmpeg, Unity, ect? I've tried alternatives like bumblebee but had problems with some installing sense im using Garuda Linux and optimus-manager is integrated with it. 

I have used `prime-run` and it works well and does what i want it to but i want like a manager to manage applications where whenever i open an application, it would automatically use that specified gpu. I've tried messing with application profiles in nvidia settings and had no luck with it and im not sure what to do at this point. I have tried using scripts but i don't want to launch scripts directly in order to open that application. 

On windows, you could set programs to the gpu you want it to and it was easier but on linux, It feels like pain. 
If there is a way or a application/process manager out there for optimus-manager, that would be really great, sorry for my ranting and i love using optimus-manager. Just wish i could select specified applications for my gpu.

**Comment by Askannz** [comment]
I understand where you're coming from but that's difficult to implement. The only way it could work is to have some kind of launcher that sits between you and _every_ application installed on your machine, and sets their GPU environment dynamically when an app is launched.

Maybe it could be done at the DE level one day, but in any case it's out of scope for this project.

**Comment by Goldenfreddy0703** [comment]
aww ok thank you. Do you by anychance know any alternative or way to atleast start several applications with a script or something?

**Comment by Askannz** [comment]
If prime-run is not enough you can use the env vars mentioned here to control which GPU is used: https://github.com/Askannz/optimus-manager/wiki/Nvidia-GPU-offloading-for-%22hybrid%22-mode (which is what prime-run does under the hood). Hope that helps.

**Comment by Goldenfreddy0703** [comment]
I guess it does help me a little but say I wanna play a game like Minecraft Java Edition for example and I'm using a launcher called multimc, sense minecraft runs Java, how could I get Java to run on my Nvidia gpu? I can get my launcher to run on my Nvidia gpu using prime run but I can't use Java to use my Nvidia gpu.
