### ISSUE TITLE
Fb* devices no longer show up

### ISSUE THREAD

**Issue by Basement561** [Askannz/optimus-manager#476]
**Describe the bug**
When this package or `nvidia` is installed, no fb* devices show up is /dev. I am trying to use an external monitor with the linux console, and it works with `fbcon=map:1`. However, when `optimus-manager` or `nvidia` are installed the monitor does not turn on.

**System info**
- Arch GNU/Linux
- Acer Nitro AN515-52
- Latest stable release (optimus-manager)

**Comment by Askannz** [comment]
This has nothing to do with optimus-manager, the proprietary Nvidia driver does not support `/dev/fb*` devices.
