### ISSUE TITLE
Run script on switch

### ISSUE THREAD

**Issue by Savanta** [Askannz/optimus-manager#481]
Hello, is there any way to run script on switch? I would like to export variables VDPAU_DRIVER and LIBVA_DRIVER_NAME to intel or nvidia depending on active gpu

**Comment by Askannz** [comment]
There isn't, but as far as I know it's not possible to dynamically set env vars system-wide.

**Comment by nwildner** [comment]
Closing because of `WONTFIX`(aka, can't implement that env-var export dinamically and system wide on switch.
