### ISSUE TITLE
Latest nvidia card never shut down with integrated mode

### ISSUE THREAD

**Issue by Mario156090** [Askannz/optimus-manager#489]
Bug description:

Nvidia 3060 mobile never shutdown when I set integrated mode from optimus manager

System info
![image](https://user-images.githubusercontent.com/47507975/163091740-80218953-afc3-4adc-8b03-8c17abe10295.png)

Display manager: lightdm
Laptop model: Asus TUF A15 2021
The version of optimus-manager you are using : latest stable release (optimus-manager).
Your custom optimus-manager configuration file:
![image](https://user-images.githubusercontent.com/47507975/163091989-8fd22fbd-6083-4b03-b259-59a18d0d3d62.png)

Logs:
![image](https://user-images.githubusercontent.com/47507975/163092115-bf646de0-c227-4938-87c9-985593fe27d9.png)
[log daemon.zip](https://github.com/Askannz/optimus-manager/files/8477912/log.daemon.zip)

[optimus manager log switch.zip](https://github.com/Askannz/optimus-manager/files/8477908/optimus.manager.log.switch.zip)

**Comment by Mario156090** [comment]
@Askannz :)

**Comment by Askannz** [comment]
What makes you think the card isn't shutting down? Have you followed the [power management guide](https://github.com/Askannz/optimus-manager/wiki/A-guide--to-power-management-options)?

**Comment by Mario156090** [comment]
> What makes you think the card isn't shutting down? Have you followed the [power management guide](https://github.com/Askannz/optimus-manager/wiki/A-guide--to-power-management-options)?

Hi @Askannz, yeah, I read the guide. I think my card is not shutting down because in integrated mode state if I run a game always use the nvidia card. With another tool as ubuntu prime inbuild and Pop OS tool the nvidia card does not working anymore in integrated mode equivalent.

Anyway, If I execute nvidia-smi show me the information for the nvidia card in integrated mode when should show me:
nvidia-smi has failed because it couldn't communicate with the nvidia driver

**Comment by FallingSnow** [comment]
Does it work when you manually try to switch the nvidia card off with bbswitch?

**Comment by Mario156090** [comment]
> Does it work when you manually try to switch the nvidia card off with bbswitch?

How I can do that?

**Comment by damian101** [comment]
Same issue here, the Nvidia driver still loads in integrated mode, making it identical to Hybrid mode, my card model is T550. 
What I want to do is force software to use the integrated Intel GPU, for troubleshooting purposes, so if anyone knows how without uninstalling the Nvidia driver, please tell me...

**Comment by damian101** [comment]
> Does it work when you manually try to switch the nvidia card off with bbswitch?

Just tried it, followed the Arch Wiki, by creating `/etc/modprobe.d/bbswitch.conf` with content `options bbswitch load_state=0 unload_state=1` and `/etc/modules-load.d/bbswitch.conf` with content `bbswitch`. The result was that my system didn't boot anymore. Maybe a conflict with Optimus Manager? Or maybe I just did something wrong...

**Comment by damian101** [comment]
Found this in the system logs: `Failed to find module 'bbswitch load_state=0'`

**Comment by FallingSnow** [comment]
> Found this in the system logs: `Failed to find module 'bbswitch load_state=0'`

I looks like you don't have bbswitch installed or the module may not be in your initramfs.

**Comment by damian101** [comment]
> > Found this in the system logs: `Failed to find module 'bbswitch load_state=0'`
> 
> I looks like you don't have bbswitch installed or the module may not be in your initramfs.

Yes, had to run `mkinitcpio -P`. 
Bbswitch can disable my Nvidia GPU.

**Comment by es20490446e** [comment]
Reopen if the method above doesn't work.
