### ISSUE TITLE
Set resolution for display manager

### ISSUE THREAD

**Issue by jamesj2** [Askannz/optimus-manager#50]
I have a laptop with a 4k screen.  The login the fonts are real small and hard to read.  If I change /usr/share/sddm/scripts/Xsetup I can get a easier to read resolution.  But it gets overwritten on the next boot.  Would it be possible to add a xrandr command to the setup script? I''m using Manjaro with KDE5 (sddm).

```
#!/bin/sh
# make login on 4k screen readable
xrandr --output eDP-1-1 --mode 2048x1152
# Xsetup - run as root before the login dialog appears
exec /usr/bin/optimus-manager_Xsetup
```

**Comment by Askannz** [comment]
I'll look into it, but if you have the time, could you test @tgwt's pull request at https://github.com/Askannz/optimus-manager/pull/47 ? I'd be curious to know if it solves your issue.

**Comment by jamesj2** [comment]
I tried pull request #47 but it reverted my DPI back to 75.  I was using DPI 100 in the optimus-manager.conf.  I have two monitors on is 4k (laptop) and the other is 3440x1440.  So if I do change the DPI for one it changes for the other.  

My solution was to force the laptop screen to a different resolution for the login screen after which KDE could handle the rest.  Ideally one could set a hash of options that could be set per output.

**Comment by tgwt** [comment]
The driver developers set native dpi to 75 (at least nvidia). So nothing will come with my pull request. Sorry.

**Comment by tgwt** [comment]
It means that my fix is not necessary.

**Comment by Askannz** [comment]
Should be fixed in latest master. DPI now defaults to 96 in Nvidia mode.
