### ISSUE TITLE
.desktop file for the systray is missing

### ISSUE THREAD

**Issue by JpegXguy** [Askannz/optimus-manager#51]
**Describe the bug**
README:
>To make the tray icon automatically launch with your DE, it is usually enough to do:
>
>```
>ln -s /usr/share/applications/optimus-manager-systray.desktop ~/.config/autostart/optimus-manager-systray.desktop
>```

After installing 0.7 version:
```
$ ls /usr/share/applications/optimus-manager-systray.desktop
ls: cannot access '/usr/share/applications/optimus-manager-systray.desktop': No such file or directory
```

Manual call of `optimus-manager-systray` in autostart works fine.

**System info**
Please include :
- Manjaro
- Cinnamon
- LightDM

**Comment by Askannz** [comment]
Yeah, I forgot to add it to the AUR package. It's fixed now.
