### ISSUE TITLE
Hotfix: Adding LightDM to `logout_current_desktop_session()` @ sessions.py

### ISSUE THREAD

**Issue by sgtrusty** [Askannz/optimus-manager#511]
**Describe the bug**
[Just as other DE/WM are exitted, exit LightDM for engaged usability.](https://github.com/Askannz/optimus-manager/blob/46249ec33a5f08287a678aa012ad166056bc7b92/optimus_manager/sessions.py#L47-L57). Currently I am using LightDM hooked up to a i3 + xmonad setup which I'm specifically using xmonad on at the moment, and when I change to the hybrid mode I need to manually kill the lightdm process in order to re-login.

## Proposed fix
![image](https://user-images.githubusercontent.com/48886164/186210828-c70518ba-96f4-4c59-8550-0de0a5240f87.png)

Add
```py
"pkill -SIGTERM -f lightdm" # lightdm
``` 
To the lines in the code above.

**Comment by nwildner** [comment]
Hello @sgtrusty .

Looking at [`sessions.py`](https://github.com/Askannz/optimus-manager/blob/master/optimus_manager/sessions.py) on the `master` branch, this change was already put in place, and `lightdm` graceful termination is already being handled.

Please use the `optimus-manager-git` package on your distribution to keep track of those changes.

Cheers.
