### ISSUE TITLE
GPU not going to sleep using runtime D3 power management with hybrid mode

### ISSUE THREAD

**Issue by asier-ochoa** [Askannz/optimus-manager#512]
**Describe the bug**
I think since the last nvidia driver update, runtime d3 doesn't seem to turn off my dgpu (mi laptop has a hardware indicator if the dgpu is being used). With nvidia-smi there's a small xorg process running on the gpu making it consume 3-18W, not ideal for battery life (I used to get 6-8 hours using hybrid mode, now I get about 2-2:30):
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   47C    P8     3W /  N/A |      5MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      4442      G   /usr/lib/Xorg                       4MiB |
+-----------------------------------------------------------------------------+
```

**System info**
Please include :
- Arch Linux
- KDE Plasma 5.25
- SDDM
- MSI GS65 9SF (RTX 2070 Max-Q)
- Optimus Manager Git from the AUR
- Config:

```
[amd]
DRI=3
driver=modesetting
tearfree=

[intel]
DRI=3
accel=
driver=modesetting
modeset=yes
tearfree=

[nvidia]
DPI=96
PAT=yes
allow_external_gpus=no
dynamic_power_management=fine
ignore_abi=no
modeset=yes
options=overclocking

[optimus]
auto_logout=yes
pci_power_control=no
pci_remove=no
pci_reset=no
startup_auto_battery_mode=integrated
startup_auto_extpower_mode=nvidia
startup_mode=nvidia
switching=none
```

No erros in logs as far as I can see.

**Comment by eric28** [comment]
hi

The same problem happens to me, I think the bug is directly from the nvidia driver. 

At first it worked until version 440 of the driver, if I install a later version it stops working. If I returned to the driver 440 it worked again so it is not an optimus-manager problem. 

Interestingly my laptop is the GS65 8SE I asked in the nvidia forum but they have not been able to give me a solution either.

**Comment by eric28** [comment]
I think it will be the same bug that happens to me. Although it should, the laptop does not support the "video memory off" functionality and if this option is not deactivated, you have consumption problems.

You can disable it from the configuration file by updating this parameter to 0: dynamic_power_management_memory_threshold=0

The energy management does not have to be changed, it must be kept in "fine"
dynamic_power_management=fine

**Comment by asier-ochoa** [comment]
What happened was that i changed my acpi_osi kernel parameter to `acpi_osi=! acpi_osi="Windows 2009"`

After removing this everything works perfectly fine!
