### ISSUE TITLE
Jitter in hybrid mode

### ISSUE THREAD

**Issue by ayasa520** [Askannz/optimus-manager#518]
Sorry I'm completely clueless about this, so it's most likely not an issue with optimus-manager. It's also possible that this is completely normal.

In short, running `glxgears -info` and `prime-run glxgears -info` in Nvidia mode and Hybrid mode respectively, although both display 144FPS, you can observe to the naked eye that the graphics in Nvidia mode are much smoother.

https://user-images.githubusercontent.com/55699692/191567228-47e576fe-a93e-456b-b04b-6fdbc922b78b.mp4

https://user-images.githubusercontent.com/55699692/191567246-77f5ee60-e75f-4e1e-baec-1f660b61ca07.mp4

**System info**
OS: Manjaro Linux x86_64 
Host: 81Q5 Legion Y7000P 2019 
Kernel: 5.19.9-zen1-1-zen 
Uptime: 37 mins 
Packages: 1439 (pacman), 3 (snap) 
Shell: zsh 5.9 
Resolution: 1920x1080 
DE: GNOME 42.5 
WM: Mutter 
WM Theme: Colloid-special 
Theme: Colloid [GTK2/3] 
Icons: Colloid [GTK2/3] 
Terminal: gjs 
CPU: Intel i7-9750H (12) @ 4.500GHz 
GPU: NVIDIA GeForce GTX 1660 Ti Mobile 
GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630] Memory: 4173MiB / 15877MiB

**Comment by nwildner** [comment]
Hi @ayasa520 

Could you please confirm if the choppyness you are seeing is on `hybrid` or on `nvidia` mode?

I'm asking this becase I'm unifying all cases related to `nvidia` mode being sluggish here:

 - #498

Also for your case, is it still reproducible today running a more modern distribution, linux kernel, nvidia drivers and using `optimus-manager-git` ?

Have a nice week.

**Comment by es20490446e** [comment]
This is on hybrid, I get the same behavior on a very similar Lenovo laptop.

Maybe this is just the GPU being not powerful enough, as I get the same behavior despite server and driver.

But I'm not completely sure.

**Comment by es20490446e** [comment]
This is most likely to the screen not being attached directly to the GPU that generates graphics, so the extra overhead of copying from one GPU to the other results in this.

I observed this being worse in the past, and also that other people were discussing it online.

So this rather looks as a driver limitation that we cannot fix on `optimus-manager`.
