### ISSUE TITLE
Unable to reload SDDM

### ISSUE THREAD

**Issue by ShaturIQ** [Askannz/optimus-manager#52]
**Describe the bug**
When I switch video card, SDDM does not start, hangs on "Reaching graphical target". But after rebooting the system, the video card change is applied and works as expected. Is short I need to reboot OS to change card.

**System info**
Please include :
Operating System: Arch Linux 
KDE Plasma Version: 5.15.0
KDE Frameworks Version: 5.55.0
Qt Version: 5.12.1
Kernel Version: 4.20.10-arch1-1-ARCH
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-8550U CPU @ 1.80GHz
Memory: 19,5 ГиБ

**Logs**

[dmesg](https://pastebin.com/fSwvaxHg)

[Xorg](https://pastebin.com/8U2UkxVB)

```
journalctl -u display-manager -b0 --no-pager
-- Logs begin at Mon 2019-02-18 21:06:12 EET, end at Tue 2019-02-19 15:22:37 EET. --
-- No entries --
```

```
journalctl -u optimus-manager -b0 --no-pager
-- Logs begin at Mon 2019-02-18 21:06:12 EET, end at Tue 2019-02-19 15:24:24 EET. --
фев 19 15:17:24 AcerAspire5 systemd[1]: Started Optimus Manager Commands Daemon.
фев 19 15:17:24 AcerAspire5 python[532]: Optimus Manager (Daemon) version 0.7.1
фев 19 15:17:24 AcerAspire5 python[532]: Awaiting commands
```

`/etc/X11/` contains nothing related to GPUs except `10-optimus-manager.conf`

**Comment by Shatur95** [comment]
Fixed it by changing `switching=nouveau` to `switching=bbswitch`.

**Comment by Askannz** [comment]
Do you have any issues if you boot directly in Nvidia mode ? (`optimus-manager --set-startup nvidia`)

To help me debug, please do the following with `switching=bbswitch` enabled :

- Boot into Intel mode
- Try to switch to nvidia mode and do that Ctrl + Alt + Backspace trick to recover the session
 - Paste the log of the sddm service here (You can redirect it to a file like this :  `journalctl -u sddm -b0 --no-pager > /path/to/file.txt`)

**Comment by Shatur95** [comment]
Boot directly in Nvidia mode works.

[Here](https://pastebin.com/Fd7kc8DF) is requested log :)

**Comment by Destroyerrrocket** [comment]
I can confirm this exact issue. If more logs are needed, I can also provide them.

**Comment by Askannz** [comment]
Sorry of the lack of updates. Could you test the current github master branch ?

**Comment by Destroyerrrocket** [comment]
I'll test it today and I'll update this comment.

**Comment by Shatur95** [comment]
Yes, with the latest changes from the master branch everything works fine. Switching works both ways without any problems.

@Destroyerrrocket, what version of the kernel are you using? I tested on `linux-lts`.

**Comment by Destroyerrrocket** [comment]
@Shatur95 `linux`, I'll check `linux-lts` and update this comment. Could you also check if reloading works for you?

**Comment by Shatur95** [comment]
@Destroyerrrocket, yes, `linux` work for me too :)
