### ISSUE TITLE
WiFi not working when i switch Optimus modes.

### ISSUE THREAD

**Issue by ghost** [Askannz/optimus-manager#520]
Ive got an Acer Nitro AN515-44 with a 1650Ti , when i switch modes i can no longer power off from the system in itself and my WiFi adapter isn't recognized. It also occasionally stops working on startup when i close my laptop lid whilst the system opens (I have hybrid set on startup)

**Comment by StrikeNP** [comment]
I'm nearly a year late, but I had this issue as well and believe it may be unrelated to optimus-manager. I was able to resolve this by setting my NetworkManager wifi backend as iwd rather than the default
https://wiki.archlinux.org/title/NetworkManager#Using_iwd_as_the_Wi-Fi_backend

**Comment by nwildner** [comment]
Closing since @StrikeNP provided some insights related to `iwd` and the original reported deleted his/her/their github account.
