### ISSUE TITLE
Unable to switch to nvidia

### ISSUE THREAD

**Issue by reikdas** [Askannz/optimus-manager#53]
**Describe the bug**
I am unable to switch to the nvidia mode. This used to work before. --switch nvidia nor --set-startup nvidia work. 

**System info**
Please include :
- Distribution - Manjaro
- Desktop Manager - i3 Community edition.
- Display manager - Lightdm
- MSI GS65 Stealth thin 8rf (Arch wiki page - https://wiki.archlinux.org/index.php/MSI_GS65)

**Logs**
Logs are after booting usingoptimus-manager --set-startup nvidia_once
- Kernel - https://pastebin.com/tg5aRQ2A
- Xorg : https://pastebin.com/Q8brLLf1
- Display manager : https://pastebin.com/sV2yUpQK
- Daemon : https://pastebin.com/6UnprkLB

**Comment by Askannz** [comment]
I see nothing wrong in the log, the Nvidia modules seem to be correctly loaded.

Just to be clear, when you say that it doesn't work, you mean that `optimus-manager --print-mode` still reports `intel` ?

If that's the case, please run the following commands  after booting into Nvidia mode and paste their outputs here :

`lspci -k | grep -A 3 NVIDIA`

`xrandr --listproviders`

`cat /etc/X11/xorg.conf.d/10-optimus-manager.conf`

**Comment by Askannz** [comment]
Also, you are still using optimus-manager 0.6. I doubt it would make a difference in this case, but just to be safe, please update to v0.7.1.

**Comment by michaldybczak** [comment]
Please update to the newest version 1.0.2 (already in testing) and edit /etc/sddm.conf and put a # before the lines DisplayCommand and DisplayStopCommand.

**Comment by Meshikhah** [comment]
I have exactly the same problem now 
It was working properly before but now it has stopped working.
```
▶ lspci -k | grep -A 3 NVIDIA
01:00.0 3D controller: NVIDIA Corporation GM108M [GeForce 940MX] (rev a2)
        Subsystem: ASUSTeK Computer Inc. GM108M [GeForce 940MX]
        Kernel driver in use: nouveau
        Kernel modules: nouveau, nvidia_drm, nvidia
```
```
▶ xrandr --listproviders
Providers: number : 2
Provider 0: id: 0x74 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 2 associated providers: 1 name:modesetting
Provider 1: id: 0x3f cap: 0x5, Source Output, Source Offload crtcs: 0 outputs: 0 associated providers: 1 name:modesetting
```
```
▶ cat /etc/X11/xorg.conf.d/10-optimus-manager.conf
Section "Device"
        Identifier "intel"
        Driver "modesetting"
        BusID "00:02:0"
        Option "DRI" "3"
        Option "modeset" "no"
EndSection
```
```
▶ inxi -Fxz                                       
System:    Host: PIPBOY Kernel: 4.20.17-1-MANJARO x86_64 bits: 64 compiler: gcc v: 8.2.1 Desktop: KDE Plasma 5.15.5 
           Distro: Manjaro Linux 
Machine:   Type: Laptop System: ASUSTeK product: X510UQ v: 1.0 serial: <filter> 
           Mobo: ASUSTeK model: X510UQ v: 1.0 serial: <filter> UEFI: American Megatrends v: X510UQ.309 date: 08/08/2018 
Battery:   ID-1: BAT0 charge: 30.5 Wh condition: 30.5/42.1 Wh (73%) model: ASUSTeK ASUS Battery status: Not charging 
CPU:       Topology: Dual Core model: Intel Core i7-7500U bits: 64 type: MT MCP arch: Kaby Lake rev: 9 L2 cache: 4096 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 23240 
           Speed: 731 MHz min/max: 400/3500 MHz Core speeds (MHz): 1: 800 2: 800 3: 802 4: 801 
Graphics:  Device-1: Intel HD Graphics 620 vendor: ASUSTeK driver: i915 v: kernel bus ID: 00:02.0 
           Device-2: NVIDIA GM108M [GeForce 940MX] vendor: ASUSTeK driver: nouveau v: kernel bus ID: 01:00.0 
           Display: x11 server: X.Org 1.20.4 driver: modesetting resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 620 (Kaby Lake GT2) v: 4.5 Mesa 19.0.4 direct render: Yes 
Audio:     Device-1: Intel Sunrise Point-LP HD Audio vendor: ASUSTeK driver: snd_hda_intel v: kernel bus ID: 00:1f.3 
           Sound Server: ALSA v: k4.20.17-1-MANJARO 
Network:   Device-1: Intel Wireless 8265 / 8275 driver: iwlwifi v: kernel port: e000 bus ID: 02:00.0 
           IF: wlp2s0 state: up mac: <filter> 
Drives:    Local Storage: total: 931.51 GiB used: 136.18 GiB (14.6%) 
           ID-1: /dev/sda vendor: Seagate model: ST1000LM035-1RK172 size: 931.51 GiB 
Partition: ID-1: / size: 608.30 GiB used: 136.16 GiB (22.4%) fs: ext4 dev: /dev/sda6 
Sensors:   System Temperatures: cpu: 49.0 C mobo: N/A 
           Fan Speeds (RPM): N/A 
Info:      Processes: 176 Uptime: 14m Memory: 11.61 GiB used: 1.27 GiB (10.9%) Init: systemd Compilers: gcc: 8.3.0 
           clang: 8.0.0 Shell: zsh v: 5.7.1 inxi: 3.0.34 
```

**Comment by michaldybczak** [comment]
> I have exactly the same problem now
> It was working properly before but now it has stopped working.

Did you update to 1.0-2? If you use Plasma and SDDM, did you modify SDDM conf accordingly to Installation info on this page?

https://github.com/Askannz/optimus-manager

**Comment by Meshikhah** [comment]
Yes I didn't know I should've modify sddm.conf .  this solved my problem Thanks anyway!

**Comment by michaldybczak** [comment]
Great. I'm happy it helped.
Then you can close the topic and enjoy the freedom of using the best GPU suited to the task :).
