### ISSUE TITLE
KDE Missing Icons and Fonts when Booting in Hybrid Mode?

### ISSUE THREAD

**Issue by TheEmeraldFalcon** [Askannz/optimus-manager#531]
**Describe the bug**
Whenever I attempt to boot into KDE (startx) while hybrid mode is enabled, the only font is the default system one, and no icons appear. Everything else seems to function as normal, though I wasn't able to test it easily.

**System info**
Distro: Arch Linux
DE: KDE
LoginMgr: None
Release: Latest Stable
Customisation: No Customisation other than changing default from Integrated to Nvidia, changing back does not affect bug.

**Comment by TheEmeraldFalcon** [comment]
So I had a chance to experiment with it a bit more, and it seems overall buggy. I can't close or move windows, many keyboard shortcuts don't work, no titlebars, etc.

(I also forgot to mention I'm using the KDE 5.27 beta.)

**Comment by bigreeen** [comment]
Ok i'm not the only one who experiment this issue. Did you find a solution ?

**Comment by es20490446e** [comment]
Are you still experiencing this issue?

What is your GPU and CPU model?

What Nvidia drivers are you using?
