### ISSUE TITLE
I can no longer log into my site. It is stuck on the loading page after I hit log in.

### ISSUE THREAD

**Issue by Liberty-library** [Askannz/optimus-manager#536]
**Describe the bug**
I can no longer log into my site. It is stuck on the loading page after I hit log in. I have tried making a new account and logging and getting the same result. I even tried the encoder site to log in and its telling it can't find my site.
https://liberty-library.com/
**System info**
Please include :
- Your distribution: latest pull
- Your desktop manager (KDE, GNOME, Cinnamon...), if you have one
- You display manager (SDDM, GDM, LightDM...), if you have one. If you do not know, you are probably using the one coming with your desktop manager.
- Your laptop model, if you think it could be related to the problem
- The version of optimus-manager you are using : latest stable release (optimus-manager), or the latest Git version (optimus-manager-git)
- Your custom optimus-manager configuration file at `/etc/optimus-manager/optimus-manager.conf`, if you made one

**Logs**
Run `optimus-manager --status` in a console, and if an error message appears, post it here. The message should also point you to a log path, attach it here as well. If there is no error message but you are still experiencing issues, grab the most recent files in `/var/log/optimus-manager/switch/` and `/var/log/optimus-manager/daemon/`.

**Comment by PixsaOJ** [comment]
You are on wrong GitHub project

**Comment by nwildner** [comment]
Not related with `optimus-manager` whatsoever. Closing.
