### ISSUE TITLE
Feature Request: Enable VRR for AMD based systems

### ISSUE THREAD

**Issue by E-daw** [Askannz/optimus-manager#540]
Laptops are now shipping with variable refresh rate displays, there should be an option within the AMD config option to enable the feature for systems with AMD integrated graphics. When trying to edit the config value in /etc/X11/xorg.conf.d/10-optimus-manager.conf to enable VRR, the changes won't be saved on the next reboot as optimus manager refreshes the config file. There should be a specific setting or a way allow arguments to be passed so that certain features can be enabled or disabled.

-Manjaro 6.2
-KDE plasma 5.27.4
-SDDM
-Lenovo Slim 7 Pro X
-Optimus Manager 1.4

No errors to report.

**Comment by nwildner** [comment]
Hello @E-daw 

Please refer to the configuration files inside your [`/etc/optimus-manager/xorg/<MODE>/<brand>-gpu.conf`](https://github.com/Askannz/optimus-manager?tab=readme-ov-file#extra-xorg-configuration) where you can add custom configuration options for any GPU running at any mode you desire. 

While this might look suboptimal and VRR should be enabled by default on AMD GPUs, we'll not have the workforce to test it to be sure that this is indeed a safe option to be shipped by default on iGPUS and dGPUS.

Meanwhile, please follow the instructions linked above so you can keep those options persistent across reboots.

Have a nice weekend.
