### ISSUE TITLE
black screen when switching to integrated

### ISSUE THREAD

**Issue by leuchtrakete666** [Askannz/optimus-manager#548]
hi,

i already tried all the suggested solutions from the wiki. different switching methods. removed early loading from mkinitcpio. checked the logs. journal and X11. nothing helps. the logs are not helpfull.

booting to integrated works. not switching from hybrid or nvidia.

i am happy to provide all infos needed.

thanks for the help.

**Comment by leuchtrakete666** [comment]
i got it.

needed to put i915 for early loading to mkinitcpio. now runs like a charm.

**Comment by ljtnono** [comment]
jíchéng móshì gāi zěnme bàn ne?
使用相机翻译文字
I have the same problem, but what should I do if I must switch from other modes to integrated mode?

**Comment by nwildner** [comment]
Hi @ljtnono , please follow #477, where there are some insights related to the `nvidia*` modules being hold by other nvidia related daemons.

As for the original report of this case, adding `i915` to the initialrd seems to be solved, and there is also the case where in laptops that are muxless (no mux switch) the intel driver is the responsible for drawing on screen so, this could explain why this worked.

Closing the case.
