### ISSUE TITLE
script before switching to new mode

### ISSUE THREAD

**Issue by leuchtrakete666** [Askannz/optimus-manager#549]
i want to stop nvidia-powerd.service before the graphic card is switched. nvidia cannot be unloaded with active powerd. so i want to stop it before unloading the nvidia drivers.

can this be achieved somehow? 

thanks.

**Comment by nwildner** [comment]
Hi @leuchtrakete666 . 
AFAIK, there is no way to automate that and currently this needs to be done manually. 
Seems to be related with #477 where someone posted a workaround of manually powering down `nvidia-powerd` before switching graphics.

**Comment by es20490446e** [comment]
If you are still experiencing this issue, reopen it and I will look into it.
