### ISSUE TITLE
When I switch to Nvidia, the built-in screen of the laptop stays black but I can still input my password or use monitors plugged to a video output

### ISSUE THREAD

**Issue by T-3B** [Askannz/optimus-manager#552]
**Describe the bug**
I'm having a problem described in the trouble shooting section of the wiki: "When I switch to Nvidia, the built-in screen of the laptop stays black but I can still input my password or use monitors plugged to a video output".

When I switch to Nvidia (or simply boot in Nvidia mode), my Display Manager won't show up: my laptop screen is black. I can enter my password, then my Window Manager starts and finally the screen is working as expected.
Therefore the black screen only happens on the log-in screen from my Display Manager.

Other modes (integrated, hybrid) don't have any problem.

The wiki suggests that this may be a Prime configuration problem. All my packages are up to date.
Any help would be greatly appreciated.

**System info**
- Arch Linux 6.5.8-arch1-1
- Display Manager: [SLiM 1.4.0-2](https://slim-fork.sourceforge.io/)
- Desktop Manager: `-`
- Window Manager: IceWM 3.4.3-1
- Laptop model: Machenike-T58V
- Intel Core i7-10870H
- Nvidia RTX 3060 laptop
- `optimus-manager` 1.5-4 (latest stable release)

`optimus-manager.conf`:
```
[optimus]
switching=none
pci_power_control=yes
pci_remove=yes
pci_reset=function_level
auto_logout=no
startup_mode=auto
startup_auto_battery_mode=hybrid
startup_auto_extpower_mode=nvidia

[intel]
driver=intel
accel=
tearfree=
DRI=3
modeset=yes

[nvidia]
modeset=yes
PAT=yes
DPI=96
ignore_abi=no
allow_external_gpus=no
options=overclocking
dynamic_power_management=fine
dynamic_power_management_memory_threshold=
```
**Logs**
`optimus-manager --status` shows no error.
Filenames should be meaningful:
[kernel.log](https://github.com/Askannz/optimus-manager/files/13198741/kernel.log)
[Xorg.0.log](https://github.com/Askannz/optimus-manager/files/13198742/Xorg.0.log)
[display-manager_slim.log](https://github.com/Askannz/optimus-manager/files/13198743/display-manager_slim.log)
[optimus-manager_service_journalctl.log](https://github.com/Askannz/optimus-manager/files/13198744/optimus-manager_service_journalctl.log)
[optimus-manager_daemon-20231029T131222.log](https://github.com/Askannz/optimus-manager/files/13198745/optimus-manager_daemon-20231029T131222.log)
[optimus-manager_switch-20231029T131222.log](https://github.com/Askannz/optimus-manager/files/13198746/optimus-manager_switch-20231029T131222.log)

Any help is appreciated, thanks!

**Comment by T-3B** [comment]
Related: #450 #410 #113

**Comment by T-3B** [comment]
After further tests, it appears that my laptop screen is NOT powered at all on my login screen.
So it's not a black screen, rather a disabled/turned off screen.

**Comment by T-3B** [comment]
@nwildner Thank you for your message!

In my BIOS (which I enter with the F12 key at startup), there very limited options (only SATA/NVMe and boot configurations are available). So I cannot do anything on this side for changing the "Ultimate" mode (except if I should change the BIOS but I never heard anything like that).

I just tried `optimus-manager-git`, and... it is even worse: after changing to `nvidia` mode, my screen is still turned off (**even after entering my password**). I know I managed to still unlock my login manager (and entering my WM) because I did some actions blindly that I could find in the future with `integrated` (or `hybrid`) mode.

**Comment by motareis** [comment]
I'm having the same or a closely similar issue:

**Describe the bug**
Starting my laptop in Hybrid mode, I can use my built-in laptop monitor and my external display port monitor. As soon as I switch to Nvidia mode, my built-in monitor stays black at login and after logging in. When I switch to TTY in Nvidia mode, the built-in monitor works again. 

In addition, when I deactivate my built-in monitor in Hybrid mode and switch to Nvidia mode, the external monitor works fine. When I activate the built-in monitor in Nvidia mode, it stays black but the display on the external monitor is shifted to the left (I only see the furthest right third of the display and the rest of the external monitor is black).

**System info**
- distribution: 6.6.40-1-MANJARO (64-bit)
- desktop manager: KDE Plasma 6.0.5
- display manager: SDDM
- Laptop: XMG CORE 15 (M20)
- optimus-manager version: optimus-manager-git 
- `/etc/optimus-manager/optimus-manager.conf`
```
[amd]
DRI=3
driver=modesetting
tearfree=

[intel]
DRI=3
accel=
driver=modesetting
modeset=yes
tearfree=

[nvidia]
DPI=96
PAT=yes
allow_external_gpus=no
dynamic_power_management=no
ignore_abi=no
modeset=yes
options=overclocking

[optimus]
auto_logout=no
pci_power_control=no
pci_remove=no
pci_reset=no
startup_auto_battery_mode=integrated
startup_auto_extpower_mode=nvidia
startup_mode=nvidia
switching=none
```

**Logs**
`optimus-manager --status`
```
Optimus Manager (Client) version 1.5

Current GPU mode : nvidia
GPU mode requested for next login : no change
GPU at startup : nvidia
Temporary config path: no
```

`/var/log/optimus-manager/switch/`
```
[15] INFO: # Xorg pre-start hook
[15] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'nvidia', 'current_mode': None}
[15] INFO: Requested mode is: nvidia
[42] INFO: Available modules: ['nouveau', 'acpi_call', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[42] INFO: Unloading modules ['nouveau'] (if loaded)
[46] INFO: switching=none, nothing to do
[77] INFO: Loading module nvidia
[1491] INFO: Loading module nvidia_drm
[2366] INFO: Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf
[2366] INFO: Writing state {'type': 'pending_post_xorg_start', 'switch_id': '20240722T103152', 'requested_mode': 'nvidia'}
[2367] INFO: Xorg pre-start hook completed successfully.
[9] INFO: # Xorg post-start hook
[47] INFO: Running xrandr commands
[142] ERROR: Cannot setup PRIME (xrandr error):
None
[142] INFO: Running /etc/optimus-manager/xsetup-nvidia.sh
[152] INFO: Writing state {'type': 'done', 'switch_id': '20240722T103152', 'current_mode': 'nvidia'}
[153] INFO: Xorg post-start hook completed successfully.
[9] INFO: # Xorg pre-start hook
[9] INFO: Previous state was: {'type': 'done', 'switch_id': '20240722T103152', 'current_mode': 'nvidia'}
[9] INFO: Requested mode is: nvidia
[35] INFO: Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf
[36] INFO: Writing state {'type': 'pending_post_xorg_start', 'switch_id': '20240722T103152', 'requested_mode': 'nvidia'}
[36] INFO: Xorg pre-start hook completed successfully.
[9] INFO: # Xorg post-start hook
[47] INFO: Running xrandr commands
[175] ERROR: Cannot setup PRIME (xrandr error):
None
[175] INFO: Running /etc/optimus-manager/xsetup-nvidia.sh
[186] INFO: Writing state {'type': 'done', 'switch_id': '20240722T103152', 'current_mode': 'nvidia'}
[187] INFO: Xorg post-start hook completed successfully.
```

`/var/log/optimus-manager/daemon/`
```
[38] INFO: # Daemon pre-start hook
[38] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[39] INFO: Copying /etc/optimus-manager/optimus-manager.conf to /var/lib/optimus-manager/tmp/config_copy.conf
[42] INFO: Startup mode is: nvidia
[42] INFO: Writing state {'type': 'pending_pre_xorg_start', 'requested_mode': 'nvidia', 'current_mode': None}
[43] INFO: Daemon pre-start hook completed successfully.
[43] INFO: Calling Xorg pre-start hook.
[1] INFO: # Commands daemon
[1] INFO: Opening UNIX socket
[1] INFO: Awaiting commands
```

**Comment by nwildner** [comment]
Hi @motareis 

And is your built-in display keeping the same name when you switch from hybrid to nvidia?

Please run the following command on hybrid and nvidia modes(open a terminal on your external monitor on nvidia mode, don't go to the tty): 

`xrandr | grep eDP`


Should print something like `eDP-1` in one of the cases and `eDP1-1`/`eDP-0-1` or some other index when you switch to nvidia.

**Comment by motareis** [comment]
Thanks @nwildner for your support.

Hybrid mode: ```xrandr | grep eDP```
```eDP-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 194mm```

Nvidia mode: 
```xrandr | grep eDP```
```eDP-1-1 connected (normal left inverted right x axis y axis)```

**Comment by nwildner** [comment]
Good. And if you manually enable the monitor using `xrandr` or any GUI frontend like `arandr`, does it brings the monitor back to life after switching to `nvidia mode`?

Trying to follow a line of thought here to check if this issue isn't the login manager not handling the monitor rename correctly(in this case `sddm`) .

I'm also using sddm and could not reproduce the same issue on my laptop.

**Comment by motareis** [comment]
Trying to activate laptop monitor via ```arandr``` 
I get a popup ```XRandR returned code error 1: b'xranrd: Configure crtc 4 failed\n'``` 
and in terminal ```(arandr:5643): Gdk-CRITICAL **: 10:55:20.803: gdk_atom_intern: assertion 'atom_name != NULL' failed```

Trying to activate it via ```xrandr --auto``` or ```xrandr --output eDP-1-1 --mode 1920x1080 --rate 144.01``` (or any other mode and rate) 
I get ```xrandr: Configure crtc 4 failed```

Searching for this error code left me with more questions than answers, unfortunately. Could be something with the X.org config files, the kernel, the driver, or - as someone in a forum suggested - "just switch to Windows, bro" :roll_eyes:

Just in case additional info might relevant: 
<details>

<summary>xrandr --prop</summary>

```
Screen 0: minimum 8 x 8, current 2560 x 1440, maximum 32767 x 32767
DP-0 connected primary 2560x1440+0+0 (normal left inverted right x axis y axis) 597mm x 336mm
        _KDE_SCREEN_INDEX: 1 
        CTM: 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 
                0 1 
        CscMatrix: 65536 0 0 0 0 65536 0 0 0 0 65536 0 
        EDID: 
                00ffffffffffff001e6d7f5b27de0300
                091e0104b53c22789f8cb5af4f43ab26
                0e5054254b007140818081c0a9c0b300
                d1c08100d1cf09ec00a0a0a067503020
                3a0055502100001a000000fd003090e6
                e63c010a202020202020000000fc004c
                4720554c545241474541520a000000ff
                003030394e544e4837463437390a012b
                02031a7123090607e305c000e6060501
                60592846100403011f13565e00a0a0a0
                29503020350055502100001a5aa000a0
                a0a0465030203a005550210000006fc2
                00a0a0a0555030203a0055502100001a
                00000000000000000000000000000000
                00000000000000000000000000000000
                000000000000000000000000000000da
        BorderDimensions: 4 
                supported: 4
        Border: 0 0 0 0 
                range: (0, 65535)
        SignalFormat: DisplayPort 
                supported: DisplayPort
        ConnectorType: DisplayPort 
        ConnectorNumber: 1 
        _ConnectorLocation: 1 
        non-desktop: 0 
                supported: 0, 1
   2560x1440    143.97 + 120.00    99.95    59.95* 
   1920x1080     74.91    60.00    59.94    50.00  
   1680x1050     59.95  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1152x864      59.96  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x480       59.94  
   640x480       75.00    59.94    59.93  
DP-1 disconnected (normal left inverted right x axis y axis)
        CTM: 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 
                0 1 
        CscMatrix: 65536 0 0 0 0 65536 0 0 0 0 65536 0 
        BorderDimensions: 4 
                supported: 4
        Border: 0 0 0 0 
                range: (0, 65535)
        SignalFormat: TMDS 
                supported: TMDS
        ConnectorType: DisplayPort 
        ConnectorNumber: 1 
        _ConnectorLocation: 1 
        non-desktop: 0 
                supported: 0, 1
DP-2 disconnected (normal left inverted right x axis y axis)
        CTM: 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 
                0 1 
        CscMatrix: 65536 0 0 0 0 65536 0 0 0 0 65536 0 
        BorderDimensions: 4 
                supported: 4
        Border: 0 0 0 0 
                range: (0, 65535)
        SignalFormat: DisplayPort 
                supported: DisplayPort
        ConnectorType: DisplayPort 
        ConnectorNumber: 2 
        _ConnectorLocation: 2 
        non-desktop: 0 
                supported: 0, 1
DP-3 disconnected (normal left inverted right x axis y axis)
        CTM: 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 
                0 1 
        CscMatrix: 65536 0 0 0 0 65536 0 0 0 0 65536 0 
        BorderDimensions: 4 
                supported: 4
        Border: 0 0 0 0 
                range: (0, 65535)
        SignalFormat: TMDS 
                supported: TMDS
        ConnectorType: DisplayPort 
        ConnectorNumber: 2 
        _ConnectorLocation: 2 
        non-desktop: 0 
                supported: 0, 1
HDMI-0 disconnected (normal left inverted right x axis y axis)
        CTM: 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 
                0 1 
        CscMatrix: 65536 0 0 0 0 65536 0 0 0 0 65536 0 
        BorderDimensions: 4 
                supported: 4
        Border: 0 0 0 0 
                range: (0, 65535)
        SignalFormat: TMDS 
                supported: TMDS
        ConnectorType: HDMI 
        ConnectorNumber: 0 
        _ConnectorLocation: 0 
        non-desktop: 0 
                supported: 0, 1
eDP-1-1 connected (normal left inverted right x axis y axis)
        EDID: 
                00ffffffffffff0038704b0000000000
                011d0104a5221378036850985c588e28
                1b505400000001010101010101010101
                010101010101008280a070381f403020
                350058c21000001a008280a070387644
                3020350058c21000001a000000fd0028
                3c43430e010a202020202020000000fe
                004c4d3135364c462d314630320a003e
        PRIME Synchronization: 1 
                supported: 0, 1
        HDCP Content Type: HDCP Type0 
                supported: HDCP Type0, HDCP Type1
        Content Protection: Undesired 
                supported: Undesired, Desired, Enabled
        vrr_capable: 0 
                range: (0, 1)
        Colorspace: Default 
                supported: Default, BT709_YCC, opRGB, BT2020_RGB, BT2020_YCC
        abm level: 0 
                range: (0, 4)
        max bpc: 16 
                range: (8, 16)
        underscan vborder: 0 
                range: (0, 128)
        underscan hborder: 0 
                range: (0, 128)
        underscan: off 
                supported: off, on, auto
        scaling mode: None 
                supported: None, Full, Center, Full aspect
        link-status: Good 
                supported: Good, Bad
        CTM: 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 
                0 1 
        CONNECTOR_ID: 87 
                supported: 87
        non-desktop: 0 
                range: (0, 1)
   1920x1080    144.01 +  72.01    60.02    50.00    48.00    59.97    59.96    59.93  
   1680x1050    144.01    59.95    59.88  
   1400x1050     74.76    59.98  
   1600x900      59.99    59.94    59.95    59.82  
   1280x1024    144.01    85.02    75.02    60.02  
   1440x900     144.01  
   1400x900      59.96    59.88  
   1280x960      85.00    60.00  
   1440x810      60.00    59.97  
   1368x768      59.88    59.85  
   1280x800     144.01    59.99    59.97    59.81    59.91  
   1152x864      75.00  
   1280x720     144.01    60.00    59.99    59.86    59.74  
   1024x768     144.01    85.00    75.05    60.04    85.00    75.03    70.07    60.00  
   1024x768i     86.96  
   960x720       85.00    75.00    60.00  
   928x696       75.00    60.05  
   896x672       75.05    60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   832x624       74.55  
   960x540       59.96    59.99    59.63    59.82  
   800x600      144.01    85.00    75.00    70.00    65.00    60.00    85.14    72.19    75.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   700x525       74.76    59.98  
   800x450       59.95    59.82  
   640x512       85.02    75.02    60.02  
   700x450       59.96    59.88  
   640x480      144.01    85.09    60.00    85.01    72.81    75.00    59.94  
   720x405       59.51    58.99  
   720x400       85.04  
   684x384       59.88    59.85  
   640x400       59.88    59.98    85.08  
   576x432       75.00  
   640x360       59.86    59.83    59.84    59.32  
   640x350       85.08  
   512x384       85.00    75.03    70.07    60.00  
   512x384i      87.06  
   512x288       60.00    59.92  
   416x312       74.66  
   480x270       59.63    59.82  
   400x300       85.27    72.19    75.12    60.32    56.34  
   432x243       59.92    59.57  
   320x240       85.18    72.81    75.00    60.05  
   360x202       59.51    59.13  
   360x200       85.04  
   320x200       85.27  
   320x180       59.84    59.32  
   320x175       85.27  
  1680x1050 (0x1c5) 146.250MHz -HSync +VSync
        h: width  1680 start 1784 end 1960 total 2240 skew    0 clock  65.29KHz
        v: height 1050 start 1053 end 1059 total 1089           clock  59.95Hz
  1280x1024 (0x1c7) 135.000MHz +HSync +VSync
        h: width  1280 start 1296 end 1440 total 1688 skew    0 clock  79.98KHz
        v: height 1024 start 1025 end 1028 total 1066           clock  75.02Hz
  1280x1024 (0x1c8) 108.000MHz +HSync +VSync
        h: width  1280 start 1328 end 1440 total 1688 skew    0 clock  63.98KHz
        v: height 1024 start 1025 end 1028 total 1066           clock  60.02Hz
  1280x800 (0x1c9) 83.500MHz -HSync +VSync
        h: width  1280 start 1352 end 1480 total 1680 skew    0 clock  49.70KHz
        v: height  800 start  803 end  809 total  831           clock  59.81Hz
  1024x768 (0x1ce) 78.750MHz +HSync +VSync
        h: width  1024 start 1040 end 1136 total 1312 skew    0 clock  60.02KHz
        v: height  768 start  769 end  772 total  800           clock  75.03Hz
  1024x768 (0x1cf) 65.000MHz -HSync -VSync
        h: width  1024 start 1048 end 1184 total 1344 skew    0 clock  48.36KHz
        v: height  768 start  771 end  777 total  806           clock  60.00Hz
  800x600 (0x1d0) 49.500MHz +HSync +VSync
        h: width   800 start  816 end  896 total 1056 skew    0 clock  46.88KHz
        v: height  600 start  601 end  604 total  625           clock  75.00Hz
  800x600 (0x1d1) 40.000MHz +HSync +VSync
        h: width   800 start  840 end  968 total 1056 skew    0 clock  37.88KHz
        v: height  600 start  601 end  605 total  628           clock  60.32Hz
  640x480 (0x1d3) 31.500MHz -HSync -VSync
        h: width   640 start  656 end  720 total  840 skew    0 clock  37.50KHz
        v: height  480 start  481 end  484 total  500           clock  75.00Hz
  640x480 (0x1d4) 25.175MHz -HSync -VSync
        h: width   640 start  656 end  752 total  800 skew    0 clock  31.47KHz
        v: height  480 start  490 end  492 total  525           clock  59.94Hz
```

</details>

<details>

<summary>xrandr --listproviders</summary>

```
Providers: number : 2
Provider 0: id: 0x1b7 cap: 0x1, Source Output crtcs: 4 outputs: 5 associated providers: 1 name:NVIDIA-0
Provider 1: id: 0x1fd cap: 0x2, Sink Output crtcs: 4 outputs: 1 associated providers: 1 name:modesetting
```

</detail>

**Comment by aka-Kush** [comment]
Facing same issue,
Hybrid and Integrated modes work just fine. Switching to nvidia mode makes my primary laptop display completely black.
I can still use my secondary display connected with HDMI. 
Checked display name using xrandr, it is changed from eDP-1 to eDP-1-1 when switched to nvidia.
Tried arandr to fix display issue, still got this error `b'xrandr: Configure crtc 4 failed\n'`

**Specs:**
HP Omen 15 laptop
Nvidia RTX 3060 mobile
AMD Ryzen 7 5000 series
Arch with Gnome

**Comment by Blixtdraken** [comment]
Exact same laptop model as aka-kush above, though I use Endevour(arch) with kde plasma and sddm

Same issue as the original issuer...

**Comment by aka-Kush** [comment]
> Exact same laptop model as aka-kush above, though I use Endevour(arch) with kde plasma and sddm
> 
> Same issue as the original issuer...

After exhausting almost every option, I’ve made my peace with just hybrid mode. 
This project is not maintained anymore, so I don’t think there is any point of discussing it here.

**Comment by es20490446e** [comment]
Try the following:

- In `hybrid`mode, check if offloading uses the nvidia card with `__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia glxinfo | grep vendor`. Otherwise the Nvidia driver not working at all is the culprit.

- Make sure the installed package of `optimus-manager` is `optimus-manager-git`.

- In the UEFI, disabling any power saving mode.

- Using as driver `nvidia-open` `dkms` version, along with `linux-headers` named after the kernel you are using.

- Having `optimus-manager` uninstalled, if setting up the screen works by running `nvidia-xconfig`. If it doesn't, remove the created config with `sudo rm  /etc/X11/xorg.conf`.

- Try the [solutions at the Arch wiki](https://wiki.archlinux.org/title/NVIDIA/Troubleshooting).

If at any moment you get a black screen, you can switch to a terminal by pressing `Control + Alt + F3`. If that doesn't work, use a live USB along with `arch-chroot` or `manjaro-chroot -a` to revert the changes.

After trying all of that, please reopen (or if you can't just comment), and we will see what we can do to prevent the issue.
