### ISSUE TITLE
Default Startup GPUs don't work

### ISSUE THREAD

**Issue by username227** [Askannz/optimus-manager#554]
Hi,
I'm using Arch on a dual-GPU laptop. I've installed optimus-manager. It's set (i believe it's the default) to start in Nvidia if it's connected to power and integrated when it's not. But it always starts up with integrated even if it's connected to the power, seemingly ignoring the conf file. 

A second problem, which may be related, is that despite all of my playing around with it, my runtime d3 status always says disabled by default. No matter what I do with optimus-manager or with nvidia settings, it continues to have this message. I'm wondering if there's something going on here that's causing it not to respect the config file? Any ideas?

**Comment by nwildner** [comment]
Hello @username227 .

Could you please provide more details on this case like?

**Distribution:
Kernel:
Nvidia driver version:
`optimus-manager` version: 
Laptop model:
GPU Model:**  (usually `lspci | grep VGA` works) 

Logs and configuration files are also welcome to help investigating this case
