### ISSUE TITLE
Games still run in intel mode

### ISSUE THREAD

**Issue by JasonYangShadow** [Askannz/optimus-manager#56]
I use steam to run some games in Nvidia mode, while it seems that the graphics list inside game stills shows 'Unknown Device', which I think is intel GPU other than Nvidia GPU and could not change. If I could pass some options to the game before running it?

**Comment by Askannz** [comment]
The game should use whatever GPU has been enabled by optimus-manager for your current desktop seesion. Run `glxinfo | grep "server glx vendor string"` while in Nvidia mode. If you see `NVIDIA Corporation`, then you're good.

**Comment by JasonYangShadow** [comment]
> The game should use whatever GPU has been enabled by optimus-manager for your current desktop seesion. Run `glxinfo | grep "server glx vendor string"` while in Nvidia mode. If you see `NVIDIA Corporation`, then you're good.

So if glxinfo shows correct GPU(Nvidia in this case), then all programs running inside current session(if they need GPU to render), they all use the correct GPU(Nvidia)? 
Meaning that the session is created associated with defined GPU, either intel or nvidia?

**Comment by Askannz** [comment]
> So if glxinfo shows correct GPU(Nvidia in this case), then all programs running inside current session(if they need GPU to render), they all use the correct GPU(Nvidia)?
Meaning that the session is created associated with defined GPU, either intel or nvidia?

Yes and yes.

**Comment by JasonYangShadow** [comment]
thank you so much!!!
