### ISSUE TITLE
System freezes when trying Wayland

### ISSUE THREAD

**Issue by FairplexVR** [Askannz/optimus-manager#577]
**Describe the bug**
I just updated Optimus Manager to 1.5, hoping that it will fix my issue with Wayland. But I still have a full system freeze when trying to logging using wayland. 

**System info**
Please include :
- Arch Linux
- Your desktop manager: KDE
- You display manager: SDDM 
- Your laptop model: MSI FX720 (ntel HD Graphics 3000 + Nvidia GT 520M)
- The version of optimus-manager you are using : latest stable release (optimus-manager)
- Your custom optimus-manager configuration: N/A

**Logs**
Run `optimus-manager --status` in a console, and if an error message appears, post it here. The message should also point you to a log path, attach it here as well. If there is no error message but you are still experiencing issues, grab the most recent files in `/var/log/optimus-manager/switch/` and `/var/log/optimus-manager/daemon/`.

[daemon-20240921T115054.log](https://github.com/user-attachments/files/17083627/daemon-20240921T115054.log)
[switch-20240921T113919.log](https://github.com/user-attachments/files/17083628/switch-20240921T113919.log)

**Comment by es20490446e** [comment]
- Have you experienced this issue prior to my update on Wayland support?

- What drivers are you using for the Nvidia card?

- Have you tried uninstalling or installing `xf86-video-intel`?

---

According to the [Debian wiki](https://wiki.debian.org/NvidiaGraphicsDrivers) Fermi is only supported up to proprietary driver version 390.144, while Arch uses 560.35.03.

So the driver may simply not be loading, which is required for `optimus-manager` to work.

**Comment by FairplexVR** [comment]
- Have you experienced this issue prior to my update on Wayland support?
Prior to the update, optimus manager worked as expected, only on X11, it was already freezing on Wayland. But I saw that you added some Wayland support so I wanted to test again.

- What drivers are you using for the Nvidia card?
I am using the driver 390.157

- Have you tried uninstalling or installing xf86-video-intel?
xf86-video-intel is installed but I will try to uninstall it and let you know if that helps.

**Comment by FairplexVR** [comment]
No luck without xf86-video-intel, system is still freezing when I try to login with Wayland.

**Comment by es20490446e** [comment]
1. With Kate make a file called `optimus-manager.conf`, with the following content:

```
[optimus]
startup_mode=hybrid
```

2. In the terminal type `optimus-manager --temp-config optimus-manager.conf`

Does the system still work, or does it crash?

**Comment by es20490446e** [comment]
I suspect this is due to the drivers not working at all.

Do you have the linux headers package installed, for your specific kernel variant?

- `linux-headers`
- `linux-zen-headers`
- `linux-lts-headers`

**Comment by FairplexVR** [comment]
I do have the kernel **6.10.10-arch1-1** and the **linux-headers 6.10.10.arch1-1**. I am not sure what you mean by the driver is not working at all? 

![image](https://github.com/user-attachments/assets/ce6ac8c3-6b02-4956-a029-e69944e0f1ea)

**Comment by FairplexVR** [comment]
> 1. With Kate make a file called `optimus-manager.conf`, with the following content:
> 
> 
> ```
> [optimus]
> startup_mode=hybrid
> ```
> 
>     2. In the terminal type:
>        `optimus-manager --temp-config optimus-manager.conf`
> 
> 
> Does the system still work, or does it crash?

Hybrid works with X11. Freeze on Wayland just like startup_mode=nvidia

**Comment by es20490446e** [comment]
That means the issue is with the driver itself.

The other two modes work just because they are using the integrated GPU driver instead.

I would try the methods described at: https://wiki.archlinux.org/title/NVIDIA
