### ISSUE TITLE
Expected fallback mechanism

### ISSUE THREAD

**Issue by de-conf** [Askannz/optimus-manager#58]
Expected fallback mechanism
Bug report
When I can't switch to NVIDIA, I can't automatically return to Intel. I don't generate the default xorg.conf in the xorg.conf.d directory.
Expect to increase the fallback mechanism, you can automatically fall back

**Comment by Askannz** [comment]
Xorg should already default to Intel if there is no config file.

**Comment by de-conf** [comment]
However, occasionally special circumstances may not fall back.
I met once
