### ISSUE TITLE
service starts too fast for eGPU

### ISSUE THREAD

**Issue by jamincollins** [Askannz/optimus-manager#581]
**Describe the bug**

I find that `optimus-manager` starts too fast/early in the boot process with an eGPU enclosure.  This results in a failure to see the nvidia card and load the module.  Which in turn results in the displays connected to the enclosure not working (obviously).

When this happens I see the following in the unit's journal:

```
Aug 21 09:42:38 odin python3[763]: [13] INFO: # Xorg pre-start hook
Aug 21 09:42:38 odin python3[763]: [13] INFO: Previous state was: {'type': 'pending_pre_xorg_start', 'requested_mode': 'nvidia', 'current_mode': None}
Aug 21 09:42:38 odin python3[763]: [13] INFO: Requested mode is: nvidia
Aug 21 09:42:38 odin python3[822]: modinfo: ERROR: Module bbswitch not found.
Aug 21 09:42:38 odin python3[824]: modinfo: ERROR: Module acpi_call not found.
Aug 21 09:42:38 odin python3[763]: [33] INFO: Available modules: ['nouveau', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
Aug 21 09:42:38 odin python3[763]: [33] INFO: Unloading modules ['nouveau'] (if loaded)
Aug 21 09:42:38 odin python3[763]: [35] INFO: switching=none, nothing to do
Aug 21 09:42:38 odin python3[763]: [227] INFO: Nvidia card not visible in PCI bus, rescanning
Aug 21 09:42:38 odin python3[763]: [228] INFO: Rescanning PCI bus
Aug 21 09:42:38 odin python3[763]: [447] ERROR: Nvidia card not showing up in PCI bus after rescan. Continuing anyways.
Aug 21 09:42:38 odin python3[763]: [449] INFO: Loading module nvidia
Aug 21 09:42:39 odin python3[763]: [1036] ERROR: Xorg pre-start setup error
Aug 21 09:42:39 odin python3[763]: Traceback (most recent call last):
Aug 21 09:42:39 odin python3[763]:   File "/usr/lib/python3.12/site-packages/optimus_manager/kernel.py", line 245, in _load_module
Aug 21 09:42:39 odin python3[763]:     subprocess.check_call(
Aug 21 09:42:39 odin python3[763]:   File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
Aug 21 09:42:39 odin python3[763]:     raise CalledProcessError(retcode, cmd)
Aug 21 09:42:39 odin python3[763]: subprocess.CalledProcessError: Command 'modprobe nvidia NVreg_UsePageAttributeTable=1' returned non-zero exit status 1.
Aug 21 09:42:39 odin python3[763]: The above exception was the direct cause of the following exception:
Aug 21 09:42:39 odin python3[763]: Traceback (most recent call last):
Aug 21 09:42:39 odin python3[763]:   File "/usr/lib/python3.12/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 51, in main
Aug 21 09:42:39 odin python3[763]:     setup_kernel_state(config, prev_state, requested_mode)
Aug 21 09:42:39 odin python3[763]:   File "/usr/lib/python3.12/site-packages/optimus_manager/kernel.py", line 22, in setup_kernel_state
Aug 21 09:42:39 odin python3[763]:     _nvidia_up(config, hybrid=(requested_mode == "hybrid"))
Aug 21 09:42:39 odin python3[763]:   File "/usr/lib/python3.12/site-packages/optimus_manager/kernel.py", line 95, in _nvidia_up
Aug 21 09:42:39 odin python3[763]:     _load_nvidia_modules(config, available_modules)
Aug 21 09:42:39 odin python3[763]:   File "/usr/lib/python3.12/site-packages/optimus_manager/kernel.py", line 164, in _load_nvidia_modules
Aug 21 09:42:39 odin python3[763]:     _load_module(available_modules, "nvidia", options=nvidia_options)
Aug 21 09:42:39 odin python3[763]:   File "/usr/lib/python3.12/site-packages/optimus_manager/kernel.py", line 249, in _load_module
Aug 21 09:42:39 odin python3[763]:     raise KernelSetupError(f"Error running modprobe for {module}: {e.stderr}") from e
Aug 21 09:42:39 odin python3[763]: optimus_manager.kernel.KernelSetupError: Error running modprobe for nvidia: None
```

If I remote into the system (via SSH) I find that the eGPU is seen, the nvidia card is present on the PCI bus, but the nvidia module is not loaded, and the X.org config is not created.  Simply restarting `optimus-manager` results in the nvidia module being loaded and the X.org config being created.  At which point I need to restart LightDM.

I believe it would be useful to allow for a (possibly configurable) startup delay to wait a few seconds for the eGPU to be fully enumerated.

I've simply added a `time.sleep(5)` to the Xorg pre-start hook and it seems to work fine for me.

**System info**
Please include :
- Your distribution -- Arch Linux
- Your desktop manager  -- XFCE
- You display manager -- LightDM 
- The version of optimus-manager you are using : 1.5-4
- Your custom optimus-manager configuration file at `/etc/optimus-manager/optimus-manager.conf`, if you made one
```
$ cat /etc/optimus-manager/optimus-manager.conf
[optimus]
switching=none
pci_power_control=no
pci_remove=no
pci_reset=no
auto_logout=yes
startup_mode=auto
startup_auto_battery_mode=integrated
startup_auto_extpower_mode=nvidia


[intel]
driver=modesetting
accel=
tearfree=
DRI=3
modeset=yes


[amd]
driver=modesetting
tearfree=
DRI=3


[nvidia]
modeset=yes
PAT=yes
DPI=96
ignore_abi=no
allow_external_gpus=yes
options=overclocking
dynamic_power_management=no
dynamic_power_management_memory_threshold=
```

**Logs**
Run `optimus-manager --status` in a console, and if an error message appears, post it here. The message should also point you to a log path, attach it here as well. If there is no error message but you are still experiencing issues, grab the most recent files in `/var/log/optimus-manager/switch/` and `/var/log/optimus-manager/daemon/`.

**Comment by es20490446e** [comment]
Most likely the `optimus-manager.service` has the wrong ordering, not waiting for another service.

To discovering which service it needs to wait, remove the Xorg pre-start hook modification.

Then at `usr/lib/systemd/system/optimus-manager.service` add `After=[SERVICE]`, where `[SERVICE]` is some other service inside that `system` folder.

It might be `nvidia-persistenced.service`, `systemd-modules-load.service`, or something else. Likely a service starting with `systemd-`, or some `.target.`

If you find out let me know and I will make a fix 🪚
