### ISSUE TITLE
Cant switch my gpu

### ISSUE THREAD

**Issue by THXRXAPXR** [Askannz/optimus-manager#583]
**Describe the bug**
i get [Xx_JXHN_xX@archlinux ~]$ optimus-manager --switch nvidia
ERROR: the latest GPU setup attempt failed at Xorg pre-start hook.
Log at /var/log/optimus-manager/switch/switch-20241005T122251.log
Error parsing config file /var/lib/optimus-manager/tmp/config_copy.conf. Falling back to default config /usr/share/optimus-manager/optimus-manager.conf. Error is : File contains no section headers.
file: '/var/lib/optimus-manager/tmp/config_copy.conf', line: 2
'switching=none\n'
Cannot execute command because of previous errors.
[Xx_JXHN_xX@archlinux ~]$ 
when trying to switch to my nvidia card.

**System info**
                   -`                    Xx_JXHN_xX@archlinux 
                  .o+`                   -------------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: G75VW 1.0 
               `+oooooo:                 Kernel: 6.11.1-zen1-1-zen 
               -+oooooo+:                Uptime: 1 hour, 25 mins 
             `/:-:++oooo+:               Packages: 1335 (pacman), 7 (flatpak) 
            `/++++/+++++++:              Shell: bash 5.2.37 
           `/++++++++++++++:             Resolution: 1600x900 
          `/+++ooooooooooooo/`           DE: Xfce 4.18 
         ./ooosssso++osssssso+`          WM: Xfwm4 
        .oossssso-````/ossssss+`         WM Theme: Default 
       -osssssso.      :ssssssso.        Theme: Adwaita-dark [GTK2], Breeze [GT 
      :osssssss/        osssso+++.       Icons: elementary [GTK2], breeze [GTK3 
     /ossssssss/        +ssssooo/-       Terminal: xfce4-terminal 
   `/ossssso+/:-        -:/+osssso+-     Terminal Font: Monospace 12 
  `+sso+:-`                 `.-/+oso:    CPU: Intel i7-3610QM (8) @ 3.300GHz 
 `++:.                           `-/+/   GPU: NVIDIA GeForce GTX 660M 
 .`                                 `/   Memory: 3228MiB / 15952MiB
- The version of optimus-manager you are using : latest stable release (optimus-manager), from AUR 
- Your custom optimus-manager configuration file at `/etc/optimus-manager/optimus-manager.conf`, if you made one: 
- # Info at `/usr/share/optimus-manager/optimus-manager.conf`.
switching=none

**Logs**
Run `optimus-manager --status` [Xx_JXHN_xX@archlinux ~]$ optimus-manager --status
ERROR: the latest GPU setup attempt failed at Xorg pre-start hook.
Log at /var/log/optimus-manager/switch/switch-20241005T122251.log
Error parsing config file /var/lib/optimus-manager/tmp/config_copy.conf. Falling back to default config /usr/share/optimus-manager/optimus-manager.conf. Error is : File contains no section headers.
file: '/var/lib/optimus-manager/tmp/config_copy.conf', line: 2
'switching=none\n'
Cannot execute command because of previous errors.
[Xx_JXHN_xX@archlinux ~]$ 
 in `/var/log/optimus-manager/switch/` and `/var/log/optimus-manager/daemon/`.
[Xx_JXHN_xX@archlinux ~]$ cat /var/lib/optimus-manager/tmp/config_copy.conf
# Info at `/usr/share/optimus-manager/optimus-manager.conf`.
switching=none
[Xx_JXHN_xX@archlinux ~]$

**Comment by es20490446e** [comment]
`Error is : File contains no section headers.`

Does your system have the following files?:

- `/etc/optimus-manager/optimus-manager.conf`
- `/usr/share/optimus-manager/optimus-manager.conf`

From which repository are you installing `optimus-manager`, which is the package name?
