### ISSUE TITLE
openGL refers to nvidia gpu even in "integrated" mode 

### ISSUE THREAD

**Issue by ECO1AI** [Askannz/optimus-manager#585]
on "integrated" if i run `glxinfo` or `glxgears` i get:
```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  28
  Current serial number in output stream:  29
```
apparently this is because the system is referring to Nvidia driver which return error instead of choosing mesa

if i add `__GLX_VENDOR_LIBRARY_NAME=mesa` as environment variable for `glxgears` it works
source : [Test software GL arch wiki](https://wiki.archlinux.org/title/NVIDIA/Troubleshooting#Other_issues) 

i am running endeavour OS ( was on manjaro on an old release ( before optimus project was looking for maintainers) everything was perfect)

all installed nvidia apps:
```
yay -Q | grep "nvidia"

lib32-nvidia-utils 565.57.01-1
lib32-opencl-nvidia 565.57.01-1
libva-nvidia-driver 0.0.13-1
nvidia-hook 1.5.1-1
nvidia-open-dkms 565.57.01-1
nvidia-prime 1.0-5
nvidia-settings 565.57.01-1
nvidia-utils 565.57.01-1
opencl-nvidia 565.57.01-1
```
mesa apps:
```
yay -Q | grep "mesa"

lib32-libva-mesa-driver 1:24.2.6-1
lib32-mesa 1:24.2.6-1
lib32-mesa-utils 9.0.0-2
lib32-mesa-vdpau 1:24.2.6-1
libva-mesa-driver 1:24.2.6-1
mesa 1:24.2.6-1
mesa-utils 9.0.0-5
mesa-vdpau 1:24.2.6-1
```

still looking at how we can change this behavior, if you need any more debug info send me what you need.

**Comment by es20490446e** [comment]
Let me investigate, and I will come back to you 🔍

**Comment by es20490446e** [comment]
What do you get if in the terminal you enter `inxi --graphics`.

**Comment by ECO1AI** [comment]
> What do you get if in the terminal you enter `inxi --graphics`?

here you go:
```
inxi --graphics
Graphics:
  Device-1: NVIDIA GA107M [GeForce RTX 3050 Mobile] driver: N/A
  Device-2: Advanced Micro Devices [AMD/ATI] Lucienne driver: amdgpu
    v: kernel
  Device-3: Chicony HD User Facing driver: uvcvideo type: USB
  Display: wayland server: X.org v: 1.21.1.14 with: Xwayland v: 24.1.4
    compositor: kwin_wayland driver: X: loaded: amdgpu dri: radeonsi gpu: amdgpu
    resolution: 1536x864
  API: EGL v: 1.5 drivers: kms_swrast,radeonsi,swrast
    platforms: gbm,wayland,x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: mesa v: 24.2.6-arch1.1
    note: incomplete (EGL sourced) renderer: llvmpipe (LLVM 18.1.8 256 bits),
    AMD Radeon Graphics (radeonsi renoir LLVM 18.1.8 DRM 3.54 6.6.59-1-lts)
  API: Vulkan Message: No Vulkan data available.
```

**Comment by es20490446e** [comment]
`optimus-manager` is just doing what I intended it to do: exposing that the Nvidia driver isn't working at all, and that it needs fixing.

Ask in the [EndeavourOS forums](https://forum.endeavouros.com/) why `nvidia-open-dkms` isn't working. They may know details about the package or the kernel I don't.

**Comment by es20490446e** [comment]
Also note that the configuration file only applies to Xorg.

On Wayland customizations aren't implemented. GLX and Vulkan always uses the dGPU, and EGL the iGPU. Which closely resembles to how Optimus behaves on Windows.

That was not possible on Xorg, because it doesn't use EGL. Hence having a configuration was more useful.

**Comment by ECO1AI** [comment]
update: `nvidia-utils` is the one causes the problems:

for some reason, even when the nvidia driver is unloaded, EGL APi is still redirected to nvidia gpu, which returns error because the GPU is powered off.

after uninstalling `nvidia-utils` MESA driver is loaded on AMD iGPU. but of course nvidia driver wont load.

**Comment by es20490446e** [comment]
What does happen if to `/etc/profile.d/optimus-manager.sh` you add `__GLX_VENDOR_LIBRARY_NAME=mesa`?

**Comment by es20490446e** [comment]
It could be that `nvidia-utils` doesn't match the version of `nvidia-open`.

Maybe try `nvidia-open-beta-dkms`.

**Comment by es20490446e** [comment]
The question I have is why working around the issue of the Nvidia drivers not working, versus fixing it.

Isn't it fixable?

**Comment by ECO1AI** [comment]
> The question I have is why working around the issue of the Nvidia drivers not working, versus fixing it.
> 
> Isn't it fixable?

there is little i can do for a closed source driver:

i reached endeavor OS telegram, they tried their best but nothing worked.

this is the easiest and cleanest solution i have.

the only question i have is that i haven't seen anyone complaining about the same issue as me ( i reinstalled the OS twice)

**Comment by es20490446e** [comment]
1. Uninstall any `nvidia-open` and `nvidia-utils` packages you have.
2. Try installing [these](https://we.tl/t-dk5IwpvZRV) with `pacman --upgrade *.pkg.*`.
