### ISSUE TITLE
Support different tray icons

### ISSUE THREAD

**Issue by GordonFreemem** [Askannz/optimus-manager#60]
I would love to see an option to change the systray icons. I'm using a transparent taskbar with monochromic icons. The 3D-like icons look very nice, but don't fit. (Especially the green nvidia icon).

Maybe you could check another (local) path first and see if there are some icons to use. Or there could be a config option in optimus-manager.conf or whatever.

optimus-manager is the best solution I used so far to get gaming on my linux laptop working, thank you very much! (And believe me, I tried very much...)

**Comment by Askannz** [comment]
Actually I plan on replacing the current built-in tray app with this one, which has support for custom icons : https://github.com/Askannz/optimus-manager/pull/57

We just need to sort an issue with it (it has no default icons), but then it should solve your problem.

**Comment by GordonFreemem** [comment]
I just installed version 0.8 and optimus-manager-qt 1.1.0 from AUR. Looks very good so far. The default icons are perfect for my theme :-)

Only issue: the tray icons are missing after login (Launch at startup is set). if I kill optimus-manager-qt (which is running) and start it manually the icon is displayed.
I'm runnning Arch Linux with Cinnamon and ligthdm. Hadn't had much time to test under which conditions it works and when not.

**Comment by Shatur95** [comment]
Please write all problems related to the interface in the [optimus-manager-qt](https://github.com/Shatur95/optimus-manager-qt) repository.

Does this problem exists with the latest version of optimus-manager-qt?
