### ISSUE TITLE
 logind_fix for gnome fix

### ISSUE THREAD

**Issue by inzar98** [Askannz/optimus-manager#61]
Please use https://github.com/Askannz/optimus-manager/tree/logind_fix branch for gnome. Its perfectly works with gnome + gdm. tried 7.1.0 and after change gpu stucked at login screen. Anyways this branch just works :)

**Comment by inzar98** [comment]
Please add systray to this branch that will be perfect @Askannz

**Comment by Askannz** [comment]
That `logind_fix` branch was some leftover from a test, it's very outdated and I cannot re-integrate it. However the new 0.8 version should include some fixes for your problem.

As for the systray, have a look at that new section of the README : https://github.com/Askannz/optimus-manager#system-tray-icon

**Comment by Askannz** [comment]
Could you test the latest Git version and see if the problem persists ?
This version introduces some major changes to the way optimus-manager works, so you need to reboot after upgrading to make sure everything is reloaded up properly.
