### ISSUE TITLE
The options `tearfree` and `accel` only apply to the intel Xorg driver

### ISSUE THREAD

**Issue by JpegXguy** [Askannz/optimus-manager#62]
The options
```
# Acceleration method (corresponds to AccelMethod in the Xorg configuration).
# Possible values : sna, xna
# Leave blank for the default (no option specified)
accel=
```
and
```
# Enable TearFree option
# Possible values : yes, no
# Leave blank for the default (no option specified)
tearfree=
```
only apply (at least as they are implemented right now) when using `xf86-video-intel`.
I think we should include a like like the one bbswitch has for the pci_reset stuff

**System info**
Arch Linux, Cinnamon, LightDM

Side note: This nice program essentially works with the defaults for me. That says something.
The only option I have set is nvidia `triple_buffer`, and I might actually get rid of it

**Comment by Askannz** [comment]
Thanks, added a mention in the config file.
