### ISSUE TITLE
Manual replacement of nvidia file is needed

### ISSUE THREAD

**Issue by jersobh** [Askannz/optimus-manager#65]
I have to switch the 10-optimus-manager.conf every time I switch to nvidia with 

Section "Files"
  ModulePath "/usr/lib/nvidia"
  ModulePath "/usr/lib32/nvidia"
  ModulePath "/usr/lib32/nvidia/xorg/modules"
  ModulePath "/usr/lib32/xorg/modules"
  ModulePath "/usr/lib64/nvidia/xorg/modules"
  ModulePath "/usr/lib64/nvidia/xorg"
  ModulePath "/usr/lib64/xorg/modules"
EndSection

Section "Module"
	Load "modesetting"
EndSection

Section "Device"
	Identifier "nvidia"
	Driver "nvidia"
	BusID "PCI:3:0:0"
	Option "AllowEmptyInitialConfiguration"
	Option "Coolbits" "28"
	Option "TripleBuffer" "true"
	Option "DRI" "3"
EndSection

I'm not sure if Files section is needed, but BusID seems to be wrong (it was something like BusID "03:00:00". Thanks in advance.

**Comment by jersobh** [comment]
Confirming here on arch, I've successfully run it creating a xorg.conf.d/05-files.conf with
```
Section "Files"
ModulePath "/usr/lib/nvidia"
ModulePath "/usr/lib32/nvidia"
ModulePath "/usr/lib32/nvidia/xorg/modules"
ModulePath "/usr/lib32/xorg/modules"
ModulePath "/usr/lib64/nvidia/xorg/modules"
ModulePath "/usr/lib64/nvidia/xorg"
ModulePath "/usr/lib64/xorg/modules"
EndSection
```
inside, and now the only issue is with BusID.

**Comment by Askannz** [comment]
What happens exactly if you don't set those `ModulePath` ?

For the BusID, the format used by optimus-manager is `03:00:00`. There may be other valid formats though.

**Comment by jersobh** [comment]
Black screen. Also, using 03:00:00 also gives me black screen. It only works with BusID "PCI:3:0:0", IDK why. It would be great to have an option to override all the xorg conf, not just add stuff inside the device section.

**Comment by Askannz** [comment]
> It only works with BusID "PCI:3:0:0"

Well that's...unusual.

I could see why not having the `ModulePath` lines could be an issue, but that PCI bus notation should work everywhere.

What are your distribution and kernel version ? Also, could you paste the output of `lspci` ? Thanks.

**Comment by jersobh** [comment]
```
$ lspci
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Host Bridge/DRAM Registers (rev 08)
00:02.0 VGA compatible controller: Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)
00:14.0 USB controller: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller (rev 21)
00:14.2 Signal processing controller: Intel Corporation Sunrise Point-LP Thermal subsystem (rev 21)
00:15.0 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #0 (rev 21)
00:16.0 Communication controller: Intel Corporation Sunrise Point-LP CSME HECI #1 (rev 21)
00:17.0 SATA controller: Intel Corporation Sunrise Point-LP SATA Controller [AHCI mode] (rev 21)
00:1c.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #3 (rev f1)
00:1c.3 PCI bridge: Intel Corporation Device 9d13 (rev f1)
00:1d.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #9 (rev f1)
00:1f.0 ISA bridge: Intel Corporation Sunrise Point-LP LPC Controller (rev 21)
00:1f.2 Memory controller: Intel Corporation Sunrise Point-LP PMC (rev 21)
00:1f.3 Audio device: Intel Corporation Sunrise Point-LP HD Audio (rev 21)
00:1f.4 SMBus: Intel Corporation Sunrise Point-LP SMBus (rev 21)
01:00.0 Network controller: Intel Corporation Wireless 8260 (rev 3a)
02:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 15)
03:00.0 3D controller: NVIDIA Corporation GM108M [GeForce 940MX] (rev ff)
```

**Comment by jersobh** [comment]
```
$ uname -a
Linux hades 5.0.7-arch1-1-ARCH #1 SMP PREEMPT Mon Apr 8 10:37:08 UTC 2019 x86_64 GNU/Linux
```

**Comment by jersobh** [comment]
Please, if you just enable it to override the whole conf it would be perfect. I loss a lot of resources when I have to enable nvidia, because I must have two enable X sessions, on with the wrong config and other after copying my config and starting X again.

**Comment by Askannz** [comment]
Sorry for the lack of updates. I added your suggesting for the ModulePath section to the latest Git version of optimus-manager. Could you check yo see if it fixes the problem ?

This version introduces some major changes to the way optimus-manager works, so you need to reboot after upgrading to make sure everything is reloaded up properly.

**Comment by jersobh** [comment]
Sure, I'll test it tonight! Thank you! Great job :)

**Comment by jersobh** [comment]
[jeff@hades optimus-manager]$ optimus-manager --switch intel
Error loading config file : Cannot find option "auto_logout" in section [optimus]

**Comment by jersobh** [comment]
Now I can't get to xfce anymore

**Comment by Askannz** [comment]
Did you delete/modify the file `/usr/share/optimus-manager.conf` ?

**Comment by jersobh** [comment]
Nope, I didn't touched anything. I've just updated by running the setup.py (I use arch and AUR is still at 0.8.2)

**Comment by Askannz** [comment]
> Nope, I didn't touched anything. I've just updated by running the setup.py (I use arch and AUR is still at 0.8.2)

Ah, that's the issue. The setup.py should not be run directly, it's very important that you use the Arch PKGBUILD instead. For the git version, see this AUR package : https://aur.archlinux.org/packages/optimus-manager-git/

(I should have added that to the README :/ )

**Comment by jersobh** [comment]
I'll try in a few minutes. Thanks man!

Em ter, 7 de mai de 2019 20:21, Robin Lange <notifications@github.com>
escreveu:

**Comment by jersobh** [comment]
Config parsing : unknown option kill_logind in section optimus. Ignoring.
Config parsing : unknown option kill_x11 in section optimus. Ignoring.
Config parsing : unknown option login_manager_control in section optimus. Ignoring.
Config parsing : unknown option pci_reset in section optimus. Ignoring.
Config parsing : unknown option terminate_sessions in section optimus. Ignoring.
Config parsing : unknown option dri in section nvidia. Ignoring.

You are about to switch GPUs. This will forcibly close all graphical sessions and all your applications WILL CLOSE.
(you can pass the --no-confirm option to disable this warning)
Continue ? (y/N)

**Comment by jersobh** [comment]
After removing /etc/optimus-manager and reinstalling the errors are gone, but --switch nvidia keeps Intel running. Also I can't use the QT Tool because It requires optimus-manager, not optimus-manager-git.

**Comment by Askannz** [comment]
Could you post the logs from `/var/log/optimus-manager/`, just after a switching attempt ?

**Comment by jersobh** [comment]
```
[jeff@hades ~]$ cat /var/log/optimus-manager/boot_setup.log 

2019-05-08 01:14:41 AM +0000 ====================

Optimus Manager (Setup script) version 1.0
Setting up boot
Cleaning up leftover Xorg conf
Loading config
Config parsing : unknown option kill_logind in section optimus. Ignoring.
Config parsing : unknown option kill_x11 in section optimus. Ignoring.
Config parsing : unknown option login_manager_control in section optimus. Ignoring.
Config parsing : unknown option pci_reset in section optimus. Ignoring.
Config parsing : unknown option terminate_sessions in section optimus. Ignoring.
Config parsing : unknown option dri in section nvidia. Ignoring.
Reading startup mode
Startup mode is : intel
Writing startup mode to requested GPU mode
Writing requested mode
Initial GPU setup
Checking for GDM display servers
Unloading Nvidia modules
Loading bbswitch module
Setting GPU power to OFF via bbswitch
bbswitch reports that the GPU is OFF
bbswitch is enabled, pci_power_control option ignored.
Loaded extra Intel Xorg options (0 lines)
Loaded extra Nvidia Xorg options (0 lines)
Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf

2019-05-08 01:41:56 AM +0000 ====================

Optimus Manager (Setup script) version 1.0
Setting up boot
Cleaning up leftover Xorg conf
Loading config
Config parsing : unknown option kill_logind in section optimus. Ignoring.
Config parsing : unknown option kill_x11 in section optimus. Ignoring.
Config parsing : unknown option login_manager_control in section optimus. Ignoring.
Config parsing : unknown option pci_reset in section optimus. Ignoring.
Config parsing : unknown option terminate_sessions in section optimus. Ignoring.
Config parsing : unknown option dri in section nvidia. Ignoring.
Reading startup mode
Startup mode is : intel
Writing startup mode to requested GPU mode
Writing requested mode
Initial GPU setup
Checking for GDM display servers
Unloading Nvidia modules
Loading bbswitch module
Setting GPU power to OFF via bbswitch
bbswitch reports that the GPU is OFF
bbswitch is enabled, pci_power_control option ignored.
Loaded extra Intel Xorg options (0 lines)
Loaded extra Nvidia Xorg options (0 lines)
Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf

2019-05-08 01:56:56 AM +0000 ====================

Optimus Manager (Setup script) version 1.0
Setting up boot
Cleaning up leftover Xorg conf
Loading config
Reading startup mode
Startup mode is : intel
Writing startup mode to requested GPU mode
Writing requested mode
Initial GPU setup
Checking for GDM display servers
Unloading Nvidia modules
Loading nouveau module
Loaded extra Intel Xorg options (0 lines)
Loaded extra Nvidia Xorg options (0 lines)
Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf

2019-05-08 02:04:36 AM +0000 ====================

Optimus Manager (Setup script) version 1.0
Setting up boot
Cleaning up leftover Xorg conf
Loading config
Reading startup mode
Startup mode is : intel
Writing startup mode to requested GPU mode
Writing requested mode
Initial GPU setup
Checking for GDM display servers
Unloading Nvidia modules
Loading nouveau module
Loaded extra Intel Xorg options (0 lines)
Loaded extra Nvidia Xorg options (0 lines)
Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf

2019-05-08 02:08:48 AM +0000 ====================

Optimus Manager (Setup script) version 1.0
Setting up boot
Cleaning up leftover Xorg conf
Loading config
Reading startup mode
Startup mode is : intel
Writing startup mode to requested GPU mode
Writing requested mode
Initial GPU setup
Checking for GDM display servers
Unloading Nvidia modules
Loading nouveau module
Loaded extra Intel Xorg options (0 lines)
Loaded extra Nvidia Xorg options (0 lines)
Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf

2019-05-08 02:12:14 AM +0000 ====================

Optimus Manager (Setup script) version 1.0
Setting up boot
Cleaning up leftover Xorg conf
Loading config
Reading startup mode
Startup mode is : intel
Writing startup mode to requested GPU mode
Writing requested mode
Initial GPU setup
Checking for GDM display servers
Unloading Nvidia modules
Loading nouveau module
Loaded extra Intel Xorg options (0 lines)
Loaded extra Nvidia Xorg options (0 lines)
Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf

2019-05-08 02:15:13 AM +0000 ====================

Optimus Manager (Setup script) version 1.0
Setting up boot
Cleaning up leftover Xorg conf
Loading config
Reading startup mode
Startup mode is : intel
Writing startup mode to requested GPU mode
Writing requested mode
Initial GPU setup
Checking for GDM display servers
Unloading Nvidia modules
Loading nouveau module
Loaded extra Intel Xorg options (0 lines)
Loaded extra Nvidia Xorg options (0 lines)
Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf

2019-05-09 01:05:04 AM +0000 ====================

Optimus Manager (Setup script) version 1.0
Setting up boot
Cleaning up leftover Xorg conf
Loading config
Reading startup mode
Startup mode is : intel
Writing startup mode to requested GPU mode
Writing requested mode
Initial GPU setup
Checking for GDM display servers
Unloading Nvidia modules
Loading nouveau module
Loaded extra Intel Xorg options (0 lines)
Loaded extra Nvidia Xorg options (0 lines)

```

**Comment by jersobh** [comment]
no deal. Btw, I've unninstalled bbswitch. Also, why don't just do allow /etc/optimus-manager/xorg-nvidia.conf  to be the whole replacement of nvidia xorg conf instead of just increment options? that would solve all config. issues related to xorg conf.

**Comment by Askannz** [comment]
Is that the only log from `/var/log/optimus-manager/` ? If yes, then it's probably the same bug as https://github.com/Askannz/optimus-manager/issues/68#issuecomment-490697614. What are your distro and DE ?

> Also, why don't just do allow /etc/optimus-manager/xorg-nvidia.conf to be the whole replacement of nvidia xorg conf instead of just increment options?

That would completely bypass the parameters auto-generated by optimus-manager, which are required to point Xorg to the proper GPU. We would have to trust the user to re-enter those parameters manually.

I'm not completely against the idea, but it's going to require putting some red flags to make sure people don't accidentally screw their setup.

**Comment by jersobh** [comment]
My distro is Arch, XFCE with lightdm.

**Comment by Askannz** [comment]
Could you paste your `/etc/lightdm/lightdm.conf` if you have one, as well as `journalctl -u lightdm -b0 --no-pager` ? Thanks.

**Comment by jersobh** [comment]
There's no lightdm.conf, only cat /etc/lightdm/lightdm.conf.d/20-optimus-manager.conf 
[jeff@hades ~]$ cat /etc/lightdm/lightdm.conf.d/20-optimus-manager.conf 
[SeatDefaults]
# Force using X
type=xlocal
display-setup-script=/sbin/prime-offload
display-stopped-script=/sbin/prime-switch


journalctl -u lightdm -b0 --no-pager
-- Logs begin at Thu 2018-11-22 01:22:51 UTC, end at Wed 2019-06-05 01:39:13 UTC. --
-- No entries --


I gave up on this for a long time, then tonight I've tried it again, but same problem. It almost works, but the BusID "3:0:0" does not work. I really need "PCI:3:0:0", or I'll get a BSOD.

**Comment by robbert-vdh** [comment]
I ran into the same problem with my new laptop (old one worked perfectly fine, but it's been a while since I'd used optimus-manager). According `man xorg.conf`, Xorg expects bus IDs in the form of `PCI:<bus>[@<domain>]:<device>:<function>`. The domain part is optional and can be left out in most cases, and all of the fields should consist of *decimal* numbers without leading zeroes (so no hexadecimal). For some reason that is never mentioned anywhere but it did lead to some fun debugging work :sweat_smile:.

My new laptop's MX250 for instance is located on bus `3c:00.0` according to `lspci`, but Xorg expects `BusID "PCI:60:0:0"` instead. I've worked around this for the time being by simply adding the `BusID "PCI:60:0:0"` line to `/etc/optimus-manager/xorg-nvidia.conf`, but it should be a pretty easy to fix in `pci.get_bus_ids()`. For instance something like this on [line 36](https://github.com/Askannz/optimus-manager/blob/1ba0632af4f3f01b2ab4321d8eea8c3b23642fa4/optimus_manager/pci.py#L36):

```python
bus_ids = "PCI:" + ":".join(str(int(field, 16)) for field in re.split("[.:]", bus_ids))
```

**Comment by jersobh** [comment]
Finally someone who feels my pain, @robbert-vdh lol :) Thanks for the tip!

**Comment by jersobh** [comment]
@Askannz pls, accept @robbert-vdh PR. Thank you man :)

**Comment by Askannz** [comment]
Sorry for the lack of updates on this issue.
I merged robbert's PR. Very good catch ! :smiley:

**Comment by jersobh** [comment]
Working flawlessly now, @Askannz ! Great!!
