### ISSUE TITLE
Random system shutdown when switching to Nvidia

### ISSUE THREAD

**Issue by Socterean** [Askannz/optimus-manager#68]
**Describe the bug**
Trying both `0.7.1-1` and `0.8-2` versions of `optimus-manager` I encounter the same issue, after 2 or 3 switches from the system-tray my laptop completely shuts off when switching from **Intel** to **Nvidia**.

With the prior releases of `optimus-manager` I have not encountered this problem.

**System info**
OS: Manjaro Linux x86_64
Host: 20217 Lenovo IdeaPad Y510P
Kernel: 5.0.5-1-MANJARO
Resolution: 1920x1080
DE: KDE 5.15.3-1
CPU: Intel i7-4700MQ (8) @ 3.400GHz
GPU: Intel 4th Gen Core Processor
GPU: NVIDIA GeForce GT 750M
Memory: 1958MiB / 7892MiB

**Logs**
I cannot, or I don't know where I can find the logs because the laptop completely shuts down.

**Comment by Askannz** [comment]
That's interesting. I've encountered that bug on my own machine too, but it's very rare and only happened a couple of times. If you can reproduce this issue consistently, there's some hope of fixing it.

> I don't know where I can find the logs because the laptop completely shuts down.

You can append `-b-1` to the `journalctl` commands to get logs from the previous boot. In particular, `journalctl -k -b-1` (kernel log) and `journalctl -u sddm -b-1` should be interesting.

**Comment by Socterean** [comment]
[journalctl -k -b-1](https://pastebin.com/kBAJsgCx)

[journalctl -u sddm -b-1](https://pastebin.com/UR4xXBd3)

**Comment by Askannz** [comment]
Can you try changing the switching method from `nouveau` to `bbswitch` in the config file ?

If that does not work, try setting `terminate_sessions` to `no`.

**Comment by Socterean** [comment]
I have tried changing from `nouveau` to `bbswitch` in `etc/optimus-manager/optimus-manager.conf` but the problem persists. 

As a note, prior to changing to `bbswitch`, after the complete shut-down when I started again the computer it started on `nvidia` and switching back to `intel` always worked. But after chnaging to bbswitch the laptop shuts down completely also when chaging from `nvidia` back to `intel`.

[journalctl -k -b-1](https://pastebin.com/TWf1pZEv)

[journalctl -u sddm -b-1](https://pastebin.com/RPByTFPQ)

As for setting `terminate_sessions` to `no` I could not find the option in `optimus-manager.conf`

**Comment by Askannz** [comment]
Could you test the latest Git version and see if the problem persists ?
This version introduces some major changes to the way optimus-manager works, so you need to reboot after upgrading to make sure everything is reloaded up properly.

**Comment by Socterean** [comment]
I made an optimus-manager --cleanup uninstalled `optimus-manager 0.8.2` and then installed `optimus-manager-git` from the `AUR`. I also uninstalled `optimus-manager-qt` to minimize the chances for external interferences.

When I try to switch from the terminal I get:
```
optimus-manager --switch nvidia

WARNING : There are 2 other(s) desktop sessions open. The GPU switch will not become effective until you have manually logged out from ALL desktop sessions.
```

And if I log out, switch to the tty and try to do the switch from there it gives me an error that Wayland couldn't be found and it aborts the switch.

I managed to get the switch working only by setting `Nvidia` as the startup `MODE` but I could not test if this is still occurring being unable to switch at runtime.

Also the #50 and #70 are still occurring when using Nvidia.

**Comment by Askannz** [comment]
Thanks for reporting. It's very frustrating that I can almost never reproduce those bugs, even with 2 different laptops running all 3 desktops environments. A few questions for you :

* When you get that `2 other(s) desktop sessions open` error, you are sure that your current desktop session is the *only* one open, right ? Have you rebooted after upgrading optimus-manager ?

* If that error indeed appears consistently every time you try to switch from a clean boot, could you paste the output of the command `loginctl` ?

* What is that Wayland error exactly ? Is it the program crashing or a warning printed by optimus-manager ?

**Comment by Socterean** [comment]
Ok, I have reinstalled **optimus-manager-git** after a proper cleanup and this time it behaved a little different. 

So the first time it seemed to work, it gave me the usual info that optimus manager will terminate all sesions and switch the GPU's. But after loging in I discovered that I'm still on the **intel** card, so I have tried the command again and this time it gave me **WARNING : There are 1 other(s) desktop sessions open**. Noticing this I did it again and I received another **WARNING : There are 2 other(s) desktop sessions open**.

Now the `loginctl` says this:
```
[socterean@soptereanc-pc ~]$ loginctl
SESSION  UID USER      SEAT  TTY
      2 1000 socterean seat0    
      5 1000 socterean seat0    
      7 1000 socterean seat0  
```

**Comment by Askannz** [comment]
@Socterean if you could run the following debugging steps, that would be tremendously helpful.

1. Set startup mode to Intel
2. Reboot
3. Report the output of the following command : `echo $(loginctl list-sessions --no-legend | awk '{print $1}') | while read -r line; do loginctl show-session $line | grep Type; done`
4. Remove any file in `/var/log/optimus-manager/` (do NOT delete the folder !)
5. Try switching to Nvidia with `optimus-manager --switch nvidia`
6. Once you are back to your desktop session, grab all the log files re-created in `/var/log/optimus-manager/` and post them here.

Thanks :slightly_smiling_face:

**Comment by Socterean** [comment]
**First** `echo $(loginctl list-sessions --no-legend | awk '{print $1}') | while read -r line; do loginctl show-session $line | grep Type; done` shows:

`Type=x11`

After the switch I am still on **intel** and in `/var/log/optimus-manager/` is no log, it's just empty.

**The second** `echo $(loginctl list-sessions --no-legend | awk '{print $1}') | while read -r line; do loginctl show-session $line | grep Type; done` shows:
```
Type=x11
Type=x11
```

**Comment by Askannz** [comment]
Well, that bug is still a mystery. At this point I wonder if SDDM even executes the setup scripts.
What's the output of `journalctl -u sddm -b0 --no-pager` after an unsuccessful switch to nvidia ?

**Comment by Socterean** [comment]
I don't know if you are referring to the same setup scripts, but in `xsetup_intel.sh` and `xsetup_nvidia.sh` `from /etc/optimus-manager/` is nothing written there.

In xsetup_intel.sh is only:
```
#!/bin/sh

# Everything you write here will be executed by the display manager when setting up the login screen in Intel mode.
```
And in xsetup_nvidia.sh is only:
```
#!/bin/sh

# Everything you write here will be executed by the display manager when setting up the login screen in Nvidia mode.
# (but before optimus-manager sets up PRIME with xrandr commands).
```

**Comment by Socterean** [comment]
journalctl -u sddm -b0 --no-pager:
```
-- Logs begin at Mon 2018-11-05 12:44:39 EET, end at Tue 2019-05-07 21:05:24 EEST. --
mai 07 20:58:51 soptereanc-pc systemd[1]: Started Simple Desktop Display Manager.
mai 07 20:58:52 soptereanc-pc sddm[967]: Initializing...
mai 07 20:58:52 soptereanc-pc sddm[967]: Starting...
mai 07 20:58:52 soptereanc-pc sddm[967]: Logind interface found
mai 07 20:58:52 soptereanc-pc sddm[967]: Adding new display on vt 1 ...
mai 07 20:58:52 soptereanc-pc sddm[967]: Loading theme configuration from ""
mai 07 20:58:52 soptereanc-pc sddm[967]: Display server starting...
mai 07 20:58:52 soptereanc-pc sddm[967]: Running: /usr/bin/X -nolisten tcp -auth /var/run/sddm/{c9319494-5b82-4c1d-82a0-6cc22a8cc838} -background none -noreset -displayfd 17 -seat seat0 vt1
mai 07 20:59:00 soptereanc-pc sddm[967]: Setting default cursor
mai 07 20:59:00 soptereanc-pc sddm[967]: Running display setup script  "/usr/share/sddm/scripts/Xsetup"
mai 07 20:59:00 soptereanc-pc sddm[967]: Display server started.
mai 07 20:59:00 soptereanc-pc sddm[967]: Socket server starting...
mai 07 20:59:00 soptereanc-pc sddm[967]: Socket server started.
mai 07 20:59:00 soptereanc-pc sddm[967]: Loading theme configuration from "/usr/share/sddm/themes/plasma-chili/theme.conf"
mai 07 20:59:00 soptereanc-pc sddm[967]: Greeter starting...
mai 07 20:59:00 soptereanc-pc sddm[967]: Adding cookie to "/var/run/sddm/{c9319494-5b82-4c1d-82a0-6cc22a8cc838}"
mai 07 20:59:00 soptereanc-pc sddm-helper[986]: [PAM] Starting...
mai 07 20:59:00 soptereanc-pc sddm-helper[986]: [PAM] Authenticating...
mai 07 20:59:00 soptereanc-pc sddm-helper[986]: [PAM] returning.
mai 07 20:59:00 soptereanc-pc sddm-helper[986]: pam_unix(sddm-greeter:session): session opened for user sddm by (uid=0)
mai 07 20:59:01 soptereanc-pc sddm[967]: Greeter session started successfully
mai 07 20:59:03 soptereanc-pc sddm[967]: Message received from greeter: Connect
mai 07 20:59:19 soptereanc-pc sddm[967]: Message received from greeter: Login
mai 07 20:59:19 soptereanc-pc sddm[967]: Reading from "/usr/share/xsessions/plasma.desktop"
mai 07 20:59:19 soptereanc-pc sddm[967]: Reading from "/usr/share/xsessions/plasma.desktop"
mai 07 20:59:19 soptereanc-pc sddm[967]: Session "/usr/share/xsessions/plasma.desktop" selected, command: "/usr/bin/startkde"
mai 07 20:59:19 soptereanc-pc sddm-helper[1057]: [PAM] Starting...
mai 07 20:59:19 soptereanc-pc sddm-helper[1057]: [PAM] Authenticating...
mai 07 20:59:19 soptereanc-pc sddm-helper[1057]: [PAM] Preparing to converse...
mai 07 20:59:19 soptereanc-pc sddm-helper[1057]: [PAM] Conversation with 1 messages
mai 07 20:59:19 soptereanc-pc sddm-helper[1057]: pam_kwallet5(sddm:auth): (null): pam_sm_authenticate
mai 07 20:59:19 soptereanc-pc sddm-helper[1057]: [PAM] returning.
mai 07 20:59:19 soptereanc-pc sddm[967]: Authenticated successfully
mai 07 20:59:19 soptereanc-pc sddm-helper[1057]: pam_kwallet5(sddm:setcred): pam_kwallet5: pam_sm_setcred
mai 07 20:59:19 soptereanc-pc sddm-helper[1057]: pam_unix(sddm:session): session opened for user socterean by (uid=0)
mai 07 20:59:19 soptereanc-pc sddm[967]: Auth: sddm-helper exited successfully
mai 07 20:59:19 soptereanc-pc sddm[967]: Greeter stopped.
mai 07 20:59:20 soptereanc-pc sddm[967]: Session started
mai 07 21:03:40 soptereanc-pc sddm[967]: kwalletd5: Checking for pam module
mai 07 21:03:40 soptereanc-pc sddm[967]: kwalletd5: Got pam-login param
mai 07 21:03:40 soptereanc-pc sddm[967]: kwalletd5: Waiting for hash on 7-
mai 07 21:03:40 soptereanc-pc sddm[967]: kwalletd5: waitingForEnvironment on: 3
mai 07 21:03:40 soptereanc-pc sddm[967]: kwalletd5: client connected
mai 07 21:03:40 soptereanc-pc sddm[967]: kwalletd5: client disconnected
mai 07 21:03:46 soptereanc-pc sddm[967]: Auth: sddm-helper exited successfully
mai 07 21:03:46 soptereanc-pc sddm[967]: Socket server stopping...
mai 07 21:03:46 soptereanc-pc sddm[967]: Socket server stopped.
mai 07 21:03:46 soptereanc-pc sddm[967]: Display server stopping...
mai 07 21:03:47 soptereanc-pc sddm[967]: Display server stopped.
mai 07 21:03:47 soptereanc-pc sddm[967]: Running display stop script  "/usr/share/sddm/scripts/Xstop"
mai 07 21:03:47 soptereanc-pc sddm[967]: Removing display ":0" ...
mai 07 21:03:47 soptereanc-pc sddm[967]: Adding new display on vt 1 ...
mai 07 21:03:47 soptereanc-pc sddm[967]: Loading theme configuration from ""
mai 07 21:03:47 soptereanc-pc sddm[967]: Display server starting...
mai 07 21:03:47 soptereanc-pc sddm[967]: Running: /usr/bin/X -nolisten tcp -auth /var/run/sddm/{8ca1d217-0650-4223-b1c9-e41f1dc4d53b} -background none -noreset -displayfd 18 -seat seat0 vt1
mai 07 21:03:49 soptereanc-pc sddm[967]: Setting default cursor
mai 07 21:03:49 soptereanc-pc sddm[967]: Running display setup script  "/usr/share/sddm/scripts/Xsetup"
mai 07 21:03:49 soptereanc-pc sddm[967]: Display server started.
mai 07 21:03:49 soptereanc-pc sddm[967]: Socket server starting...
mai 07 21:03:49 soptereanc-pc sddm[967]: Socket server started.
mai 07 21:03:49 soptereanc-pc sddm[967]: Loading theme configuration from "/usr/share/sddm/themes/plasma-chili/theme.conf"
mai 07 21:03:49 soptereanc-pc sddm[967]: Greeter starting...
mai 07 21:03:49 soptereanc-pc sddm[967]: Adding cookie to "/var/run/sddm/{8ca1d217-0650-4223-b1c9-e41f1dc4d53b}"
mai 07 21:03:49 soptereanc-pc sddm-helper[1796]: [PAM] Starting...
mai 07 21:03:49 soptereanc-pc sddm-helper[1796]: [PAM] Authenticating...
mai 07 21:03:49 soptereanc-pc sddm-helper[1796]: pam_unix(sddm-greeter:session): session opened for user sddm by (uid=0)
mai 07 21:03:49 soptereanc-pc sddm-helper[1796]: [PAM] returning.
mai 07 21:03:49 soptereanc-pc sddm[967]: Greeter session started successfully
mai 07 21:03:49 soptereanc-pc sddm[967]: Message received from greeter: Connect
mai 07 21:04:02 soptereanc-pc sddm[967]: Message received from greeter: Login
mai 07 21:04:02 soptereanc-pc sddm[967]: Reading from "/usr/share/xsessions/plasma.desktop"
mai 07 21:04:02 soptereanc-pc sddm[967]: Reading from "/usr/share/xsessions/plasma.desktop"
mai 07 21:04:02 soptereanc-pc sddm[967]: Session "/usr/share/xsessions/plasma.desktop" selected, command: "/usr/bin/startkde"
mai 07 21:04:02 soptereanc-pc sddm-helper[1819]: [PAM] Starting...
mai 07 21:04:02 soptereanc-pc sddm-helper[1819]: [PAM] Authenticating...
mai 07 21:04:02 soptereanc-pc sddm-helper[1819]: [PAM] Preparing to converse...
mai 07 21:04:02 soptereanc-pc sddm-helper[1819]: [PAM] Conversation with 1 messages
mai 07 21:04:02 soptereanc-pc sddm-helper[1819]: pam_kwallet5(sddm:auth): (null): pam_sm_authenticate
mai 07 21:04:02 soptereanc-pc sddm-helper[1819]: [PAM] returning.
mai 07 21:04:02 soptereanc-pc sddm[967]: Authenticated successfully
mai 07 21:04:02 soptereanc-pc sddm-helper[1819]: pam_kwallet5(sddm:setcred): pam_kwallet5: pam_sm_setcred
mai 07 21:04:02 soptereanc-pc sddm-helper[1819]: pam_unix(sddm:session): session opened for user socterean by (uid=0)
mai 07 21:04:02 soptereanc-pc sddm-helper[1819]: pam_kwallet5(sddm:session): pam_kwallet5: pam_sm_open_session
mai 07 21:04:02 soptereanc-pc sddm-helper[1819]: Starting: "/usr/share/sddm/scripts/Xsession \"/usr/bin/startkde\""
mai 07 21:04:02 soptereanc-pc sddm[967]: Session started
mai 07 21:04:02 soptereanc-pc sddm[967]: Auth: sddm-helper exited successfully
mai 07 21:04:02 soptereanc-pc sddm[967]: Greeter stopped.
```

**Comment by Askannz** [comment]
I was referring to `/sbin/prime-offload` and `/sbin/prime-switch/`, which are two scripts provided by optimus-manager v1.0.

optimus-manager also provides a configuration file for SDDM at `/etc/sddm.conf.d/20-optimus-manager.conf` which hooks those scripts into the login manager. But judging from the log you posted, it looks like it didn't work :

```
mai 07 20:59:00 soptereanc-pc sddm[967]: Running display setup script  "/usr/share/sddm/scripts/Xsetup"
mai 07 20:59:00 soptereanc-pc sddm[967]: Running display setup script  "/usr/share/sddm/scripts/Xsetup"
```
Those scripts are just the default ones for SDDM, they are just empty files.

What files do you have in `/etc/sddm.conf.d/` currently ? Also, are `DisplayCommand` and `DisplayStopCommand` overwritten somewhere in `/etc/sddm.conf` ?

**Comment by Socterean** [comment]
Well, I have commented the two lines `DisplayCommand` and `DisplayStopCommand` and now switching seems to work again and now the login window appears as normal on **nvidia** and on **intel**, but I have no idea if commenting those line can break things or not.

But the problem with `WARNING : There are 1 other(s) desktop sessions open. The GPU switch will not become effective until you have manually logged out from ALL desktop sessions` still remains, and as long as I switch back and forth desktop sessions add up, 2, 3, 4, etc. which doesn't seem normal to me why are those sessions still running, why are they not closed on switch?

**Comment by Socterean** [comment]
ok, so starting from those information I searched to see what is written in `/sbin/prime-offload` and in `/sbin/prime-switch` but in `/sbin/` I cannot find `prime-switch`

**Comment by Askannz** [comment]
Thanks for investigating !

So it seems that the `DisplayCommand` and `DisplayStopCommand` keys provided by optimus-manager in `/etc/sddm.conf.d/10-optimus-manager.conf` are overruled by your main configuration file in `/etc/sddm.conf`.

I assume this isn't a change you made, and the file was like this from stock Manjaro ? It's a little weird because the default sddm package does not contain an `/etc/sddm.conf`. But maybe it's provided by Manjaro as part of the distribution. Out of curiosity, what is the output of `pacman -Qo /etc/sddm.conf` ?

As for the sessions not closing, this seems to be a bug. Another user has reported it happening on Archlinux+KDE as well, which is frustrating because that's also my setup and I cannot reproduce it. Even worse, it seems to happen even when auto-logout is disabled and the user logs out manually, and that means it could be a problem external to optimus-manager.

To help me investigate, could you do the following : reboot, then switch to another GPU, check that the previous session has not closed (run the command `loginctl`, you should see 2 sessions), then grab the log `journalctl -u systemd-logind -b0 --no-pager` ?

Thanks.

**Comment by Socterean** [comment]
No I didn't made any changes to `sddm.conf`

**pacman -Qo /etc/sddm.conf** outputs:
`error: No package owns /etc/sddm.conf`

And yes, running **loginctl** gives me 2 sessions:
```
SESSION  UID USER      SEAT  TTY
      2 1000 socterean seat0    
      5 1000 socterean seat0    

2 sessions listed.
```

And **journalctl -u systemd-logind -b0 --no-pager** outputs:
```
-- Logs begin at Sat 2018-12-08 17:55:27 EET, end at Thu 2019-05-09 21:08:24 EEST. --
mai 09 20:55:32 soptereanc-pc systemd[1]: Starting Login Service...
mai 09 20:55:33 soptereanc-pc systemd-logind[714]: New seat seat0.
mai 09 20:55:33 soptereanc-pc systemd-logind[714]: Watching system buttons on /dev/input/event3 (Power Button)
mai 09 20:55:33 soptereanc-pc systemd-logind[714]: Watching system buttons on /dev/input/event0 (Power Button)
mai 09 20:55:33 soptereanc-pc systemd-logind[714]: Watching system buttons on /dev/input/event1 (Sleep Button)
mai 09 20:55:33 soptereanc-pc systemd-logind[714]: Watching system buttons on /dev/input/event2 (Lid Switch)
mai 09 20:55:33 soptereanc-pc systemd-logind[714]: Watching system buttons on /dev/input/event5 (Logitech USB Receiver)
mai 09 20:55:33 soptereanc-pc systemd-logind[714]: Watching system buttons on /dev/input/event7 (Logitech USB Receiver Consumer Control)
mai 09 20:55:33 soptereanc-pc systemd-logind[714]: Watching system buttons on /dev/input/event8 (Logitech USB Receiver System Control)
mai 09 20:55:34 soptereanc-pc systemd-logind[714]: Watching system buttons on /dev/input/event4 (AT Translated Set 2 keyboard)
mai 09 20:55:38 soptereanc-pc systemd[1]: Started Login Service.
mai 09 20:55:58 soptereanc-pc systemd-logind[714]: New session c1 of user sddm.
mai 09 20:56:22 soptereanc-pc systemd-logind[714]: New session 2 of user socterean.
mai 09 20:56:22 soptereanc-pc systemd-logind[714]: Session c1 logged out. Waiting for processes to exit.
mai 09 20:56:22 soptereanc-pc systemd-logind[714]: Removed session c1.
mai 09 21:07:22 soptereanc-pc systemd-logind[714]: Session 2 logged out. Waiting for processes to exit.
mai 09 21:07:26 soptereanc-pc systemd-logind[714]: New session c2 of user sddm.
mai 09 21:07:42 soptereanc-pc systemd-logind[714]: New session 5 of user socterean.
mai 09 21:07:42 soptereanc-pc systemd-logind[714]: Session c2 logged out. Waiting for processes to exit.
mai 09 21:07:42 soptereanc-pc systemd-logind[714]: Removed session c2.
```

**Comment by Socterean** [comment]
I have tested the new modifications made and now the problem with sessions not closing is gone and in my testing the system didn't shut down randomly anymore.

Still there remains the problem with sddm.conf in Manjaro because of `DisplayCommand` and `DisplayStopCommand` but I believe that this issue can be closed.

**Comment by es20490446e** [comment]
This fix causes https://github.com/Askannz/optimus-manager/issues/592

**Comment by es20490446e** [comment]
The root problem seemed to be that a new session was created on a second login, rather than reusing the existing session.

Which is probably fixed now at:
https://github.com/sddm/sddm/pull/1216

You probably didn't notice the option, because it isn't mentioned in the manual:
https://github.com/sddm/sddm/issues/2086

**Comment by es20490446e** [comment]
Since this setting seems that is no longer needed, I have deleted it at: https://github.com/Askannz/optimus-manager/commit/db3ee118640c339a79d2bbed055552ccd2b623f5

If you still experience it, let me know here 👍
