### ISSUE TITLE
Unable to resume LightDM after suspend

### ISSUE THREAD

**Issue by lzkbloodmage** [Askannz/optimus-manager#71]
**Describe the bug**
Laptop was set to suspend mode. Opening the lid and attempting to resume usage, results in black screen. TTY works and able to switch to tty2. Executing "sudo lightdm" in tty2 results in black screen with a constant flashing underscore at the top left (unable to switch tty at all).

The only solution that works is by restarting lightdm when resuming from laptop suspend mode.

**System info**
Please include:
- Your distribution: **Manjaro 18.0.4 XFCE**
- Your desktop manager: **XFCE**
- You display manager: **LightDM**
- Your laptop model: **Clevo N860EP6**
- Graphic card: **Nvidia GTX 1060 Mobile**
- Additional grub parameters: **acpi_osi=! acpi_osi=\"Windows 2009\" acpi_backlight=vendor**

**Logs**
Obtained after encountering error:
- Kernel: [dmesg log](https://pastebin.com/UByQJFC5)
- Xorg : [xorg.0 log](https://pastebin.com/eT15fMa8), [xorg.1 log](https://pastebin.com/kkiedx2u), [Xorg.2 log](https://pastebin.com/ZMS12h2L)
- Display manager : [lightdm log](https://pastebin.com/1RU5VSi6)
- Optimus-manager: [log](https://pastebin.com/ugXwm8Cg)

**Comment by Askannz** [comment]
Are you sure this issue is caused by optimus-manager ? GPU issues when suspending are unfortunately quite common on Linux.

Your dmesg log shows some errors with nouveau, so you could try setting the power switching backend to "bbswitch" or "none".

**Comment by lzkbloodmage** [comment]
Not sure what I did, but problem is now gone. Previously, suspend caused LightDM issue and taskbar doesn't auto display the systray upon login. All I've done is updated whatever updates there are, and removed some unwanted programs. Strange.

Now it works totally fine. Thanks and sorry for the trouble.
