### ISSUE TITLE
Cannot switch to Nvidia GPU

### ISSUE THREAD

**Issue by advpetc** [Askannz/optimus-manager#72]
**Describe the bug**

Hello, thanks for the project! I have an issue when using the patched gdm when switching to nvidia gpu. It keeps bring me to tty, and I cannot use startx. However, after waiting for about 4 min, I can still log in but with intel gpu.

**System info**
Please include :
- Your distribution
- Your desktop manager (KDE, GNOME, Cinnamon...), if you have one
- You display manager (SDDM, GDM, LightDM...), if you have one. If you do not know, you are probably using the one coming with your desktop manager.
- Your laptop model, if you think it could be related to the problem

Using Manjaro Linux Gnome. GDM-prime installed. With version 0.8 of optimus-manger installed. My laptop is X1 Extreme.
currently have video-nvidia and video-linux driver, did I install them incorrectly?

**Logs**
If you are able to, please attach all the logs you can find in `/var/log/optimus-manager/`. *Do not directly copy paste the logs into the GitHub issue.* Join them as text files or save them to pastebins (https://pastebin.com/) and post the links here.

there is nothing under `/var/log/optimus-manager/`
gdm.service log: https://pastebin.com/Fi5C5at4
optimus-manager.service: https://pastebin.com/ABgY2BKB
optimus config file: https://pastebin.com/LhQtunpB

Thank you for helping out! Please let me know if you need any other info maybe I'm missing, since it's my first time posting issue.

**Comment by advpetc** [comment]
Forgot to mention, during normal boot, I also experience a very long booting time, but it will eventually bring me to x session correctly (intel). Also if in the tty during switch to nvidia, I can see some screen tearing at the top right corner of my screen. Not sure if these info will help.

**Comment by Askannz** [comment]
Ah, sorry. The instructions you read on GitHub are for the v1.0 version, which introduces quite a number of changes but has not been released yet. You can install it with [this AUR package](https://aur.archlinux.org/packages/optimus-manager-git/).
It should have better stability with GDM than v0.8, but it's still in testing, so please let me know how it goes :slightly_smiling_face:

**Comment by advpetc** [comment]
@Askannz thank you for your suggestion. However, when I update to git version of optimus-manager, I got the below error: https://pastebin.com/TVs67Wpk

I have done --cleanup and disable/stop beforehand when I remove my 0.8 version.

**Comment by Askannz** [comment]
Ok, looks like `loginctl` is not returning the session type ? That's odd. Could you do the following :

1. Reboot and login to make sure you are in a clean session
2. Run the command `echo $(loginctl list-sessions --no-legend | awk '{print $1}') | while read -r line; do loginctl show-session $line; done` and paste its output here.

**Comment by advpetc** [comment]
Hi @Askannz, I've reboot (it takes a while, but it success boot me to intel). 
The output is `Failed to get session path: No session '2 c1' known`, so looks like `loginctl` isn't running? 
I also checked my gdm, it still have the error 
```
May 05 19:28:42 core systemd[1]: Starting GNOME Display Manager...
May 05 19:28:42 core systemd[1]: Started GNOME Display Manager.
May 05 19:29:20 core gdm-password][1387]: gkr-pam: unable to locate daemon control file
May 05 19:29:20 core gdm-password][1387]: pam_unix(gdm-password:session): session opened for user advpetc by (uid=0)
```
do you think it might be the issue with gdm-prime? Thanks!

**Comment by advpetc** [comment]
I also found some logs under `/var/log/optimus-manager` if that helps
boot_setup.log: https://pastebin.com/z37ZrsAE
gpu_setup.log: https://pastebin.com/pX47XegZ
prime_setup.log: https://pastebin.com/2DFzHyY7

**Comment by Askannz** [comment]
@advpetc That GDM error is harmless I think, I also had it during my own testing.

That loginctl error is so strange. What do you see if you run `loginctl list-sessions --no-legend` directly ?

**Comment by advpetc** [comment]
@Askannz I got 
```
 2 1000 advpetc seat0 tty2
c1  120 gdm     seat0 tty1
```

**Comment by Askannz** [comment]
I think I swatted the bug, could you retry the latest master ?

**Comment by advpetc** [comment]
@Askannz I think it's still not working, can I know if my process to switch to using gdm-prime is correct?
1. stop/disable gdm.service
2. remove gdm package from pamac (since I'm using manjaro)
3. install gdm-prime package from aur. (v 3.32.0+2+g820f90f5-2)
4. reboot.

It sometimes doesn't even allow me to boot (not even tty) to x.

I also tested to use gdm (instead of gdm-prime), and it works, but I can only boot to intel gpu, which takes a very long time to boot though.

**Comment by Askannz** [comment]
> can I know if my process to switch to using gdm-prime is correct?
Yes, that should work.

> I think it's still not working
Do you still have the same error as before ? (that one : https://pastebin.com/TVs67Wpk). The failure to boot to X and the very long boot time are unrelated bugs, I think, so before solving them I'd like to make sure the first one is fixed.

**Comment by advpetc** [comment]
Hi @Askannz , I'm sorry I didn't make it clear, your commit does solve my problem, and it no long show that weird error! However, I still got the problem with booting and I still cannot switch to nvidia gpu from optimus-manager. My screen will freeze and I can hear my fan is running very fast. Can I know what may possible cause it?
logs:
boot_setup.log: https://pastebin.com/gqpbSCWH
gpu_setup.log: https://pastebin.com/vXY3Jcdx
prime_setup.log: https://pastebin.com/qJbHxEGp
gdm log: https://pastebin.com/gRFBsjj2
kernel log (which looks kinda weird to me): https://pastebin.com/DRYTZqr3

Thank you very much for bearing with me!

**Comment by Askannz** [comment]
Thanks for the logs. I don't see any error there, but what you are describing sounds like a system lockup caused by powering off the GPU. Unfortunately this kind of issues is common with Optimus laptops, and very hardware-specific.

I assume that once your computer is frozen, you cannot even switch to a TTY ?

If that's the case, try this : create the file `/etc/optimus-manager/optimus-manager.conf` and put those options :

```
[optimus]
switching=none
pci_power_control=no
```

Then reboot. Those options are going to disable power switching, which will of course reduce your battery time but should help narrow the problem down.

**Comment by advpetc** [comment]
It does solve my issue, thanks. However, the main reason I want to switch gpu is because of power control, so I will switch back to bumblebee for now. I'm happy to test any new release of your project in the future!

**Comment by Askannz** [comment]
If you know that bumblebee works for your machine, then just change `switching=none` to `switching=bbswitch` and optimus-manager should work too (this option makes it use the same power switching method as bumblebee).

**Comment by advpetc** [comment]
@Askannz yeah I've tested that as well, and it works like a charm!

**Comment by Askannz** [comment]
Great !
