### ISSUE TITLE
Just wanted to say something and couldn't think of a better way to reach you.

### ISSUE THREAD

**Issue by Socterean** [Askannz/optimus-manager#73]
Hi,

I know that I should have asked first, but it is what it is, I have shared the new v1.0 release on Reddit and things have somewhat taken some traction.

I just wanted to let you know about this [thread](https://www.reddit.com/r/linux_gaming/comments/bnoy7m/optimusmanager_v10_released_greatly_improving/) and this [thread](https://www.reddit.com/r/ManjaroLinux/comments/bnpf3m/optimusmanager_v10_released_greatly_improving/).

And maybe it would be a good thing if this is posted on other related subreddits so more people can know about this project, might even find some great new contributors, who knows, but this is your project and it's you call on what happens.

Also someone asked on one thread on multi monitor setups but in my brief testing I couldn't get anything out of my HDMI, it was just a quick test and didn't had time to investigate, also I didn't tested my VGA out.

If you just want me to delete the threads and never do that again, I will do that and I am sorry.

**Comment by Askannz** [comment]
I would have preferred if you notified me first, but no biggie, don't worry about it :slightly_smiling_face: 


> And maybe it would be a good thing if this is posted on other related subreddits so more people can know about this project,

I think the r/linux_gaming thread gave enough exposure, and I'd prefer not too spam too many subreddit with that project. But perhaps I'll make one more post in r/archlinux.

> Also someone asked on one thread on multi monitor setups but in my brief testing I couldn't get anything out of my HDMI, it was just a quick test and didn't had time to investigate, also I didn't tested my VGA out.

All video outputs should work in Nvidia mode. In Intel mode, outputs connected to the Nvidia card should work *in theory* if you have the `nouveau` driver loaded. But in practice, I don't know how good nouveau is on that front, so it's possible that some cards don't support that feature.
