### ISSUE TITLE
"optimus-manager --switch" doesn't log out automatically anymore

### ISSUE THREAD

**Issue by kpatel28** [Askannz/optimus-manager#74]
EDIT: I'm using Arch / X11 / lightdm / no DE.

After updating to the new version of optimus-manager on the AUR I found that the command
"optimus-manager --switch" doesn't automatically log out of the session anymore.

I speculate that this has to do with recent changes to the sessions.py module because I don't use a DE. My current workaround is to restart the lightdm service after switching GPUs and after doing that I get the old behavior.

**Comment by Askannz** [comment]
v1.0 does not restart the display manager anymore, and instead logs the user out using DBus commands. Unfortunately those commands are DE-specific, and *only* work if a DE is running.

If you know a command-line way to log out from your current graphical session, I can try adding it to optimus-manager.

**Comment by kpatel28** [comment]
I don't know of a way to do this for X across the board other than killing all the user's processes. I'm sure there is a better way of doing it. I'm fine with using my own lightdm specific solution for now. Thanks for the reply

**Comment by Askannz** [comment]
I'm considering adding a config option to let user specify their own logout command (in your case, that would be `kill X`, or `systemctl restart lightdm`). I'll let you know.

**Comment by Noiden** [comment]
Hi.. Why is this closed? I need this function too the systemctl restart lightdm was not working so good... it hang my computer :S. Well I did get logged out, but after I wrote my password and logged in again it hangs. It works fine when in "intel mode" but not when switching to nvidia...

**Comment by Noiden** [comment]
hmm.. weird, now it hangs even when I log out and logins again... it worked one time tough.

**Comment by kpatel28** [comment]
> Hi.. Why is this closed? I need this function too the systemctl restart lightdm was not working so good... it hang my computer :S. Well I did get logged out, but after I wrote my password and logged in again it hangs. It works fine when in "intel mode" but not when switching to nvidia...

If you are not using my setup (Arch / X11 / lightdm / no DE), you might need to do something other than restarting lighdm.
Have you tried just killing X?

**Comment by kpatel28** [comment]
Another way that worked for me was killing all my running processes:

`killall -u $(whoami)`

but I'm not currently using this because restarting lightdm works for me

**Comment by Noiden** [comment]
This is some other error... now X totally hangs when changing to nvidia and log out.. well, the login screen is working but after i login it hangs, very weird.

**Comment by kpatel28** [comment]
This might help you out:
https://wiki.archlinux.org/index.php/Xinit#Usage
You can try running your window manager's exit function (I'm guessing if you have a DE or DM, using their exit/service restarts would handle this okay). If all else fails you could trying terminating all Xorg processes:
`pkill -15 Xorg`
Also note my .profile runs startx if X isn't already running. It might be that you are logging out fine but there is nothing that is logging in or starting up X for you

**Comment by michaldybczak** [comment]
I was unaware of this thread but I opened the same issue and I'm not going to close it abruptly ;).
Anyway, here is the new topic:

https://github.com/Askannz/optimus-manager/issues/79
