### ISSUE TITLE
Does not switch to nvidia

### ISSUE THREAD

**Issue by Keyj1n** [Askannz/optimus-manager#75]
**Describe the bug**
When i execute the command for switching to nvidia
`optimus-manager --switch nvidia`
i will be auto-logout and after login i'm still on intel.
Tried it also with bbswitch.

**System info**
Im using Manjaro 18.04 KDE on a Razer Blade late 2017.
Kernel is 4.19.

**Logs**
https://pastebin.com/vx5nxGPZ

**Comment by Askannz** [comment]
* Is there any other log in `/var/log/optimus-manager/` ?

* Have you followed instructions for Manjaro KDE [here](https://github.com/Askannz/optimus-manager#installation) ? (this has been update din v1.0).

**Comment by Keyj1n** [comment]
Thank you very much for the fast response.... Yeah didn't see the KDE instructions... my bad sry.
Thanks for this awesome tool!
