### ISSUE TITLE
Steam segfault/crash - 1.02

### ISSUE THREAD

**Issue by tj8892** [Askannz/optimus-manager#77]
Firstly: this program is really useful to me, thanks for your work on it.

When using the NVIDIA mode, steam and any steam games all segfault and crash immediately. 
This never happens in intel mode and has only occurred since using Optimus-manager. I've used optimus-manager for a long time and started having this problem around 0.7, I think?

I'm using a fully updated Arch, using GDM-Prime and Gnome with Nvidia package. 
GPU tests like glxspheres work perfectly normally in nvidia mode. My laptop is an XPS 15 with gtx 1050. I'm using bbswitch for switching.

Console output after running steam: 

> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: swrast
> Installing breakpad exception handler for appid(steam)/version(1556574584)
> Installing breakpad exception handler for appid(steam)/version(1556574584)
> 
> (steam:6389): Gtk-WARNING **: 19:50:35.429: Unable to locate theme engine in module_path: "adwaita",
> /usr/share/themes/Materia/gtk-2.0/main.rc:790: error: unexpected identifier 'direction', expected character '}'
> 
> (steam:6389): Gtk-WARNING **: 19:50:35.434: Unable to locate theme engine in module_path: "adwaita",
> /usr/share/themes/Materia/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: swrast
> Steam: An X Error occurred
> X Error of failed request:  GLXBadContext
> Major opcode of failed request:  152
> Serial number of failed request:  52
> xerror_handler: X failed, continuing
> Steam: An X Error occurred
> X Error of failed request:  BadValue (integer parameter out of range for operation)
> Major opcode of failed request:  152
> Value in failed request:  0x0
> Serial number of failed request:  51
> xerror_handler: X failed, continuing
> Steam: An X Error occurred
> X Error of failed request:  BadMatch (invalid parameter attributes)
> Major opcode of failed request:  152
> Serial number of failed request:  53
> xerror_handler: X failed, continuing
> crash_20190516195031_1.dmp[6411]: Uploading dump (out-of-process)
> /tmp/dumps/crash_20190516195031_1.dmp
> /home/tristan/.local/share/Steam/steam.sh: line 906:  6389 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
> crash_20190516195031_1.dmp[6411]: Finished uploading minidump (out-of-process): success = yes
> crash_20190516195031_1.dmp[6411]: response: CrashID=bp-eb0910de-da24-450b-9d1c-83f022190516
> crash_20190516195031_1.dmp[6411]: file ''/tmp/dumps/crash_20190516195031_1.dmp'', upload yes: ''CrashID=bp-eb0910de-da24-450b-9d1c-83f022190516''
> 

dmesg output: 

> [  522.278527] steam[6389]: segfault at 0 ip 00000000f79d4831 sp 00000000ffc0396c error 4 in libc-2.29.so[f7954000+14e000]

**Comment by Askannz** [comment]
Hmm, are you sure the problem comes from optimus-manager ? Do you have `nvidia-utils` and `lib32-nvidia-utils` installed, with versions matching the nvidia driver ?

Also, make sure you don't have an auto-generated Nvidia config file at `/etc/X11/xorg.conf`, [it messes with Optimus setups](https://bbs.archlinux.org/viewtopic.php?id=244575).

**Comment by tj8892** [comment]
I just installed lib32-nvidia-utils, which previously wasn't installed, and it works perfectly again! Thanks!
Not sure why this only became a problem recently, I might have accidentally removed it at some point. Optimus-manager isn't responsible then (I assumed it was because when using bbswitch/bumblebee I never had this problem before.)
