### ISSUE TITLE
SDDM doesn't autolog during a switch in Manjaro

### ISSUE THREAD

**Issue by michaldybczak** [Askannz/optimus-manager#79]
**Describe the bug**
Just as in topic. When autologin is set, switching session should just log in automatically and that is how it worked in 0.6 version. Now during a switch using git version I am always presented with SDDM screen and need to put my password, although autologin is set and working (first boot).
It's a minor inconvenience but since 0.6 had no problem with it, I assume this could be fixed at some point.

**System info**
Operating System: Manjaro Linux 
KDE Plasma Version: 5.15.5
KDE Frameworks Version: 5.57.0
Qt Version: 5.12.3
Kernel Version: 5.1.1-2-MANJARO
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-6700HQ CPU @ 2.60GHz
Memory: 7,7 GiB

**Logs**

I would gladly add SDDM log but... `journalctl -u sddm.service` shows logs from 1st March and after scrolling down 3 minutes I was still on 3rd March... this is too long to scroll down. When I use End key, it just cuts the output, enters `...skiping...` and then shows logs from the CURRENT boot, but not from the ones before it.  This is super annoying and not usable.

I tried to specify the date with -U but timestamp couldn't be specified. I have no idea how the date should be presented in commandline but the usual 18.05.2019 or variations of thereof aren't recognized and the --help isn't helpful at all.

So how can I show a simple log from the current date or previous boots?

**Comment by Askannz** [comment]
> So how can I show a simple log from the current date or previous boots?

To get the logs for the current boot, simply add `-b0` to the `journalctl` command (`-b-1` for the previous boot, etc)

The disappearance of autologin is due to the new architecture of optimus-manager, since version v1.0. See the [release notes](https://github.com/Askannz/optimus-manager/releases/tag/v1.0) :

```
Because the login manager isn't completely restarted anymore, auto-login will not kick in on a GPU switch in even if you have it enabled. In other words, you need to type your password in the login screen every time you switch GPUs. I realize this can be an annoyance, but this is the proper method and the stability gains are worth it.
```

Unfortunately I haven't found a way to bring autologin back with the new switching method.

**Comment by michaldybczak** [comment]
Ah, in that case, I'm closing this topic. It's not a bug but a feature ;). I can live with it. Maybe in the future, you will come across some solution but for the time being it is what it is - a fair tradeoff.
Thanks for the explanation.
