### ISSUE TITLE
Nvidia mode hangs computer

### ISSUE THREAD

**Issue by Noiden** [Askannz/optimus-manager#80]
**Describe the bug**
When I switch to mode nvidia and log out and in the computer hangs.

I also tried with the mode nvidia_once and rebootet, but it failed back to intel or something, because I got intel when I logged in and not nvidia.

**System info**
Please include :
- Your distribution - Manjaro
- Your desktop manager - Deepin
- You display manager - LightDM (I Think...)
- Your laptop model - Asus Zenbook UX303L

**Logs**
boot_setup.log - https://pastebin.com/z4zNgBWP
gpu_setup.log - https://pastebin.com/XMW4iFwR
prime_setup.log - https://pastebin.com/i6zkBJ9Q

**Comment by Noiden** [comment]
I looked in the logs and it says it write to this file,
Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf

but I don't have any file there with that name. I only got 00-keyboard.conf

I do have a folder /etc/X11/mhwd.d/nvidia.conf and nvidia.conf.nvidia-xconfig-original

After i Switch the login screen works, but it hangs when I login.. I checked the xorg.log before I logged in and I got some NVIDIA complaining about ACPI: failed to connect to the ACPI event daemon: the daemon may not be running or the "AcpidSocketPath" X configuration option may not be set correctly. When the ACPI even daemon is available, the NVIDIA x driver till try to use it to recieve ACPI event nofications..
Setting mode "NULL"
Disabling share memory pixmaps

**Comment by Noiden** [comment]
It also says Virtual screen size determined to be 640x480 and DPI set to 75, 75, computed from buil-in default.

I have better resolutation than that on my screen. :)

**Comment by Askannz** [comment]
Ah, from your logs it seems that there is a crash when using `nvidia_once`. Thanks for reporting, gonna fix that. It's probably unrelated to your issue, though. Just don't use `nvidia_once` for now.

If your completely locks up, it could be an ACPI problem. Try setting the options `switching=none` and `pci_power_control=no` in the config file (that's going to leave the GPU on but should help narrow down the issue).

If that does not work, then reproduce the hang, reboot and post the output of `journalctl -b-1 --no-pager` (logs from the previous boot).

**Comment by Noiden** [comment]
It hangs with ordinary nvidia also... When I change to nvidia and log out and log in the computer hangs totally... When I use nvidia_once it didn't hang, just that nvidia didn't start it started with intel.

In what config file should I put that switching thing? In the optimus-manager.conf ?

But if I don't use switching, wouldn't that mean that booth nvidia card and Intel card is online and using power?

**Comment by Askannz** [comment]
> In what config file should I put that switching thing? In the optimus-manager.conf ?

Yes, create the file `/etc/optimus-manager/optimus-manager.conf` and put this :

```
[optimus]
switching=none
pci_power_control=no
```

> But if I don't use switching, wouldn't that mean that booth nvidia card and Intel card is online and using power?

Indeed, but I'm not suggesting that as a solution to your problem. It's just a troubleshooting step to check if the hang issues comes from power switching the Nvidia card.

**Comment by Noiden** [comment]
Cool... but I don't have time to try until tommorow. ;)
Thanks.

**Comment by Noiden** [comment]
That didn't help... =(

Here is a pastebin of the configuration,
https://pastebin.com/3ax3SMsD

**Comment by Noiden** [comment]
aah, I forgot, here is a link to that big fat log file :dagger: 
https://pastebin.com/uvafYBB9

**Comment by Askannz** [comment]
Sorry for the lack of updates.

Finally had a look at your log, it looks like optimus-manager is still crashing at boot :

```
maj 22 20:23:00 slaptop prime-switch-boot[503]: Traceback (most recent call last):
maj 22 20:23:00 slaptop prime-switch-boot[503]:   File "/usr/bin/optimus-manager-setup", line 11, in <module>
maj 22 20:23:00 slaptop prime-switch-boot[503]:     load_entry_point('optimus-manager==1.0', 'console_scripts', 'optimus-manager-setup')()
maj 22 20:23:00 slaptop prime-switch-boot[503]:   File "/usr/lib/python3.7/site-packages/optimus_manager/optimus_manager_setup.py", line 46, in main
maj 22 20:23:00 slaptop prime-switch-boot[503]:     _write_gpu_mode(config, startup_mode)
maj 22 20:23:00 slaptop prime-switch-boot[503]:   File "/usr/lib/python3.7/site-packages/optimus_manager/optimus_manager_setup.py", line 100, in _write_gpu_mode
maj 22 20:23:00 slaptop prime-switch-boot[503]:     write_requested_mode(mode)
maj 22 20:23:00 slaptop prime-switch-boot[503]:   File "/usr/lib/python3.7/site-packages/optimus_manager/var.py", line 33, in write_requested_mode
maj 22 20:23:00 slaptop systemd[1]: Started Hostname Service.
maj 22 20:23:00 slaptop audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
maj 22 20:23:00 slaptop prime-switch-boot[503]:     assert mode in ["intel", "nvidia"]
maj 22 20:23:00 slaptop prime-switch-boot[503]: AssertionError
```

Is your startup mode still set to `nvidia_once` ?

According to the log there seems to be also a crash in the Deepin itself. I've never tested optimus-manager with that environment before, so there may be some compatibility issue I'm not aware of.

Have you used any other optimus solution before, like bumblebee (primusrun/optirun), or nvidia-xrun ? If yes, did it work ? That could help narrow down the issue.

**Comment by Noiden** [comment]
optirun did work, but I'm sorry I can't help you anymore with troubleshooting of this error, because I don't run Linux on that machine anymore. :) So for my concern you can close the ticket.

Thank you.
