### ISSUE TITLE
DBUS ERROR: After Updating to version 1.0 im unable to switch from Intel to Nvidia

### ISSUE THREAD

**Issue by AncalagonTheBlack** [Askannz/optimus-manager#84]
I followed the instructions for KDE on Manjaro. But it only ended up in errors. Kernel 5.1

```
You are about to switch GPUs. This will forcibly close all graphical sessions and all your applications WILL CLOSE.
(you can pass the --no-confirm option to disable this warning)
Continue ? (y/N)
Switching to mode : nvidia
Logging out the current desktop session
Traceback (most recent call last):
  File "/usr/bin/optimus-manager", line 11, in <module>
    load_entry_point('optimus-manager==1.0', 'console_scripts', 'optimus-manager')()
  File "/usr/lib/python3.7/site-packages/optimus_manager/optimus_manager_client.py", line 87, in main
    gpu_switch(config, switch_mode)
  File "/usr/lib/python3.7/site-packages/optimus_manager/optimus_manager_client.py", line 113, in gpu_switch
    sessions.logout_current_desktop_session()
  File "/usr/lib/python3.7/site-packages/optimus_manager/sessions.py", line 12, in logout_current_desktop_session
    session_bus = dbus.SessionBus()
  File "/usr/lib/python3.7/site-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python3.7/site-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3.7/site-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead


```

**Comment by henrikeri** [comment]
KDE Manjaro, Kernel 5.2 experimental here, getting the same error as above when attempting to shift

**Comment by AncalagonTheBlack** [comment]
5.0 Kernel doesn't work either. Im 100% sure this did work before

**Comment by AncalagonTheBlack** [comment]
Update:
After trying to specify the dbus address manually i got this error:

`Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.`


After replacing dbus with dbus-x11 i get this message:

```
Switching to mode : nvidia
Logging out the current desktop session


```

But nothing happens.

**Comment by Askannz** [comment]
I can't reproduce the problem with my Manjaro KDE setup...

Is `$DBUS_SESSION_BUS_ADDRESS` set at all, and is `dbus.service` running at all ?

**Comment by de-conf** [comment]
Situation +1
And running optimus-manager will have some errors.
Config parsing : unknown option kill_logind in section optimus. Ignoring.
Config parsing : unknown option kill_x11 in section optimus. Ignoring.
Config parsing : unknown option login_manager_control in section optimus. Ignoring.
Config parsing : unknown option pci_reset in section optimus. Ignoring.
Config parsing : unknown option terminate_sessions in section optimus. Ignoring.
Config parsing : unknown option dri in section nvidia. Ignoring.

**Comment by AncalagonTheBlack** [comment]
I cant tell if $DBUS_SESSION_BUS_ADDRESS was set. But after i replaced dbus with dbus-X11 everything seems to work except automatically logging off.

**Comment by zinus1** [comment]
> Situation +1
> And running `optimus-manager` will have some errors.
> 
> ```
> Config parsing : unknown option kill_logind in section optimus. Ignoring.
> Config parsing : unknown option kill_x11 in section optimus. Ignoring.
> Config parsing : unknown option login_manager_control in section optimus. Ignoring.
> Config parsing : unknown option pci_reset in section optimus. Ignoring.
> Config parsing : unknown option terminate_sessions in section optimus. Ignoring.
> Config parsing : unknown option dri in section nvidia. Ignoring.
> ```
You need to ovewrite /etc/optimus-manager/optimus-manager.conf (the older config) with /usr/share/optimus-manager.conf (the newer) because there are some differences between the old config and the new one. Also you need to have the new config at /usr/share.
(https://github.com/Askannz/optimus-manager/issues/78)

**Comment by de-conf** [comment]
> > Situation +1
> > And running `optimus-manager` will have some errors.
> > ```
> > Config parsing : unknown option kill_logind in section optimus. Ignoring.
> > Config parsing : unknown option kill_x11 in section optimus. Ignoring.
> > Config parsing : unknown option login_manager_control in section optimus. Ignoring.
> > Config parsing : unknown option pci_reset in section optimus. Ignoring.
> > Config parsing : unknown option terminate_sessions in section optimus. Ignoring.
> > Config parsing : unknown option dri in section nvidia. Ignoring.
> > ```
> 
> You need to ovewrite /etc/optimus-manager/optimus-manager.conf (the older config) with /usr/share/optimus-manager.conf (the newer) because there are some differences between the old config and the new one. Also you need to have the new config at /usr/share.
> (#78)

Thanks for your reminder, I have noticed their changes!

**Comment by Askannz** [comment]
Can you check the return value of `echo $DBUS_SESSION_BUS_ADDRESS`, and also if the dbus service is running (with `systemctl status dbus.service`) ?

**Comment by AncalagonTheBlack** [comment]
> Can you check the return value of `echo $DBUS_SESSION_BUS_ADDRESS`, and also if the dbus service is running (with `systemctl status dbus.service`) ?
Sorry for my late answer. 

The output of $DBUS_SESSION_BUS_ADDRESS is:
unix:path=/run/user/1000/bus

and the output of system ctl is: 

```
● dbus.service - D-Bus System Message Bus
   Loaded: loaded (/usr/lib/systemd/system/dbus.service; static; vendor preset: disabled)
   Active: active (running) since Fri 2019-06-21 20:01:21 CEST; 5min ago
     Docs: man:dbus-daemon(1)
 Main PID: 607 (dbus-daemon)
    Tasks: 1 (limit: 4915)
   Memory: 4.4M
   CGroup: /system.slice/dbus.service
           └─607 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only

Jun 21 20:01:35 Manjaro18 dbus-daemon[607]: [system] Activating via systemd: service name='org.freedesktop.UPower' unit='upower.service' requested by ':1.43' (uid=968 pid=1899 comm="/usr/bin/sddm-greeter --socket /tmp/sddm-:0-bRdiBP")
Jun 21 20:01:36 Manjaro18 dbus-daemon[607]: [system] Successfully activated service 'org.freedesktop.UPower'
Jun 21 20:02:47 Manjaro18 dbus-daemon[607]: [system] Activating via systemd: service name='org.freedesktop.RealtimeKit1' unit='rtkit-daemon.service' requested by ':1.79' (uid=1000 pid=4835 comm="/usr/bin/pulseaudio --daemonize=no ")
Jun 21 20:02:47 Manjaro18 dbus-daemon[607]: [system] Successfully activated service 'org.freedesktop.RealtimeKit1'
Jun 21 20:02:49 Manjaro18 dbus-daemon[607]: [system] Activating service name='org.kde.powerdevil.discretegpuhelper' requested by ':1.92' (uid=1000 pid=4862 comm="/usr/lib/org_kde_powerdevil ") (using servicehelper)
Jun 21 20:02:50 Manjaro18 dbus-daemon[607]: [system] Successfully activated service 'org.kde.powerdevil.discretegpuhelper'
Jun 21 20:02:50 Manjaro18 dbus-daemon[607]: [system] Activating service name='org.kde.powerdevil.backlighthelper' requested by ':1.92' (uid=1000 pid=4862 comm="/usr/lib/org_kde_powerdevil ") (using servicehelper)
Jun 21 20:02:50 Manjaro18 dbus-daemon[607]: [system] Successfully activated service 'org.kde.powerdevil.backlighthelper'
Jun 21 20:03:04 Manjaro18 dbus-daemon[607]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service' requested by ':1.5' (uid=0 pid=611 comm="/usr/bin/NetworkManager --no-daemon ")
Jun 21 20:03:04 Manjaro18 dbus-daemon[607]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
mike@Manjaro18 ~> 

```

**Comment by Askannz** [comment]
I've added better error detection and fallback to executable commands if DBus is unavailable. That should at least make optimus-manager usable, although I still don't know where the real issue is. My guess is that Manjaro broke something in user-side Dbus but I have no idea what.

@AncalagonTheBlack Sorry, I gave you the wrong command. Please try with `systemctl --user status dbus` instead.

**Comment by AncalagonTheBlack** [comment]
Here is the output:
```
● dbus.service - D-Bus User Message Bus
   Loaded: loaded (/usr/lib/systemd/user/dbus.service; static; vendor preset: enabled)
   Active: active (running) since Sun 2019-06-23 14:01:33 CEST; 1min 19s ago
     Docs: man:dbus-daemon(1)
 Main PID: 4459 (dbus-daemon)
   CGroup: /user.slice/user-1000.slice/user@1000.service/dbus.service
           ├─4459 /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
           ├─4511 /usr/bin/kglobalaccel5
           ├─4516 /usr/lib/dconf-service
           ├─4522 /usr/lib/kf5/kscreen_backend_launcher
           ├─4600 /usr/lib/kactivitymanagerd
           └─5208 /usr/bin/kuiserver5

Jun 23 14:01:49 Manjaro18 kuiserver5[5208]: Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/24x24/legacy/"
Jun 23 14:01:49 Manjaro18 kuiserver5[5208]: Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/24x24/ui/"
Jun 23 14:01:49 Manjaro18 kuiserver5[5208]: Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/32x32/legacy/"
Jun 23 14:01:49 Manjaro18 kuiserver5[5208]: Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/32x32/ui/"
Jun 23 14:01:49 Manjaro18 kuiserver5[5208]: Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/48x48/legacy/"
Jun 23 14:01:49 Manjaro18 kuiserver5[5208]: Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/48x48/ui/"
Jun 23 14:01:49 Manjaro18 kuiserver5[5208]: Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/256x256/legacy/"
Jun 23 14:01:49 Manjaro18 kuiserver5[5208]: Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/512x512/legacy/"
Jun 23 14:01:49 Manjaro18 kuiserver5[5208]: Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/scalable/ui/"
Jun 23 14:01:51 Manjaro18 dbus-daemon[4459]: [session uid=1000 pid=4459] Successfully activated service 'org.freedesktop.Notifications'

```


I build your newest version: It dosent show any dbus-error but it wont switch the graphics either.

**Comment by Askannz** [comment]
Hi, @AncalagonTheBlack, do you still experience this issue ?

**Comment by bguerout** [comment]
Hello i have the same message on Arch (5.6.10-arch1-1) with Cinnamon 4.4.8

Running `optimus-manager --status` shows the following message :

```sh
ERROR: a GPU setup was initiated but Xorg post-start hook did not run.
Log at /var/log/optimus-manager/switch/switch-20200512T000707.log
If your login manager is GDM, make sure to follow those instructions:
https://github.com/Askannz/optimus-manager#important--gnome-and-gdm-users
If your display manager is neither GDM, SDDM nor LightDM, or if you don't use one, read the wiki:
https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting
Config parsing : error in option "dri" in section [intel] : invalid value "0"

Cannot execute command because of previous errors.
```

Log file

```sh
> cat  /var/log/optimus-manager/switch/switch-20200512T000707.log
[10] INFO: # Xorg pre-start hook
[10] INFO: Requested mode is: intel
[10] INFO: Checking for GDM display servers
[28] ERROR: Config parsing : error in option "dri" in section [intel] : invalid value "0"
[29] INFO: Falling back to default value "3"
[865] INFO: Available modules: ['nouveau', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[865] INFO: Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] (if loaded)
[906] INFO: Loaded extra Intel Xorg options (0 lines)
[906] INFO: Loaded extra Intel Xorg options (0 lines)
[906] INFO: Writing to /etc/X11/xorg.conf.d/10-optimus-manager.conf
[906] INFO: Writing state {'type': 'pending_post_xorg_start', 'switch_id': '20200512T000707', 'requested_mode': 'intel'}
[907] INFO: Xorg pre-start hook completed successfully
```

And 

```
> cat /etc/X11/xorg.conf.d/10-optimus-manager.conf 
Section "Device"
	Identifier "intel"
	Driver "modesetting"
	BusID "PCI:0:2:0"
	Option "DRI" "3"
EndSection
```

**Comment by Askannz** [comment]
This is a different problem, please make a new issue.
