### ISSUE TITLE
Cannot find Header for Section [Optimus]

### ISSUE THREAD

**Issue by AncalagonTheBlack** [Askannz/optimus-manager#85]
After i had major problems with the new version so i tried to downgrade to 0.8 but it seems the setup.py does not contain all the files that are needed to use optimus-manager is that correct or am i overseeing something ?

**Comment by Askannz** [comment]
> it seems the setup.py does not contain all the files that are needed to use optimus-manager is that correct

Yes, this is correct. Running setup.py directly won't work, you have to use the AUR package. If you need to downgrade, you can check out a previous version of the PKGBUILD on AUR and build the package from here.
