### ISSUE TITLE
Crash when updating kernel

### ISSUE THREAD

**Issue by de-conf** [Askannz/optimus-manager#88]
**Describe the bug**
When updating the current kernel or NVIDIA driver, when the upgrade is performed, the desktop display card is dead and must be restarted. Is it suspected that the module is not loaded correctly?

**System info**
Please include :
- Arch (linux-zen
- KDE
- SDDM
- Your laptop model, if you think it could be related to the problem

**Comment by Askannz** [comment]
> the desktop display card is dead and must be restarted

What does that mean exactly ? Does the display turn off ? Does the current X session crashes ?

I can generally update my kernel and driver while the GPU is active, although some parts of Plasma tend to crash after that if the computer isn't rebooted.
