### ISSUE TITLE
Select the bootmode from GRUB

### ISSUE THREAD

**Issue by andreisergiu98** [Askannz/optimus-manager#89]
**Describe the bug**
This is not a bug, it's a feature request. 

So, my default boot mode is nvidia, but there are some scenarios where i know i want to use intel, so after the system boots up, i have to switch from the default (nvidia), to intel. 
I was thinking that we can create multiple boot entries with different kernel parameters, where we can set the start-up mode like 'optimus-manager.startupmode.intel=1' or smth like that. And in the code we can make a syscall to 'cat /proc/cmdline | grep ...' (there might be a better way to do this, but this one is the only one i know) and then set the start-up mode according to those params.

I can make a pr, but i want to hear your thoughts on this.

**Comment by Rojikku** [comment]
I don't know the difficulty of doing this, but I do agree it would be very convenient. Currently, the only option if your default graphics option doesn't work, is to set the target to multi-user in grub (add a 3 after quiet), then enable optimus-manager service, and run the command. Assuming you can't just access a TTY, like I couldn't, for various glitch-related reasons.

**Comment by Askannz** [comment]
I've been thinking about that as well. There does not seem to be a way for systemd to relay specific kernel parameters to services, but parsing `/proc/cmdline` is fine [according to the man himself, Linus Torvalds](http://lkml.iu.edu/hypermail/linux/kernel/1404.0/01488.html) (ignore the second part of the email, it's just old systemd drama).

Doesn't sound hard to implement, I'm going to give it a shot.

**Comment by Askannz** [comment]
Done ! With the current Git master version, you can now set `optimus-manager.startup=intel` or `optimus-manager.startup=nvidia`. This parameter overrides the normal startup mode set with `--set-startup`.

Let me know if there is any issue with it :)

**Comment by Askannz** [comment]
The feature is part of the latest master branch. Tested on my own system, it seems to work, so I'll include it in the next release.

Closing the issue, feel free to re-open if needed :slightly_smiling_face:
