### ISSUE TITLE
Black screen upon login manager restart

### ISSUE THREAD

**Issue by jmayniac** [Askannz/optimus-manager#9]
I am getting a black screen upon trying to restart in nvidia mode.  I've read through the troubleshooting guide and none of the suggestions help.

Here is what I've tried:

1. Removed all extraneous *.conf files from /etc/modules.d and /etc/X11.
2. Made sure optimus-manager.service is started.
3. Made sure bumblebeed.service is disabled.
4. Made sure bbswitch is not started on startup.
5. Changed "switching=" option in /usr/share/optimus-manager.conf to be "bbswitch".
6. Changed "modeset=" option in /usr/share/optimus-manager.conf to be "no".
7. Reinstalled optimus-manager
8. Reinstalled nvidia drivers.

Using latest updates to Manajaro on kernel 4.19 on a Dell 9560 laptop with a Nvidia 1050 card.

**journalctl -u optimus-manager.service**
[https://pastebin.com/mPiNDNf9](https://pastebin.com/mPiNDNf9)

**/var/log/Xorg.0.log**
[https://pastebin.com/M42ZBJJR](https://pastebin.com/M42ZBJJR)

**Comment by jmayniac** [comment]
Looks like I solved my own problem.  The issue was, I didn't have xorg-xrandr installed.  I installed that and it worked.

**Comment by Askannz** [comment]
Good idea, I'll add it.
