### ISSUE TITLE
Overclocking option causes NVIDIA setting to crash infinitely

### ISSUE THREAD

**Issue by Rojikku** [Askannz/optimus-manager#90]
**Describe the bug**
NVIDIA setting will open lightdm, and immediately close it, repeating forever, making it impossible to do anything.

**System info**
Arch
i3wm
Lightdm

**Solution**
Disabling the overclocking option fixes the issue.
I'm making a bug report because I don't see any other issues like it in a search.
Personally, I don't think overclocking should be the default if it causes issues, and should be something people enable on their own when they want it.
Though it could just be inproper autodetection causing the issue or something, as well, which might be important to note.

**Comment by Askannz** [comment]
Weird. That option is enabled by default because to my knowledge there is absolutely no downside in leaving it on, but if it's causing crashes then it's worth investigating.

Any chance you could provide logs of this issue ? The Xorg log in particular.

Also, what is your GPU model ? This option actually sets a value in the "Coolbits" field of the Xorg conf, and that value is known to be incompatible with _very_ old Nvidia GPUs. I doubt it's the issue (and wouldn't cause a crash anyways) but better be safe.

**Comment by Rojikku** [comment]
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 630 (rev 04)
01:00.0 3D controller: NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile] (rev a1)
https://termbin.com/b0vk
Happy to help. I have a log from today, a log from the 14th (Day before the issue), and the 16th, so I went with the 16th.
I don't know if they're actually useful, though...I could try reproducing the issue, if necessary, but I'd rather avoid doing so if those logs have anything useful in them.
Honestly, I can't even get the intel side to load, currently, it just kinda locks up. But maybe I'm setting about it wrong.
I didn't see anything valuable in the other logs when I flipped through, so I didn't include them. Didn't think about Xorg, but didn't see anything when I searched for coolbits.

**Comment by Askannz** [comment]
Well, nothing jumps out in this log.

Just to be clear, if you run your desktop session in Nvidia mode with overclocking enabled, everything works fine, right ? You are able to run 3D applications and they run off the proper GPU ?

> Honestly, I can't even get the intel side to load, currently, it just kinda locks up.

That sounds like a common case of broken power switching. See https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting#when-i-switch-gpus-my-system-completely-locks-up-i-cannot-even-switch-to-a-tty-with-ctrlaltfx.

**Comment by Rojikku** [comment]
I haven't tried nvidia mode with overclocking since I ran into the issue, honestly. Disabling the option was what originally allowed me to access the environment at all.
When I run any application it is off the correct GPU now, yes. It wasn't before I started using optimus-manager, not sure why, but for that it is very useful.

I'll look into the link when I get home.

**Comment by Askannz** [comment]
Hi @Rojikku , do you still experience this issue with the latest version of optimus-manager ?
