### ISSUE TITLE
Nvidia driver does not shutdown

### ISSUE THREAD

**Issue by inzar98** [Askannz/optimus-manager#95]
**Describe the bug**
After latest patch nvidia driver doesnt shutdown complately. nvidia-smi shows info

**System info**
Please include :
Arch linux
Gnome + GDM(patched)

**Logs**
http://ix.io/1MFs
http://ix.io/1MFt
http://ix.io/1MFu

**Comment by Askannz** [comment]
The startup mode `nvidia_once` has been deprecated, that's what is causing the crash. Remove `/var/lib/optimus-manager/startup_mode` and it should work again. I'll add a fix so that it does not crash the program in the future.

**Comment by Askannz** [comment]
Fixed in cc9dcda07caba73cd03257cd3d8f852ff4d6062f.
