### ISSUE TITLE
Can't really use Optimus manager

### ISSUE THREAD

**Issue by JavaCafe01** [Askannz/optimus-manager#96]
I use a Thinkpad X1 extreme running on Arch with i3-gaps and lightdm. I followed the instructions correctly, but once after the dm shows up and I log in, i3 freezes. I can't seem to do anything. Any suggestions or tips?

**Comment by Askannz** [comment]
I can't properly diagnose the issue without logs, but that sounds like a classic case of ACPI lockup. Follow this FAQ section : https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting#when-i-switch-gpus-my-system-completely-locks-up-i-cannot-even-switch-to-a-tty-with-ctrlaltfx

**Comment by JavaCafe01** [comment]
Yes, I just read your readme and realized it was an ACPI problem. I looked through all the kernel parameters to try from the post you mentioned, but unfortunately, none of them work. I'm running Manjaro on a Thinkpad X1 Extreme. I will have to stick with bumblebee... There is another person who got GPU switching perfectly working on a Thinkpad X1 Extreme on Manjaro [here](https://github.com/mrjoes/manjaro-optimus-config). Thanks for your help!

**Comment by JavaCafe01** [comment]
@Askannz Somehow, I fixed it without editing any of my kernel options. I reinstalled Manjaro, installed the linux51-nvidia package, and the xf86... intel one, but it still didn't work after that. 
It froze at nvidia switch. However, I then created a config file with the template one, restarted my pc and it suddenly started to work again.
