### ISSUE TITLE
Changing from PRIME to optimus-manager Manjaro

### ISSUE THREAD

**Issue by naquiroz** [Askannz/optimus-manager#97]
Hi, recently I switched to Manjaro KDE, on my MSI P65 8RE with an Nvidia 1060 Mobile.

I followed [this form instructions](https://forum.manjaro.org/t/howto-set-up-prime-with-nvidia-proprietary-driver/40225) to switch from bumblebee (came out of the box with manjaro) to PRIME. However, I wanted to check out optimus manager, as that forum instructions won't let me to switch from nvidia to intel. 

I tried following the `README` from this _repo_,  however when I rebooted, the system froze on the splash screen after logging in. I managed to roll back to prime by following the uninstall instructions, and re-applying the forum instructions. 

So my question is,
 Given the state of my computer, based on the forum instructions, can someone help me in switching from PRIME to `optimus-manager`?

Thanks in advance. :smile:

**Comment by JavaCafe01** [comment]
@naquiroz naquiroz I also use manjaro, however with lightdm.

1. First uninstall bumblebee. You can use the manjaro settings manager to do so. After, it should show that you don't have any drivers installed for nvidia.

2. Install the nvidia drivers according to your kernel. If you run 5.1, for example, you would do `pacman -S linux51-nvidia`

3. Follow the instructions on the readme, especially the ones that tell you to remove any gpu related files. There are specific ones for Manjaro KDE also. 

4. Create a config file. The steps and template are on the readme. 

5. Reboot, and it all should be good!

If this doesn't work, a couple of questions:

What type of computer do you have?
Do you have a hybrid/discrete mode in your BIOS for display settings?

**Comment by Askannz** [comment]
It shouldn't be necessary to use `pacman -S linux51-nvidia` anymore, the default Nvidia drivers bundled with Manjaro will work. You need to disable the bumblebee service though.

When you experience the freeze, are you still able to switch to aTTY console with Ctrl+Alt+F2,3,4 etc ? If not, do the following : create the file `/etc/optimus-manager/optimus-manager.conf` and paste this :

```
[optimus]
switching=none
pci_power_control=no
```

Then reboot.

Also make sure you applied the KDE fix as @JavaCafe01 suggested.

**Comment by jediafr** [comment]
A very good tutorial had been put together detailing HOT to do it on Manajaro.
(it worked perfectly on my Manjao KDE edition).

https://forum.manjaro.org/t/how-to-install-and-configure-optimus-manager-for-hybrid-gpu-setups-intel-nvidia/92196

**Comment by naquiroz** [comment]
Thanks @JavaCafe01 and @Askannz ! I will try this afterwards, however I think @jediafr  guide is more according to the state of my computer so I will try that one first. I'll keep you informed! :+1:

**Comment by DOGGO20** [comment]
this sounds like you're missing the xrandr package, the graphics card won't initialize without this tool and will produce this behavior, in order to fix it you need to boot into an install media and chroot into your drive to install xrandr, then reboot and it should be good to go. @naquiroz

**Comment by naquiroz** [comment]
Hi @DOGGO20 , seems to this the problem. Could you explain a bit more on the part of `chroot` part, I don't want to mess things up.

**Comment by JavaCafe01** [comment]
@naquiroz Here's a post about how to chroot into manjaro...

https://forum.manjaro.org/t/how-to-save-your-manjaro-installation-when-it-breaks/75

Once you change the root to into the new mounting point, you can install the missing package.

**Comment by Askannz** [comment]
`xorg-xrandr` has been part of the dependencies of optimus-manager for quite some time, so I doubt it's the issue.

chroot is only useful if you can't boot into your system at all and need to fix it from another install.

**Comment by naquiroz** [comment]
You are right, that is not the issue. Please take in mind the files that I modified with the form link on my first comment.

**Comment by naquiroz** [comment]
> It shouldn't be necessary to use `pacman -S linux51-nvidia` anymore, the default Nvidia drivers bundled with Manjaro will work. You need to disable the bumblebee service though.
> 
> When you experience the freeze, are you still able to switch to aTTY console with Ctrl+Alt+F2,3,4 etc ? If not, do the following : create the file `/etc/optimus-manager/optimus-manager.conf` and paste this :
> 
> ```
> [optimus]
> switching=none
> pci_power_control=no
> ```
> 
> Then reboot. This isn't a proper solution because it'll disable power switching, but at least it should narrow the problem down.
> 
> Also make sure you applied the KDE fix as @JavaCafe01 suggested.

I can enter to the `tty` though (some, like 6 but not 1)

**Comment by Askannz** [comment]
It's very likely another case of ACPI lockup. Try using the config options I suggested.

**Comment by naquiroz** [comment]
Problem solved. Added the file you mentioned, installed the nvidia library as @JavaCafe01  suggested and it worked. Thanks!

**Comment by naquiroz** [comment]
Problem solved. Added the file you mentioned, installed the nvidia library as @JavaCafe01  suggested and it worked. Thanks!

**Comment by Askannz** [comment]
As I mentioned before, the new config file fixes the issue by completely disabling power switching. That's not really a proper solution, unless you don't care at all about battery life.

Try that one :

```
[optimus]
switching=bbswitch
```

**Comment by naquiroz** [comment]
Worked. Now I have another issue that the system wont sleep. I do have a linux swap partition though.

**Comment by naquiroz** [comment]
Solved the issue was related to the Bluetooth driver. Thanks
