### ISSUE TITLE
"couldn't find RGB GLX visual or fbconfig" only when switching to nvidia

### ISSUE THREAD

**Issue by leledumbo** [Askannz/optimus-manager#99]
**Describe the bug**
Switching to nvidia doesn't crash, but the dGPU isn't actually active, instead the current active GPU is still the iGPU. glxinfo reports "couldn't find RGB GLX visual or fbconfig" when nvidia is chosen, while it outputs correct info for intel.

**System info**
Please include :
- Manjaro
- KDE
- SDDM
- ASUS GL503VD

**Logs**
[all-three-logs.txt](https://github.com/Askannz/optimus-manager/files/3353269/all-three-logs.txt)
Sorry for the superfluous logs, it's a result of multiple relogins/reboots.

**Additional info**
I previously uses [nvidia-prime-switch-sddm](https://github.com/vetzki/nvidia-prime-switch-sddm), with the following config:
[nvidia.conf.txt](https://github.com/Askannz/optimus-manager/files/3353272/nvidia.conf.txt)
which works.

**Comment by leledumbo** [comment]
I try executing the logged xrandr command manually and ended up with "Could not find provider with name modesetting". Indeed `xrandr --listproviders` doesn't have such a provider. However, that expected provider does exist in Intel mode.

**Comment by leledumbo** [comment]
more info, my dmesg is polluted with these messages every 2-3 seconds:
```
[13714.979575] nvidia-nvlink: Nvlink Core is being initialized, major device number 235
[13714.980375] NVRM: The NVIDIA probe routine was not called for 1 device(s).
[13714.980377] NVRM: This can occur when a driver such as: 
               NVRM: nouveau, rivafb, nvidiafb or rivatv 
               NVRM: was loaded and obtained ownership of the NVIDIA device(s).
[13714.980377] NVRM: Try unloading the conflicting kernel module (and/or
               NVRM: reconfigure your kernel without the conflicting
               NVRM: driver(s)), then try loading the NVIDIA kernel module
               NVRM: again.
[13714.980378] NVRM: No NVIDIA devices probed.
[13714.980720] nvidia-nvlink: Unregistered the Nvlink Core, major device number 235
```

**Comment by Askannz** [comment]
Hi, sorry for the late reply.

Sounds like there is some conflict going on between nouveau and nvidia. Do you still have the issue if you boot directly in Nvidia mode (with `optimus-manager --set-startup nvidia`) ?

**Comment by leledumbo** [comment]
> Hi, sorry for the late reply.

Sorry, too. Gotta go back to my previous method as I can't live long without the dGPU.

> Sounds like there is some conflict going on between nouveau and nvidia. Do you still have the issue if you boot directly in Nvidia mode (with `optimus-manager --set-startup nvidia`) ?

Yes, exactly the same:

* prime_setup.log: `Error : cannot setup PRIME : Cannot setup PRIME : Failed to execute 'xrandr --setprovideroutputsource modesetting NVIDIA-0'`
* glxinfo: `name of display: :0
Error: couldn't find RGB GLX visual or fbconfig`
* lspci -k: `01:00.0 3D controller: NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile] (rev a1)
	Subsystem: ASUSTeK Computer Inc. GP107M [GeForce GTX 1050 Mobile]
	Kernel driver in use: nvidia
	Kernel modules: nouveau, nvidia_drm, nvidia
`
* optimus-manager --print-startup: `GPU mode for next startup : nvidia`
* optimus-manager --print-mode: `Current GPU mode : intel`
* optimus-manager --print-next-mode: `GPU mode requested for next login : nvidia`

The last two doesn't change regardless what `optimus-manager --set-startup` or  `optimus-manager --switch` I execute. Only if I set to intel, then glxinfo will not show error and display correct information.

The only positive improvement (after recent system update) is gone the polluted dmesg, it seems to be related to my old kernel (5.0) being EOL, while the current one is not yet (5.1). Scanning dmesg for nouveau shows nothing, while scanning for nvidia shows:

```
[    4.563909] nvidiabl: loading driver version 0.88
[    4.563936] nvidiabl: No supported Nvidia graphics adapter found
[    5.662903] nvidia: module license 'NVIDIA' taints kernel.
[    5.675653] nvidia-nvlink: Nvlink Core is being initialized, major device number 236
[    5.676102] nvidia 0000:01:00.0: enabling device (0006 -> 0007)
[    5.776456] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  430.26  Tue Jun  4 17:40:52 CDT 2019
[    5.796249] nvidia-modeset: Loading NVIDIA Kernel Mode Setting Driver for UNIX platforms  430.26  Tue Jun  4 17:45:09 CDT 2019
[    5.799322] [drm] [nvidia-drm] [GPU ID 0x00000100] Loading driver
[    6.478338] [drm] Initialized nvidia-drm 0.0.0 20160202 for 0000:01:00.0 on minor 1
```

which LGTM.

Last but not least, I found the issue that /etc/X11/xorg.conf.d/10-optimus-manager.conf can not be created by the service. Logging in or switching to any virtual terminal after installation and reboot will instantly shut down the computer. But if I create the file by hand afterwards, even if it's empty, as long as it's writable by root, then it will be filled correctly and logging in or switching to virtual terminal works without needing to resort to init level 3.

**Comment by leledumbo** [comment]
Sorry, the polluted dmesg issue returns. It happens only if current mode is intel, apparently. Sometimes, these lines also appear:
```
[ 1253.937015] pcieport 0000:00:1c.5: AER: Corrected error received: 0000:00:1c.5
[ 1253.937033] pcieport 0000:00:1c.5: PCIe Bus Error: severity=Corrected, type=Data Link Layer, (Transmitter ID)
[ 1253.937036] pcieport 0000:00:1c.5:   device [8086:a115] error status/mask=00001000/00002000
[ 1253.937038] pcieport 0000:00:1c.5:    [12] Timeout
```
The desktop freezes a second or two whenever it happens.

**Comment by leledumbo** [comment]
Tried using bbswitch instead of nouveau for switching backend, the gpu_setup.log says:
```
Cannot setup GPU : kernel setup error : bbswitch failed to set the GPU to OFF
```
indeed the dGPU is still on with nvidia driver in use.

**Comment by Askannz** [comment]
This is definitely a weird case, but all that kernel spamming could mean that something is going wrong at the PCI level. Try using the following config, and boot directly in Nvidia mode to eliminate any switching weirdness :

```
[optimus]
switching=none
pci_power_control=no
```

Are you sure that `/etc/X11/xorg.conf.d/10-optimus-manager.conf` is never created, even after the display manager has started (in Intel mode) ? That would be a pretty serious bug, and it's really odd that creating this file would silently fail without an error in the log.

**Comment by leledumbo** [comment]
> Try using the following config, and boot directly in Nvidia mode to eliminate any switching weirdness

With that two options, magically `/etc/X11/xorg.conf.d/10-optimus-manager.conf` is created successfully, which is very weird I'm gonna have to ensure whether it's a leftover from previous installation or not. However, it still doesn't use nvidia for display though the card is indeed active. `sudo journalctl -S'2019-07-15 00:00:00' | grep -i nvidia` Shows me this, which is also in `dmesg`:
```
Jul 15 00:56:50 Lelesus systemd-modules-load[1075]: Failed to insert module 'nvidiabl': No such device
Jul 15 00:56:50 Lelesus kernel: nvidiabl: loading driver version 0.88
Jul 15 00:56:50 Lelesus kernel: nvidiabl: No supported Nvidia graphics adapter found
Jul 15 00:56:50 Lelesus systemd-modules-load[1075]: Failed to insert module 'nvidiabl': No such device
Jul 15 00:56:50 Lelesus systemd-modules-load[1075]: Module 'nvidia' is blacklisted
Jul 15 00:56:50 Lelesus systemd-modules-load[1075]: Module 'nvidia_modeset' is blacklisted
Jul 15 00:56:50 Lelesus systemd-modules-load[1075]: Module 'nvidia_drm' is blacklisted
Jul 15 00:56:50 Lelesus systemd-modules-load[1075]: Module 'nvidia_uvm' is blacklisted
Jul 15 00:56:51 Lelesus prime-switch-boot[1134]: Startup mode is : nvidia
Jul 15 00:56:51 Lelesus prime-switch-boot[1134]: Loading Nvidia modules
Jul 15 00:56:51 Lelesus kernel: nvidia: module license 'NVIDIA' taints kernel.
Jul 15 00:56:51 Lelesus kernel: nvidia-nvlink: Nvlink Core is being initialized, major device number 236
Jul 15 00:56:51 Lelesus kernel: nvidia 0000:01:00.0: enabling device (0006 -> 0007)
Jul 15 00:56:51 Lelesus kernel: NVRM: loading NVIDIA UNIX x86_64 Kernel Module  430.26  Tue Jun  4 17:40:52 CDT 2019
Jul 15 00:56:51 Lelesus kernel: nvidia-modeset: Loading NVIDIA Kernel Mode Setting Driver for UNIX platforms  430.26  Tue Jun  4 17:45:09 CDT 2019
Jul 15 00:56:51 Lelesus kernel: [drm] [nvidia-drm] [GPU ID 0x00000100] Loading driver
Jul 15 00:56:52 Lelesus kernel: [drm] Initialized nvidia-drm 0.0.0 20160202 for 0000:01:00.0 on minor 1
Jul 15 00:56:52 Lelesus prime-switch-boot[1134]: Loaded extra Nvidia Xorg options (0 lines)
```
Despite those blacklist logs, the modules are actually loaded:
```
$ lspci -k -s 01:00.0
01:00.0 3D controller: NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile] (rev a1)
	Subsystem: ASUSTeK Computer Inc. GP107M [GeForce GTX 1050 Mobile]
	Kernel driver in use: nvidia
	Kernel modules: nouveau, nvidia_drm, nvidia
```
and I can't find where they are disabled either:
```
$ grep -r nvidia /etc/modprobe.d/
/etc/modprobe.d/mhwd-gpu.conf:options nvidia-drm modeset=1
$ grep -r nvidia /etc/modules-load.d/
/etc/modules-load.d/mhwd-gpu.conf:nvidia
/etc/modules-load.d/mhwd-gpu.conf:nvidia-modeset
/etc/modules-load.d/mhwd-gpu.conf:nvidia-drm
/etc/modules-load.d/mhwd-gpu.conf:nvidia-uvm
/etc/modules-load.d/linux419-nvidiabl.conf:nvidiabl
/etc/modules-load.d/linux420-nvidiabl.conf:nvidiabl
/etc/modules-load.d/linux51-nvidiabl.conf:nvidiabl
/etc/modules-load.d/linux50-nvidiabl.conf:nvidiabl
/etc/modules-load.d/linux50-rt-nvidiabl.conf:nvidiabl
```

Logs from `/var/log/optimus-manager/` are still the same.

**Comment by leledumbo** [comment]
OK, I found the perfect configuration when `/etc/X11/xorg.conf.d/10-optimus-manager.conf` will not be successfully created:
```
[optimus]
switching=nouveau
pci_power_control=yes
```
then set startup to intel. Simply switch it to nvidia from runlevel 3 then reboot will fix it.

My guess is not that the code that writes the file that fails, but even that particular code may not even be reached somehow. No additional log, unfortunately.

**Comment by Askannz** [comment]
Looks like there may be two issues at play here : some conflict with the power switching method that's causing the dmesg spam, and another issue that's causing Xorg to not use the Nvidia GPU.

Let's focus on the second issue first. At this point, I think it should help to get all possible logs from a clean slate. Sorry, it's going to be a little tedious, but it should help figuring out what's wrong.

Please do the following :

* Remove all logs from `/var/log/optimus-manager/` or move them elsewhere
* Set the config file to the options I suggested before (`switching=none` and `pci_power_control=no`)
* Set startup mode to Nvidia
* Reboot
* Grab all 3 logs from optimus-manager, and also the Xorg log (`/var/log/Xorg.0.log`), the SDDM log (`journalctl -u sddm -b0`) and the output of `nvidia-smi`.

**Comment by leledumbo** [comment]
Fresh from the oven:
[gpu_setup.log](https://github.com/Askannz/optimus-manager/files/3394053/gpu_setup.log)
[boot_setup.log](https://github.com/Askannz/optimus-manager/files/3394054/boot_setup.log)
[prime_setup.log](https://github.com/Askannz/optimus-manager/files/3394055/prime_setup.log)
[Xorg.0.log](https://github.com/Askannz/optimus-manager/files/3394056/Xorg.0.log)

`journalctl -u sddm -b0`:
```
Jul 16 03:25:40 Lelesus systemd[1]: Started Simple Desktop Display Manager.
Jul 16 03:25:40 Lelesus sddm[1740]: Initializing...
Jul 16 03:25:40 Lelesus sddm[1740]: Starting...
Jul 16 03:25:40 Lelesus sddm[1740]: Logind interface found
Jul 16 03:25:40 Lelesus sddm[1740]: Adding new display on vt 1 ...
Jul 16 03:25:40 Lelesus sddm[1740]: Loading theme configuration from ""
Jul 16 03:25:40 Lelesus sddm[1740]: Display server starting...
Jul 16 03:25:40 Lelesus sddm[1740]: Running: /usr/bin/X -nolisten tcp -dpi 96 -auth /var/run/sddm/{e738b887-4c10-49e1-b4f0-c9b941e2c43d} -background none -noreset -displayfd 17 -seat seat0 vt1
Jul 16 03:25:41 Lelesus sddm[1740]: Setting default cursor
Jul 16 03:25:41 Lelesus sddm[1740]: Running display setup script  "/sbin/prime-offload"
Jul 16 03:25:41 Lelesus sddm[1740]: Display server started.
Jul 16 03:25:41 Lelesus sddm[1740]: Socket server starting...
Jul 16 03:25:41 Lelesus sddm[1740]: Socket server started.
Jul 16 03:25:41 Lelesus sddm[1740]: Loading theme configuration from "/usr/share/sddm/themes/breeze/theme.conf"
Jul 16 03:25:41 Lelesus sddm[1740]: Greeter starting...
Jul 16 03:25:41 Lelesus sddm[1740]: Adding cookie to "/var/run/sddm/{e738b887-4c10-49e1-b4f0-c9b941e2c43d}"
Jul 16 03:25:41 Lelesus sddm-helper[1785]: [PAM] Starting...
Jul 16 03:25:41 Lelesus sddm-helper[1785]: [PAM] Authenticating...
Jul 16 03:25:41 Lelesus sddm-helper[1785]: [PAM] returning.
Jul 16 03:25:41 Lelesus sddm-helper[1785]: pam_unix(sddm-greeter:session): session opened for user sddm by (uid=0)
Jul 16 03:25:41 Lelesus sddm[1740]: Greeter session started successfully
Jul 16 03:25:41 Lelesus sddm[1740]: Message received from greeter: Connect
Jul 16 03:25:44 Lelesus sddm[1740]: Message received from greeter: Login
Jul 16 03:25:44 Lelesus sddm[1740]: Reading from "/usr/share/xsessions/plasma.desktop"
Jul 16 03:25:44 Lelesus sddm[1740]: Reading from "/usr/share/xsessions/plasma.desktop"
Jul 16 03:25:44 Lelesus sddm[1740]: Session "/usr/share/xsessions/plasma.desktop" selected, command: "/usr/bin/startkde"
Jul 16 03:25:44 Lelesus sddm-helper[1846]: [PAM] Starting...
Jul 16 03:25:44 Lelesus sddm-helper[1846]: [PAM] Authenticating...
Jul 16 03:25:44 Lelesus sddm-helper[1846]: [PAM] Preparing to converse...
Jul 16 03:25:44 Lelesus sddm-helper[1846]: [PAM] Conversation with 1 messages
Jul 16 03:25:44 Lelesus sddm-helper[1846]: gkr-pam: unable to locate daemon control file
Jul 16 03:25:44 Lelesus sddm-helper[1846]: pam_kwallet5(sddm:auth): (null): pam_sm_authenticate
Jul 16 03:25:44 Lelesus sddm-helper[1846]: [PAM] returning.
Jul 16 03:25:44 Lelesus sddm[1740]: Authenticated successfully
Jul 16 03:25:44 Lelesus sddm-helper[1846]: pam_kwallet5(sddm:setcred): pam_kwallet5: pam_sm_setcred
Jul 16 03:25:44 Lelesus sddm-helper[1846]: pam_unix(sddm:session): session opened for user leledumbo by (uid=0)
Jul 16 03:25:44 Lelesus sddm-helper[1785]: pam_unix(sddm-greeter:session): session closed for user sddm
Jul 16 03:25:44 Lelesus sddm-helper[1846]: pam_kwallet5(sddm:session): pam_kwallet5: pam_sm_open_session
Jul 16 03:25:44 Lelesus sddm-helper[1785]: [PAM] Closing session
Jul 16 03:25:44 Lelesus sddm-helper[1785]: [PAM] Ended.
Jul 16 03:25:44 Lelesus sddm[1740]: Auth: sddm-helper exited successfully
Jul 16 03:25:44 Lelesus sddm[1740]: Greeter stopped.
Jul 16 03:25:44 Lelesus sddm-helper[1846]: Starting: "/usr/share/sddm/scripts/Xsession \"/usr/bin/startkde\""
Jul 16 03:25:44 Lelesus sddm[1740]: Session started
```
`nvidia-smi`:
```
Tue Jul 16 03:28:00 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.26       Driver Version: 430.26       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1050    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   46C    P8    N/A /  N/A |      0MiB /  4042MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by Askannz** [comment]
Well, after some troubles and a broken laptop, I was able to install Manjaro KDE on a test machine. But everything is working as intended, and I still can't reproduce your issue...

In particular, it makes zero sense that Xorg just plain ignores the file `10-optimus-manager.conf` and goes straight for the Intel GPU. The log even says :

```
OutputClass "nvidia" setting /dev/dri/card1 as PrimaryGPU
```

To be honest I'm starting to run out of ideas here...Just in case, you're not running Wayland, are you ? Also, make sure that there is no `/etc/X11/xorg.conf` file and nothing in `/etc/X11/xorg.conf.d/` that could interfere with the generated configuration (but you've probably checked already).

**Comment by Askannz** [comment]
Does Xorg start on Nvidia if you completely remove optimus-manager and manually set the Xorg config to the one you gave in your very first message ? ([that one](https://github.com/Askannz/optimus-manager/files/3353272/nvidia.conf.txt))

**Comment by leledumbo** [comment]
> Just in case, you're not running Wayland, are you ?

```
$ echo $XDG_SESSION_TYPE
x11
```

> make sure that there is no /etc/X11/xorg.conf file
```
$ ls /etc/X11/
mhwd.d  xinit  xorg.conf.d  Xsession.d
```

>  and nothing in /etc/X11/xorg.conf.d/ that could interfere with the generated configuration

```
]$ cat  /etc/X11/xorg.conf.d/*
# Written by systemd-localed(8), read by systemd-localed and Xorg. It's
# probably wise not to edit this file manually. Use localectl(1) to
# instruct systemd-localed to update it.
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "us"
        Option "XkbModel" "pc105"
        Option "XkbOptions" "terminate:ctrl_alt_bksp,grp:alt_shift_toggle"
EndSection
Section "InputClass"
	Identifier "libinput touchpad catchall"
#        Identifier "ELAN1200:00 04F3:3090 Touchpad"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
	Option "libinput Middle Emulation Enabled" "1"
EndSection

Section "InputClass"
        Identifier      "Touchpad"                      # required
        MatchIsTouchpad "yes"                           # required
        Driver          "synaptics"                     # required
        Option          "MinSpeed"              "0.5"
        Option          "MaxSpeed"              "1.0"
        Option          "AccelFactor"           "0.075"
        Option          "TapButton1"            "1"
        Option          "TapButton2"            "2"     # multitouch
        Option          "TapButton3"            "3"     # multitouch
        Option          "VertTwoFingerScroll"   "1"     # multitouch
        Option          "HorizTwoFingerScroll"  "1"     # multitouch
        Option          "VertEdgeScroll"        "1"
        Option          "CoastingSpeed"         "8"
        Option          "CornerCoasting"        "1"
        Option          "CircularScrolling"     "1"
        Option          "CircScrollTrigger"     "7"
        Option          "EdgeMotionUseAlways"   "1"
        Option          "LBCornerButton"        "8"     # browser "back" btn
        Option          "RBCornerButton"        "9"     # browser "forward" btn
EndSection

Section "InputDevice"
  Identifier      "Wireless Mouse"
  Driver          "evdev"
  Option          "Name" "YK 2.4GHz Wireless Device"
#  Option          "Device" "/dev/input/by-id/usb-YK_2.4G_Wireless_Device-event-mouse"
  Option          "Buttons" "5"
  Option          "ZAxisMapping" "4 5"
  Option          "ButtonMapping" "1 2 3"
EndSection
```

> Does Xorg start on Nvidia if you completely remove optimus-manager and manually set the Xorg config to the one you gave in your very first message ?

That alone is not enough, it's my configuration to be used with [this](https://github.com/vetzki/nvidia-prime-switch-sddm). Before you ask, yes it's different from the one in that page, the default doesn't work for me. Perhaps it's also the same problem as what we're facing with optimus manager? Something odd that ASUS implements, maybe. Note that I don't use any custom config so essentially what the package does is only switch the used .conf symlink in /etc/X11/xorg.conf.d and some startup script in sddm:

```
#!/bin/sh
# Xsetup - run as root before the login dialog appears

check() {
python -c '
import os

SYSFS_PATH="/sys/bus/pci/devices"
devs = os.listdir(SYSFS_PATH)
gpus = [ "/sys/bus/pci/devices/"+i+"/" for i in devs if "0x03000" in open(SYSFS_PATH+"/"+i+"/class").read() ]

_g = (True for i in gpus if "nouveau" in os.path.realpath(i+"driver"))

for v in _g:
  if True:
    print(v)
    exit(0)
exit(1)
'
}

if [[ $(check) == True ]];
    then
	# nouveau (see also https://nouveau.freedesktop.org/wiki/Optimus/)
	xrandr --setprovideroffloadsink nouveau Intel;
	# if second gpu output not accessible
	# xrandr --setprovideroutputsource nouveau Intel
    else
	# nvidia
	xrandr --setprovideroutputsource modesetting NVIDIA-0; # not necessarily needed
fi

xrandr --auto;

unset check;
```

and it works.

**Comment by Askannz** [comment]
> it's different from the one in that page, the default doesn't work for me. Perhaps it's also the same problem as what we're facing with optimus manager?

The default configuration used by nvidia-prime-switch-sddm looks very similar to the one used by optimus-manager, so it's worth a shot. I've made a new branch which uses your configuration instead, could you test it out ?

https://github.com/Askannz/optimus-manager/tree/alternate-xorg-conf

**Comment by leledumbo** [comment]
> Does Xorg start on Nvidia if you completely remove optimus-manager and manually set the Xorg config to the one you gave in your very first message ? ([that one](https://github.com/Askannz/optimus-manager/files/3353272/nvidia.conf.txt))

ulala baby:
```
$ glxinfo | grep -i vendor
server glx vendor string: NVIDIA Corporation
client glx vendor string: NVIDIA Corporation
OpenGL vendor string: NVIDIA Corporation
$ optimus-manager --print-mode

Current GPU mode : nvidia
```

**Comment by leledumbo** [comment]
Moving back to testing backend and pci_power_control values, only none and no works. Through experiments, I found that the dGPU may only be turned off once the graphical session finishes starting. i.e., from a running session, I can run `/usr/share/linux51-acpi_call/examples/turn_off_gpu.sh` which basically does:

```
echo "\_SB.PCI0.PEG0.PEGP._OFF" > /proc/acpi/call
```

and indeed it completely turns the GPU off. However, I must turn it on (`_OFF` -> `_ON`) again before suspend/sleep/hibernate or else it won't do it right (system lockup, either on sleep or wakeup) and turn it off again after the system is fully woken up. I guess that's the characteristic of the acpi implementation in this particular laptop.

**Comment by Askannz** [comment]
Alright, now we're getting somewhere 😀

Thanks for the detailed testing, it's very helpful.

I'm not sure how to handle this particular ACPI implementation, it's weird that neither bbswitch nor the default kernel power management seem to cover it. I'll look into it, the power switching backend of optimus-manager needs a rewrite anyways.

**Comment by Askannz** [comment]
Hi @leledumbo, the latest version of optimus-manager implements both the `acpi_call` power management and the Xorg config fix. So everything should work on your end now, feel free to re-open this issue if it's not the case.
